import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { createServer } from "vite";

const root = fileURLToPath(new URL("..", import.meta.url));
const read = path => JSON.parse(readFileSync(new URL(`../${path}`, import.meta.url), "utf8"));
const conditions = read("public/game-lines/vampire/data/conditions.json");
const localized = conditions.filter(item => item.presentationPt);
const nonElders = localized.filter(item => !item.id.startsWith("elder-"));
const enabledErrata = conditions.filter(item => item.errataFor).map(item => item.id);
const escape = value => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#x27;" })[char]);

test("VtR visually verified official and Homebrew Conditions retain their complete rules and IDs", () => {
  assert.deepEqual(localized.map(item => item.id).sort(), ["vtr-better-feared:overwhelming-hunger", "vtr-better-feared:despondent", "vtr-better-feared:frantic", "vtr-better-feared:potent-curse", "vtr-false-gods:subsumed", "vtr-false-gods:chronic-malkavia", "vtr-false-gods:terminal-malkavia", "vtr-false-gods:pareidolia", "vtr-false-gods:directive", "radio-sickness", "agonized", "promised", "primeval-truths", "oathbreaker-invictus", "vtr-sin-again:depressed", "vtr-sin-again:self-loathing", "vtr-sin-again:inflamed", "vtr-sin-again:fired-up", "vtr-strange-shades:scorned", "vtr-strange-shades:soulmate", "addicted", "bestial", "charmed", "competitive", "confused", "delusional", "dependent", "distracted", "dominated", "drained", "ecstatic", "enervated", "enslaved", "enthralled", "false-memories", "frightened", "humbled", "intoxicated", "jaded", "languid", "lethargic", "mesmerized", "raptured", "sated", "scarred", "stumbled", "subservient", "tainted", "tasked", "tempted", "thrall", "wanton", "vtr-wild-hunt:beastless", "h-vtr-fire-revolution:contrary", "h-vtr-agony-ecstasy:errata:seed-of-her-divinity", "h-vtr-fire-revolution:errata:carthian-backup", "elder-anchored-heart", "elder-beasts-bargain", "elder-beloved-enemy", "elder-crushed", "elder-forgotten", "elder-immutable-heart", "elder-imprisoned-echo", "elder-living-legend", "elder-lost-lineage", "elder-quiet-echo", "elder-synchronized", "elder-vitaes-resoluteness", "soulless"].sort());
  for (const item of localized) {
    for (const field of ["name", "description", "resolution", ...(item.penalty ? ["penalty"] : []), ...(item.beat ? ["beat"] : [])]) {
      assert.ok(item.presentationPt[field]?.trim(), `${item.id}.${field}`);
      assert.deepEqual(item.presentationPt[field].match(/\d+/g) ?? [], item[field].match(/\d+/g) ?? []);
    }
    assert.equal(item.name, item.errataFor ? `${item.originalName} — Errata` : item.originalName);
    assert.equal(Boolean(item.presentationPt.beat), Boolean(item.beat));
  }
  const [hunger, despondent, frantic, curse, subsumed, chronic, terminal, pareidolia, directive, radio, agonized, promised, primeval, oathbreaker, depressed, loathing, inflamed, firedUp, scorned, soulmate] = nonElders;
  assert.equal(hunger.page, 31);
  assert.equal(hunger.persistent, undefined);
  assert.equal(hunger.beat, undefined);
  assert.match(hunger.description, /scene ends.*Size 2.*Deprived/);
  assert.equal(despondent.page, 101);
  assert.equal(despondent.persistent, true);
  assert.match(despondent.description, /−3.*3 successes instead of 5.*only to vampires with Nightmare.*bite heals/);
  assert.match(despondent.resolution, /Integrity or Humanity.*consent/);
  assert.match(despondent.beat, /Dramatically fail/);
  assert.equal(frantic.page, 98);
  assert.equal(frantic.persistent, true);
  assert.match(frantic.description, /extended action.*1 Willpower.*does not grant \+3.*same Skill suffer −2.*ends without resolving.*hours.*exceptional success.*nights/);
  assert.match(frantic.resolution, /depressant drugs.*alcohol.*frenzy/);
  assert.equal(curse.page, 107);
  assert.equal(curse.persistent, true);
  assert.match(curse.description, /Choose 2 Skills.*unskilled penalties.*±1 at Humanity 6, ±2 at 5.*Humanity 1.*9-again.*loses 10-again.*only to mundane actions.*do not affect derived/);
  assert.match(curse.resolution, /not your Touchstone.*Humanity 7/);
  assert.doesNotMatch(curse.description, /Ease the Curse/);
  assert.equal(subsumed.page, 26);
  assert.equal(subsumed.persistent, undefined);
  assert.equal(subsumed.beat, undefined);
  assert.match(subsumed.description, /Pilot.*half your Covenant Status, rounded up.*lose the usual bonus.*ends without resolving/);
  assert.doesNotMatch(subsumed.description, /Adrestoi|Blood Tether/);
  assert.match(subsumed.resolution, /Anchor.*all Willpower.*breaking point.*directive exactly/);
  assert.equal(chronic.page, 81);
  assert.equal(chronic.persistent, true);
  assert.match(chronic.description, /Once per session.*progression.*chance die.*−2.*always a dramatic failure/);
  assert.match(chronic.description, /Except for the first use.*remaining temporary Willpower.*levels 1 or 2.*level 3 has −1.*level 4 has −2.*level 5 has −3/);
  assert.match(chronic.description, /dramatic failure counts as 2 failures.*exceptional success removes.*exceeds permanent Willpower.*Terminal Malkavia.*Beat.*Aspiration/);
  assert.equal(chronic.resolution, "The cure?");
  assert.equal(terminal.page, 81);
  assert.equal(terminal.persistent, true);
  assert.match(terminal.description, /once per scene.*Resolve \+ Composure.*cumulative −1.*maximum of −5.*night ends.*succeed or fail/);
  assert.match(terminal.description, /no longer costs Willpower.*aggravated damage.*equal to its successes.*frenzy.*cannot end early.*progression resets.*breaking points suffer −2/);
  assert.match(terminal.beat, /witnesses cannot rationalize/);
  assert.equal(pareidolia.page, 98);
  assert.equal(pareidolia.persistent, true);
  assert.match(pareidolia.description, /Once per night.*\+5.*Investigation.*Social actions.*−3/);
  assert.equal(pareidolia.resolution, "Find the answer to your question.");
  assert.equal(directive.page, 113);
  assert.equal(directive.persistent, true);
  assert.match(directive.description, /Once per session.*9-again.*Breaking points.*−1.*cannot be resolved.*Lingering Motivation/);
  assert.doesNotMatch(directive.description, /chapter/);
  assert.equal(radio.page, 23);
  assert.match(radio.description, /Mental rolls, Stealth rolls.*combat suffer −1.*each week.*maximum of −5.*fatal/);
  assert.equal(agonized.page, 135);
  assert.equal(agonized.source, "Guide to the Night");
  assert.equal(agonized.persistent, undefined);
  assert.equal(agonized.beat, undefined);
  assert.match(agonized.description, /All rolls suffer −3/);
  assert.match(agonized.resolution, /instant action.*Resolve \+ Composure.*negate the penalty.*turns equal to your successes.*scene ends.*incapacitated/);
  assert.equal(promised.page, 28);
  assert.equal(promised.persistent, true);
  assert.match(promised.description, /mortal gains Merit dots equal to.*Majesty.*Allies, Resources, or Status.*cannot use Siphon.*anyone else.*exceptional success.*restores 1 Willpower/);
  assert.match(promised.resolution, /mortal loses Integrity.*any level of Vinculum.*Humanity 1 breaking point.*mortal dies/);
  assert.match(promised.beat, /rightmost Health box.*Siphon feeding.*vampire goes a week.*another vessel/);
  assert.equal(primeval.page, 184);
  assert.equal(primeval.persistent, undefined);
  assert.equal(primeval.beat, undefined);
  assert.match(primeval.description, /cannot regain Willpower.*1 additional Vitae.*each night/);
  assert.match(primeval.resolution, /Humanity detachment.*significant action.*void/);
  assert.equal(oathbreaker.page, 189);
  assert.equal(oathbreaker.presentationPt.name, "Quebrador de Juramento");
  assert.equal(oathbreaker.persistent, true);
  assert.match(oathbreaker.penalty, /2 dots of Invictus Status.*1 dot each of Resources, Allies, Contacts, Herd, and Mentor.*if you have.*dramatic failures/);
  assert.match(oathbreaker.resolution, /Final Death for an Invictus member.*member or the Invictus at large/);
  assert.deepEqual(oathbreaker.nameQualifier, { "en-US": "Kindred", "pt-BR": "Membro" });
  assert.equal(depressed.page, 24);
  assert.equal(depressed.persistent, true);
  assert.match(depressed.description, /10-again.*instant Mental and Social.*Nightmare dots.*Manipulation.*ends without resolving.*hours.*exceptional success.*nights/);
  assert.match(depressed.resolution, /short-term Aspiration.*restitution/);
  assert.equal(loathing.page, 25);
  assert.equal(loathing.persistent, true);
  assert.match(loathing.description, /cannot spend or regain Willpower.*extended actions automatically fail.*ends without resolving.*nights.*Blood Potency/);
  assert.match(loathing.beat, /Tell the vampire.*dangerous for anyone/);
  assert.equal(inflamed.page, 30);
  assert.equal(inflamed.persistent, undefined);
  assert.equal(inflamed.beat, undefined);
  assert.match(inflamed.description, /Celerity dots.*all Composure- and Stamina-based.*Induce.*Vigor is higher.*ends without resolving.*scene.*exceptional success.*night/);
  assert.match(inflamed.resolution, /greater than your Stamina.*mortal affected by Inure.*Stamina \+ Resilience/);
  assert.equal(firedUp.page, 41);
  assert.equal(firedUp.persistent, undefined);
  assert.equal(firedUp.beat, undefined);
  assert.match(firedUp.description, /\+3.*Physical and Social.*−2.*physical violence or destruction.*3 successes instead of 5.*ends without resolving.*night/);
  assert.match(firedUp.resolution, /5 bashing or 2 lethal or aggravated damage to another person/);
  assert.match(scorned.description, /Blood Potency 1.*Integrity for Humanity.*do not cause breaking points.*that vampire/);
  assert.match(scorned.resolution, /Kill.*Touchstones.*reputation/);
  assert.match(soulmate.description, /existing and new blood bonds.*Majesty.*Once per night.*greater than their Stamina.*more than their Size/);
  assert.match(soulmate.penalty, /Each month/);
  assert.match(soulmate.beat, /Either partner.*The mortal.*The vampire/);
  const [addicted, bestial, charmed, competitive] = nonElders.slice(20);
  assert.equal(addicted.page, 301);
  assert.equal(addicted.persistent, true);
  assert.match(addicted.description, /may cause Deprived.*multiple times for different addictions/);
  assert.match(addicted.resolution, /Integrity.*exceptional success.*breaking-point/);
  assert.equal(bestial.page, 301);
  assert.equal(bestial.persistent, undefined);
  assert.equal(bestial.beat, undefined);
  assert.match(bestial.penalty, /−2.*frenzy or physical impulses.*−2 to Defense.*3 successes instead of 5/);
  assert.match(bestial.description, /nights.*winner.*own Blood Potency.*After resolving.*full month/);
  assert.equal(bestial.resolution, "Cause damage in someone's last 3 Health boxes.");
  assert.equal(charmed.page, 301);
  assert.equal(charmed.persistent, true);
  assert.match(charmed.description, /Majesty dots.*Manipulation.*Wits \+ Empathy or Wits \+ Subterfuge.*Supernatural lie detection requires a Clash.*expires without resolving.*hour per dot/);
  assert.equal(competitive.page, 302);
  assert.equal(competitive.persistent, undefined);
  assert.equal(competitive.beat, undefined);
  assert.match(competitive.description, /direct competition.*do not spend Willpower suffer −2.*contested and extended.*3 successes instead of 5.*nights.*After resolving.*full month/);
  assert.match(competitive.resolution, /competition.*someone reaches a breaking point/);
  const [confused, delusional, dependent, distracted] = nonElders.slice(24);
  assert.equal(confused.page, 302);
  assert.equal(confused.persistent, undefined);
  assert.equal(confused.beat, undefined);
  assert.match(confused.penalty, /−2 to Intelligence and Wits/);
  assert.match(confused.resolution, /half an hour.*any amount of lethal damage/);
  assert.equal(delusional.persistent, true);
  assert.match(delusional.description, /without actually hallucinating.*cannot truly suppress.*1 Willpower.*explanation.*does not apply to a specific situation/);
  assert.equal(dependent.persistent, true);
  assert.match(dependent.description, /mortal.*attention and blood.*all effects of a second-stage blood bond.*p\. 100/);
  assert.equal(dependent.resolution, "The mortal dies.");
  assert.equal(distracted.persistent, undefined);
  assert.equal(distracted.beat, undefined);
  assert.match(distracted.description, /extended actions.*does not grant a Beat/);
  assert.match(distracted.penalty, /−2.*perception, concentration, or precision/);
  assert.equal(distracted.resolution, "Leave the swarm.");
  const [dominated, drained, ecstatic, enervated] = nonElders.slice(28);
  assert.equal(dominated.page, 302);
  assert.equal(dominated.persistent, undefined);
  assert.equal(dominated.beat, undefined);
  assert.match(dominated.description, /naturally limited task ends when completed.*sunrise.*cannot clearly remember/);
  assert.match(dominated.resolution, /bashing or lethal damage than Stamina.*Resolve \+ Composure.*fulfill the vampire's command/);
  assert.equal(drained.page, 303);
  assert.match(drained.description, /roll Stamina.*unconscious.*hour.*Taking damage, being fed from.*Willpower.*count as physical exertion/);
  assert.match(drained.penalty, /−2.*does not apply.*Stamina roll.*wound penalties do/);
  assert.equal(drained.resolution, "Heal all lethal damage through normal means.");
  assert.equal(ecstatic.page, 303);
  assert.match(ecstatic.description, /Blood Potency were 3 dots lower.*minimum of 1.*\+2/);
  assert.equal(enervated.page, 303);
  assert.equal(enervated.persistent, true);
  assert.match(enervated.description, /Integrity is gone.*Soulless.*Virtue, only Vice.*permanent Willpower by 1 dot.*new maximum/);
  assert.equal(enervated.beat, "Lose a dot of permanent Willpower.");
  const [enslaved, enthralled, memories, frightened] = nonElders.slice(32);
  assert.equal(enslaved.page, 303);
  assert.equal(enslaved.persistent, true);
  assert.match(enslaved.description, /remember what she tells.*Mesmerized.*hear her voice, but not eye contact.*Resolve does not penalize.*Entombed Command and Possession/);
  assert.match(enslaved.resolution, /Kill.*supernatural means/);
  assert.equal(enthralled.page, 303);
  assert.equal(enthralled.persistent, true);
  assert.match(enthralled.description, /risking your life.*one night per dot.*1 Willpower.*Humanity 1 breaking point.*Only success.*failure.*back down/);
  assert.match(enthralled.resolution, /more lethal damage than your Stamina.*protecting the vampire.*succeed.*breaking-point/);
  assert.equal(enthralled.beat, "Put yourself in harm's way to protect the vampire.");
  assert.equal(memories.page, 303);
  assert.equal(memories.persistent, true);
  assert.match(memories.description, /proof that a memory is false is a breaking point.*level set by the Storyteller/);
  assert.match(memories.resolution, /proof.*succeed/);
  assert.equal(frightened.page, 304);
  assert.equal(frightened.persistent, undefined);
  assert.equal(frightened.beat, undefined);
  assert.match(frightened.description, /cannot approach or act against.*only exit.*collapse in terror.*roll to avoid frenzy.*scene ends.*1 Willpower suppresses all its effects for one turn/);
  assert.equal(frightened.resolution, "Escape from the source of fear.");
  const [humbled, intoxicated, jaded, languid] = nonElders.slice(36);
  assert.equal(humbled.page, 304);
  assert.deepEqual(humbled.nameQualifier, { "en-US": "Kindred", "pt-BR": "Membro" });
  assert.equal(humbled.persistent, undefined);
  assert.equal(humbled.beat, undefined);
  assert.match(humbled.description, /unable to regain Willpower from the Requiem/);
  assert.equal(humbled.penalty, "−2 to Resolve rolls.");
  assert.match(humbled.resolution, /Willpower.*Mask/);
  assert.equal(intoxicated.page, 304);
  assert.equal(intoxicated.persistent, undefined);
  assert.equal(intoxicated.beat, undefined);
  assert.match(intoxicated.penalty, /−2 to Dexterity and Wits.*two fewer Doors/);
  assert.match(intoxicated.resolution, /Sleep.*breaking point/);
  assert.equal(jaded.page, 304);
  assert.equal(jaded.persistent, undefined);
  assert.equal(jaded.beat, undefined);
  assert.match(jaded.description, /resist frenzy.*capped at your Humanity dots.*cannot spend Willpower.*may still ride the wave/);
  assert.equal(jaded.resolution, "Meaningful interaction with a Touchstone.");
  assert.equal(languid.page, 304);
  assert.equal(languid.persistent, undefined);
  assert.equal(languid.beat, undefined);
  assert.match(languid.description, /Each night.*cumulative −1.*all actions.*daysleep.*one Vitae per dot of Blood Potency/);
  assert.doesNotMatch(languid.description, /final Touchstone/);
  assert.equal(languid.resolution, "Fall into torpor.");
  const [lethargic, mesmerized, raptured, sated] = nonElders.slice(40);
  for (const item of [lethargic, mesmerized, raptured, sated]) {
    assert.equal(item.page, 305);
    assert.equal(item.persistent, undefined);
    assert.equal(item.beat, undefined);
  }
  assert.deepEqual(lethargic.nameQualifier, { "en-US": "Kindred", "pt-BR": "Membro" });
  assert.match(lethargic.description, /prevents you from spending Willpower.*six hours.*cumulative −1.*Stamina \+ Resolve with this penalty.*next sunset/);
  assert.equal(lethargic.resolution, "Sleep for a full day.");
  assert.match(mesmerized.description, /unusual commands.*After resolving.*\+3.*same scene.*cannot clearly remember.*fading.*does not count as resolving/);
  assert.doesNotMatch(mesmerized.description, /resist that vampire's further/);
  assert.match(mesmerized.resolution, /any amount.*bashing or lethal.*breaking point/);
  assert.match(raptured.description, /no Willpower.*3 successes instead of 5/);
  assert.doesNotMatch(raptured.description, /exceptionally/);
  assert.equal(sated.penalty, "+1 to rolls to resist frenzy.");
  assert.match(sated.resolution, /Enter frenzy.*resist.*−3 or worse/);
  const [scarred, stumbled, subservient, tainted] = nonElders.slice(44);
  assert.equal(scarred.page, 305);
  assert.equal(scarred.persistent, undefined);
  assert.equal(scarred.beat, undefined);
  assert.match(scarred.description, /Predatory aura.*frighten or intimidate.*\+2/);
  assert.match(scarred.penalty, /−2.*fear.*Nightmare and Intimidation/);
  assert.match(scarred.resolution, /at least three levels of lethal damage/);
  assert.equal(stumbled.page, 306);
  assert.equal(stumbled.persistent, undefined);
  assert.equal(stumbled.beat, undefined);
  assert.match(stumbled.description, /does not grant a Beat/);
  assert.match(stumbled.penalty, /Each subsequent roll.*extended action.*−3/);
  assert.equal(stumbled.resolution, "The ritual ends.");
  assert.equal(subservient.page, 306);
  assert.equal(subservient.persistent, true);
  assert.match(subservient.description, /Mesmerized even without.*1 Willpower.*still Mesmerize.*memories still requires Dominate.*week unless.*reapplies/);
  assert.match(subservient.resolution, /more lethal damage than Stamina.*breaking point.*succeed/);
  assert.equal(tainted.page, 306);
  assert.equal(tainted.persistent, undefined);
  assert.equal(tainted.beat, undefined);
  assert.match(tainted.description, /Once per session.*penalize.*victim's Blood Potency.*add that many dice.*separate instances/);
  assert.doesNotMatch(tainted.description, /chapter/);
  assert.match(tainted.resolution, /months.*victim's Blood Potency.*each level of aggravated damage.*one month/);
  const [tasked, tempted, thrall, wanton] = nonElders.slice(48);
  for (const item of [tasked, tempted, thrall, wanton]) assert.equal(item.page, 307);
  for (const item of [tasked, tempted, wanton]) {
    assert.equal(item.persistent, undefined);
    assert.equal(item.beat, undefined);
  }
  assert.match(tasked.penalty, /8-again.*related.*unrelated.*10-again/);
  assert.match(tasked.resolution, /Complete.*fail/);
  assert.match(tempted.description, /resist frenzy suffer −1.*further successful resistance increases.*until you shed/);
  assert.equal(tempted.resolution, "Kill, fall into frenzy, or make a meaningful connection with a Touchstone.");
  assert.equal(thrall.persistent, true);
  assert.deepEqual(thrall.nameQualifier, { "en-US": "Kindred", "pt-BR": "Membro" });
  assert.match(thrall.description, /unable to spend Willpower, use Defense, or spend Experiences.*Broken.*chance of regaining the soul/);
  assert.equal(thrall.beat, "The character is victimized because of the Condition.");
  assert.match(wanton.description, /Resolve or Composure.*−2.*3 successes instead of 5.*Majesty.*nights.*winner.*own Blood Potency.*After resolving.*full month/);
  assert.equal(wanton.resolution, "Indulge in something that constitutes a breaking point.");
  for (const item of [bestial, competitive, wanton]) assert.match(item.presentationPt.description, /teste de Desapego/);
  assert.doesNotMatch(JSON.stringify(localized.map(item => item.presentationPt)), /Distanciamento/);
  const [beastless, contrary, seed, backup] = nonElders.slice(52);
  assert.equal(beastless.page, 39);
  assert.equal(beastless.beat, undefined);
  assert.equal(beastless.persistent, undefined);
  assert.match(beastless.description, /cannot frenzy.*Disciplines or Devotions.*mortal.*predatory aura.*Resolve \+ Composure.*bonus for hunger.*ends without resolving/);
  assert.equal(beastless.resolution, "Suffer a breaking point due to inflicting violence.");
  assert.equal(contrary.page, 91);
  assert.equal(contrary.persistent, true);
  assert.match(contrary.description, /distrust everything.*Supernatural abilities.*do not work.*ends without resolving.*hours.*Blood Potency/);
  assert.equal(seed.page, 107);
  assert.equal(seed.defaultDisabled, true);
  assert.equal(seed.errataFor, "vtr-sotc:seed-of-her-divinity");
  assert.match(seed.description, /3 successes instead of 5.*all Social.*ends without resolving.*nights.*Presence/);
  assert.match(seed.resolution, /share and spread.*Presence \+ Expression/);
  assert.equal(backup.page, 114);
  assert.equal(backup.defaultDisabled, true);
  assert.equal(backup.errataFor, "vtr-core:carthian-backup");
  assert.match(backup.description, /start of each turn.*lethal.*Army of One dots.*2 damage.*evenly.*lowest Defense.*Initiative.*Defense does not apply.*Resilience.*Celerity/);
  assert.match(backup.resolution, /5 \+ Army of One.*no Defense.*cannot heal.*at most 1 damage.*exceeds.*lethal damage above 5.*aggravated damage.*torpor.*Contest or resist.*lethal attack/);
  assert.match(backup.presentationPt.description, /Exército de Um Só/);
  const [anchored, bargain, beloved, crushed] = ["elder-anchored-heart", "elder-beasts-bargain", "elder-beloved-enemy", "elder-crushed"].map(id => conditions.find(item => item.id === id));
  for (const item of [anchored, bargain, beloved, crushed]) assert.equal(item.page, 135);
  for (const item of [anchored, bargain, beloved]) assert.equal(item.persistent, true);
  assert.match(anchored.beat, /regardless of its outcome.*situation the elder set up/);
  assert.match(anchored.resolution, /dies.*cuts.*detachment/);
  assert.match(bargain.description, /frenzy-roll penalty for Hunger.*even when full.*immediate, significant harm.*Masquerade.*other consequences are irrelevant/);
  assert.match(beloved.resolution, /stops fighting.*always a breaking point/);
  assert.doesNotMatch(beloved.resolution, /permanently/);
  assert.equal(crushed.persistent, undefined);
  assert.equal(crushed.beat, undefined);
  assert.match(crushed.description, /cannot regain Willpower.*two points.*one/);
  assert.match(crushed.resolution, /breaking point.*lethal or aggravated.*three rightmost Health boxes/);
  const [forgotten, immutable, imprisoned, legend] = ["elder-forgotten", "elder-immutable-heart", "elder-imprisoned-echo", "elder-living-legend"].map(id => conditions.find(item => item.id === id));
  for (const item of [forgotten, immutable, imprisoned, legend]) assert.equal(item.page, 136);
  for (const item of [forgotten, immutable, legend]) assert.equal(item.persistent, true);
  assert.match(forgotten.description, /always under Face in the Crowd.*acquaintances.*1 Willpower.*scene.*Only your regnant, your own thralls.*Conditions with Dominate or Majesty/);
  assert.match(forgotten.resolution, /blood bond.*Humanity or Integrity/);
  assert.match(immutable.description, /first Touchstone.*\+3.*additional Touchstones.*\+4.*cannot be replaced/);
  assert.match(immutable.resolution, /Languid.*abandon.*detachment/);
  assert.equal(imprisoned.persistent, undefined);
  assert.equal(imprisoned.beat, undefined);
  assert.match(imprisoned.description, /Rank.*escape captivity, including grapples, or flee danger.*ends after nights.*next full session.*penalty equal to its Rank/);
  assert.match(imprisoned.resolution, /Break the mirror.*dramatically failing a Social roll.*immediately interferes/);
  assert.doesNotMatch(imprisoned.description, /chapter|turns failed Social actions into dramatic failures/);
  assert.match(legend.description, /Kindred.*−1.*Invictus.*−2.*not cumulative.*mortals.*\+2/);
  assert.equal(legend.resolution, "Separate your identity from the fictional character.");
  const [lineage, quiet, synchronized, vitae] = ["elder-lost-lineage", "elder-quiet-echo", "elder-synchronized", "elder-vitaes-resoluteness"].map(id => conditions.find(item => item.id === id));
  for (const item of [lineage, quiet, synchronized, vitae]) assert.equal(item.page, 137);
  assert.equal(lineage.persistent, true);
  assert.match(lineage.description, /never gain Clan Status.*all your Social Merits.*3 in-clan Disciplines excluding Coils, Crúac, and Theban Sorcery.*Bane.*not currently in play/);
  assert.match(lineage.resolution, /Storyteller permission.*normally.*no resolution/);
  assert.equal(quiet.persistent, undefined);
  assert.equal(quiet.beat, undefined);
  assert.match(quiet.description, /Twilight.*visible only to you.*player chooses.*character has no innate control.*will not harm itself.*next sunrise/);
  assert.match(quiet.resolution, /significant favor or service.*1 Willpower/);
  assert.equal(synchronized.persistent, undefined);
  assert.equal(synchronized.beat, undefined);
  assert.match(synchronized.description, /damage or Conditions.*lethal pistol damage.*mortal.*bashing damage.*only one instance.*different victim replaces/);
  assert.match(synchronized.resolution, /dies.*Humanity.*new instance/);
  assert.equal(vitae.persistent, true);
  assert.equal(vitae.beat, undefined);
  assert.match(vitae.description, /Addicted \(vitae\) and Languid.*when you gain Languid.*only in scenes when you drink vitae.*torpor.*Humanity were 2 dots lower/);
  assert.equal(vitae.resolution, "Wake from torpor.");
  const soulless = conditions.find(item => item.id === "soulless");
  assert.equal(soulless.page, 306);
  assert.equal(soulless.persistent, true);
  assert.match(soulless.description, /cannot attempt abjuration, warding, or binding.*Virtue and Vice.*1 Willpower per scene.*once per session.*Integrity breaking point with −5.*Integrity is already 1.*Humanity 2 breaking point/);
  assert.match(soulless.penalty, /−2.*possession/);
  assert.equal(localized.length, conditions.length, "Every currently included Vampire Condition has complete PT presentation");
});

test("Vampire Desktop/Mobile and Homebrew render localized Conditions in EN/PT/EN without changing saved instances", async () => {
  const before = JSON.stringify(conditions);
  for (const locale of ["en-US", "pt-BR", "en-US"]) {
    let mobile = false;
    const vite = await createServer({ appType: "custom", configFile: false, root, resolve: { alias: { "@": root } }, server: { middlewareMode: true, hmr: false, ws: false }, optimizeDeps: { noDiscovery: true, include: [] }, plugins: [{ name: "condition-surfaces", enforce: "pre", transform(code, id) {
      const path = id.replaceAll("\\", "/");
      if (path.endsWith("/lib/homebrew.ts")) return code.replace("export const EMPTY_HOMEBREW_PREFERENCES: HomebrewPreferences = { disabledIds: [] };", `export const EMPTY_HOMEBREW_PREFERENCES: HomebrewPreferences = { disabledIds: [], enabledIds: ${JSON.stringify(enabledErrata)} };`);
      if (path.endsWith("/hooks/use-mobile.ts")) return "export let mobile = false; export const setTestMobile = value => { mobile = value; }; export const useIsMobile = () => mobile;";
      if (path.endsWith("/components/ui/tabs.tsx")) return code.replace("<TabsPrimitive.Content", "<TabsPrimitive.Content forceMount");
      // Reveal closed portal content for presentation checks; interaction smoke remains separate.
      if (path.endsWith("/components/ui/dialog.tsx")) return ["Dialog", "DialogClose", "DialogContent", "DialogDescription", "DialogFooter", "DialogHeader", "DialogOverlay", "DialogPortal", "DialogTitle", "DialogTrigger"].map(name => `export const ${name} = ({children}) => children;`).join("\n");
      if (path.endsWith("/components/ui/popover.tsx")) return ["Popover", "PopoverTrigger", "PopoverContent", "PopoverAnchor", "PopoverHeader", "PopoverTitle", "PopoverDescription"].map(name => `export const ${name} = ({children}) => children;`).join("\n");
      if (locale === "pt-BR" && path.endsWith("/lib/i18n.tsx")) return code.replace('const serverLocale = ():Locale => "en-US";', 'const serverLocale = ():Locale => "pt-BR";');
    } }] });
    try {
      const { vampireConditionPresentation: present } = await vite.ssrLoadModule("/game-lines/vampire/condition-presentation.ts");
      const { vampireConditionsCatalogGroup } = await vite.ssrLoadModule("/game-lines/vampire/catalogs/conditions.ts");
      const { freezeCatalogData } = await vite.ssrLoadModule("/lib/catalog/catalog-service.ts");
      const requests = [];
      const catalog = freezeCatalogData(await vampireConditionsCatalogGroup.load({ getCatalog: async id => { requests.push(id); return conditions; } }));
      assert.deepEqual(requests, ["vampire-conditions"]);
      const { activeVampireItems } = await vite.ssrLoadModule("/game-lines/vampire/homebrew-catalog.ts");
      assert.equal(activeVampireItems(catalog, { disabledIds: ["h-vtr-strange-shades"] }).some(item => item.id === "vtr-strange-shades:scorned"), false);
      const base = localized[0], errata = { ...base, id: "homebrew:errata", errataFor: base.id, description: "Authored replacement stays.", presentationPt: undefined };
      const replacement = activeVampireItems([base, errata], { disabledIds: [] })[0];
      assert.equal(present(replacement, locale).description, errata.description, "An untranslated replacement never inherits obsolete PT");
      const authored = { ...base, id: "homebrew:authored", name: "Authored name", description: "Authored effect", presentationPt: undefined };
      assert.equal(present(authored, locale), authored);
      const { blankPrintCharacter } = await vite.ssrLoadModule("/app/workspace/blank-print-character.ts");
      const { VampireCharacterPaper } = await vite.ssrLoadModule("/game-lines/vampire/sheet-view.tsx");
      const { vampireHomebrew } = await vite.ssrLoadModule("/game-lines/vampire/homebrew.tsx");
      const { setTestMobile } = await vite.ssrLoadModule("/hooks/use-mobile.ts");
      const { LanguageProvider } = await vite.ssrLoadModule("/lib/i18n.tsx");
      const reference = Object.fromEntries(["clans", "covenants", "anchors", "blood-potency", "torpor", "bloodlines"].map(group => [group === "blood-potency" ? "bloodPotency" : group, read(`public/game-lines/vampire/data/${group}.json`)]));
      const catalogs = { get: id => ({ "vampire-powers": read("public/game-lines/vampire/data/powers.json"), "vampire-reference": reference, "core-merits": [], "vampire-merits": [], "core-reference": { conditions: read("public/shared/data/conditions.json"), presentation: read("public/shared/data/conditions-pt.json") }, "vampire-conditions": catalog })[id] };
      const character = blankPrintCharacter("VtR");
      character.line_data.clan_id = "daeva";
      character.line_data.humanity = 10;
      const powers = catalogs.get("vampire-powers");
      const dynasty = powers.coils.find(item => item.levels.some(level => level.ruleEffects?.some(effect => effect.rule === "embrace-humanity")));
      character.line_data.ordo_dracul = { ...character.line_data.ordo_dracul, coil_ratings: { [dynasty.id]: 5 } };
      const detachment = read("game-lines/vampire/catalog-data/detachment.json");
      const breakingPoints = [...detachment.tiers.flatMap(item => item.breakingPoints), detachment.vastDynastyEmbrace];
      character.line_data.banes = [breakingPoints[0], breakingPoints[40], detachment.vastDynastyEmbrace].map((point, index) => ({ id: `authored:${index}`, name: `Authored bane ${index}`, breaking_point_id: point.id, breaking_point_level: point.level }));
      character.current_state.conditions = localized.map(item => ({ id: item.errataFor ?? item.id, instanceId: `saved:${item.id}`, persistent: Boolean(item.persistent), notes: "Authored note" }));
      const saved = JSON.stringify(character);
      const noMutation = () => { throw new Error("Render mutated the saved character"); };
      const render = (Component, props) => renderToStaticMarkup(createElement(LanguageProvider, null, createElement(Component, props)));
      const homebrew = render(vampireHomebrew.Component, { catalogs });
      for (mobile of [false, true]) {
        setTestMobile(mobile);
        const sheet = render(VampireCharacterPaper, { character, updateState: noMutation, updateSheet: noMutation, catalogs });
        for (const point of breakingPoints) assert.ok(sheet.includes(`<span>${escape(locale === "pt-BR" ? point.labelPt : point.label)}</span>`), `${locale}/${mobile ? "mobile" : "desktop"}: Breaking Point menu ${point.id}`);
        for (const point of [breakingPoints[0], breakingPoints[40], detachment.vastDynastyEmbrace]) assert.ok(sheet.includes(`title="${escape(locale === "pt-BR" ? point.labelPt : point.label)}"`), "Linked Bane titles use the same localized label");
        const active = activeVampireItems(catalog, { disabledIds: [], enabledIds: enabledErrata });
        for (const errata of localized.filter(item => item.errataFor)) {
          assert.ok(active.some(item => item.id === errata.errataFor));
          assert.ok(!activeVampireItems(catalog, { disabledIds: [] }).some(item => item.id === errata.errataFor), "Optional errata remain disabled by default");
          assert.ok(!activeVampireItems(catalog, { disabledIds: [errata.sourceId], enabledIds: enabledErrata }).some(item => item.id === errata.errataFor), "Disabled sources hide optional errata");
        }
        for (const item of active.filter(item => item.presentationPt).map(item => present(item, locale))) {
          for (const field of ["name", "description", "resolution", ...(item.penalty ? ["penalty"] : []), ...(item.beat ? ["beat"] : [])])
            assert.ok(sheet.includes(escape(item[field])), `${locale}/${mobile ? "mobile" : "desktop"}: ${item.id}.${field}`);
          if (item.nameQualifier?.[locale]) assert.ok(sheet.includes(escape(`${item.name}(${item.nameQualifier[locale]})`)), "Homonymous Conditions retain their presentation-only line qualifier");
        }
        for (const item of localized.filter(item => item.homebrew).map(item => present(item, locale))) {
          for (const field of ["name", "description", "resolution", ...(item.penalty ? ["penalty"] : []), ...(item.beat ? ["beat"] : [])])
            assert.ok(homebrew.includes(escape(item[field])), `${locale}: Homebrew ${item.id}.${field}`);
        }
      }
      assert.equal(JSON.stringify(character), saved);
      assert.equal(JSON.stringify(conditions), before);
      assert.equal(Object.isFrozen(catalog[0].presentationPt), true);
    } finally { await vite.close(); }
  }
});
