import type { Locale } from "./i18n";
import { KITH_TEXT_EN } from "./changeling-kiths-en";
import { systemTerm } from "./system-terms";

export type KithDefinition = {
  id: string;
  name: string;
  translatedName?: string;
  skill: string;
  description: string;
  blessing: string;
  source: string;
  page: number;
  sourceId?: "h-seemings";
};

// Names and IDs stay stable for existing sheets; localization only changes presentation.
export const KITH_NAMES_PT: Record<string, string> = {
  Absinthial: "Absintial", Airtouched: "Tocado pelo Ar", Antiquarian: "Antiquário",
  Apoptosome: "Apoptossomo", Artist: "Artista", Asclepian: "Asclepiano",
  Bearskin: "Pele de Urso", Beastcaller: "Chamador de Feras", Becquerel: "Becquerel",
  Blightbent: "Corrompido", Bricoleur: "Artífice", Bridgeguard: "Guardião da Ponte",
  "Bright One": "Resplandecente", Chalomot: "Calomote", Chatelaine: "Castelão",
  Chevalier: "Cavaleiro", Chimera: "Quimera", Cleverquick: "Astuto",
  Climacteric: "Climatérico", Cloakskin: "Pele de Manto", Concubus: "Côncubo",
  Cyclopean: "Ciclópico", Delver: "Escavador", Doppelganger: "Sósia",
  Draconic: "Dracônico", Dryad: "Dríade", Enkrateia: "Autodomínio",
  Farwalker: "Andarilho Distante", Flowering: "Florescente", Flickerflash: "Relampejante",
  Ghostheart: "Coração Fantasma", Glimmerwisp: "Névoa Cintilante", Gravewight: "Espectro Tumular",
  Gremlin: "Gremlin", Gristlegrinder: "Triturador de Cartilagem", Helldiver: "Mergulhador Infernal",
  Hunterheart: "Coração de Caçador", Leechfinger: "Dedos de Sanguessuga", Lethipomp: "Condutor do Esquecimento",
  Levinquick: "Veloz como o Raio", Librorum: "Guardião dos Livros", Liminal: "Liminar",
  Lullescent: "Sussurrante", Manikin: "Manequim", Mirrorskin: "Pele de Espelho",
  Moonborn: "Nascido da Lua", Muse: "Musa", Nightsinger: "Cantor Noturno",
  Notary: "Tabelião", Nymph: "Ninfa", Oculus: "Óculo", Playmate: "Companheiro de Brincadeiras",
  Plaguesmith: "Forjador de Pragas", Polychromatic: "Policromático", Razorhand: "Mão de Navalha",
  Reborn: "Renascido", Riddleseeker: "Buscador de Enigmas", Sandharrowed: "Flagelado pela Areia",
  Shadowsoul: "Alma Sombria", Sideromancer: "Sideromante", Snowskin: "Pele de Neve",
  Spiegelbild: "Reflexo", Stoneflesh: "Carne de Pedra", Swarmflight: "Voo de Enxame",
  Swimmerskin: "Pele de Nadador", Telluric: "Telúrico", Uttervoice: "Voz Absoluta",
  Valkyrie: "Valquíria", Veneficus: "Venéfico", Venombite: "Mordida Venenosa",
  Whisperwisp: "Sussurro Fugaz", Wisewitch: "Bruxo Sábio", Witchtooth: "Dente de Bruxa",
  Bloodbrute: "Brutamontes Sangrento", Chirurgeon: "Cirurgião",
  Dancer: "Dançarino", Drudge: "Serviçal", Echoveil: "Véu de Ecos", Fireheart: "Coração de Fogo",
  Gargantuan: "Gargantuesco", Palewraith: "Espectro Pálido", Treasured: "Tesouro",
  Truefriend: "Amigo Verdadeiro", Woodblood: "Sangue de Madeira",
};

const kith = (name:string, skill:string, description:string, blessing:string, source:string, page:number):KithDefinition => ({
  id: name.toLocaleLowerCase("en-US").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""), name, translatedName: KITH_NAMES_PT[name] ?? name, skill, description, blessing, source, page,
});

export const KITHS: KithDefinition[] = [
  kith("Absinthial","Ofícios","Fadas verdes que destilam as bebidas oníricas de Arcádia.","3 sucessos contam como excepcionais em Ofícios para preparar consumíveis com ingredientes feéricos. Uma vez por cena, gaste 1 Glamour, toque o alvo e teste Presença + Ofícios contra Compostura + Fado: imponha Insensato e, quando terminar, Confuso. Não afeta Fae Verdadeiros nem Caçadores.","Kith & Kin",88),
  kith("Airtouched","Atletismo","Changelings que viveram nos céus de Arcádia, afastados do restante do mundo.","3 sucessos contam como excepcionais em Atletismo para escalar, saltar ou mover-se verticalmente. Gaste 1 Glamour para andar sobre água, neve e superfícies frágeis como se quase não pesasse; rastreá-lo pelas pegadas sofre penalidade igual à metade do Fado, arredondada para baixo, mínimo 1.","Kith & Kin",107),
  kith("Antiquarian","Empatia","Guardiões de segredos e repositórios vivos de conhecimento.","3 sucessos contam como excepcionais em Empatia para descobrir segredos. Uma vez por sessão, gaste 1 Glamour e teste Inteligência + Compostura para obter uma resposta; o Narrador determina os sucessos necessários e como a informação chega.","DE:CtL",23),
  kith("Apoptosome","Diversas","Perdidos que, isolados, foram obrigados a lutar e morrer repetidamente.","Lembra perfeitamente as lutas que perdeu e recebe +1 em um teste por cena contra o mesmo adversário, em disputas físicas ou mentais. Gaste 1 Glamour para causar 1 dano agravado a alguém que já o feriu. Pelo restante da cena, cada novo ferimento causado por esse inimigo inflige também 1 dano agravado a ambos.","Kith & Kin",116),
  kith("Artist","Ofícios ou Expressão","Criadores cujos corpos se fundiram aos materiais de sua arte.","Escolha Ofícios ou Expressão: 3 sucessos contam como excepcionais ao usar uma Especialização artística dessa Perícia. Gaste 1 Glamour para manifestar as ferramentas por uma cena e receber bônus igual ao Fado, máximo +5, em um teste de criação artística com uma de suas Especializações.","Changeling the Lost",51),
  kith("Asclepian","Medicina","Curandeiros que realizam seu trabalho com materiais improvisados.","3 sucessos contam como excepcionais em Medicina para primeiros socorros. Seu toque estabiliza ferimentos. Com 1 Glamour e Inteligência + Medicina, realiza cirurgia improvisada, tratando até lesões normalmente incuráveis ou morte ocorrida na última cena. Enxertos são permanentes e podem resolver Condições Físicas Persistentes; somente em changelings ficam ocultos pela Máscara.","Kith & Kin",103),
  kith("Bearskin","Intimidação ou Armas Brancas","Soldados de Arcádia dedicados às causas que consideram importantes.","Escolha Intimidação ou Armas Brancas: 3 sucessos contam como excepcionais ao defender uma Aspiração de um companheiro de grupo. Após obter rendição, intimidação ou coerção bem-sucedida, gaste 1 Glamour para substituir uma Aspiração do alvo por uma sua até o fim da história; se não for cumprida, a original retorna.","Kith & Kin",111),
  kith("Beastcaller","Empatia com Animais","Perdidos ligados às feras goblin.","3 sucessos contam como excepcionais em Empatia com Animais para domar feras goblins. Com 1 Glamour e Presença + Empatia com Animais + Fado, possui uma fera por Fado turnos. Cada dano letal nela causa 1 contundente em você; cada agravado causa 1 letal. Se ela morrer ou perder a consciência, você retorna ao próprio corpo e sofre mais 1 agravado.","Kith & Kin",112),
  kith("Becquerel","Furtividade","Perdidos radioativos.","3 sucessos contam como excepcionais em Furtividade na penumbra. Após agarrar com sucesso, gaste 1 Glamour para queimar o alvo como fogo do tamanho de uma tocha e calor de vela. A cada turno mantendo o agarrão, pode impor Atordoado ou Envenenado. Não queima objetos inertes.","Kith & Kin",117),
  kith("Blightbent","Doença ou Veneno","Perdidos permanentemente maculados por venenos e poluição.","Ao testar Vigor + Perseverança contra doenças ou venenos, reduz dano agravado a letal, letal a contundente ou ignora contundente. Após agarrar com sucesso, gaste 1 Glamour para impor a Inclinação Envenenado.","Kith & Kin",117),
  kith("Bricoleur","Ofícios ou Expressão","Manipuladores engenhosos de símbolos e conexões.","Escolha uma Especialização de Ofícios ou Expressão: 3 sucessos contam como excepcionais ao usá-la. Com 1 Glamour, Raciocínio + Persuasão e um objeto simbolicamente adequado, altera uma verdade sobre si por Fado dias; os demais acreditam nela. A mesma alteração ocorre permanentemente no simulacro.","Kith & Kin",98),
  kith("Bridgeguard","Intimidação","Changelings que enfrentam adversidades aparentemente insuperáveis e se destacam quando estão em desvantagem numérica.","3 sucessos contam como excepcionais em Intimidação contra vários alvos. Em desvantagem numérica, gaste 1 Glamour e teste Compostura + Intimidação: some os sucessos à Defesa e deixe de reduzi-la ao aplicá-la contra ataques.","Kith & Kin",104),
  kith("Bright One","Socialização","Seres radiantes e luminosos, acesos pela chama interior de suas paixões.","3 sucessos contam como excepcionais em Socialização para ser o centro das atenções. Emite um brilho normalmente oculto pela Máscara. Por 1 Glamour a cada turno, intensifica-o: inimigos que o veem sofrem 1 dano contundente e −2 nas ações Físicas e Mentais naquele turno.","Changeling the Lost",52),
  kith("Chalomot","Empatia","Batedores dos Fae Verdadeiros nas Estradas dos Sonhos, especializados em invadir Bastiões.","3 sucessos contam como excepcionais em Empatia para avaliar a força de um Bastião. Gaste 1 Glamour para receber bônus à tecelagem onírica igual à metade do Fado, arredondada para baixo, mínimo 1, pela cena. Cada Glamour adicional estende o benefício a outro oniromante no Bastião, até cinco.","Kith & Kin",107),
  kith("Chatelaine","Empatia","Perdidos submetidos a um treinamento interminável em etiqueta e serviço doméstico.","3 sucessos contam como excepcionais em Empatia para identificar desejos imediatos. Com 1 Glamour e Manipulação + Socialização, usa por uma cena os Méritos Sociais de outra pessoa presente. Depois, os envolvidos agem como se o proprietário dos Méritos os tivesse usado.","Changeling the Lost",52),
  kith("Chevalier","Persuasão ou Intimidação","Changelings ligados à própria montaria, seja ela um animal ou um veículo.","Escolha Persuasão ou Intimidação: 3 sucessos contam como excepcionais ao usá-la enquanto conduz sua montaria ou veículo. Gaste 1 Glamour para designar um Nobre Corcel; outro ponto o chama reflexivamente. Ele tenta chegar por meios normais, sem teleporte, e seres conscientes podem recusar. Só pode manter um por vez; perigo ao cavaleiro pode disparar o chamado gratuitamente.","Kith & Kin",107),
  kith("Chimera","Subterfúgio","Changelings animalescos costurados com partes de muitas feras de Arcádia.","3 sucessos contam como excepcionais em Subterfúgio para detectar trapaças faladas ou escritas. A cada capítulo, escolha um Contrato Goblin conhecido que não gerará Débito Goblin. Deve alternar entre os Contratos, sem repetir até que todos tenham recebido o benefício.","DE:CtL",23),
  kith("Cleverquick","Ocultismo","Trapaceiros que aperfeiçoaram a astúcia e a intriga durante o cativeiro em Arcádia.","3 sucessos contam como excepcionais em Ocultismo para superar um inimigo pela astúcia. Gaste 1 Glamour para descobrir uma Fragilidade, Perdição ou Interdição do alvo. Por 3 Glamour, imponha uma temporária por um capítulo, aceitando-a também. Dois Astutos podem dividir o custo e ambos recebem o efeito e a desvantagem.","DE:CtL",222),
  kith("Climacteric","Investigação","Perdidos que se tornaram relógios climáticos e meteorologistas, aprisionando o tempo nos elementos.","3 sucessos contam como excepcionais em Investigação para identificar padrões. Quando alguém rolar Iniciativa, gaste 1 Glamour para escolher outro personagem que agirá primeiro, sem teste. Não pode escolher a si mesmo.","Kith & Kin",88),
  kith("Cloakskin","Social","Perdidos solitários cuja Máscara é invisível.","Recebe +1 em todos os testes Sociais. Com 1 Glamour e Presença + Furtividade + Fado, torna a Aparência feérica invisível por uma cena, inclusive para câmeras. Testes visuais para detectá-lo falham; testes com outros sentidos sofrem −3.","Kith & Kin",98),
  kith("Concubus","Empatia","Companheiros noturnos e tecelões de sonhos que cuidavam das mentes dos Outros.","3 sucessos contam como excepcionais em Empatia para invadir um Bastião. Após dormir seis horas junto ao alvo e obter Agressor dos Sonhos, pode remover uma Condição mental ou psicossomática não Persistente com uma mudança de paradigma de três sucessos. Condições Persistentes exigem três períodos consecutivos de seis horas, Intruso dos Sonhos e alterações sutis e de paradigma.","Kith & Kin",89),
  kith("Cyclopean","Investigação","Perdidos transformados em gigantes ou estruturas magníficas, muitas vezes marcados por deficiência.","3 sucessos contam como excepcionais em Investigação para rastrear seres feéricos, exceto Caçadores. Uma vez por cena, gaste 1 Glamour para reduzir em 2 as penalidades de ataques localizados, até o mínimo de −1; esses ataques causam dano letal em vez de contundente.","Kith & Kin",112),
  kith("Delver","Investigação","Mineradores de coisas preciosas.","3 sucessos contam como excepcionais em Investigação para encontrar algo perdido ou oculto. Gaste 1 Glamour para enviar uma mensagem cifrada pelo solo a qualquer número de destinatários a até Fado milhas. Para decifrar uma mensagem terrestre interceptada, gaste 1 Glamour e teste Investigação.","Kith & Kin",93),
  kith("Doppelganger","Empatia","Ladrões de traços familiares.","3 sucessos contam como excepcionais em Empatia para conquistar confiança. Gaste 1 Glamour e teste Presença + Empatia + Fado contra Perseverança + Fado para incorporar à Máscara um traço físico ou vocal do alvo. Ele perde o traço por Fado dias; deve receber uma tarefa que permita recuperá-lo antes.","Kith & Kin",99),
  kith("Draconic","Briga ou Armas Brancas","Changelings transformados em grandiosas feras guardiãs.","Escolha Briga ou Armas Brancas: 3 sucessos contam como excepcionais ao defender algo ou alguém importante. Ao despir a Máscara, gaste mais 1 Glamour para amedrontar todos os oponentes que percebam sua demonstração de poder. Também pode gastar 1 Glamour reflexivamente para voar a Deslocamento 60 por Fado turnos; uma investida aérea recebe +2.","Kith & Kin",90),
  kith("Dryad","Sobrevivência","Perdidos que passaram o cativeiro em Arcádia como criaturas de jardins e da vegetação.","3 sucessos contam como excepcionais em Sobrevivência em áreas arborizadas, inclusive na Sebe. Após um turno sem ser observado, gaste 1 Glamour para esconder-se atrás de vegetação grande. Fica perfeitamente oculto enquanto imóvel; movendo-se, soma Fado à Furtividade. Detecção sobrenatural exige Confronto de Vontades.","DE:CtL",24),
  kith("Enkrateia","Empatia, Persuasão ou Subterfúgio","Conselheiros e mediadores de Arcádia que serviam como a voz da razão para seus Guardiões.","Ao tentar acalmar um conflito, usa a maior entre Empatia, Persuasão e Subterfúgio. Em ações prolongadas de Investigação, a perda de dados só começa depois do terceiro teste consecutivo.","Kith & Kin",118),
  kith("Farwalker","Sobrevivência","Patrulheiros do ermo, perfeitamente à vontade na natureza.","3 sucessos contam como excepcionais em Sobrevivência para obter abrigo, comida ou água. Com 1 Glamour, cria por um dia um Local Seguro 1 no ermo, ou usa o nível do seu Local Seguro existente. Abriga metade do Fado em pessoas, arredondada para baixo, mínimo 1; cada Glamour extra abriga mais uma. Na Sebe, reduz em um grau a hostilidade da área e pode copiar uma característica de seu Refúgio.","Kith & Kin",108),
  kith("Flowering","Socialização","Perdidos que viveram entre a flora de Arcádia e assimilaram seu fascínio passivo.","3 sucessos contam como excepcionais em Socialização para convencer alguém de que precisa de você. Com 1 Glamour e Presença + Empatia, emite um perfume pela cena; presentes e recém-chegados resistem com Compostura + Fado. Quem falhar fica Coagido. Mais 1 Glamour impõe Amedrontado, Imprudente ou Enamorado a um alvo Coagido; não pode encerrar o perfume antes do fim.","Kith & Kin",90),
  kith("Flickerflash","Atletismo","Perdidos feitos para correr a velocidades extraordinárias.","3 sucessos contam como excepcionais em Atletismo durante perseguições. Gaste 1 Glamour reflexivamente para triplicar o Deslocamento antes de aplicar quaisquer outros modificadores.","Kith & Kin",110),
  kith("Ghostheart","Percepção","Psicopompos e coveiros enviados para cuidar dos mortos.","3 sucessos contam como excepcionais em Raciocínio + Compostura para perceber fantasmas manifestados ou entidades do Crepúsculo. Começa com três pontos extras de Aliados fantasmas, distribuídos entre um ou mais aliados. Cada um recebe um Numen escolhido, exceto Drenar Lucidez, Aprisionar e Chamado do Guardião.","Kith & Kin",91),
  kith("Glimmerwisp","Persuasão","Perdidos transformados em névoas de Faerie para encobrir atos vergonhosos e monstruosos.","3 sucessos contam como excepcionais em Persuasão para desviar a atenção de algo terrível ou maravilhoso. Com 1 Glamour e Manipulação + Persuasão + Fado, cria névoa por uma cena em um cômodo ou área de até dez metros. Quem falhar em Perseverança + Compostura deixa de ver atos vergonhosos ou causadores de pontos de ruptura cometidos por outros na névoa.","Kith & Kin",94),
  kith("Gravewight","Empatia ou Intimidação","Perdidos ligados à morte.","Escolha Empatia ou Intimidação: 3 sucessos contam como excepcionais ao influenciar alguém com sua Aparência feérica, presença física ou conhecimento da morte. Gaste 1 Glamour para ver e ouvir fantasmas no Crepúsculo; sua presença também facilita manifestações próximas.","Kith & Kin",119),
  kith("Gremlin","Ofícios","Perfeccionistas que destroem impulsivamente criações defeituosas.","3 sucessos contam como excepcionais em Ofícios para reparar objetos quebrados ou defeituosos. Uma vez por cena, gaste 1 Glamour para transformar uma ação prolongada em instantânea, desde que ela envolva desmontar ou destruir algo.","Kith & Kin",94),
  kith("Gristlegrinder","Briga","Monstros consumidos pela fome e assombrados pelo gosto de carne.","3 sucessos contam como excepcionais em Briga para agarrar alguém com intenção de devorá-lo. Mordidas causam dano letal sem agarrar. Segurando um alvo menor, gaste 1 Glamour e teste Vigor + Sobrevivência para engoli-lo: causa 2 danos letais por turno. Para escapar, a vítima deve causar 5 danos letais em um único ataque interno, contra o qual não há Defesa nem armadura.","Changeling the Lost",53),
  kith("Helldiver","Furto","Espiões e exploradores presos a Faerie por um cordão de prata.","3 sucessos contam como excepcionais em Furto em reinos sobrenaturais. Com 1 Glamour e Destreza + Ocultismo, torna-se incorpóreo e invisível em 10 − Lucidez atual turnos, mínimo 1. Interage com seres imateriais e pode atravessar portais de outros reinos por 1 Glamour. Retornar exige novo gasto e teste; durante a transição, só age reflexivamente.","Changeling the Lost",53),
  kith("Hunterheart","Investigação ou Sobrevivência","Caçadores que escaparam de um cativeiro em Arcádia marcado pela predação sangrenta.","Escolha Investigação ou Sobrevivência: 3 sucessos contam como excepcionais ao rastrear criaturas de Faerie. Se o alvo vir seus olhos, gaste 1 Glamour e teste Presença + Fado contra Compostura + Tolerância Sobrenatural. O jogador do alvo escolhe entre Insensato e Amedrontado; seus ataques desarmados contra a vítima afetada causam dano letal.","Changeling the Lost",54),
  kith("Leechfinger","Medicina","Parasitas secretos que drenam a força vital alheia.","3 sucessos contam como excepcionais em Medicina para avaliar a saúde de uma possível vítima. Após um turno de contato, gaste 1 Glamour para causar 1 dano contundente e reduzir em um grau um ferimento próprio. Pode repetir a cada turno de contato. Contra changelings, causa 2 danos e reduz dois ferimentos por ponto de Glamour.","Changeling the Lost",55),
  kith("Lethipomp","Empatia","Coletores de lembranças dolorosas, desprovidos de emoção.","3 sucessos contam como excepcionais em Empatia para adivinhar segredos. Com 1 Glamour e um teste disputado de Compostura + Empatia + Fado, absorve a emoção de uma memória conhecida. O alvo fica Letárgico por 24 horas; você recebe uma Condição correspondente por 12 horas e pode incitar Desvario para fazer outros reviverem a memória. A fonte não especifica a parada de resistência.","Kith & Kin",99),
  kith("Levinquick","Computação","Batedores e mensageiros inquietos de paisagens digitais.","3 sucessos contam como excepcionais em Computação durante perseguições na BriarNet. Toque um aparelho de telecomunicação ligado à rede terrestre, gaste 3 Glamour e teste Raciocínio + Atletismo + Fado para surgir em outro aparelho conhecido a até Fado milhas. Leva apenas o que cabe nos bolsos e mãos; acompanhantes custam +1 Glamour cada, e levar alguém à força exige Confronto de Vontades.","Kith & Kin",110),
  kith("Librorum","Intimidação","Defensores de bibliotecas e do conhecimento.","3 sucessos contam como excepcionais em Intimidação para obter ou proteger conhecimento. Uma vez por capítulo, gaste 1 Glamour e teste Inteligência + Ocultismo + Fado após breve meditação. Distribua os sucessos entre Biblioteca, Idioma ou um repositório de informações.","Kith & Kin",104),
  kith("Liminal","Sobrevivência ou Manha","Defensores de limiares.","3 sucessos contam como excepcionais em Sobrevivência ou Manha para navegar. Em um limiar, declare uma exigência, gaste 1 Glamour e teste Perseverança + Intimidação + Fado contra Compostura + Fado. Quem falhar e atravessar sem cumprir a exigência fica Perdido; a passagem não é bloqueada fisicamente.","Kith & Kin",105),
  kith("Lullescent","Furtividade","Ouvintes silenciosos de audição extraordinária.","3 sucessos contam como excepcionais em Furtividade para escutar escondido. Gaste 1 Glamour para usar ecolocalização. Raciocínio + Ocultismo + Fado também revela seres ou objetos ocultos por magia, exigindo Confronto de Vontades se quem os ocultou ainda estiver vivo.","Kith & Kin",100),
  kith("Manikin","Socialização","Perdidos transformados em telas vivas para a arte dos Fae Verdadeiros.","3 sucessos contam como excepcionais em Socialização para se integrar a uma situação. Com 1 Glamour e Presença + Ofícios, oculta defeitos de um objeto pela cena e recebe bônus Social igual aos sucessos, máximo +5. Usar o objeto para melhorar uma impressão a eleva um passo adicional; a qualidade física não muda.","Kith & Kin",95),
  kith("Mirrorskin","Furtividade","Perdidos que aprenderam a esvaziar a própria natureza e tornar-se qualquer pessoa ou ninguém.","3 sucessos contam como excepcionais em Furtividade enquanto disfarçado. Com 1 Glamour e Raciocínio + Subterfúgio + Fado reflexivo, remodela a Máscara; +1 Glamour também remodela a Aparência feérica. O efeito é indefinido, exige nova ativação para desfazê-lo e provoca Confronto de Vontades contra detecção sobrenatural.","Changeling the Lost",55),
  kith("Moonborn","Empatia ou Intimidação","Perdidos instigados a paixões selvagens para divertir seus Guardiões.","Escolha Empatia ou Intimidação: 3 sucessos contam como excepcionais para alterar emoções. Uma vez por capítulo, gaste 1 Glamour e teste Manipulação + Expressão contra Compostura + Fado de até Fado alvos. Quem falhar recebe Competitivo, Amedrontado, Imprudente, Letárgico ou Devasso, à sua escolha.","Kith & Kin",92),
  kith("Muse","Manto","Changelings cuja influência se manifesta por sua beleza.","Uma vez por sessão, interaja com outros Perdidos como se seu Manto ou Boa Vontade da Corte fosse um ponto maior. Com 1 Glamour e um teste Social, inspire um humano: os sucessos viram dados extras para criar uma obra duradoura, e três sucessos contam como excepcionais. Não pode colher Glamour dessa criação.","DE:CtL",24),
  kith("Nightsinger","Expressão","Sereias e vocalistas cujas canções moviam a própria terra de Faerie.","3 sucessos contam como excepcionais em Expressão para cantar ou compor. Com 1 Glamour, teste Presença + Expressão + Fado contra Compostura + Tolerância Sobrenatural de quem ouvir. Quem falhar fica Enamorado e imóvel enquanto a canção continuar, mas conserva Defesa. Pode ser conduzido pela mão; interromper a audição, vencer um poder oposto ou causar dano igual ao Vigor quebra o transe.","Changeling the Lost",56),
  kith("Notary","Política","Humanos usados como documentos vivos para os juramentos dos Fae Verdadeiros.","3 sucessos contam como excepcionais em Política para negociar, ler ou interpretar promessas feéricas. Uma vez por capítulo, anula o custo de Glamour de uma promessa de cuja criação participe, sem teste. Pode recitar perfeitamente seus termos enquanto ela durar.","Changeling the Lost",57),
  kith("Nymph","Atletismo","Changelings que habitavam os oceanos e cursos d’água de Faerie.","3 sucessos contam como excepcionais em Atletismo ao nadar. Com 1 Glamour e Vigor + Atletismo, desenvolve guelras e cauda pela cena: respira ar e água, dobra o Deslocamento aquático e ignora penalidades para usar armas ou realizar tarefas submerso.","DE:CtL",24),
  kith("Oculus","Persuasão","Diplomatas e negociadores capazes de fazer outros enxergarem sua perspectiva.","3 sucessos contam como excepcionais em Persuasão para fazer alguém considerar seu ponto de vista. Com 1 Glamour e Presença + Persuasão + Fado contra Perseverança + Fado, oculta do alvo todos os caminhos físicos exceto aquele que deseja que ele siga.","Kith & Kin",95),
  kith("Playmate","Persuasão","Amigos, bichos de estimação e brinquedos que sobreviviam por amor e confiança.","3 sucessos contam como excepcionais em Persuasão para fazer alguém gostar de você ou de seus amigos. Toque um ferido e gaste 1 Glamour para curar dano contundente ou letal, recebendo respectivamente dano leve ou grave de Lucidez. Aplique o leve primeiro; não pode curar além das caixas de Lucidez disponíveis.","Changeling the Lost",57),
  kith("Plaguesmith","Medicina","Perdidos moldados como armas biológicas.","3 sucessos contam como excepcionais em Medicina para tratar doenças infecciosas. Com toque, 1 Glamour e Força + Medicina + Fado contra Vigor + Fado, infecta o alvo com doença grave: 1 dano agravado a cada 12 horas. Interromper a progressão exige um número de testes de resistência bem-sucedidos igual ao Fado; depois, o dano se cura normalmente.","Kith & Kin",113),
  kith("Polychromatic","Empatia","Perdidos coloridos e chamativos, hábeis em agitar e acalmar emoções.","3 sucessos contam como excepcionais em Empatia para acalmar nervosismo ou raiva. Uma vez por capítulo, gaste 1 Glamour: os demais presentes gastam 1 Força de Vontade ou ficam Enamorados. Os afetados também sofrem −2 para resistir à sua Empatia pelo restante da cena.","Kith & Kin",96),
  kith("Razorhand","Briga","Perdidos cujas mãos foram substituídas ou equipadas com lâminas.","3 sucessos contam como excepcionais ao atacar com suas mãos-lâmina. Por 1 Glamour, transforma uma mão em faca 1L pela cena; outro ponto transforma a segunda. Usa Briga e estilos desarmados, mantém penalidades da mão inábil e só pode ser desarmado se perder o membro.","Kith & Kin",114),
  kith("Reborn","Ocultismo","Changelings mortos e trazidos de volta repetidamente.","3 sucessos contam como excepcionais em Ocultismo para distinguir fatos de falsidades. Após sofrer 1 dano letal, gaste 1 Glamour e teste Inteligência + Ocultismo: transfira pontos iguais aos sucessos de uma Perícia para outra pela cena, respeitando o limite do Fado. Uma vez por capítulo, perder um ponto permanente de Força de Vontade torna a redistribuição permanente.","Kith & Kin",105),
  kith("Riddleseeker","Investigação","Mestres de enigmas.","3 sucessos contam como excepcionais em Investigação para resolver enigmas. Com 1 Glamour e Raciocínio + Expressão + Fado, propõe resolver um conflito por enigma. Se o alvo não acertar em três tentativas, deve deixá-lo ir até o fim da cena. Se a mesa resolver por dados, o alvo disputa com Raciocínio + Investigação.","Kith & Kin",100),
  kith("Sandharrowed","Sobrevivência","Perdidos que sobreviveram aos desertos de Arcádia.","3 sucessos contam como excepcionais em Sobrevivência para atravessar uma área com Inclinação Ambiental. Uma vez por cena, antes de atacar com Briga ou Armas Brancas, gaste 1 Glamour. Se acertar, o alvo fica Imobilizado em uma coluna de areia com Durabilidade 2, que também concede cobertura à própria vítima.","Kith & Kin",115),
  kith("Shadowsoul","Subterfúgio","Perdidos ligados às estrelas e à noite.","Soma Fado a testes mundanos de Subterfúgio e recebe 8-novamente neles. Possui afinidade adicional com Espelho. Uma vez por cena, após um sucesso excepcional em um ataque, pode impor Cegueira temporária a alguém que tocar, até o fim da cena.","Kith & Kin",119),
  kith("Sideromancer","Ocultismo","Adivinhos do Fado.","3 sucessos contam como excepcionais em Ocultismo com Especialização em adivinhação. Após cinco minutos, gaste 1 Glamour e teste Raciocínio + Ocultismo + Fado: faça uma pergunta de sim ou não por sucesso sobre uma promessa, dívida ou pagamento de que participe, antes de ocorrer na mesma cena. Prever além disso causa falha dramática automática.","Kith & Kin",101),
  kith("Snowskin","Subterfúgio","Aqueles que escaparam de Faerie apagando o próprio calor e congelando-se.","3 sucessos contam como excepcionais em Subterfúgio para ocultar emoções. Ao humilhar alguém diante de uma plateia, gaste 1 Glamour e teste Presença + Intimidação + Fado contra Compostura + Tolerância Sobrenatural. O alvo fica Abalado e sofre −2 nos testes Sociais com outros changelings até resolver a Condição.","Changeling the Lost",58),
  kith("Spiegelbild","Persuasão","Conselheiros que habitam espelhos.","3 sucessos contam como excepcionais em Persuasão para evitar fazer uma promessa. Com 1 Glamour e Raciocínio + Compostura, entra no espaço dos espelhos, podendo ver e ouvir o outro lado. Seu rosto aparece e deve responder com a verdade. Ocultar-se exige Manipulação + Furtividade + Fado contra Raciocínio + Compostura; isso não libera da obrigação se sua presença for conhecida.","Kith & Kin",102),
  kith("Stoneflesh","Intimidação","Changelings resistentes, de pele endurecida e determinação inabalável.","3 sucessos contam como excepcionais em Intimidação com sua presença física. Gaste 1 Glamour e teste Vigor + Atletismo + Fado: distribua os sucessos entre Armadura, Perseverança e Compostura pela cena.","Kith & Kin",106),
  kith("Swarmflight","Furtividade","Perdidos capazes de dissolver-se em um enxame de animais, objetos ou fenômenos.","3 sucessos contam como excepcionais em Furtividade na forma de enxame. Por 1 Glamour, assume um enxame escolhido na criação, de criaturas ou objetos de Tamanho 0–1, cobrindo até Fado × 5 metros e impondo Distraído aos presentes. Ataques individuais causam no máximo 1 dano, ou 2 com sucesso excepcional; ferro, fogo e ataques de área causam dano normal. Enxames apropriados atacam com Força + Briga, ignorando Defesa e dividindo o dano letal entre vítimas. Não usa Contratos que exijam fala, gestos ou contato visual.","Kith & Kin",110),
  kith("Swimmerskin","Briga","Sereias e seus semelhantes.","3 sucessos contam como excepcionais em Briga para agarrar na água ou emboscar a partir dela. Respira ar e água naturalmente. Gaste 1 Glamour para assumir uma cauda, dobrar o Deslocamento aquático e ignorar penalidades em tarefas submersas; pode desfazer a transformação reflexivamente.","Kith & Kin",111),
  kith("Telluric","Condução ou Manha","Perdidos que se tornaram corpos celestes e estrelas nos céus de Arcádia.","3 sucessos contam como excepcionais em Condução ou Manha durante perseguições sob um céu noturno estrelado e visível. Gaste 1 Glamour para arremessar fogo estelar com Destreza + Atletismo, como uma chama do tamanho de uma tocha e calor de vela.","Kith & Kin",120),
  kith("Uttervoice","Intimidação","Changelings cuja frustração afiou a voz como uma lâmina.","3 sucessos contam como excepcionais em Intimidação usando a voz. Por 1 Glamour, teste Presença + Fado contra Compostura + Fado de todos que ouvirem, inclusive aliados. Quem falhar sofre 1 dano contundente, ou letal com sucesso excepcional. O grito quebra vidro e ignora Durabilidade inferior a 2. Também se ativa acidentalmente quando um teste de Presença se beneficia de 10-novamente.","Kith & Kin",92),
  kith("Valkyrie","Persuasão ou Intimidação","Perdidos obrigados a decidir quem vive ou morre nos campos de batalha de Arcádia.","Escolha Persuasão ou Intimidação: 3 sucessos contam como excepcionais para inspirar aliados ou intimidar inimigos no campo de batalha. Até metade do Fado vezes por cena, arredondada para baixo, gaste 1 Glamour e teste Raciocínio + Ocultismo + Fado contra Perseverança + Fado. Concede Inspirado ou Resoluto, ou impõe Amedrontado ou Imprudente. Aliados podem dispensar a resistência.","Kith & Kin",115),
  kith("Veneficus","Sobrevivência","Herbalistas e cozinheiros de Faerie.","3 sucessos contam como excepcionais em Sobrevivência para identificar frutas goblins. Gaste 1 Glamour reflexivamente para tornar comestível uma planta tóxica ou tornar tóxica uma planta comestível.","Kith & Kin",97),
  kith("Venombite","Briga","Perdidos que se tornaram venenosos, consumidos por ressentimentos mesquinhos.","3 sucessos contam como excepcionais em Briga para agarrar. Uma vez por cena, gaste 1 Glamour antes de atacar com Briga: se acertar, causa dano letal e impõe a versão grave da Inclinação Envenenado.","Kith & Kin",116),
  kith("Whisperwisp","Mentiras","Espiões e sabotadores.","3 sucessos contam como excepcionais ao influenciar alguém com uma falsidade conhecida; com a verdade, o limiar continua sendo cinco. Escolha Furtividade ou Persuasão na criação: testes mundanos da Perícia escolhida somam Fado e recebem 9-novamente.","Kith & Kin",120),
  kith("Wisewitch","Persuasão","Changelings permanentemente tocados pelo Título de um Guardião.","3 sucessos contam como excepcionais em Persuasão para alertar alguém sobre perigo sobrenatural. Pode firmar promessas com espíritos e anjos não feéricos.","Kith & Kin",106),
  kith("Witchtooth","Intimidação","Bruxos reclusos que conhecem o poder da terra.","3 sucessos contam como excepcionais em Intimidação contra mortais. Com 1 Glamour e Perseverança + Intimidação, altera a aparência de uma área de uma milha quadrada por Fado turnos, impondo −1 aos testes de Sobrevivência.","Kith & Kin",97),
  {...kith("Bloodbrute","Atletismo ou Intimidação","Combatentes moldados para amar a violência.","Após sofrer dano na cena, 3 sucessos contam como excepcionais em Atletismo ou Intimidação. Uma vez por cena, gaste 1 Glamour e teste Presença + Briga, Armas de Fogo ou Armas Brancas reflexivamente. Receba Fado como bônus aos ataques com a Perícia e como armadura geral contra ela pela cena; ambos terminam se um turno acabar sem realizar nem sofrer um ataque bem-sucedido.","Book of Seemings",35),sourceId:"h-seemings"},
  {...kith("Chimera","Empatia com Animais ou Socialização","Perdidos adaptáveis formados por partes díspares.","Ao interagir pela primeira vez com um animal ou humano usando Empatia com Animais ou Socialização, 3 sucessos contam como excepcionais. Gaste 1 Glamour e escolha Perícias Mentais, Físicas ou Sociais; redistribua os pontos da categoria, sem elevar nenhuma acima de 5, pela cena. Use até Fado vezes ao dia, no máximo uma vez por cena.","Book of Seemings",36),id:"chimera-book-of-seemings",sourceId:"h-seemings"},
  {...kith("Chirurgeon","Medicina","Especialistas feéricos em remodelar corpos.","3 sucessos contam como excepcionais em Medicina para cirurgia. Toque um alvo imóvel, gaste um ou mais Glamour e teste Destreza + Medicina, disputado por Vigor + Tolerância Sobrenatural se relutante. Remodela aparência dentro da anatomia humana ou changeling e concede 8-novamente em duas Perícias Físicas ou Sociais influenciadas pela aparência por uma cena por Glamour. Não pode usar em si.","Book of Seemings",37),sourceId:"h-seemings"},
  {...kith("Dancer","Expressão","Artistas feéricos definidos pela graça e pelo movimento.","3 sucessos contam como excepcionais em Expressão para apresentações físicas. Use Expressão no lugar de Atletismo em ações de graça, equilíbrio ou flexibilidade. Gaste 1 Glamour para usar Expressão no lugar de Atletismo no cálculo da Defesa durante cenas violentas; Esquivar triplica a Defesa enquanto ativo.","Book of Seemings",38),sourceId:"h-seemings"},
  {...kith("Drudge","Furtividade","Serviçais discretos aperfeiçoados para o trabalho doméstico.","3 sucessos contam como excepcionais em Furtividade em ambiente doméstico. Gaste 1 Glamour para transformar uma ação prolongada em instantânea quando consistir em tarefas domésticas, mesmo fora de casa, a critério do Narrador.","Book of Seemings",38),sourceId:"h-seemings"},
  {...kith("Echoveil","Expressão","Músicos sombrios usados como atmosfera para horrores feéricos.","3 sucessos contam como excepcionais em Expressão para afetar outros com música triste ou assustadora. Gaste 1 Glamour para criar uma paisagem sonora pela cena; tentativas de causar, manipular ou aumentar medo ou tristeza recebem +2. Teste Manipulação + Expressão + Fado contra a maior Compostura + Tolerância Sobrenatural dos ouvintes para impor Abalado a todos que a ouvem.","Book of Seemings",39),sourceId:"h-seemings"},
  {...kith("Fireheart","Ofícios ou Sobrevivência","Perdidos feitos de fogo literal e paixão ardente.","3 sucessos contam como excepcionais em Ofícios ou Sobrevivência para acender fogo. Ao cruzar o olhar com um alvo, gaste 1 Glamour e teste Raciocínio + Empatia contra Compostura + Tolerância Sobrenatural. Descubra uma Aspiração do alvo e uma pessoa por quem ele possui Enamorado ou vínculo semelhante.","Book of Seemings",40),sourceId:"h-seemings"},
  {...kith("Gargantuan","Intimidação","Gigantes feéricos criados para dominar pela escala.","3 sucessos contam como excepcionais em Intimidação ao impressionar ou assustar por seu tamanho. Gaste 1 Glamour para somar metade do Fado, arredondada para cima, a Tamanho, Força e Presença pela cena, inclusive acima dos limites normais, recalculando características derivadas. Outro Glamour estende por uma cena; dano nas caixas temporárias desaparece ao encolher.","Book of Seemings",41),sourceId:"h-seemings"},
  {...kith("Palewraith","Furtividade","Sombras quase esquecidas que se apagam da percepção.","3 sucessos contam como excepcionais em Furtividade para evitar detecção onde há pouca ou nenhuma luz natural. Gaste 1 Glamour para reduzir ou extinguir luz em um raio de Fado × 3 metros. O Narrador aplica bônus, Inclinações ou modificadores adequados; o Espectro Pálido enxerga normalmente na escuridão que cria.","Book of Seemings",41),sourceId:"h-seemings"},
  {...kith("Treasured","Socialização","Obras de arte vivas moldadas para serem contempladas.","3 sucessos contam como excepcionais em Socialização para capturar ou manter a atenção de quem possa vê-lo. Gaste 1 Glamour e teste Manipulação + Persuasão + Fado contra Compostura + Tolerância Sobrenatural; imponha Maravilhado em relação ao Tesouro enquanto a vítima puder vê-lo em tempo real.","Book of Seemings",43),sourceId:"h-seemings"},
  {...kith("Truefriend","Empatia","Paragons de lealdade, generosidade e autossacrifício.","3 sucessos contam como excepcionais em Empatia para compreender o que alguém quer. Gaste 1 Glamour para dar +2 à ação de outro personagem que você veja e saiba que está tentando, acompanhado de apoio evidente, uma vez por cena por alvo. Ao ajudar numa ação em equipe sem ser o ator principal, gaste 1 Glamour para conceder Ação Avançada ao teste.","Book of Seemings",43),sourceId:"h-seemings"},
  {...kith("Woodblood","Ciência ou Sobrevivência","Perdidos vegetais que incorporam a resistência das florestas.","3 sucessos contam como excepcionais em Ciência ou Sobrevivência ao lidar com plantas. Gaste 1 Glamour e teste Presença + Sobrevivência: a vegetação próxima cresce descontroladamente, concedendo Fado como bônus a Atletismo e Furtividade do changeling e aliados e reduzindo igualmente o Deslocamento dos inimigos. Requer folhagem suficiente.","Book of Seemings",45),sourceId:"h-seemings"},
];

export function findKith(name:unknown) {
  const wanted=kithSearchText(String(name??""));
  return KITHS.find((item)=>[item.id, item.name, item.translatedName].some(value=>value && kithSearchText(value)===wanted));
}

export function kithSearchText(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toLocaleLowerCase("pt-BR");
}

/** Individual canonical Skill keys, not localized choice phrases. */
export function kithSkillOptions(item: Pick<KithDefinition,"id"|"skill">): string[] {
  const text=KITH_TEXT_EN[item.id]?.skill??item.skill;
  return [...new Set(text.split(/\s+(?:or|ou|and|e)\s+|\s*[,/]\s*/i).map(skill=>systemTerm(skill.trim(),"en-US")).filter(Boolean))];
}

export function kithDisplayName(name: unknown, custom = false, locale:Locale="pt-BR") {
  const value = String(name ?? "");
  if(custom)return value;
  const found=findKith(value);
  return locale==="en-US"?(found?.name??value):(found?.translatedName??value);
}

export function kithPresentation(name:unknown,locale:Locale="pt-BR",custom=false){
  const found=findKith(name);
  if(custom||!found)return {name:String(name??""),description:"",blessing:"",skill:""};
  const english=KITH_TEXT_EN[found.id];
  return locale==="en-US"
    ? {name:found.name,description:english?.description??found.description,blessing:english?.blessing??found.blessing,skill:english?.skill??found.skill}
    : {name:found.translatedName??found.name,description:found.description,blessing:found.blessing,skill:found.skill};
}
