export type ChangelingCondition = {
  id: string;
  name: string;
  originalName: string;
  category: "Mental" | "Física" | "Social" | "Sobrenatural" | "Changeling";
  description: string;
  penalty?: string;
  resolution?: string;
  beat?: string;
  persistent?: boolean;
  source: string;
  sourceCode: string;
  page: number;
};

export const CHANGELING_CONDITIONS: ChangelingCondition[] = [
  {id:"amnesia",name:"Amnésia",originalName:"Amnesia",category:"Mental",description:"Uma parte importante da memória desapareceu, trazendo dificuldades quando pessoas, inimigos ou obrigações esquecidas retornam.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"broken",name:"Quebrado",originalName:"Broken",category:"Mental",description:"O personagem perdeu a capacidade de enfrentar pressão emocional e recua diante de confrontos.",penalty:"−2 em testes Sociais e com Perseverança; −5 em Intimidação.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"deprived",name:"Privado",originalName:"Deprived",category:"Mental",description:"A abstinência de um vício impede o personagem de se concentrar e se controlar.",penalty:"−1 dado em paradas de Vigor, Perseverança e Compostura.",source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"dissociation",name:"Dissociação",originalName:"Dissociation",category:"Mental",description:"A realidade parece distante e o changeling observa as próprias ações como um passageiro em seu corpo.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:336},
  {id:"fixated",name:"Fixado",originalName:"Fixated",category:"Mental",description:"Um único pensamento ou comando domina a atenção até ser cumprido.",penalty:"−2 em todas as ações até cumprir o comando ou a cena terminar.",source:"Hurt Locker",sourceCode:"HL",page:150},
  {id:"fugue",name:"Fuga",originalName:"Fugue",category:"Mental",description:"Trauma provoca apagões; situações semelhantes podem entregar o controle do personagem ao Narrador por uma cena.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"guilty",name:"Culpado",originalName:"Guilty",category:"Mental",description:"Remorso profundo torna o personagem emocionalmente vulnerável.",penalty:"−2 para defender-se com Perseverança ou Compostura contra Subterfúgio, Empatia ou Intimidação.",source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"informed",name:"Informado",originalName:"Informed",category:"Mental",description:"Pesquisa fornece informação decisiva sobre um assunto; ao resolver, uma falha vira sucesso e um sucesso vira sucesso excepcional.",source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"inspired",name:"Inspirado",originalName:"Inspired",category:"Mental",description:"Uma inspiração guia a ação; ao resolver, três sucessos bastam para um sucesso excepcional e o personagem recupera Força de Vontade.",source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"lost",name:"Perdido",originalName:"Lost",category:"Mental",description:"O personagem não sabe onde está nem como alcançar seu destino e precisa se orientar antes de progredir.",source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"madness",name:"Loucura",originalName:"Madness",category:"Mental",description:"Horrores sobrenaturais romperam sua compreensão da realidade; o Narrador pode impor um modificador negativo uma vez por capítulo.",penalty:"Até −(10 − Lucidez atual) em um teste Mental ou Social, uma vez por capítulo.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"oblivious",name:"Alheio",originalName:"Oblivious",category:"Mental",description:"O personagem está ausente e deixa de perceber o que acontece ao redor.",penalty:"−2 em testes de Percepção.",source:"Hurt Locker",sourceCode:"HL",page:150},
  {id:"obsession",name:"Obsessão",originalName:"Obsession",category:"Mental",description:"Uma obsessão domina a atenção e favorece apenas ações diretamente relacionadas a ela.",penalty:"9-novamente ao perseguir a obsessão; perde 10-novamente em ações não relacionadas.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:290},
  {id:"reckless",name:"Imprudente",originalName:"Reckless",category:"Mental",description:"O personagem ignora consequências e procura riscos pelo prazer da ação.",penalty:"−2 em Percepção e outros testes de Compostura para notar algo.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:344},
  {id:"shaken",name:"Abalado",originalName:"Shaken",category:"Mental",description:"Um medo severo interfere nas ações; o jogador pode optar por falhar numa ação prejudicada pelo medo para resolver a Condition.",source:"Chronicles of Darkness",sourceCode:"CofD",page:290},
  {id:"sleepwalking",name:"Sonambulismo",originalName:"Sleepwalking",category:"Mental",description:"Sonho e vigília se confundem, causando tempo perdido, falsas lembranças de tarefas e obrigações não cumpridas.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:344},
  {id:"spooked",name:"Assombrado",originalName:"Spooked",category:"Mental",description:"O contato com o sobrenatural fascina e assusta até o personagem complicar a situação por causa disso.",source:"Chronicles of Darkness",sourceCode:"CofD",page:291},
  {id:"steadfast",name:"Resoluto",originalName:"Steadfast",category:"Mental",description:"A determinação permite resolver a Condition após uma falha para transformar o resultado em um sucesso simples.",source:"Chronicles of Darkness",sourceCode:"CofD",page:291},
  {id:"stoic",name:"Estoico",originalName:"Stoic",category:"Mental",description:"O personagem fecha-se emocionalmente, ocultando traumas mas bloqueando cura de Lucidez e expressão sincera.",penalty:"+2 em Subterfúgio para ocultar emoções; −2 em Hedgespinning; não cura Lucidez enquanto persistir.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:345},
  {id:"swooned",name:"Enamorado",originalName:"Swooned",category:"Mental",description:"A atração por uma pessoa torna o personagem vulnerável à influência e relutante em prejudicá-la.",penalty:"−2 em ações que prejudiquem a pessoa; ela recebe +2 em testes Sociais contra o personagem.",source:"Chronicles of Darkness",sourceCode:"CofD",page:291},
  {id:"withdrawn",name:"Retraído",originalName:"Withdrawn",category:"Mental",description:"Dúvida e insegurança levam o personagem a buscar isolamento e segurança.",penalty:"−2 em todos os testes que exijam interação com outras pessoas.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:346},
  {id:"arm-disability",name:"Deficiência no Braço",originalName:"Arm Disability",category:"Física",description:"Um ou ambos os braços não funcionam sem tratamento ou tecnologia assistiva apropriada.",penalty:"Um braço: penalidade de mão inábil; ambos: dado de sorte em destreza manual e −3 em outras ações Físicas.",persistent:true,source:"Hurt Locker",sourceCode:"HL",page:57},
  {id:"blind",name:"Cego",originalName:"Blind",category:"Física",description:"O personagem perdeu a visão e precisa substituir esse sentido ou lidar com a escuridão total.",penalty:"Dado de sorte em ações que exigem visão; −3 quando outro sentido puder substituí-la.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"chronic-agony",name:"Agonia Crônica",originalName:"Chronic Agony",category:"Física",description:"Dores incapacitantes retornam após estresse ou esforço físico e impõem os efeitos de Atordoado.",penalty:"Atordoado: perde a próxima ação e a Defesa até voltar a agir.",persistent:true,source:"Hurt Locker",sourceCode:"HL",page:57},
  {id:"chronic-sickness",name:"Doença Crônica",originalName:"Chronic Sickness",category:"Física",description:"Doença ou toxina persiste e piora durante esforço e estresse.",penalty:"−1 em todas as ações, aumentando em −1 a cada dois turnos, até −5.",persistent:true,source:"Hurt Locker",sourceCode:"HL",page:57},
  {id:"deaf",name:"Surdo",originalName:"Deaf",category:"Física",description:"A audição de um ou ambos os ouvidos está severamente comprometida.",penalty:"Um ouvido: −3 em Percepção; ambos: dado de sorte em Percepção e −2 em combate.",persistent:true,source:"Hurt Locker",sourceCode:"HL",page:58},
  {id:"disabled",name:"Incapacitado",originalName:"Disabled",category:"Física",description:"O personagem não consegue caminhar de modo eficaz sem cadeira de rodas ou outro auxílio.",penalty:"Deslocamento efetivo 1; cadeira manual usa Força, cadeira elétrica possui Deslocamento 3.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"fragile",name:"Frágil",originalName:"Fragile",category:"Física",description:"Equipamento improvisado ou danificado perde resistência e pode se desfazer durante o uso.",source:"Chronicles of Darkness",sourceCode:"CofD",page:102},
  {id:"leg-disability",name:"Deficiência na Perna",originalName:"Leg Disability",category:"Física",description:"Uma perna não funciona adequadamente sem tratamento ou prótese apropriada.",penalty:"Metade do Deslocamento e −2 em ações Físicas relacionadas a movimento.",persistent:true,source:"Hurt Locker",sourceCode:"HL",page:58},
  {id:"lethargic",name:"Letárgico",originalName:"Lethargic",category:"Física",description:"Exaustão extrema pesa sobre o personagem até que ele durma uma noite inteira.",penalty:"Não pode gastar Força de Vontade; −1 cumulativo em todas as ações a cada seis horas sem dormir.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:342},
  {id:"mute",name:"Mudo",originalName:"Mute",category:"Física",description:"O personagem não consegue falar e precisa se comunicar por escrita, gestos ou sinais.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:290},
  {id:"numb",name:"Entorpecido",originalName:"Numb",category:"Física",description:"Trauma deixa o corpo dormente e torna ações mundanas imprecisas, enquanto a magia parece aliviar os sintomas.",penalty:"−2 em todas as ações físicas mundanas.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:343},
  {id:"volatile",name:"Volátil",originalName:"Volatile",category:"Física",description:"Equipamento ou plano está prestes a falhar de modo catastrófico.",penalty:"Qualquer falha ao usar o equipamento torna-se falha dramática.",source:"Chronicles of Darkness",sourceCode:"CofD",page:102},
  {id:"bonded",name:"Vinculado",originalName:"Bonded",category:"Social",description:"Um vínculo profundo com um animal fortalece influência, confiança e resistência ao medo.",penalty:"+2 para influenciar o animal; ele pode usar Trato com Animais do personagem contra medo ou coerção.",source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"connected",name:"Conectado",originalName:"Connected",category:"Social",description:"O personagem estabeleceu relações úteis dentro de um grupo específico.",penalty:"+2 em testes relacionados ao grupo; pode resolver para obter um sucesso excepcional automático ao influenciá-lo.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:288},
  {id:"embarrassing-secret",name:"Segredo Constrangedor",originalName:"Embarrassing Secret",category:"Social",description:"Um segredo pode provocar ostracismo, chantagem ou consequências legais caso se torne público.",source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"hunted",name:"Caçado",originalName:"Hunted",category:"Social",description:"Um inimigo sério persegue o personagem para feri-lo ou atormentá-lo.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:342},
  {id:"leveraged",name:"Coagido",originalName:"Leveraged",category:"Social",description:"Alguém possui influência, chantagem ou vantagem suficiente para exigir um favor sem resistência.",source:"Chronicles of Darkness",sourceCode:"CofD",page:289},
  {id:"notoriety",name:"Notoriedade",originalName:"Notoriety",category:"Social",description:"Má fama provoca repulsa e ostracismo entre aqueles que a conhecem.",penalty:"−2 em testes Sociais com quem conhece a fama; uma Porta adicional em Manobra Social.",source:"Chronicles of Darkness",sourceCode:"CofD",page:290},
  {id:"reluctant-aggressor",name:"Agressor Relutante",originalName:"Reluctant Aggressor",category:"Social",description:"O personagem foi levado a ferir alguém contra sua vontade e hesita diante da vítima.",penalty:"−2 em ataques contra a vítima designada.",source:"Hurt Locker",sourceCode:"HL",page:150},
  {id:"surveilled",name:"Vigiado",originalName:"Surveilled",category:"Social",description:"Uma pessoa ou organização acompanha os movimentos do personagem e reúne informações sobre ele.",source:"Hurt Locker",sourceCode:"HL",page:150},
  {id:"goblin-queen",name:"Rainha Goblin",originalName:"Goblin Queen",category:"Sobrenatural",description:"A natureza goblin fragmentada prende o personagem na Sebe e atrai seguidores hobgoblins.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:339},
  {id:"hedge-denizen",name:"Habitante da Sebe",originalName:"Hedge Denizen",category:"Sobrenatural",description:"Dívidas e pactos transformaram o personagem em goblin, mudando Contratos, Corte e sua relação com a Sebe.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:340},
  {id:"soulless",name:"Sem Alma",originalName:"Soulless",category:"Sobrenatural",description:"A perda da alma corrói lentamente a vontade, a identidade e a capacidade de resistir à degeneração.",persistent:true,source:"Chronicles of Darkness",sourceCode:"CofD",page:290},
  {id:"ravaged",name:"Devastado",originalName:"Ravaged",category:"Sobrenatural",description:"Predação feérica destruiu sonhos ou emoções, deixando o personagem vazio e incapaz de descansar.",penalty:"−2 em todos os testes; não recupera Força de Vontade dormindo.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:344},
  {id:"behind-your-eyes",name:"Atrás de Seus Olhos",originalName:"Behind Your Eyes",category:"Changeling",description:"Um fantasma da Sebe, hobgoblin ou Fae Verdadeiro compartilha os sentidos do changeling e pode descobrir seus segredos.",source:"Kith and Kin",sourceCode:"Kith",page:140},
  {id:"comatose",name:"Comatoso",originalName:"Comatose",category:"Changeling",description:"Com Lucidez zero, o changeling recua para um sonho contínuo que acredita ser realidade.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:334},
  {id:"cursed",name:"Amaldiçoado",originalName:"Cursed",category:"Changeling",description:"Uma maldição imposta por outro changeling persiste enquanto ele mantiver a rotina ou exigência definida.",persistent:true,source:"Kith and Kin",sourceCode:"Kith",page:140},
  {id:"deep-kenning",name:"Kenning Profundo",originalName:"Deep Kenning",category:"Changeling",description:"Lucidez restaurada concede um lampejo de conhecimento sobre fenômenos sobrenaturais próximos.",source:"Kith and Kin",sourceCode:"Kith",page:140},
  {id:"dream-assailant",name:"Agressor dos Sonhos",originalName:"Dream Assailant",category:"Changeling",description:"Mudanças excessivas tornaram os eidolons hostis e resistentes a novas alterações do sonho.",penalty:"−5 para interação pacífica ou agir despercebido; mudanças de paradigma custam +2 sucessos.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:336},
  {id:"dream-infiltrator",name:"Infiltrador dos Sonhos",originalName:"Dream Infiltrator",category:"Changeling",description:"Uma mudança significativa tornou os eidolons desconfiados do personagem.",penalty:"−2 para interação pacífica; −3 para agir despercebido; mudanças sutis custam +1 sucesso.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:337},
  {id:"dream-intruder",name:"Intruso dos Sonhos",originalName:"Dream Intruder",category:"Changeling",description:"Múltiplas alterações deixaram o sonho e seus eidolons desconfortáveis com a presença do personagem.",penalty:"−3 para interação pacífica e −4 para agir despercebido.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:338},
  {id:"egomaniac",name:"Egomaníaco",originalName:"Egomaniac",category:"Changeling",description:"Sem Lucidez, o changeling imita o ego ilimitado dos Fae Verdadeiros e ignora as necessidades alheias.",penalty:"Falhas em testes Sociais tornam-se falhas dramáticas sem conceder Beat.",source:"Kith and Kin",sourceCode:"Kith",page:141},
  {id:"enchanted-obligation",name:"Obrigação Encantada",originalName:"Enchanted Obligation",category:"Changeling",description:"Uma barganha encantada protege o changeling enquanto concede ao mortal visão através da Máscara e acesso a sua ajuda feérica.",source:"Kith and Kin",sourceCode:"Kith",page:141},
  {id:"glamour-addicted",name:"Viciado em Glamour",originalName:"Glamour Addicted",category:"Changeling",description:"O corpo definha quando o personagem não se alimenta regularmente de Glamour suficiente.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:339},
  {id:"hexed",name:"Enfeitiçado",originalName:"Hexed",category:"Changeling",description:"Um changeling impôs um inconveniente temporário que termina apenas quando a ação ou missão especificada é cumprida.",source:"Kith and Kin",sourceCode:"Kith",page:141},
  {id:"icon-shard",name:"Fragmento de Ícone",originalName:"Icon Shard",category:"Changeling",description:"Um juramento rompido deu vida maliciosa a um fragmento do Ícone, que passa a atormentar o changeling.",persistent:true,source:"Kith and Kin",sourceCode:"Kith",page:141},
  {id:"indebted",name:"Endividado",originalName:"Indebted",category:"Changeling",description:"O personagem deve um serviço a um ser feérico e pode pagar aceitando dano, uma Condition prejudicial ou uma Inclinação pessoal.",persistent:true,source:"Kith and Kin",sourceCode:"Kith",page:142},
  {id:"kithseeker",name:"Buscador de Fratria",originalName:"Kithseeker",category:"Changeling",description:"O changeling enfrenta cinco provações na Sebe para encontrar uma Fratria que corresponda ao chamado de sua alma.",persistent:true,source:"Kith and Kin",sourceCode:"Kith",page:142},
  {id:"oathbreaker",name:"Quebrador de Juramento",originalName:"Oathbreaker",category:"Changeling",description:"O Wyrd marca quem violou um juramento e desperta desconfiança entre os changelings.",penalty:"−1 em ações Sociais com changelings; não pode selar declarações com Glamour.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:343},
  {id:"obliged",name:"Obrigado",originalName:"Obliged",category:"Changeling",description:"Uma barganha de serviço com um mortal protege o changeling contra Caçadores e perseguidores vinculados ao Wyrd.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:343},
  {id:"hedge-addiction",name:"Vício na Sebe",originalName:"Hedge Addiction",category:"Changeling",description:"A Sebe chama e tenta o personagem, tornando difícil permanecer longe de seus caminhos e perigos.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:340},
  {id:"arcadian-dreams",name:"Sonhos Arcadianos",originalName:"Arcadian Dreams",category:"Changeling",description:"Visões do protegido preso em Arcádia distraem o personagem, mas também indicam sua direção dentro da Sebe.",penalty:"+1 para navegar pela Sebe em direção ao protegido; o jogador pode escolher falhar para representar as visões.",persistent:true,source:"Changeling the Lost",sourceCode:"CTL 2e",page:333},
];

export function findChangelingCondition(id: string) {
  return CHANGELING_CONDITIONS.find((condition) => condition.id === id);
}

// As edições de CofD sempre apresentam uma Resolução e, nas Conditions
// persistentes, um gatilho de Beat. Os textos abaixo também servem como
// migração segura para registros importados antes de esses campos existirem.
for (const condition of CHANGELING_CONDITIONS) {
  condition.resolution ??= condition.persistent
    ? "Remova de modo duradouro a causa da Condition ou cumpra a forma de recuperação estabelecida pelo Narrador e pela fonte indicada."
    : "Cumpra a circunstância que encerra o efeito descrito ou elimine sua causa durante a história.";
  condition.beat ??= condition.persistent
    ? "Receba um Beat quando esta Condition causar uma complicação ou limitação significativa (no máximo uma vez por capítulo)."
    : undefined;
}
