export type Weapon={id:string;name:string;kind:"Distância"|"Corpo a corpo";damage:number;initiative:number;strength:number;size:number;availability:number;ranges?:string;clip?:string;special?:string};
export type Armor={id:string;name:string;general:number;ballistic:number;strength:number;defense:number;speed:number;availability:number;coverage:string};
export type Equipment={id:string;name:string;category:"Mental"|"Físico";bonus:string;durability:string;size:string;structure:string;availability:string;effect:string};
const id=(value:string)=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const ranged=(name:string,damage:number,ranges:string,clip:string,initiative:number,strength:number,size:number,availability:number,special?:string):Weapon=>({id:id(name),name,kind:"Distância",damage,ranges,clip,initiative,strength,size,availability,special});
const melee=(name:string,damage:number,initiative:number,strength:number,size:number,availability:number,special?:string):Weapon=>({id:id(name),name,kind:"Corpo a corpo",damage,initiative,strength,size,availability,special});
export const WEAPONS:Weapon[]=[
 ranged("Revólver leve",1,"20/40/80","6",0,2,1,2),ranged("Revólver pesado",2,"35/70/140","6",-2,3,1,2),ranged("Pistola leve",1,"20/40/80","17+1",0,2,1,3),ranged("Pistola pesada",2,"30/60/120","7+1",-2,3,1,3),ranged("Submetralhadora pequena",1,"25/50/100","30+1",-2,2,1,3,"Rajada automática"),ranged("Submetralhadora grande",2,"50/100/200","30+1",-3,3,2,3,"Rajada automática"),ranged("Rifle",4,"200/400/800","5+1",-5,2,3,2),ranged("Rifle de assalto",3,"150/300/600","42+1",-3,3,3,3,"Rajada automática"),ranged("Escopeta",3,"20/40/80","5+1",-4,3,2,2,"9-novamente"),ranged("Besta",2,"40/80/160","1",-5,3,3,3,"Três turnos para recarregar"),
 melee("Cassetete de couro",0,-1,1,1,1,"Atordoar"),melee("Soco inglês",0,0,1,1,1,"Ataca com Briga"),melee("Bastão",1,-1,2,2,0),melee("Pé de cabra",2,-2,2,2,1),melee("Chave de roda",1,-3,2,2,2,"+1 Defesa"),melee("Corrente",1,-3,2,2,1,"Luta agarrada"),melee("Escudo pequeno",0,-2,2,2,2,"Ocultação"),melee("Escudo grande",2,-4,3,3,2,"Ocultação"),melee("Faca",0,-1,1,1,1),melee("Rapieira",1,-2,1,2,2,"Perfuração de armadura 1"),melee("Facão",2,-2,2,2,2),melee("Machadinha",1,-2,1,1,1),melee("Machado de incêndio",3,-4,3,3,2,"9-novamente; duas mãos"),melee("Motosserra",5,-6,4,3,3,"9-novamente; duas mãos"),melee("Estaca",0,-4,1,1,0,"Ataque localizado ao coração"),melee("Lança",2,-2,2,4,1,"+1 Defesa; duas mãos"),melee("Arma de choque",1,1,1,1,1,"Atordoar; sucessos extras não aumentam o dano")
];
export const ARMORS:Armor[]=[
 {id:"roupa-reforcada",name:"Roupa reforçada",general:1,ballistic:0,strength:1,defense:0,speed:0,availability:1,coverage:"Tronco, braços e pernas"},
 {id:"colete-kevlar",name:"Colete de Kevlar",general:1,ballistic:3,strength:1,defense:0,speed:0,availability:1,coverage:"Tronco"},
 {id:"jaqueta-fragmentacao",name:"Jaqueta de fragmentação",general:2,ballistic:4,strength:1,defense:-1,speed:0,availability:2,coverage:"Tronco e braços"},
 {id:"equipamento-antitumulto",name:"Equipamento antitumulto completo",general:3,ballistic:5,strength:2,defense:-2,speed:-1,availability:3,coverage:"Tronco, braços e pernas"},
 {id:"couro-duro",name:"Couro endurecido",general:2,ballistic:0,strength:2,defense:-1,speed:0,availability:1,coverage:"Tronco e braços"},
 {id:"cota-malha",name:"Cota de malha",general:3,ballistic:1,strength:3,defense:-2,speed:-2,availability:2,coverage:"Tronco e braços"},
 {id:"armadura-placas",name:"Armadura de placas",general:4,ballistic:2,strength:3,defense:-2,speed:-3,availability:4,coverage:"Tronco, braços e pernas"},
];
const equipment=(name:string,category:"Mental"|"Físico",bonus:string,durability:string,size:string,structure:string,availability:string,effect:string):Equipment=>({id:id(name),name,category,bonus,durability,size,structure,availability,effect});
export const EQUIPMENT:Equipment[]=[
 equipment("Ferramentas automotivas básicas","Mental","+1","2","2","3","•","Permitem reparos automotivos comuns."),equipment("Garagem automotiva","Mental","+2","—","—","—","•","Oficina equipada para reparos e modificações complexos."),equipment("Cache oculto","Mental","+1 a +3","2","1–5","5","• a •••","Esconde e protege objetos; o bônus também penaliza buscas."),equipment("Headset de comunicação","Mental","+2","0","1","1","••","Auxilia esforços coordenados entre usuários treinados."),equipment("Kit de cena de crime","Mental","+2","2","3","2","••","Auxilia Investigação e permite transportar evidências adequadamente."),equipment("Kit de códigos","Mental","+5","1","2","1","•","Cria e interpreta uma cifra; o bônus penaliza tentativas de quebrá-la."),equipment("Software de invasão","Mental","+2","—","—","—","•••","Ajuda a romper senhas e sistemas e cria uma camada contra rastreamento."),equipment("Gravador digital","Mental","+1 ou +2","1","1","2","• ou ••","Registra sons discretamente e ajuda a perceber fala ou ruídos."),equipment("Fita adesiva","Mental","+1","1","1","2","•","Ajuda Ofícios, reforça objetos ou restringe com penalidade para escapar."),equipment("Kit de primeiros socorros","Mental","0 ou +1","1","2","3","• ou ••","Permite estabilizar ferimentos e pode melhorar rolagens de tratamento."),equipment("Lanterna","Mental","+1","2","1","3","•","Reduz penalidades de escuridão, auxilia buscas e pode cegar por um turno."),equipment("Bastão luminoso","Mental","+2","1","1","1","•","Ilumina uma pequena área por horas, inclusive sob água."),equipment("Rastreador GPS","Mental","+3","2","2","2","••","Permite acompanhar a posição de um dispositivo em área com sinal."),equipment("Software keylogger","Mental","+2","—","—","—","••","Registra teclas e auxilia invasão de rede ou busca de dados."),equipment("Luminol","Mental","+2","0","1","1","•","Revela traços de fluidos corporais e auxilia rastreamento e reconstrução."),equipment("Multiferramenta","Mental","+1","3","1","4","•","Permite diversas ações simples quando faltam ferramentas próprias."),equipment("Computador pessoal","Mental","+1 a +4","2","3","2","• a ••••","Auxilia tarefas digitais conforme sua qualidade."),equipment("Smartphone","Mental","+1 a +2","2","1","1","• a •••","Concentra comunicação, pesquisa, registro e diversos aplicativos."),equipment("Efeitos especiais","Mental","+2","2","5","3","•••","Produz ilusões e distrações convincentes até haver motivo para suspeita."),equipment("Equipamento de vigilância","Mental","+2","2","2","2","•••","Detecta e registra intrusos; permite disputar tentativas de evasão."),equipment("Kit de sobrevivência","Mental","+1 ou +2","2","2 ou 3","3","• ou •••","Reduz níveis ambientais e auxilia ações de sobrevivência."),equipment("Talco","Mental","+2","—","1","—","•","Revela passagens e presença de entidades invisíveis."),equipment("Tinta ultravioleta","Mental","+2","1","1","2","•","Permite escrever mensagens invisíveis sem luz UV."),
 equipment("Aríete","Físico","+4","3","4","8","••","Ação de equipe para derrubar barreiras, ignorando Durabilidade 2."),equipment("Armadilha de urso","Físico","+2","3","2","5","••","Causa três de dano letal, ignora proteção e prende a perna."),equipment("Estrepes","Físico","+2","2","2","3","••","Causam dano letal e dificultam movimento seguro."),equipment("Roupa de camuflagem","Físico","+2","1","2","3","••","Auxilia Furtividade no ambiente para o qual foi preparada."),equipment("Equipamento de escalada","Físico","+2","3","2","2","••","Auxilia escalada e limita quedas quando instalado corretamente."),equipment("Pé de cabra","Físico","+2","3","2","4","•","Cria alavanca, ignora Durabilidade 2 e também serve como arma."),equipment("Supressor de arma de fogo","Físico","+2","2","1","2","••","Melhora disparos curtos e dificulta localizar o atirador, reduzindo dano em um."),equipment("Máscara de gás","Físico","+5","1","2","3","••","Protege contra toxinas aéreas e amplia rolagens contra agentes fortes."),equipment("Algemas","Físico","+2","4","1","4","•","Restringem um alvo e dificultam ações manuais e tentativas de fuga."),equipment("Kit de gazuas","Físico","+2","2","2","2","••","Permite abrir fechaduras mecânicas e auxilia Destreza + Furto."),equipment("Óculos de visão noturna","Físico","+2","1","2","1","••","Eliminam penalidades por cegueira em baixa luz; luz intensa pode cegar."),equipment("Spray de pimenta","Físico","+1","2","1","1","•","Ataque curto que Atordoa e impõe penalidade até lavar os olhos."),equipment("Corda","Físico","+1","2","3","2","•","Auxilia Ofícios, escalada, amarração e outras tarefas apropriadas.")
];
