import type { ContractDefinition } from "./contracts";

const base = {
  categoryKind: "Regalia" as const,
  regalia: "Chalice",
  sourceId: "ctl-kith-and-kin",
  source: "Kith and Kin",
};

export const KITH_AND_KIN_CONTRACTS: ContractDefinition[] = [
  {
    ...base, id:"ctl-kith-and-kin:filling-the-cup", name:"Filling the Cup", originalName:"Filling the Cup", type:"Comum", page:34,
    description:"The changeling identifies people experiencing powerful emotions within Wyrd x 40 yards or meters, learning their direction, general distance, and whether each emotion is positive or negative. He also automatically notices Bedlam incited within range.",
    hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"One scene or until the changeling regains Glamour, whichever comes first",
    loophole:"The changeling publicly states his strongest current emotion and its cause or subject when invoking the Contract.",
    seemingBenefits:{
      Beast:"After previously identifying a known person's emotions with this or another relevant power, the Beast can recognize that person again at range by the scent of their feelings.",
      Fairest:"The Fairest can distinguish people in range experiencing an intense emotion related to him, though he learns the emotion rather than the person's identity.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:frail-as-the-dying-word", name:"Frail as the Dying Word", originalName:"Frail as the Dying Word", type:"Comum", page:35,
    description:"By touching the target, the changeling tricks the Wyrd into applying one of his own frailties to them.",
    hasRoll:true, dicePool:"Manipulation + Occult + Wyrd vs. Composure + Tolerance", cost:"●", action:"Contested", duration:"One scene",
    success:"The target gains one of the changeling's minor frailties. If already possessed, it becomes major for the duration; a target already suffering its major version is unaffected. The changeling retains the frailty.",
    exceptionalSuccess:"The changeling may instead inflict one major frailty or two minor frailties. Iron counts as major.", failure:"The Contract fails.",
    dramaticFailure:"The Wyrd inflicts a new major frailty on the changeling for the scene.",
    loophole:"The changeling has suffered from the chosen frailty during the same scene.",
    seemingBenefits:{
      Fairest:"The Fairest may inflict a frailty belonging to any fae being present rather than one of his own.",
      Darkling:"For +●, the Darkling transfers the frailty instead of sharing it, losing it for the duration. This cannot transfer his iron bane.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:sleeps-sweet-embrace", name:"Sleep's Sweet Embrace", originalName:"Sleep's Sweet Embrace", type:"Comum", page:35,
    description:"The changeling touches the target and replaces their dreams with restorative, dreamless sleep. The invocation is resisted only if the target is unwilling.",
    hasRoll:true, dicePool:"Manipulation + Expression + Wyrd - Resolve", cost:"●●○", action:"Instant or resisted", duration:"A number of days equal to successes",
    success:"Whenever the target sleeps during the duration, they heal 1 lethal damage per hour but regain no Willpower from rest. They have no Bastion and cannot be affected by oneiromancy or dream magic. More than two days causes Dissociation until they regain full Willpower after the Contract ends.",
    exceptionalSuccess:"The target suffers Dissociation only if the effect lasts more than three days.", failure:"The Contract fails.",
    dramaticFailure:"The next time the changeling sleeps, he cannot meditate, enter the Gate of Ivory, or dream. He suffers the Contract's drawbacks for one night without its healing.",
    loophole:"During the same scene, the changeling persuades or forces the target to completely consume a prepared drink used as a sleep aid.",
    seemingBenefits:{
      Beast:"The Beast adds two days to the Contract's duration.",
      Darkling:"While asleep, the Darkling's target appears recently dead to mundane examination; supernatural detection prompts a Clash of Wills.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:curses-cure", name:"Curse's Cure", originalName:"Curse's Cure", type:"Comum", page:36,
    description:"The changeling mixes the target's blood, Hedge herbs, his spit, and wine into one full dose of antidote for a single poisoned victim.",
    hasRoll:true, dicePool:"Intelligence + Medicine + Wyrd", cost:"●", action:"Instant", duration:"Instant",
    success:"Drinking the full dose halves a poison's recovery time or makes a lethal poison survivable. Related Conditions fade without resolution. Supernatural poison requires a Clash of Wills.",
    exceptionalSuccess:"The poison is completely and immediately cured.", failure:"The Contract fails.",
    dramaticFailure:"The changeling poisons himself, gaining Fatigued, which becomes the moderate Poisoned Tilt in action scenes.",
    loophole:"The changeling tastes the same toxin during the scene; the Contract does not protect him from that exposure.",
    seemingBenefits:{
      Beast:"During the chapter, the Beast may bite a grappled opponent as a unique grapple action to inflict moderate Poisoned.",
      Wizened:"The Wizened may instead reduce a disease's severity or end a drug's effects; related Conditions fade without resolution.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:dreamers-phalanx", name:"Dreamer's Phalanx", originalName:"Dreamer's Phalanx", type:"Comum", page:36,
    description:"Willing sleepers in physical contact enter a shared dream whose distinct Bastions count as one for oneiromancy. Each gains +1 Fortification per participant, maximum +5, against outsiders; teamwork within the linked Bastions gains 8-again, and location shifts may move subjects between Bastions. Forced magical awakening destroys every linked Bastion.",
    hasRoll:false, dicePool:"None", cost:"● + ●/subject beyond 2nd", action:"Instant", duration:"One chapter or until all participants wake",
    loophole:"All participants belong to the same sworn oath, including one sworn for this purpose during the same scene.",
    seemingBenefits:{
      Beast:"All participants gain +2 to actions contested by an outside oneiropomp intruding on any linked Bastion.",
      Wizened:"Teamwork between participants also achieves exceptional success on three successes.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:closing-deaths-door", name:"Closing Death's Door", originalName:"Closing Death's Door", type:"Real", page:36,
    description:"With an intimate gesture, the changeling attempts to return a recently dead character to life.",
    hasRoll:true, dicePool:"Manipulation + Empathy + Wyrd", cost:"●●●○", action:"Instant", duration:"Instant",
    success:"A character dead for no more than one chapter returns with every Health box filled with aggravated damage except the undamaged rightmost box. The changeling gains Goblin Debt equal to hours dead, minimum 1 and subject to the usual maximum.",
    exceptionalSuccess:"The Contract can revive someone who died at any point in the current story; otherwise a target dead longer than one chapter cannot be revived.", failure:"The Contract fails.",
    dramaticFailure:"The corpse becomes a mindless marionette with one Health box, no Willpower, and all dice pools equal to the changeling's Wyrd.",
    loophole:"The deceased is the changeling's Touchstone, a fae-touched promised to him, or someone bound to him by a personal oath.",
    seemingBenefits:{
      Fairest:"The revived character gains Swooned regarding the Fairest.",
      Darkling:"The Darkling briefly experiences the deceased's final moments from their point of view.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:feast-of-plenty", name:"Feast of Plenty", originalName:"Feast of Plenty", type:"Real", page:37,
    description:"The changeling publicly offers freely given food, drink, medicine, or similar comforts to everyone present.",
    hasRoll:true, dicePool:"Presence + Socialize + Wyrd", cost:"●●", action:"Instant", duration:"Instant",
    success:"The Contract creates enough suitable nourishment or medicine for everyone present. A willing participant removes one physical non-Persistent Condition or one physical Personal Tilt and regains Willpower equal to half the successes, rounded up, but gains Indebted to the changeling. The changeling cannot benefit from his own feast.",
    exceptionalSuccess:"Indebted becomes Persistent.", failure:"The Contract fails.", dramaticFailure:"The changeling gains Notoriety.",
    loophole:"During the scene, the changeling greets everyone present by name with a gesture, learning and using any unknown names before invocation.",
    seemingBenefits:{
      Elemental:"Everyone perceiving the feast contests with Composure + Wyrd or is compelled to partake.",
      Ogre:"Participants gain +1 Defense for the rest of the chapter.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:still-waters-run-deep", name:"Still Waters Run Deep", originalName:"Still Waters Run Deep", type:"Real", page:38,
    description:"The target watches the changeling's serene breathing as he suppresses their emotional turmoil and joy.",
    hasRoll:true, dicePool:"Manipulation + Subterfuge + Wyrd - Resolve", cost:"●●", action:"Instant", duration:"One scene",
    success:"Suppress emotional Conditions equal to successes, including Clarity and Bedlam Conditions. Their effects, resolutions, and Beats are suspended, and the target cannot gain new emotional Conditions, Hedgespin, dreamweave, incite Bedlam, or harvest Glamour from living beings during the scene.",
    exceptionalSuccess:"Additional successes only increase the number of suppressed Conditions.", failure:"The Contract fails.",
    dramaticFailure:"The changeling gains either one suppressed detrimental Condition from the target or Demoralized, chosen by the Storyteller, and must resolve it normally.",
    loophole:"During the scene, the changeling writes at least one paragraph about his current emotional state and seals it in a bottle.",
    seemingBenefits:{
      Wizened:"The Wizened may suppress purely mental Conditions as well as emotional ones.",
      Ogre:"The Ogre may resolve one suppressed temporary Condition during the effect and receives its resolution Beat instead of the target.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:poison-the-well", name:"Poison the Well", originalName:"Poison the Well", type:"Real", page:38,
    description:"The changeling poisons the target's relationship with the subject of one Social Merit.",
    hasRoll:true, dicePool:"Manipulation + Expression + Wyrd vs. Resolve + Tolerance", cost:"●", action:"Contested", duration:"One chapter",
    success:"A mundane Social Merit becomes inaccessible and its subject actively hinders the target. In the Hedge, an eligible changeling-specific connection Merit may instead remain usable but inflict Goblin Debt equal to its rating per use; this counts as Hedgespinning without its usual invocation penalty.",
    exceptionalSuccess:"The target also gains Notoriety.", failure:"The Contract fails.",
    dramaticFailure:"The changeling poisons his own most important connections, detaching one Touchstone from his Clarity track for the chapter.",
    loophole:"During the scene, the changeling personally interacts with the Merit's subject to sow conflict or sabotage the resource.",
    seemingBenefits:{
      Fairest:"The Fairest gains access to the poisoned Merit for the Contract's duration.",
      Elemental:"When the Contract ends, the target's Merit returns at one dot per scene rather than immediately.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:shared-cup", name:"Shared Cup", originalName:"Shared Cup", type:"Real", page:39,
    description:"The changeling equally shares a drink or meal with a group, creating a supernatural emotional bond among willing or unwitting participants.",
    hasRoll:true, dicePool:"Presence + Occult + Wyrd vs. Composure + Tolerance", cost:"● + ●/subject beyond 2nd", action:"Instant or contested", duration:"One chapter",
    success:"Bind participants up to successes, including the changeling. Their Social impressions improve one step and they suffer -3 to contest each other's Social actions. Emotional Conditions, Personal Tilts, recovered Willpower, and recovered Glamour propagate to the group; non-Wyrd participants gain Inspired instead of Glamour. Hedgespinning and Bedlam achieve exceptional success on three successes.",
    exceptionalSuccess:"Additional successes increase the maximum participants.", failure:"The Contract fails.",
    dramaticFailure:"The changeling involuntarily incites Bedlam in every participant without a roll.",
    loophole:"During the shared meal's scene, the changeling collects blood, hair, nail clippings, or another body part from every participant.",
    seemingBenefits:{
      Darkling:"By paying ● when a shared effect would occur, the Darkling can briefly exclude himself from that effect and all passive effects; others may notice with Wits + Composure contested by his Wits + Wyrd.",
      Fairest:"Every other participant gains Swooned regarding the Fairest upon invocation.",
    },
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:book-of-black-and-red", name:"Book of Black and Red", originalName:"Book of Black and Red", type:"Comum", page:39,
    description:"The changeling reads the five most significant mundane or supernatural debts and sworn obligations burdening a visible target, including their Goblin Debt. Exploiting this knowledge during the chapter grants +2 and gives the target Leveraged regarding her.",
    hasRoll:true, dicePool:"Wits + Academics + Wyrd vs. Resolve + Tolerance", cost:"●", action:"Instant", duration:"Instant",
    success:"Learn the target's five most significant debts and obligations and their Goblin Debt total.", exceptionalSuccess:"Also learn each debt's creditor, origin, and obstacle to repayment.", failure:"The Contract fails.", dramaticFailure:"The changeling gains 1 Goblin Debt.",
    loophole:"The target allowed the changeling to examine their records or accounts during the scene.",
    seemingBenefits:{Darkling:"The Darkling may interpose herself in one non-Goblin, non-pledge debt: the target owes her, while she owes the original creditor; defaulting gives her Oathbreaker.",Wizened:"The Wizened needs only three successes for exceptional success when exploiting this knowledge."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:give-and-take", name:"Give and Take", originalName:"Give and Take", type:"Comum", page:40,
    description:"With consent, exchange up to half the changeling's Wyrd in points between different categories of Glamour, Willpower, social currency, or personal-scale Merit dots. Merit exchanges last one scene, require prerequisites, cannot affect world-scale Merits, and cannot exchange one Merit for another.",
    hasRoll:false, dicePool:"None", cost:"●/●●", action:"Instant", duration:"Instant, or one scene for Merits",
    loophole:"The parties permanently exchange new physical gifts of equal value or meaning.",
    seemingBenefits:{Ogre:"The Ogre may exchange points of mild Clarity damage.",Wizened:"The exchange need not be equal, but each party must consensually contribute at least one point."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:beggar-knight", name:"Beggar Knight", originalName:"Beggar Knight", type:"Comum", page:40,
    description:"The changeling curses someone who can hear and understand her to benefit only from things he personally makes.",
    hasRoll:true, dicePool:"Manipulation + Academics + Wyrd - Composure", cost:"●●", action:"Instant", duration:"One chapter per success",
    success:"The victim gains no equipment, damage, or armor bonus from items he did not make; failures with them become dramatic without a Beat. He loses externally created Resources and cannot receive teamwork bonuses.", exceptionalSuccess:"Invocation successes also become an immediate Clarity attack, or a breaking-point penalty for a target without Clarity.", failure:"The Contract fails.", dramaticFailure:"For the chapter, the changeling loses her Resources to the target and takes 1 of his Goblin Debt, if any.",
    loophole:"During the scene, the victim directly benefited from another's work rather than his own.",
    seemingBenefits:{Elemental:"Mundane possessions the victim did not make degrade until permanently transferred away, and disintegrate if returned.",Wizened:"The curse also denies others Resources produced through the victim's constructive work until his involvement ends."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:coin-mark", name:"Coin Mark", originalName:"Coin Mark", type:"Comum", page:41,
    description:"The changeling enchants a coin, bill, gift, or other traded object. She always knows its direction and distance, and learns each new owner's identity and transaction price. After interacting with its owner, she may spend ● to inflict Avarice.",
    hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"One story", loophole:"The changeling permanently marks her name on the object.",
    seemingBenefits:{Beast:"The Beast may inflict Apprehensive regarding the object instead of Avarice.",Wizened:"The Wizened may reflexively snap her fingers to return the object immediately to her person."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:grease-the-wheels", name:"Grease the Wheels", originalName:"Grease the Wheels", type:"Comum", page:41,
    description:"Direct interaction with the correct official makes a normally available administrative or bureaucratic result resolve in the changeling's favor in one-tenth the usual time, without scrutiny or red tape.",
    hasRoll:true, dicePool:"Presence + Persuasion + Wyrd", cost:"●", action:"Instant", duration:"Instant",
    success:"The administrative process resolves favorably in one-tenth its normal time, provided the organization could normally produce that outcome.", exceptionalSuccess:"It resolves immediately and favorably despite sheer improbability.", failure:"The process proceeds normally.", dramaticFailure:"The matter becomes hopelessly stalled for at least the rest of the story.",
    loophole:"The official accepts a bribe or gift from the changeling during the scene.",
    seemingBenefits:{Darkling:"The Darkling's interaction leaves no trace except where useful to her.",Fairest:"The Fairest gains Connected regarding the organization."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:blood-debt", name:"Blood Debt", originalName:"Blood Debt", type:"Real", page:42,
    description:"Whenever someone inflicts lethal or aggravated Health damage, or mild or severe Clarity damage, on the changeling, that offender suffers 1 lethal damage ignoring armor. Add 1 damage for each of: causing lost Willpower, causing lost Glamour, and inflicting a Condition or Tilt.",
    hasRoll:false, dicePool:"None", cost:"●●", action:"Instant", duration:"One scene", loophole:"Jewelry or another adornment freshly cuts or pierces the changeling during the scene.",
    seemingBenefits:{Elemental:"The Elemental's retaliation begins at 2 lethal damage.",Ogre:"While conscious, the Ogre may retaliate against damage inflicted on her allies instead of herself."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:exchange-of-gilded-contracts", name:"Exchange of Gilded Contracts", originalName:"Exchange of Gilded Contracts", type:"Real", page:42,
    description:"With another changeling's consent, borrow one Common Contract they know. The borrower gains only her own Seeming benefits and cannot use its Loophole; the lender loses access and temporarily receives Exchange of Gilded Contracts, which can only end the exchange reflexively.",
    hasRoll:false, dicePool:"None", cost:"●●●", action:"Instant", duration:"Up to one chapter", loophole:"During the scene, each party wears a convincing mask of the other.",
    seemingBenefits:{Darkling:"The Darkling may exploit the borrowed Contract's Loophole.",Ogre:"The Ogre retains the borrowed Contract until chapter's end even if recalled, but loses its Loophole after recall."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:golden-promise", name:"Golden Promise", originalName:"Golden Promise", type:"Real", page:42,
    description:"The changeling projects impossible affluence to lower the Availability of a feasible service she wishes to obtain.",
    hasRoll:true, dicePool:"Presence + Socialize + Wyrd - Availability", cost:"●●", action:"Instant", duration:"Instant",
    success:"Reduce one service's Availability by successes, potentially to zero; repeated invocations may reduce it further, and no additional recompense is required beyond the reduced Availability.", exceptionalSuccess:"The changeling also gains Connected to the provider.", failure:"The Contract fails.", dramaticFailure:"Her pretense is exposed and she gains Notoriety.",
    loophole:"The changeling arrives displaying ostentatious wealth and openly flaunts it.",
    seemingBenefits:{Fairest:"The Fairest may divide successes among multiple services in the scene.",Wizened:"The Wizened adds +1 to the acquired service's equipment bonus."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:grand-revel-of-the-harvest", name:"Grand Revel of the Harvest", originalName:"Grand Revel of the Harvest", type:"Real", page:43,
    description:"For the scene, everyone except the changeling who deliberately celebrates achieves exceptional success on Social rolls with three successes and improves Social impressions one step. Until chapter's end, affected characters regain +1 Willpower, heal +1 Health or Clarity damage of the same type, and add +1 equipment bonus to acquired windfalls.",
    hasRoll:false, dicePool:"None", cost:"●●●○", action:"Instant", duration:"One chapter", loophole:"The changeling supplies a feast for everyone present and visibly participates in every revel.",
    seemingBenefits:{Beast:"Revelers gain +2 to Physical rolls for mutual competition and physical entertainment during the scene.",Fairest:"Social impressions improve two steps instead of one."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:thirty-pieces", name:"Thirty Pieces", originalName:"Thirty Pieces", type:"Real", page:44,
    description:"The changeling plants a command to perform one genuine betrayal, immediately or when a trigger occurs before story's end. It cannot compel self-harm or a non-treacherous act, and a new invocation replaces an existing pending one.",
    hasRoll:true, dicePool:"Wits + Empathy + Wyrd vs. Resolve + Tolerance", cost:"●●●", action:"Instant", duration:"Until triggered or the story ends",
    success:"The target performs the specified betrayal when appropriate and gains Guilty.", exceptionalSuccess:"The target also gains Fugue after the betrayal.", failure:"The Contract fails.", dramaticFailure:"Before chapter's end, someone known to the motley betrays them and the changeling gains an appropriate detrimental Condition.",
    loophole:"During the story, the target accepted the changeling's payment to betray their fellows, even without intending to comply.",
    seemingBenefits:{Darkling:"After the betrayal, the target also gains Notoriety and becomes isolated from those betrayed.",Elemental:"Safeguards that could prevent the betrayal fail; for example, a treacherous attack gains surprise."},
  },
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:burning-ambition",name:"Burning Ambition",originalName:"Burning Ambition",type:"Comum",page:44,description:"After taking something without permission, the changeling gains an additional Aspiration reflecting what or whom she most desires. Fulfilling it grants a Beat, restores Willpower equal to half Wyrd, and inflicts Competitive.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"Until the Aspiration is fulfilled",loophole:"During the scene, she completely burns a symbol of an obligation she owes another.",seemingBenefits:{Beast:"If the Beast consumes the object of the craving, fulfilling it restores all Willpower.",Fairest:"If the object is a character, fulfilling it gives that character Swooned regarding the Fairest."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:jealous-vengeance",name:"Jealous Vengeance",originalName:"Jealous Vengeance",type:"Comum",page:44,description:"The changeling names someone obstructing her desire and issues an ultimatum: step aside or suffer a curse.",hasRoll:true,dicePool:"Presence + Intimidation + Wyrd vs. Resolve + Tolerance",cost:"●",action:"Contested",duration:"One chapter",success:"Unless the target does everything possible to step aside within the chapter, inflict Blind (temporary), Bestial, Embarrassing Secret, Guilty, Leveraged, Lethargic, Paranoid, Ravaged, Reckless, or Spooked. It cannot resolve until the target bests the changeling in a contest.",exceptionalSuccess:"Inflict two listed Conditions.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Notoriety.",loophole:"During the scene, the target gained Oathbreaker because of the changeling.",seemingBenefits:{Elemental:"The Elemental may choose Mute, and Blind becomes Persistent.",Ogre:"The Ogre achieves exceptional success on three successes."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:litany-of-rivals",name:"Litany of Rivals",originalName:"Litany of Rivals",type:"Comum",page:45,description:"The changeling names one Aspiration and questions still water about the most immediate or dangerous people opposing it.",hasRoll:true,dicePool:"Intelligence + Occult + Wyrd",cost:"●",action:"Instant",duration:"Instant",success:"Per success, learn one new detail about a relevant rival: name, face, location, a frailty or weakness, or the name or face of a close ally. Answers may concern different rivals.",exceptionalSuccess:"Additional successes provide additional answers.",failure:"The Contract fails.",dramaticFailure:"The would-be subject learns of the attempt and that the changeling regards them as a rival.",loophole:"During the scene, the changeling throws a temper tantrum before someone outside her motley.",seemingBenefits:{Beast:"For +● when learning a location, track it for the chapter.",Ogre:"When learning a name or face, roll Manipulation + Intimidation vs. Resolve + Empathy to inflict Paranoid."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:knights-oath",name:"Knight's Oath",originalName:"Knight's Oath",type:"Comum",page:45,description:"A willing non-changeling is ceremonially knighted, gaining half Wyrd to Initiative and Defense while perceiving the changeling and to Social actions in her name. Disobedience or betrayal inflicts Cowed and alerts her.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"One chapter",loophole:"The changeling anoints the knight with blood from at least 1 lethal damage she inflicted on herself during the scene.",seemingBenefits:{Darkling:"On betrayal, also learn exactly when and where it happened and the knight's emotions.",Fairest:"Knight up to Wyrd targets with one invocation, performing the gesture for each."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:unmask-the-dark-horse",name:"Unmask the Dark Horse",originalName:"Unmask the Dark Horse",type:"Comum",page:46,description:"The changeling publicly challenges a rival and may pay +● to replace one of her Aspirations with one directly opposing the target's.",hasRoll:true,dicePool:"Presence + Persuasion + Wyrd vs. Composure + Tolerance",cost:"●●",action:"Contested",duration:"Instant",success:"Learn one short-term Aspiration and inflict Competitive, which cannot resolve until the target defeats the changeling in a contest or fight.",exceptionalSuccess:"Learn all the target's Aspirations.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Berserk.",loophole:"Issue the challenge before a large crowd containing a loved one, friend, or colleague of the target.",seemingBenefits:{Fairest:"The challenge and ensuing competition are supernaturally broadcast live within five miles.",Beast:"Defeating the target during the effect inflicts Notoriety."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:a-benevolent-hand",name:"A Benevolent Hand",originalName:"A Benevolent Hand",type:"Real",page:46,description:"After a gesture benefiting another without helping herself, the changeling improves first impressions with everyone newly met during the chapter, up to perfect. Successful Social actions can grant temporary Allies dots, maximum five.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One chapter",loophole:"The changeling gives up something significant when invoking the Contract.",seemingBenefits:{Elemental:"Each qualifying success grants 2 Allies dots rather than 1.",Wizened:"Gain a separate temporary Resources dot instead, maximum five."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:fake-it-til-you-make-it",name:"Fake It ‘Til You Make It",originalName:"Fake It ‘Til You Make It",type:"Real",page:46,description:"A proclamation alters mundane reality within 10 yards or meters like Hedgespinning. Spend successes on subtle shifts at +2 each; scenery is unresisted, characters resist, and the effect cannot instantly annihilate anyone. Invocation causes a four-die breaking point.",hasRoll:true,dicePool:"Presence + Persuasion + Wyrd - Resolve",cost:"●●",action:"Instant",duration:"One scene",success:"Apply purchased temporary shifts consistent with the proclamation's emotional tenor.",exceptionalSuccess:"For +● and +○, successes may also purchase subtle or paradigm shifts.",failure:"The Contract fails.",dramaticFailure:"Incite Bedlam in everyone present, including the changeling.",loophole:"Point and declaim with a real scepter.",seemingBenefits:{Fairest:"Give one witness a temporary Delusional Condition resolved by accepting one of her lies.",Wizened:"Shifts affecting human-made inanimate objects or structures cost 2 fewer successes."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:tempters-quest",name:"Tempter's Quest",originalName:"Tempter's Quest",type:"Real",page:47,description:"Assign a clear, achievable quest lasting no more than one story and promise a reward that advances the target's most important Aspiration.",hasRoll:true,dicePool:"Presence + Persuasion + Wyrd vs. Composure + Tolerance",cost:"●○",action:"Contested",duration:"One story",success:"The target gains Persistent Obsession, replaces an Aspiration with the quest, and cannot regain Willpower from Anchors after a chapter without progress. Withholding the earned reward gives the changeling Leveraged and marks her as an oathbreaker.",exceptionalSuccess:"A session without progress also inflicts Lethargic.",failure:"The Contract fails.",dramaticFailure:"The changeling suffers the consequences of reneging despite assigning no quest.",loophole:"Give the quester a provision of significant practical value for the quest.",seemingBenefits:{Darkling:"After default, spend ○ and win Manipulation + Larceny + Wyrd vs. Resolve + Wyrd to transfer consequences to an informed witness.",Fairest:"Assign the same quest to up to half Wyrd subjects with proportionate rewards."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:curse-of-hidden-strings",name:"Curse of Hidden Strings",originalName:"Curse of Hidden Strings",type:"Real",page:48,description:"Destroy an item bearing the target's signature and choose a documented obligation the changeling knows, plus a related beneficial action that can break the curse.",hasRoll:true,dicePool:"Manipulation + Larceny + Wyrd vs. Resolve + Tolerance",cost:"●●",action:"Contested",duration:"One scene",success:"The target forgets her involvement but remains bound. The defined action ends the curse and reveals the obligation and culprit; normal expiration restores memory without identifying the changeling.",exceptionalSuccess:"Duration becomes one chapter.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Leveraged regarding the target.",loophole:"During the scene, knowingly and deliberately break one of the changeling's own agreements.",seemingBenefits:{Fairest:"Affect up to Wyrd targets sharing the obligation.",Wizened:"Make the target believe the obligation is owed to the Wizened instead of erasing it."}},
  {...base,regalia:"Scepter",id:"ctl-kith-and-kin:spare-not-the-rod",name:"Spare Not the Rod",originalName:"Spare Not the Rod",type:"Real",page:48,description:"Create a one-handed Glamour scepter: a 0B melee weapon without Initiative penalty, or a 0L ranged weapon with 30-yard/meter range for ● per attack. A successful attack or Intimidation inflicts Demoralized. Only characters with Wyrd can use its ranged attack.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One scene",loophole:"Break a miniature scepter crafted from precious metals and gems.",seemingBenefits:{Fairest:"For +●●, a successful attack or intimidation inflicts Persistent Awestruck instead of Demoralized.",Wizened:"Summon the scepter to a free hand; an unwilling holder contests Presence + Intimidation with Strength + Stamina."}},
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:pole-star", name:"Pole Star", originalName:"Pole Star", type:"Comum", page:49,
    description:"Name a person, place, or object. The changeling's body points unerringly toward it, revealing direction but not location or distance. Finding a supernaturally hidden target prompts a Clash of Wills, and the Contract functions only in the mundane realm.",
    hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"One scene",
    loophole:"Hold a piece of the target while invoking the Contract.",
    seemingBenefits:{Beast:"Gain +2 dice on a Clash of Wills to uncover a hidden target.",Wizened:"Ask the Storyteller one question about an opponent or obstacle along the path."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:straight-on-til-morning", name:"Straight On ‘Til Morning", originalName:"Straight On ‘Til Morning", type:"Comum", page:49,
    description:"Choose a destination and travel tirelessly without needing food or rest until reaching it. Ignore ill effects from Environmental Tilts along the way and gain 8-again on navigation rolls on the Wishing Roads; encounters and obstacles still impede the journey normally.",
    hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"Until the changeling reaches the destination",
    loophole:"Promise to sleep when the task is done and have an ally seal the statement; Glamour may not refute the sealing, and the changeling gains Fatigued when the Contract ends.",
    seemingBenefits:{Fairest:"Extend the Contract to up to Wyrd fellow travelers.",Ogre:"Gain Steadfast."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:cynosure", name:"Cynosure", originalName:"Cynosure", type:"Comum", page:49,
    description:"By candidly discussing one of his own dreams, the changeling prompts a target to reveal an Aspiration and receives stellar guidance toward an opportunity that could advance it during the next chapter or story.",
    hasRoll:true, dicePool:"Manipulation + Empathy + Wyrd vs. Composure + Tolerance", cost:"●", action:"Contested", duration:"One scene",
    success:"Learn one Aspiration chosen by the target and an event or opportunity that would help fulfill it. A short-term Aspiration may be resolved completely; a long-term one advances to its next significant step.", exceptionalSuccess:"Also learn the name of someone already connected to the changeling who would be immensely helpful to the target's goal.", failure:"The Contract fails.", dramaticFailure:"The target suffers a setback and blames the changeling, or succeeds despite his sabotage and learns he tried to interfere.",
    loophole:"Let an opportunity to fulfill one of the changeling's own Aspirations slip away during the same scene.",
    seemingBenefits:{Darkling:"Gain Informed regarding the target's Aspiration.",Ogre:"Gain +2 dice to convince the target to take bold action toward the Aspiration."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:shooting-star", name:"Shooting Star", originalName:"Shooting Star", type:"Comum", page:50,
    description:"A creator's work briefly captures public attention. The target gains one Fame dot, or +1 die to Fame's Social bonus if this would exceed three dots. Changelings gain +1 to harvest Glamour from people affected by that Fame.",
    hasRoll:false, dicePool:"None", cost:"●●", action:"Instant", duration:"One chapter",
    loophole:"Complete a Build Equipment action for a creative work during the same scene; a Beast may instead succeed at an impressive Athletics feat.",
    seemingBenefits:{Beast:"The Beast may target someone who performs feats of physical excellence rather than creative work.",Fairest:"Gain +2 to rolls to harvest Glamour from those affected by the target's Fame instead of +1."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:retrograde", name:"Retrograde", originalName:"Retrograde", type:"Comum", page:50,
    description:"While telling a story about the target, the changeling gestures counterclockwise and calls down a series of minor misfortunes upon the target's routine communications, finances, travel, and daily affairs.",
    hasRoll:true, dicePool:"Presence + Expression + Wyrd vs. Resolve + Tolerance", cost:"●", action:"Contested", duration:"One chapter",
    success:"Routine matters that require no roll go wrong for the target whenever inconvenient.", exceptionalSuccess:"The target also rolls every dice pool twice and takes the worse result.", failure:"The Contract fails.", dramaticFailure:"The changeling's luck sours instead, imposing −2 on all his actions for the chapter.",
    loophole:"Spin around widdershins while telling the story.",
    seemingBenefits:{Darkling:"Name up to Wyrd specific routine matters that will go wrong; avoided predicted actions cause no substitute misfortune.",Elemental:"Declare an environmental or personal weather-based Tilt to affect the target whenever most inconvenient during the Contract."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:frozen-star", name:"Frozen Star", originalName:"Frozen Star", type:"Real", page:51,
    description:"Trace a known person's, place's, or object's likeness among the stars and name a visible subject other than the changeling. The target must be reasonably reachable before sunrise and cannot be intended expressly to harm the subject.",
    hasRoll:true, dicePool:"Intelligence + (Empathy or Persuasion) + Wyrd vs. Resolve + Tolerance", cost:"●●", action:"Contested", duration:"Until the next sunrise or the subject touches the target",
    success:"The subject abandons their current activity and travels toward the traced target. On arrival or expiration, the effect ends and the subject gains Shaken, remembering no reason for the pursuit.", exceptionalSuccess:"Touching the target does not end the effect; the subject gains Persistent Addicted regarding it until resolved normally or the next sunrise.", failure:"The Contract fails.", dramaticFailure:"The nearest agent of the True Fae learns the changeling's location, becomes drawn to him as the Contract dictates, and the changeling gains Hunted.",
    loophole:"Be in physical contact with the target or a piece of it while tracing the subject in the stars.",
    seemingBenefits:{Darkling:"Also inflict Spooked, driving the subject to reach the target as quickly as possible.",Fairest:"If the Fairest traces herself as the target, the subject gains one Goblin Debt per scene spent outside her presence."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:star-light-star-bright", name:"Star Light, Star Bright", originalName:"Star Light, Star Bright", type:"Real", page:51,
    description:"Learn a wish the target made during the last month, or a random wish made within one mile if no target is specified. The changeling chooses how to fulfill it within his actual capabilities but gains Persistent Oathbreaker if he has not done so by story's end. Paying the higher cost permits attaching a drawback to the granted wish.",
    hasRoll:false, dicePool:"None", cost:"●/●●", action:"Instant", duration:"Instant",
    loophole:"Coax the target into making the wish in the changeling's presence during the same scene.",
    seemingBenefits:{Ogre:"If the target is non-fae, gain +2 to one attempt to harvest Glamour from them.",Wizened:"Also learn the underlying force driving the wish, such as fear, hardship, or regret."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:light-of-ancient-stars", name:"Light of Ancient Stars", originalName:"Light of Ancient Stars", type:"Real", page:51,
    description:"Ask up to Wyrd questions about a past event connected to someone the changeling knows more closely than an acquaintance, or about a known event at a location she has personally visited. The Storyteller answers truthfully.",
    hasRoll:false, dicePool:"None", cost:"●●", action:"Instant", duration:"Instant",
    loophole:"Sing the names of the stars in a constellation currently visible in the sky.",
    seemingBenefits:{Darkling:"Gain Informed about the event; it fades without a Beat if unresolved by chapter's end.",Wizened:"Receive a clear image of a simple Size 3 or smaller object present and gain +2 to build a mundane facsimile, including exact writing or simple diagrams without their interpretation."},
  },
  {
    ...base, regalia:"Stars", id:"ctl-kith-and-kin:pinch-of-stardust", name:"Pinch of Stardust", originalName:"Pinch of Stardust", type:"Real", page:52,
    description:"Build a simulacrum from scraps and starlight that the target remembers as trusted and important. It can become a Touchstone or an equivalent mentor or loved one, inflicts Persistent Delusional, and causes the appropriate breaking point or Clarity risk when it crumbles. Targeting a changeling makes invocation a four-die breaking point rather than three.",
    hasRoll:true, dicePool:"Intelligence + Crafts + Wyrd vs. Resolve + Tolerance", cost:"●●●○", action:"Instant for a willing target; Contested for a hostile target", duration:"One chapter or until Delusional resolves",
    success:"Create the entity with Echoes equal to Wyrd and attach it as a Touchstone or equivalent important relationship. A self-targeting changeling forgets the invocation and believes it is real.", exceptionalSuccess:"The target's closest real friends and loved ones also remember the creature as real, though evidence can make them suspicious and they do not gain Delusional.", failure:"The Contract fails.", dramaticFailure:"The creation becomes an ill-intentioned double of the changeling, acting as a second fetch that knows what it is.",
    loophole:"Add a part of the changeling — such as hair, blood, or nail clippings — to the creature.",
    seemingBenefits:{Darkling:"Hear any secret the target whispers to the creature.",Wizened:"For +●, the creation lasts until story's end."},
  },
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:briars-herald",name:"Briar's Herald",originalName:"Briar's Herald",type:"Comum",page:53,description:"Taunt a target and promise to become a thorn in their side. Within 100 yards or meters of the changeling, the target loses 10-again and every failure becomes dramatic without granting Beats; the changeling senses every failed roll regardless of range.",hasRoll:true,dicePool:"Manipulation + Larceny + Wyrd vs. Composure + Tolerance",cost:"●",action:"Instant",duration:"One chapter",success:"The curse takes effect and the target knows the changeling is responsible despite any lack of evidence.",exceptionalSuccess:"Each failed roll in range also inflicts 1 lethal damage.",failure:"The Contract fails and the changeling suffers a minor broken-seal effect chosen by the Storyteller.",dramaticFailure:"The changeling suffers a major broken-seal effect instead.",loophole:"Directly or indirectly cause a thorn, needle, or similar pointed object to prick the target and draw blood.",seemingBenefits:{Darkling:"Whenever the victim fails, whisper a message of up to 37 words across any distance and receive one reply.",Wizened:"Specify a short clause whose fulfillment ends the Contract early."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:by-the-pricking-of-my-thumbs",name:"By the Pricking of My Thumbs",originalName:"By the Pricking of My Thumbs",type:"Comum",page:54,description:"Extend hearing, sight, smell, and touch through one perceived living plant, switching between it and the changeling as an instant action. Acting on unrelated matters while inhabiting a plant imposes −3 on actions, Defense, and Initiative.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One scene",loophole:"Brew poison ivy, newt, and thistles into a potion during the same scene and peer into it.",seemingBenefits:{Beast:"Use the inhabited plant as a Strength + Brawl or Weaponry natural weapon dealing bashing damage, or lethal if it has thorns or needles.",Darkling:"Occupy up to Resolve plants simultaneously, shifting or withdrawing one sensory extension per instant action."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:thistles-rebuke",name:"Thistle's Rebuke",originalName:"Thistle's Rebuke",type:"Comum",page:54,description:"Grow thorns from clothing or armor, adding two general armor, dealing 1 lethal to anyone who touches or engages the changeling in melee, and 2 lethal per grapple turn. Fire them up to 50 yards or meters as a 2L weapon, forfeiting the other benefits that turn.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One scene",loophole:"Drink an entire glass of water immediately before invocation.",seemingBenefits:{Elemental:"Reflexively retract or extend the thorns; extending them deals 2 lethal to anyone touching the Elemental.",Fairest:"Make the effect invisible even to observers who see through the Mask."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:the-gouging-curse",name:"The Gouging Curse",originalName:"The Gouging Curse",type:"Comum",page:54,description:"Issue a warning that forbids one specific instant action the target could perform during the chapter.",hasRoll:true,dicePool:"Manipulation + Occult + Wyrd vs. Composure + Tolerance",cost:"●",action:"Instant",duration:"One chapter",success:"If the target performs the forbidden action, barbs inflict Arm Wrack, Blinded in one eye, Deafened in one ear, or Leg Wrack until the Contract ends.",exceptionalSuccess:"Triggering the curse also inflicts Guilty.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Reckless.",loophole:"Make an agreement allowing the victim to forbid one action by the changeling; violating it requires immediately paying ● and taking 1 lethal damage, or the Contract ends.",seemingBenefits:{Fairest:"Specify another valid action that ends the curse early but inflicts Persistent Awestruck regarding the Fairest.",Ogre:"If the forbidden act would harm an ally, duration becomes one story."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:embrace-of-nettles",name:"Embrace of Nettles",originalName:"Embrace of Nettles",type:"Comum",page:55,description:"While in the Hedge's Thorns, respond to a Hedge shift by deflecting it to another target; deferring up to half Wyrd successes into the Hedge's next successful, immune roll; or adding up to half Wyrd successes to both its roll and the changeling's next successful Hedgespinning roll this scene. Each option must be used before repeating one.",hasRoll:false,dicePool:"None",cost:"●",action:"Reflexive",duration:"Instant",loophole:"Leave a meaningful personal possession for the Hedge to consume; recovering it later gives 2 Goblin Debt.",seemingBenefits:{Darkling:"When deferring, negate up to Manipulation or half Wyrd successes, whichever is preferred.",Fairest:"When doubling down, grant the later bonus successes to an ally instead."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:acanthas-fury",name:"Acantha's Fury",originalName:"Acantha's Fury",type:"Real",page:55,description:"Begin an eight-stage, one-stage-per-minute transformation of the target into a Size 4–12 thorny plant. At every stage offer an achievable, harmless one-scene task; accepting makes the transformation regress, but breaking the promise restarts it. Stages impose sunlight penalties, reduced Stamina, limb Tilts, Immobilized, and finally complete plant form. Invocation is a four-die breaking point.",hasRoll:true,dicePool:"Presence + Survival + Wyrd vs. Stamina + Tolerance",cost:"●●○",action:"Contested",duration:"One scene",success:"The staged transformation begins and may be reversed by accepting the binding task.",exceptionalSuccess:"Regain 1 Willpower when the target successfully fulfills the promise.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Hunted.",loophole:"Hold a fresh, no-more-than-one-day-old clipping of the plant species chosen for the transformation.",seemingBenefits:{Elemental:"Target up to Wyrd characters, tracking each progression separately.",Wizened:"Seal the accepted promise without Glamour; increasing seal severity costs ● instead of ○."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:awaken-portal",name:"Awaken Portal",originalName:"Awaken Portal",type:"Real",page:56,description:"Smear blood on an unguarded Hedgeway, Bastion, or Hollow entrance to awaken it as a stationary goblin. It perceives its surroundings, communicates mentally over any distance, and permits kenning from its viewpoint; blocking or sealing it inhibits its senses.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"One chapter",loophole:"Spend at least 15 minutes during the scene cleaning, repairing, or improving the entrance and its surroundings before awakening it.",seemingBenefits:{Beast:"The portal gains a reflexive Presence + Intimidation 2L bite that ejects intruders five yards or meters.",Elemental:"The portal gains a two-dot Influence in the Elemental's chosen element."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:crown-of-thorns",name:"Crown of Thorns",originalName:"Crown of Thorns",type:"Real",page:57,description:"Anonymously deliver a written prohibition against one specific instant action.",hasRoll:true,dicePool:"Presence + Occult + Wyrd vs. Resolve + Tolerance",cost:"●●",action:"Contested",duration:"One story",success:"If the target performs the forbidden act, invisible thorns inflict 1 lethal damage and Comatose. Non-changelings require dream intervention or a supernatural Clash of Wills to awaken; otherwise the Condition fades without a Beat at story's end.",exceptionalSuccess:"Comatose must resolve properly and does not fade at story's end.",failure:"The Contract fails.",dramaticFailure:"The changeling becomes Comatose instead.",loophole:"Weave a real crown of thorns and place it on the target's head during the same scene.",seemingBenefits:{Beast:"The sleeping target loses 1 Willpower each night and cannot regain Willpower through rest.",Darkling:"While disguised or unnoticed, achieve exceptional success on three successes when manipulating the target into the forbidden act."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:shrikes-larder",name:"Shrike's Larder",originalName:"Shrike's Larder",type:"Real",page:57,description:"Spend ● per effect, up to all three, to curse one target with spines: −2 to chase movement rolls and no Edge, bypassed for one turn with ○; −3 Initiative; or halved Speed, bypassed for one turn by taking 1 bashing damage.",hasRoll:false,dicePool:"None",cost:"● to ●●●",action:"Instant",duration:"One scene",loophole:"Impale an effigy of the target on a thorn or another small piercing object.",seemingBenefits:{Beast:"Harvest 2 Glamour per success from the victim instead of 1.",Wizened:"Target a vehicle, applying the effects to occupants and flattening its tires."}},
  {...base,regalia:"Thorn",id:"ctl-kith-and-kin:witchs-brambles",name:"Witch's Brambles",originalName:"Witch's Brambles",type:"Real",page:58,description:"While performing a mundane action with a precise, Size 1 or smaller flesh-piercing object, suffer −3 and spend excess successes on subtle shifts as though Hedgespinning, without its other effects. On an exceptional success, paying the higher cost permits a paradigm shift. The Contract has no effect in the Hedge or another otherworldly realm.",hasRoll:false,dicePool:"None",cost:"●●○/●●●○",action:"Reflexive",duration:"Instant",loophole:"Pierce the changeling's own flesh with the pointed object used for invocation.",seemingBenefits:{Beast:"Instead enhance a bite attack that deals lethal or aggravated damage.",Darkling:"Add one success when using only subtle shifts, but subtract one when using any paradigm shift."}},
];
