import type { SeemingKey } from "./contract-details";

export type ReviewedContractDetail = {
  dicePool: string;
  cost: string;
  action: string;
  duration: string;
  loophole: string;
  seemingBenefits: Partial<Record<SeemingKey,string>>;
};

export const REVIEWED_CONTRACT_DETAILS_PT: Record<string,ReviewedContractDetail> = {
  "ctl-2ed:hostile-takeover": { dicePool:"Nenhum", cost:"2 Glamour", action:"Instantânea", duration:"Cena", loophole:"O changeling carrega um objeto pertencente ao proprietário ou residente principal.", seemingBenefits:{ Beast:"A Besta convence sentinelas animais a servi-la ativamente.", Fairest:"A Belíssima recebe +2 dados no Choque de Vontades contra o proprietário de uma habitação sobrenatural." } },
  "ctl-2ed:mask-of-superiority": { dicePool:"Presença + Subterfúgio + Fado", cost:"1 Glamour", action:"Instantânea", duration:"Cena", loophole:"O changeling veste uma imitação aproximada do código de vestimenta da organização; roupas brancas comuns e um boné, por exemplo, podem passar por uniforme naval.", seemingBenefits:{ Fairest:"Reduza em um todas as Portas iniciais nas Manobras Sociais que a Belíssima iniciar contra personagens afetados.", Ogre:"O Ogro parece integrar a segurança da organização. Some os sucessos da ativação, até +5, aos testes de Intimidação contra quem acreditar no disfarce." } },
  "ctl-2ed:paralyzing-presence": { dicePool:"Presença + Intimidação + Fado vs. Compostura + Fado", cost:"2 Glamour", action:"Disputada", duration:"Um turno", loophole:"A vítima está sozinha, exceto pelo changeling, e ele a toca.", seemingBenefits:{ Darkling:"O Trevoso pode usar Manipulação no lugar de Presença para ativar o Contrato.", Fairest:"A Belíssima recebe +3 dados para ativar o Contrato." } },
  "ctl-2ed:summon-the-loyal-servant": { dicePool:"Nenhum", cost:"1 Glamour", action:"Instantânea", duration:"Uma cena ou até o servo ser destruído", loophole:"Nesta cena, o changeling prestou um favor significativo ao elemento ou material, como limpar completamente uma fonte pública ou polir uma grande estátua de pedra.", seemingBenefits:{ Elemental:"Por +1 Glamour e 1 Força de Vontade, o Elemental pode fundir-se ao servo: substitui seus Atributos pelos do servo quando desejar, torna-se imune ao dano do elemento ou material e recebe +1L no modificador de arma de seus ataques.", Fairest:"A Belíssima pode gastar 1 Força de Vontade para vincular o servo ao seu Recanto. Ele permanece animado enquanto estiver lá; só pode existir um servo vinculado por vez." } },
  "ctl-2ed:tumult": { dicePool:"Presença + Empatia + Fado − Perseverança", cost:"2 Glamour", action:"Instantânea", duration:"Instantânea", loophole:"Nesta cena, o changeling colocou um pássaro de origami junto aos pertences ou às roupas do alvo.", seemingBenefits:{ Fairest:"Acrescente Inspirado, Arrebatado e Devasso à lista de Condições possíveis.", Ogre:"Acrescente Bestial, Acovardado e Aterrorizado à lista de Condições possíveis." } },
  "ctl-2ed:discreet-summons": { dicePool:"Manipulação + Persuasão + Fado vs. Compostura + Fado", cost:"1 Glamour (objeto) ou 2 Glamour (hobgoblin)", action:"Instantânea (objeto) ou Disputada (hobgoblin)", duration:"Uma cena; termina antes se o objeto deixar suas mãos ou se deixar de prestar atenção ao hobgoblin", loophole:"Para o objeto, retire-o de um local pertencente a um inimigo ou guardado por ele. Para o hobgoblin, prometa algo difícil de obter por razões práticas ou morais e cumpra a promessa.", seemingBenefits:{ Darkling:"O Trevoso pode retirar o objeto ou convocar o hobgoblin de qualquer sombra ou espaço escuro grande o bastante.", Fairest:"O hobgoblin convocado serve até a próxima vez em que o sol cruzar o horizonte, mesmo sem receber atenção constante." } },
  "ctl-2ed:masterminds-gambit": { dicePool:"Nenhum", cost:"2 Glamour", action:"Instantânea; o monólogo leva ao menos cinco minutos", duration:"Um capítulo, ou até o plano triunfar ou fracassar definitivamente", loophole:"O changeling registra a hierarquia da organização, o índice do repositório ou o plano em papel com pelo menos 50 anos.", seemingBenefits:{ Elemental:"Gaste 1 Força de Vontade para fazer um repositório durar pela história e abranger uma Especialização de Perícia Mental que possua; a informação assume uma forma ligada ao elemento do personagem.", Fairest:"A Belíssima pode criar uma organização em vez de um plano ou repositório; o Glamour reúne os mortais adequados para combater a influência do inimigo." } },
  "ctl-2ed:pipes-of-the-beastcaller": { dicePool:"Manipulação + Empatia com Animais + Fado vs. Perseverança + Compostura", cost:"1 Glamour", action:"Instantânea (animais dispostos) ou Disputada (hostis)", duration:"Até a tarefa terminar; em sucesso excepcional, um dia e uma noite", loophole:"Enquanto toca a flauta, o changeling dança imitando os movimentos da espécie que deseja convocar.", seemingBenefits:{ Beast:"A Besta mantém um vínculo empático com os animais comandados: pode dar novas ordens à distância e conhece sua condição física geral e posição relativa.", Fairest:"Por +1 Glamour, a Belíssima pode convocar e comandar uma segunda espécie animal." } },
  "ctl-2ed:the-royal-court": { dicePool:"Nenhum", cost:"3 Glamour + 1 Força de Vontade", action:"Instantânea", duration:"Uma cena", loophole:"O changeling se levanta e faz um discurso com pelo menos cinco minutos de duração.", seemingBenefits:{ Fairest:"A proteção também impede intimidação e ameaças entre os alvos, embora ainda permita gentilezas destinadas a promover boa vontade.", Wizened:"A proteção também impede dano mental, inclusive ataques à Lucidez, mas não pontos de ruptura." } },
  "ctl-2ed:spinning-wheel": { dicePool:"Inteligência + Ocultismo + Fado − Perseverança", cost:"3 Glamour + 1 Força de Vontade", action:"Prolongada; cada teste leva 10 minutos, com sucessos necessários iguais ao maior entre Fado e Perseverança do alvo", duration:"Até o fim do mês lunar ou até o evento ocorrer", loophole:"O changeling perfura o alvo com uma agulha ou alfinete e extrai ao menos uma gota de sangue; isso não causa dano em um alvo voluntário.", seemingBenefits:{ Fairest:"A Belíssima recebe +3 dados para ativar o Contrato ao promover uma experiência positiva e recebe Inspirado para ações que favoreçam sua ocorrência.", Ogre:"O Ogro recebe +3 dados para ativar o Contrato ao promover uma experiência negativa e recebe Resoluto para ações que favoreçam sua ocorrência." } },
};

export const REVIEWED_CONTRACT_DETAILS_EN: Record<string,ReviewedContractDetail> = {
  "ctl-2ed:hostile-takeover": { dicePool:"None", cost:"2 Glamour", action:"Instant", duration:"One scene", loophole:"The changeling carries an object that belongs to the owner or main resident.", seemingBenefits:{ Beast:"The Beast persuades animal sentries to actively serve her.", Fairest:"The Fairest gains two bonus dice on the Clash of Wills against the owner of a supernatural dwelling." } },
  "ctl-2ed:mask-of-superiority": { dicePool:"Presence + Subterfuge + Wyrd", cost:"1 Glamour", action:"Instant", duration:"One scene", loophole:"The changeling loosely imitates the organization's dress code; plain white slacks, shirt, and hat can pass for a marine uniform.", seemingBenefits:{ Fairest:"Reduce all starting Doors by one for Social maneuvering the Fairest initiates against affected characters.", Ogre:"The Ogre appears to be organization security. Add invocation successes, up to +5, to Intimidation rolls against anyone who believes the ruse." } },
  "ctl-2ed:paralyzing-presence": { dicePool:"Presence + Intimidation + Wyrd vs. Composure + Wyrd", cost:"2 Glamour", action:"Contested", duration:"One turn", loophole:"The victim is otherwise alone and the changeling touches them.", seemingBenefits:{ Darkling:"The Darkling may use Manipulation instead of Presence to invoke the Contract.", Fairest:"The Fairest gains a three-die bonus to invoke the Contract." } },
  "ctl-2ed:summon-the-loyal-servant": { dicePool:"None", cost:"1 Glamour", action:"Instant", duration:"One scene or until the servitor is destroyed", loophole:"During this scene, the changeling performed a significant favor for the element or material, such as thoroughly cleaning a public fountain or polishing a large stone statue.", seemingBenefits:{ Elemental:"For 1 additional Glamour and 1 Willpower, the Elemental may merge with the servitor: substitute its Attributes for his where desired, become immune to damage from its element or material, and add +1L to his attack weapon modifier.", Fairest:"The Fairest may spend 1 Willpower to bind the servitor to his Hollow. It remains animate while inside; he may only have one bound servitor at a time." } },
  "ctl-2ed:tumult": { dicePool:"Presence + Empathy + Wyrd − Resolve", cost:"2 Glamour", action:"Instant", duration:"Instant", loophole:"During this scene, the changeling planted an origami bird on the target's person.", seemingBenefits:{ Fairest:"Add Inspired, Swooned, and Wanton to the available Conditions.", Ogre:"Add Bestial, Cowed, and Frightened to the available Conditions." } },
  "ctl-2ed:discreet-summons": { dicePool:"Manipulation + Persuasion + Wyrd vs. Composure + Wyrd", cost:"1 Glamour (object) or 2 Glamour (hobgoblin)", action:"Instant (object) or contested (hobgoblin)", duration:"One scene; ends earlier if the object leaves his hands or he stops paying attention to the hobgoblin", loophole:"For an object, retrieve it from a place owned or guarded by an enemy. For a hobgoblin, promise something practically or morally difficult to procure and keep the promise.", seemingBenefits:{ Darkling:"The Darkling may draw the object or summon the hobgoblin from any sufficiently large shadow or dark space.", Fairest:"The summoned hobgoblin serves until the sun next crosses the horizon, even without constant attention." } },
  "ctl-2ed:masterminds-gambit": { dicePool:"None", cost:"2 Glamour", action:"Instant; the monologue takes at least five minutes", duration:"One chapter, or until the plan definitively succeeds or fails", loophole:"The changeling records the organization's hierarchy, repository index, or plan on paper at least 50 years old.", seemingBenefits:{ Elemental:"Spend 1 Willpower to make a repository last for the story and encompass one Mental Skill Specialty you possess; its information assumes a form tied to your element.", Fairest:"The Fairest may create an organization instead of a plan or repository; Glamour assembles the right mortals to counter the enemy's influence." } },
  "ctl-2ed:pipes-of-the-beastcaller": { dicePool:"Manipulation + Animal Ken + Wyrd vs. Resolve + Composure", cost:"1 Glamour", action:"Instant (willing animals) or contested (hostile animals)", duration:"Until the task ends; one day and one night on an exceptional success", loophole:"While playing the flute, the changeling dances in imitation of the species he wishes to summon.", seemingBenefits:{ Beast:"The Beast maintains an empathic link with the commanded animals, can issue new orders remotely, and knows their general condition and relative location.", Fairest:"For 1 additional Glamour, the Fairest may summon and command a second animal species." } },
  "ctl-2ed:the-royal-court": { dicePool:"None", cost:"3 Glamour + 1 Willpower", action:"Instant", duration:"One scene", loophole:"The changeling stands and gives a speech lasting at least five minutes.", seemingBenefits:{ Fairest:"The protection also prevents targets from intimidating or threatening one another, though they may still use pleasantries to foster goodwill.", Wizened:"The protection also prevents mental harm, including Clarity attacks, but not breaking points." } },
  "ctl-2ed:spinning-wheel": { dicePool:"Intelligence + Occult + Wyrd − Resolve", cost:"3 Glamour + 1 Willpower", action:"Extended; each roll takes 10 minutes, requiring successes equal to the higher of the target's Wyrd or Resolve", duration:"Until the lunar month ends or the event occurs", loophole:"The changeling pricks the target with a needle or pin and draws at least one drop of blood; this causes no damage to a willing target.", seemingBenefits:{ Fairest:"The Fairest gains +3 dice to invoke the Contract when encouraging a positive experience and gains Inspired for actions supporting its occurrence.", Ogre:"The Ogre gains +3 dice to invoke the Contract when encouraging a negative experience and gains Steadfast for actions supporting its occurrence." } },
};
