import type { ContractDefinition } from "./contracts";

const base = {
  categoryKind: "Regalia" as const,
  regalia: "Chalice",
  sourceId: "ctl-kith-and-kin",
  source: "Kith and Kin",
};

export const KITH_AND_KIN_CONTRACTS: ContractDefinition[] = [
  {
    ...base, id:"ctl-kith-and-kin:filling-the-cup", name:"Filling the Cup", originalName:"Filling the Cup", type:"Comum", page:34,
    description:"The changeling identifies people experiencing powerful emotions within Wyrd x 40 yards or meters, learning their direction, general distance, and whether each emotion is positive or negative. He also automatically notices Bedlam incited within range.",
    hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"One scene or until the changeling regains Glamour, whichever comes first",
    loophole:"The changeling publicly states his strongest current emotion and its cause or subject when invoking the Contract.",
    seemingBenefits:{
      Beast:"After previously identifying a known person's emotions with this or another relevant power, the Beast can recognize that person again at range by the scent of their feelings.",
      Fairest:"The Fairest can distinguish people in range experiencing an intense emotion related to him, though he learns the emotion rather than the person's identity.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:frail-as-the-dying-word", name:"Frail as the Dying Word", originalName:"Frail as the Dying Word", type:"Comum", page:35,
    description:"By touching the target, the changeling tricks the Wyrd into applying one of his own frailties to them.",
    hasRoll:true, dicePool:"Manipulation + Occult + Wyrd vs. Composure + Tolerance", cost:"●", action:"Contested", duration:"One scene",
    success:"The target gains one of the changeling's minor frailties. If already possessed, it becomes major for the duration; a target already suffering its major version is unaffected. The changeling retains the frailty.",
    exceptionalSuccess:"The changeling may instead inflict one major frailty or two minor frailties. Iron counts as major.", failure:"The Contract fails.",
    dramaticFailure:"The Wyrd inflicts a new major frailty on the changeling for the scene.",
    loophole:"The changeling has suffered from the chosen frailty during the same scene.",
    seemingBenefits:{
      Fairest:"The Fairest may inflict a frailty belonging to any fae being present rather than one of his own.",
      Darkling:"For +●, the Darkling transfers the frailty instead of sharing it, losing it for the duration. This cannot transfer his iron bane.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:sleeps-sweet-embrace", name:"Sleep's Sweet Embrace", originalName:"Sleep's Sweet Embrace", type:"Comum", page:35,
    description:"The changeling touches the target and replaces their dreams with restorative, dreamless sleep. The invocation is resisted only if the target is unwilling.",
    hasRoll:true, dicePool:"Manipulation + Expression + Wyrd - Resolve", cost:"●●○", action:"Instant or resisted", duration:"A number of days equal to successes",
    success:"Whenever the target sleeps during the duration, they heal 1 lethal damage per hour but regain no Willpower from rest. They have no Bastion and cannot be affected by oneiromancy or dream magic. More than two days causes Dissociation until they regain full Willpower after the Contract ends.",
    exceptionalSuccess:"The target suffers Dissociation only if the effect lasts more than three days.", failure:"The Contract fails.",
    dramaticFailure:"The next time the changeling sleeps, he cannot meditate, enter the Gate of Ivory, or dream. He suffers the Contract's drawbacks for one night without its healing.",
    loophole:"During the same scene, the changeling persuades or forces the target to completely consume a prepared drink used as a sleep aid.",
    seemingBenefits:{
      Beast:"The Beast adds two days to the Contract's duration.",
      Darkling:"While asleep, the Darkling's target appears recently dead to mundane examination; supernatural detection prompts a Clash of Wills.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:curses-cure", name:"Curse's Cure", originalName:"Curse's Cure", type:"Comum", page:36,
    description:"The changeling mixes the target's blood, Hedge herbs, his spit, and wine into one full dose of antidote for a single poisoned victim.",
    hasRoll:true, dicePool:"Intelligence + Medicine + Wyrd", cost:"●", action:"Instant", duration:"Instant",
    success:"Drinking the full dose halves a poison's recovery time or makes a lethal poison survivable. Related Conditions fade without resolution. Supernatural poison requires a Clash of Wills.",
    exceptionalSuccess:"The poison is completely and immediately cured.", failure:"The Contract fails.",
    dramaticFailure:"The changeling poisons himself, gaining Fatigued, which becomes the moderate Poisoned Tilt in action scenes.",
    loophole:"The changeling tastes the same toxin during the scene; the Contract does not protect him from that exposure.",
    seemingBenefits:{
      Beast:"During the chapter, the Beast may bite a grappled opponent as a unique grapple action to inflict moderate Poisoned.",
      Wizened:"The Wizened may instead reduce a disease's severity or end a drug's effects; related Conditions fade without resolution.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:dreamers-phalanx", name:"Dreamer's Phalanx", originalName:"Dreamer's Phalanx", type:"Comum", page:36,
    description:"Willing sleepers in physical contact enter a shared dream whose distinct Bastions count as one for oneiromancy. Each gains +1 Fortification per participant, maximum +5, against outsiders; teamwork within the linked Bastions gains 8-again, and location shifts may move subjects between Bastions. Forced magical awakening destroys every linked Bastion.",
    hasRoll:false, dicePool:"None", cost:"● + ●/subject beyond 2nd", action:"Instant", duration:"One chapter or until all participants wake",
    loophole:"All participants belong to the same sworn oath, including one sworn for this purpose during the same scene.",
    seemingBenefits:{
      Beast:"All participants gain +2 to actions contested by an outside oneiropomp intruding on any linked Bastion.",
      Wizened:"Teamwork between participants also achieves exceptional success on three successes.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:closing-deaths-door", name:"Closing Death's Door", originalName:"Closing Death's Door", type:"Real", page:36,
    description:"With an intimate gesture, the changeling attempts to return a recently dead character to life.",
    hasRoll:true, dicePool:"Manipulation + Empathy + Wyrd", cost:"●●●○", action:"Instant", duration:"Instant",
    success:"A character dead for no more than one chapter returns with every Health box filled with aggravated damage except the undamaged rightmost box. The changeling gains Goblin Debt equal to hours dead, minimum 1 and subject to the usual maximum.",
    exceptionalSuccess:"The Contract can revive someone who died at any point in the current story; otherwise a target dead longer than one chapter cannot be revived.", failure:"The Contract fails.",
    dramaticFailure:"The corpse becomes a mindless marionette with one Health box, no Willpower, and all dice pools equal to the changeling's Wyrd.",
    loophole:"The deceased is the changeling's Touchstone, a fae-touched promised to him, or someone bound to him by a personal oath.",
    seemingBenefits:{
      Fairest:"The revived character gains Swooned regarding the Fairest.",
      Darkling:"The Darkling briefly experiences the deceased's final moments from their point of view.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:feast-of-plenty", name:"Feast of Plenty", originalName:"Feast of Plenty", type:"Real", page:37,
    description:"The changeling publicly offers freely given food, drink, medicine, or similar comforts to everyone present.",
    hasRoll:true, dicePool:"Presence + Socialize + Wyrd", cost:"●●", action:"Instant", duration:"Instant",
    success:"The Contract creates enough suitable nourishment or medicine for everyone present. A willing participant removes one physical non-Persistent Condition or one physical Personal Tilt and regains Willpower equal to half the successes, rounded up, but gains Indebted to the changeling. The changeling cannot benefit from his own feast.",
    exceptionalSuccess:"Indebted becomes Persistent.", failure:"The Contract fails.", dramaticFailure:"The changeling gains Notoriety.",
    loophole:"During the scene, the changeling greets everyone present by name with a gesture, learning and using any unknown names before invocation.",
    seemingBenefits:{
      Elemental:"Everyone perceiving the feast contests with Composure + Wyrd or is compelled to partake.",
      Ogre:"Participants gain +1 Defense for the rest of the chapter.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:still-waters-run-deep", name:"Still Waters Run Deep", originalName:"Still Waters Run Deep", type:"Real", page:38,
    description:"The target watches the changeling's serene breathing as he suppresses their emotional turmoil and joy.",
    hasRoll:true, dicePool:"Manipulation + Subterfuge + Wyrd - Resolve", cost:"●●", action:"Instant", duration:"One scene",
    success:"Suppress emotional Conditions equal to successes, including Clarity and Bedlam Conditions. Their effects, resolutions, and Beats are suspended, and the target cannot gain new emotional Conditions, Hedgespin, dreamweave, incite Bedlam, or harvest Glamour from living beings during the scene.",
    exceptionalSuccess:"Additional successes only increase the number of suppressed Conditions.", failure:"The Contract fails.",
    dramaticFailure:"The changeling gains either one suppressed detrimental Condition from the target or Demoralized, chosen by the Storyteller, and must resolve it normally.",
    loophole:"During the scene, the changeling writes at least one paragraph about his current emotional state and seals it in a bottle.",
    seemingBenefits:{
      Wizened:"The Wizened may suppress purely mental Conditions as well as emotional ones.",
      Ogre:"The Ogre may resolve one suppressed temporary Condition during the effect and receives its resolution Beat instead of the target.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:poison-the-well", name:"Poison the Well", originalName:"Poison the Well", type:"Real", page:38,
    description:"The changeling poisons the target's relationship with the subject of one Social Merit.",
    hasRoll:true, dicePool:"Manipulation + Expression + Wyrd vs. Resolve + Tolerance", cost:"●", action:"Contested", duration:"One chapter",
    success:"A mundane Social Merit becomes inaccessible and its subject actively hinders the target. In the Hedge, an eligible changeling-specific connection Merit may instead remain usable but inflict Goblin Debt equal to its rating per use; this counts as Hedgespinning without its usual invocation penalty.",
    exceptionalSuccess:"The target also gains Notoriety.", failure:"The Contract fails.",
    dramaticFailure:"The changeling poisons his own most important connections, detaching one Touchstone from his Clarity track for the chapter.",
    loophole:"During the scene, the changeling personally interacts with the Merit's subject to sow conflict or sabotage the resource.",
    seemingBenefits:{
      Fairest:"The Fairest gains access to the poisoned Merit for the Contract's duration.",
      Elemental:"When the Contract ends, the target's Merit returns at one dot per scene rather than immediately.",
    },
  },
  {
    ...base, id:"ctl-kith-and-kin:shared-cup", name:"Shared Cup", originalName:"Shared Cup", type:"Real", page:39,
    description:"The changeling equally shares a drink or meal with a group, creating a supernatural emotional bond among willing or unwitting participants.",
    hasRoll:true, dicePool:"Presence + Occult + Wyrd vs. Composure + Tolerance", cost:"● + ●/subject beyond 2nd", action:"Instant or contested", duration:"One chapter",
    success:"Bind participants up to successes, including the changeling. Their Social impressions improve one step and they suffer -3 to contest each other's Social actions. Emotional Conditions, Personal Tilts, recovered Willpower, and recovered Glamour propagate to the group; non-Wyrd participants gain Inspired instead of Glamour. Hedgespinning and Bedlam achieve exceptional success on three successes.",
    exceptionalSuccess:"Additional successes increase the maximum participants.", failure:"The Contract fails.",
    dramaticFailure:"The changeling involuntarily incites Bedlam in every participant without a roll.",
    loophole:"During the shared meal's scene, the changeling collects blood, hair, nail clippings, or another body part from every participant.",
    seemingBenefits:{
      Darkling:"By paying ● when a shared effect would occur, the Darkling can briefly exclude himself from that effect and all passive effects; others may notice with Wits + Composure contested by his Wits + Wyrd.",
      Fairest:"Every other participant gains Swooned regarding the Fairest upon invocation.",
    },
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:book-of-black-and-red", name:"Book of Black and Red", originalName:"Book of Black and Red", type:"Comum", page:39,
    description:"The changeling reads the five most significant mundane or supernatural debts and sworn obligations burdening a visible target, including their Goblin Debt. Exploiting this knowledge during the chapter grants +2 and gives the target Leveraged regarding her.",
    hasRoll:true, dicePool:"Wits + Academics + Wyrd vs. Resolve + Tolerance", cost:"●", action:"Instant", duration:"Instant",
    success:"Learn the target's five most significant debts and obligations and their Goblin Debt total.", exceptionalSuccess:"Also learn each debt's creditor, origin, and obstacle to repayment.", failure:"The Contract fails.", dramaticFailure:"The changeling gains 1 Goblin Debt.",
    loophole:"The target allowed the changeling to examine their records or accounts during the scene.",
    seemingBenefits:{Darkling:"The Darkling may interpose herself in one non-Goblin, non-pledge debt: the target owes her, while she owes the original creditor; defaulting gives her Oathbreaker.",Wizened:"The Wizened needs only three successes for exceptional success when exploiting this knowledge."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:give-and-take", name:"Give and Take", originalName:"Give and Take", type:"Comum", page:40,
    description:"With consent, exchange up to half the changeling's Wyrd in points between different categories of Glamour, Willpower, social currency, or personal-scale Merit dots. Merit exchanges last one scene, require prerequisites, cannot affect world-scale Merits, and cannot exchange one Merit for another.",
    hasRoll:false, dicePool:"None", cost:"●/●●", action:"Instant", duration:"Instant, or one scene for Merits",
    loophole:"The parties permanently exchange new physical gifts of equal value or meaning.",
    seemingBenefits:{Ogre:"The Ogre may exchange points of mild Clarity damage.",Wizened:"The exchange need not be equal, but each party must consensually contribute at least one point."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:beggar-knight", name:"Beggar Knight", originalName:"Beggar Knight", type:"Comum", page:40,
    description:"The changeling curses someone who can hear and understand her to benefit only from things he personally makes.",
    hasRoll:true, dicePool:"Manipulation + Academics + Wyrd - Composure", cost:"●●", action:"Instant", duration:"One chapter per success",
    success:"The victim gains no equipment, damage, or armor bonus from items he did not make; failures with them become dramatic without a Beat. He loses externally created Resources and cannot receive teamwork bonuses.", exceptionalSuccess:"Invocation successes also become an immediate Clarity attack, or a breaking-point penalty for a target without Clarity.", failure:"The Contract fails.", dramaticFailure:"For the chapter, the changeling loses her Resources to the target and takes 1 of his Goblin Debt, if any.",
    loophole:"During the scene, the victim directly benefited from another's work rather than his own.",
    seemingBenefits:{Elemental:"Mundane possessions the victim did not make degrade until permanently transferred away, and disintegrate if returned.",Wizened:"The curse also denies others Resources produced through the victim's constructive work until his involvement ends."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:coin-mark", name:"Coin Mark", originalName:"Coin Mark", type:"Comum", page:41,
    description:"The changeling enchants a coin, bill, gift, or other traded object. She always knows its direction and distance, and learns each new owner's identity and transaction price. After interacting with its owner, she may spend ● to inflict Avarice.",
    hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"One story", loophole:"The changeling permanently marks her name on the object.",
    seemingBenefits:{Beast:"The Beast may inflict Apprehensive regarding the object instead of Avarice.",Wizened:"The Wizened may reflexively snap her fingers to return the object immediately to her person."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:grease-the-wheels", name:"Grease the Wheels", originalName:"Grease the Wheels", type:"Comum", page:41,
    description:"Direct interaction with the correct official makes a normally available administrative or bureaucratic result resolve in the changeling's favor in one-tenth the usual time, without scrutiny or red tape.",
    hasRoll:true, dicePool:"Presence + Persuasion + Wyrd", cost:"●", action:"Instant", duration:"Instant",
    success:"The administrative process resolves favorably in one-tenth its normal time, provided the organization could normally produce that outcome.", exceptionalSuccess:"It resolves immediately and favorably despite sheer improbability.", failure:"The process proceeds normally.", dramaticFailure:"The matter becomes hopelessly stalled for at least the rest of the story.",
    loophole:"The official accepts a bribe or gift from the changeling during the scene.",
    seemingBenefits:{Darkling:"The Darkling's interaction leaves no trace except where useful to her.",Fairest:"The Fairest gains Connected regarding the organization."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:blood-debt", name:"Blood Debt", originalName:"Blood Debt", type:"Real", page:42,
    description:"Whenever someone inflicts lethal or aggravated Health damage, or mild or severe Clarity damage, on the changeling, that offender suffers 1 lethal damage ignoring armor. Add 1 damage for each of: causing lost Willpower, causing lost Glamour, and inflicting a Condition or Tilt.",
    hasRoll:false, dicePool:"None", cost:"●●", action:"Instant", duration:"One scene", loophole:"Jewelry or another adornment freshly cuts or pierces the changeling during the scene.",
    seemingBenefits:{Elemental:"The Elemental's retaliation begins at 2 lethal damage.",Ogre:"While conscious, the Ogre may retaliate against damage inflicted on her allies instead of herself."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:exchange-of-gilded-contracts", name:"Exchange of Gilded Contracts", originalName:"Exchange of Gilded Contracts", type:"Real", page:42,
    description:"With another changeling's consent, borrow one Common Contract they know. The borrower gains only her own Seeming benefits and cannot use its Loophole; the lender loses access and temporarily receives Exchange of Gilded Contracts, which can only end the exchange reflexively.",
    hasRoll:false, dicePool:"None", cost:"●●●", action:"Instant", duration:"Up to one chapter", loophole:"During the scene, each party wears a convincing mask of the other.",
    seemingBenefits:{Darkling:"The Darkling may exploit the borrowed Contract's Loophole.",Ogre:"The Ogre retains the borrowed Contract until chapter's end even if recalled, but loses its Loophole after recall."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:golden-promise", name:"Golden Promise", originalName:"Golden Promise", type:"Real", page:42,
    description:"The changeling projects impossible affluence to lower the Availability of a feasible service she wishes to obtain.",
    hasRoll:true, dicePool:"Presence + Socialize + Wyrd - Availability", cost:"●●", action:"Instant", duration:"Instant",
    success:"Reduce one service's Availability by successes, potentially to zero; repeated invocations may reduce it further, and no additional recompense is required beyond the reduced Availability.", exceptionalSuccess:"The changeling also gains Connected to the provider.", failure:"The Contract fails.", dramaticFailure:"Her pretense is exposed and she gains Notoriety.",
    loophole:"The changeling arrives displaying ostentatious wealth and openly flaunts it.",
    seemingBenefits:{Fairest:"The Fairest may divide successes among multiple services in the scene.",Wizened:"The Wizened adds +1 to the acquired service's equipment bonus."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:grand-revel-of-the-harvest", name:"Grand Revel of the Harvest", originalName:"Grand Revel of the Harvest", type:"Real", page:43,
    description:"For the scene, everyone except the changeling who deliberately celebrates achieves exceptional success on Social rolls with three successes and improves Social impressions one step. Until chapter's end, affected characters regain +1 Willpower, heal +1 Health or Clarity damage of the same type, and add +1 equipment bonus to acquired windfalls.",
    hasRoll:false, dicePool:"None", cost:"●●●○", action:"Instant", duration:"One chapter", loophole:"The changeling supplies a feast for everyone present and visibly participates in every revel.",
    seemingBenefits:{Beast:"Revelers gain +2 to Physical rolls for mutual competition and physical entertainment during the scene.",Fairest:"Social impressions improve two steps instead of one."},
  },
  {
    ...base, regalia:"Coin", id:"ctl-kith-and-kin:thirty-pieces", name:"Thirty Pieces", originalName:"Thirty Pieces", type:"Real", page:44,
    description:"The changeling plants a command to perform one genuine betrayal, immediately or when a trigger occurs before story's end. It cannot compel self-harm or a non-treacherous act, and a new invocation replaces an existing pending one.",
    hasRoll:true, dicePool:"Wits + Empathy + Wyrd vs. Resolve + Tolerance", cost:"●●●", action:"Instant", duration:"Until triggered or the story ends",
    success:"The target performs the specified betrayal when appropriate and gains Guilty.", exceptionalSuccess:"The target also gains Fugue after the betrayal.", failure:"The Contract fails.", dramaticFailure:"Before chapter's end, someone known to the motley betrays them and the changeling gains an appropriate detrimental Condition.",
    loophole:"During the story, the target accepted the changeling's payment to betray their fellows, even without intending to comply.",
    seemingBenefits:{Darkling:"After the betrayal, the target also gains Notoriety and becomes isolated from those betrayed.",Elemental:"Safeguards that could prevent the betrayal fail; for example, a treacherous attack gains surprise."},
  },
];
