export const CONTRACT_COSTS_PT: Record<string, string> = {
"ctl-2ed:autumns-fury": "2 ou 3 Glamour",
"ctl-2ed:baleful-sense": "1 Glamour",
"ctl-2ed:blessing-of-forgetfulness": "2 Glamour",
"ctl-2ed:blessing-of-perfection": "2 Glamour",
"ctl-2ed:blessing-of-spring": "2 Glamour (animais e plantas), ou 2 Glamour + 1 Força de Vontade (criaturas sapientes)",
"ctl-2ed:boon-of-the-scuttling-spider": "1 Glamour",
"ctl-2ed:changeling-hours": "1 Glamour, +1 por 5 de Tamanho",
"ctl-2ed:changing-fortunes": "2 Glamour",
"ctl-2ed:child-of-the-hearth": "1 Glamour",
"ctl-2ed:chrysalis": "2 Glamour",
"ctl-2ed:cloak-of-night": "1 Glamour",
"ctl-2ed:cupids-arrow": "1 Glamour",
"ctl-2ed:dance-of-the-toys": "2 Glamour",
"ctl-2ed:discreet-summons": "1 Glamour (objeto) ou 2 Glamour (hobgoblin)",
"ctl-2ed:dreams-of-the-earth": "2 Glamour",
"ctl-2ed:dreamsteps": "1 Glamour",
"ctl-2ed:elemental-fury": "1 ou mais Glamour",
"ctl-2ed:elemental-weapon": "2 Glamour",
"ctl-2ed:ermines-winter-coat": "1 Glamour",
"ctl-2ed:fae-cunning": "2 Glamour",
"ctl-2ed:fallow-fields": "2 Glamour",
"ctl-2ed:famines-bulwark": "1 Glamour",
"ctl-2ed:field-of-regret": "1 Glamour por alvo + 1 Força de Vontade",
"ctl-2ed:fiery-tongue": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:flames-of-summer": "2 Glamour",
"ctl-2ed:flickering-hours": "1 Glamour apenas para o changeling; 1 Glamour + 1 Força de Vontade para um grupo",
"ctl-2ed:fortifying-presence": "2 Glamour",
"ctl-2ed:gift-of-warm-blood": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:gift-of-warm-breath": "1 Glamour",
"ctl-2ed:glib-tongue": "1 Glamour",
"ctl-2ed:glimpse-of-a-distant-mirror": "1 Glamour",
"ctl-2ed:goblins-eye": "1 Glamour",
"ctl-2ed:goblins-luck": "1 Glamour",
"ctl-2ed:heart-of-ice": "2 Glamour",
"ctl-2ed:hedgewall": "2 Glamour + 1 Força de Vontade",
"ctl-2ed:helios-judgment": "1 Glamour, ou 1 Glamour + 1 Força de Vontade; veja a descrição",
"ctl-2ed:helios-light": "1 Glamour",
"ctl-2ed:hidden-reality": "1 Glamour",
"ctl-2ed:high-summers-zeal": "2 Glamour",
"ctl-2ed:hostile-takeover": "2 Glamour",
"ctl-2ed:huntsmans-clarion": "2 Glamour",
"ctl-2ed:ice-queens-call": "1 Glamour",
"ctl-2ed:know-the-competition": "1 Glamour",
"ctl-2ed:last-harvest": "2 ou 3 Glamour",
"ctl-2ed:leaping-toward-nightfall": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:light-shy": "1 Glamour",
"ctl-2ed:lost-visage": "2 Glamour",
"ctl-2ed:mantle-mask": "1 Glamour",
"ctl-2ed:mantle-of-frost": "2 Glamour",
"ctl-2ed:mask-of-superiority": "1 Glamour",
"ctl-2ed:masterminds-gambit": "2 Glamour",
"ctl-2ed:mien-of-the-baba-yaga": "2 Glamour",
"ctl-2ed:might-of-the-terrible-brute": "2 Glamour",
"ctl-2ed:mirror-walk": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:murkblur": "1 Glamour",
"ctl-2ed:nevertread": "1 Glamour",
"ctl-2ed:oathbreakers-punishment": "2 Glamour",
"ctl-2ed:overpowering-dread": "1 Glamour",
"ctl-2ed:pandoras-gift": "2 Glamour",
"ctl-2ed:paralyzing-presence": "2 Glamour",
"ctl-2ed:pathfinder": "1 Glamour",
"ctl-2ed:pipes-of-the-beastcaller": "1 Glamour",
"ctl-2ed:portents-and-visions": "1 Glamour",
"ctl-2ed:primal-glory": "2 Glamour",
"ctl-2ed:prince-of-ivy": "2 Glamour + 1 Força de Vontade",
"ctl-2ed:props-and-scenery": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:pure-clarity": "2 Glamour + 1 Força de Vontade",
"ctl-2ed:read-lucidity": "1 Glamour",
"ctl-2ed:red-revenge": "3 Glamour",
"ctl-2ed:reflections-of-the-past": "1 Glamour por período (semana, mês, estação, ano ou década)",
"ctl-2ed:relentless-pursuit": "2 Glamour",
"ctl-2ed:riddle-kith": "1 Glamour",
"ctl-2ed:riding-the-falling-leaves": "2 Glamour",
"ctl-2ed:seven-league-leap": "1 Glamour",
"ctl-2ed:shared-burden": "2 Glamour",
"ctl-2ed:sight-of-truth-and-lies": "1 Glamour",
"ctl-2ed:skinmask": "2 Glamour",
"ctl-2ed:slipknot-dreams": "1 Glamour",
"ctl-2ed:solstice-revelation": "1 Glamour",
"ctl-2ed:sorcerers-rebuke": "2 Glamour",
"ctl-2ed:spinning-wheel": "3 Glamour + 1 Força de Vontade",
"ctl-2ed:springs-kiss": "1–2 Glamour",
"ctl-2ed:stealing-the-solid-reflection": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:summon-the-loyal-servant": "1 Glamour",
"ctl-2ed:sunburnt-heart": "2 Glamour",
"ctl-2ed:tale-of-the-baba-yaga": "1 Glamour",
"ctl-2ed:talon-and-wing": "1–3 Glamour",
"ctl-2ed:tasting-the-harvest": "1 Glamour por alvo",
"ctl-2ed:tatterdemalions-workshop": "2 Glamour",
"ctl-2ed:the-dragon-knows": "1 Glamour",
"ctl-2ed:the-royal-court": "3 Glamour + 1 Força de Vontade",
"ctl-2ed:thief-of-reason": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:thorns-and-brambles": "2 Glamour",
"ctl-2ed:touch-of-winter": "1 Glamour",
"ctl-2ed:touch-of-wrath": "1 Glamour",
"ctl-2ed:trapdoor-spiders-trick": "1 Glamour, ou 1 Glamour + 1 Força de Vontade",
"ctl-2ed:trivial-reworking": "1 Glamour",
"ctl-2ed:tumult": "2 Glamour",
"ctl-2ed:twilights-harbinger": "1 Glamour",
"ctl-2ed:uncanny": "2 Glamour",
"ctl-2ed:unravel-the-tapestry": "2 Glamour + 1 Força de Vontade",
"ctl-2ed:vigilance-of-ares": "1 Glamour",
"ctl-2ed:vow-of-no-compromise": "1 Glamour + 1 Força de Vontade",
"ctl-2ed:waking-the-inner-fae": "1 Glamour",
"ctl-2ed:walls-have-ears": "1–3 Glamour",
"ctl-2ed:wayward-guide": "1 Glamour por alvo",
"ctl-2ed:whispers-of-morning": "2 Glamour",
"ctl-2ed:winters-curse": "2 Glamour + 1 Força de Vontade",
"ctl-2ed:witches-intuition": "1 Glamour",
"ctl-2ed:wyrd-faced-stranger": "1 Glamour",
"ctl-dark-eras:peacemakers-draw": "1 Glamour",
"ctl-kith-kin:a-benevolent-hand": "1 Glamour",
"ctl-kith-kin:acanthas-fury": "2 Glamour + 1 Força de Vontade",
"ctl-kith-kin:awaken-portal": "2 Glamour",
"ctl-kith-kin:beggar-knight": "2 Glamour",
"ctl-kith-kin:blood-debt": "2 Glamour",
"ctl-kith-kin:book-of-black-and-red": "1 Glamour",
"ctl-kith-kin:briars-herald": "1 Glamour",
"ctl-kith-kin:burning-ambition": "1 Glamour",
"ctl-kith-kin:by-the-pricking-of-my-thumbs": "1 Glamour",
"ctl-kith-kin:closing-deaths-door": "3 Glamour + 1 Força de Vontade",
"ctl-kith-kin:coin-mark": "1 Glamour",
"ctl-kith-kin:coming-darkness": "1 Glamour",
"ctl-kith-kin:cracked-mirror": "1 Glamour, ou 1 Glamour + 1 Força de Vontade",
"ctl-kith-kin:crown-of-thorns": "2 Glamour",
"ctl-kith-kin:curse-of-hidden-strings": "2 Glamour",
"ctl-kith-kin:curses-cure": "1 Glamour",
"ctl-kith-kin:cynosure": "1 Glamour",
"ctl-kith-kin:dread-companion": "1 Glamour",
"ctl-kith-kin:dreamers-phalanx": "1 Glamour + 1 Glamour por sonhador adicional além do segundo",
"ctl-kith-kin:earths-gentle-movements": "1 Glamour",
"ctl-kith-kin:earths-impenetrable-walls": "2 Glamour",
"ctl-kith-kin:embrace-of-nettles": "1 Glamour",
"ctl-kith-kin:exchange-of-gilded-contracts": "2 Glamour",
"ctl-kith-kin:feast-of-plenty": "2 Glamour",
"ctl-kith-kin:filling-the-cup": "1 Glamour",
"ctl-kith-kin:frozen-star": "2 Glamour",
"ctl-kith-kin:give-and-take": "1 Glamour, ou 2 Glamour para trocar Méritos",
"ctl-kith-kin:golden-promise": "2 Glamour",
"ctl-kith-kin:grand-revel-of-the-harvest": "3 Glamour + 1 Força de Vontade",
"ctl-kith-kin:grease-the-wheels": "1 Glamour",
"ctl-kith-kin:jealous-vengeance": "1 Glamour",
"ctl-kith-kin:knights-oath": "2 Glamour",
"ctl-kith-kin:light-of-ancient-stars": "2 Glamour",
"ctl-kith-kin:listen-with-the-winds-ears": "1 Glamour, ou 2 Glamour + 1 Força de Vontade",
"ctl-kith-kin:litany-of-rivals": "1 Glamour",
"ctl-kith-kin:momentary-respite": "2 Glamour",
"ctl-kith-kin:pinch-of-stardust": "3 Glamour + 1 Força de Vontade",
"ctl-kith-kin:poison-the-well": "1 Glamour",
"ctl-kith-kin:pole-star": "1 Glamour",
"ctl-kith-kin:pomp-and-circumstance": "1 Glamour, ou 1 Glamour + 1 Força de Vontade",
"ctl-kith-kin:retrograde": "1 Glamour",
"ctl-kith-kin:shadow-puppet": "1 Glamour",
"ctl-kith-kin:shared-cup": "2 Glamour + 1 Glamour por participante adicional além do segundo",
"ctl-kith-kin:shooting-star": "2 Glamour",
"ctl-kith-kin:shrikes-larder": "1–3 Glamour",
"ctl-kith-kin:sleeps-sweet-embrace": "2 Glamour + 1 Força de Vontade",
"ctl-kith-kin:spare-not-the-rod": "1 Glamour",
"ctl-kith-kin:steal-influence": "1 Glamour por ponto de Influência",
"ctl-kith-kin:still-waters-run-deep": "2 Glamour",
"ctl-kith-kin:tempters-quest": "1 Glamour + 1 Força de Vontade",
"ctl-kith-kin:the-gouging-curse": "1 Glamour",
"ctl-kith-kin:thirty-pieces": "3 Glamour",
"ctl-kith-kin:thistles-rebuke": "1 Glamour",
"ctl-kith-kin:unmask-the-dark-horse": "2 Glamour",
"ctl-kith-kin:witchs-brambles": "2–3 Glamour + 1 Força de Vontade",
"ctl-oak-ash-thorn:autonomous-payload": "2 Glamour",
"ctl-oak-ash-thorn:donning-the-grand-mantle": "2 Glamour + 1 Força de Vontade",
"ctl-oak-ash-thorn:principle": "2 Glamour",
"ctl-oak-ash-thorn:the-widening-gyre": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:babels-curse": "1 Glamour, ou 1 Glamour + 1 Força de Vontade",
"h-beyond-hedge:babels-tower": "1 Glamour",
"h-beyond-hedge:banshees-wail": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:bar-the-door": "2 Glamour, ou 2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:bauble-of-the-mind": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:crown-envoys-splendid-defense": "3 Glamour",
"h-beyond-hedge:curse-of-fading": "3 Glamour + 1 Força de Vontade",
"h-beyond-hedge:dead-mens-tales": "2 Glamour",
"h-beyond-hedge:doorway-to-desire": "2 Glamour",
"h-beyond-hedge:elfshot": "1 Glamour, ou 1 Glamour + 1 Força de Vontade",
"h-beyond-hedge:faerie-feast": "1 Glamour",
"h-beyond-hedge:foul-is-fair": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:ghostly-presence": "1 Glamour",
"h-beyond-hedge:haunted-house": "2 ou mais Glamour; veja a descrição",
"h-beyond-hedge:in-vino-veritas": "1 Glamour",
"h-beyond-hedge:mantle-of-terrible-beauty": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:memory-of-stone": "1 Glamour, ou 1 Glamour + 1 Força de Vontade",
"h-beyond-hedge:memory-of-trees": "2 Glamour",
"h-beyond-hedge:merry-meet": "1 Glamour",
"h-beyond-hedge:mindveil": "1 Glamour",
"h-beyond-hedge:my-anger-is-my-armor": "2 Glamour",
"h-beyond-hedge:my-sorrow-is-my-armor": "2 Glamour",
"h-beyond-hedge:persephones-doorway": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:smoke-stepping": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:solstice-revelations": "3 Glamour",
"h-beyond-hedge:soul-rime": "1 Glamour + 1 Força de Vontade",
"h-beyond-hedge:sunflash": "1 Glamour",
"h-beyond-hedge:sweet-nothings": "1 Glamour + 1 Força de Vontade",
"h-beyond-hedge:the-perfect-talent": "2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:turings-enigma": "2 Glamour, ou 2 Glamour + 1 Força de Vontade",
"h-beyond-hedge:veil-of-tears": "1 Glamour",
"h-beyond-hedge:wake-the-dead": "3 Glamour + 1 Força de Vontade",
"h-beyond-hedge:waylaid-traveler": "2 Glamour",
"h-beyond-hedge:whispers-in-the-dark": "2 Glamour, ou 2 Glamour + 1 Força de Vontade (para conhecimento verdadeiramente antigo ou perdido)",
"h-beyond-hedge:whisperward": "1 Glamour",
"h-beyond-hedge:wildwalking": "1 Glamour",
"h-beyond-hedge:withering-glare": "2 Glamour",
"h-courts:aether-crossing": "2 Glamour",
"h-courts:age-of-aquarius": "3 Glamour + 1 Força de Vontade",
"h-courts:all-roads-closed": "5 Glamour",
"h-courts:always-solvent": "2 Glamour",
"h-courts:assuming-the-stellar-mantle": "2 Glamour",
"h-courts:cast-out": "2 Glamour",
"h-courts:celestial-might": "1 Glamour + 1 Força de Vontade",
"h-courts:celestial-shield": "2 Glamour",
"h-courts:celestial-summons": "2 Glamour",
"h-courts:climate-change": "2 Glamour + 1 Força de Vontade",
"h-courts:cook-the-books": "2 Glamour",
"h-courts:create-path": "3 Glamour + 1 Força de Vontade",
"h-courts:davy-jones-locker": "1 ou mais Glamour + 1 Força de Vontade",
"h-courts:dredge-the-depths": "2 Glamour",
"h-courts:elemental-cycle": "3 Glamour + 1 Força de Vontade",
"h-courts:escape-route": "2 Glamour (+1 Força de Vontade, opcional)",
"h-courts:family-friendly-feud": "2 Glamour",
"h-courts:frozen-in-time": "2 Glamour",
"h-courts:gone-by-the-board": "2 Glamour",
"h-courts:harmony-enforced": "1 Glamour",
"h-courts:hearths-respite": "1 Glamour + 1 Força de Vontade",
"h-courts:if-two-are-dead": "1 ou mais Glamour + 1 Força de Vontade",
"h-courts:labyrinth": "2 Glamour",
"h-courts:nothing-to-see-here": "2 Glamour",
"h-courts:one-with-the-elements": "1 Glamour + 1 Força de Vontade",
"h-courts:protection-of-the-innocent": "3 Glamour + 1 Força de Vontade",
"h-courts:rain-of-terror": "2 Glamour + 1 Força de Vontade",
"h-courts:raise-the-band": "3 Glamour + 1 Força de Vontade",
"h-courts:red-sky-at-morning": "2 Glamour",
"h-courts:red-sky-at-night": "2 Glamour + 1 Força de Vontade",
"h-courts:restringing-the-loom": "2 Glamour + 1 Força de Vontade",
"h-courts:shared-remembrance": "2 Glamour",
"h-courts:shifting-balance": "2 Glamour",
"h-courts:steal-harmony": "1 Glamour + 1 Força de Vontade",
"h-courts:storm-of-the-century": "3 Glamour + 1 Força de Vontade",
"h-courts:supply-and-demand": "2 Glamour",
"h-courts:tempestuous-hearts": "3 Glamour + 1 Força de Vontade",
"h-courts:thunder-steed": "2 Glamour",
"h-courts:vigil-of-silver-and-gold": "2 Glamour",
"h-courts:weaponize-mob": "2 Glamour",
"h-seemings:carrion-feast": "1 ou mais Glamour + 1 Força de Vontade",
"h-seemings:last-hope": "2 Glamour",
"h-seemings:no-escape": "2 Glamour + 1 Força de Vontade",
"h-seemings:starvations-savagery": "2 Glamour + 1 Força de Vontade",
"h-seemings:swallow-whole": "2 Glamour",
"h-seemings:the-troll-toll": "2 Glamour + 1 Força de Vontade",
"h-seemings:you-are-who-you-eat": "2 Glamour",
};
