import type { ContractDefinition } from "./contracts";

const source = { categoryKind: "Corte" as const, sourceId: "h-courts", source: "Book of Courts" };
const circadian = { ...source, regalia: "Circadian", courtFamily: "circadian", courtIds: ["sun", "moon"] };
const undercourt = { ...source, regalia: "Undercourt", courtFamily: "undercourt", courtIds: ["undercourt"] };
const weather = { ...source, regalia: "Weather", courtFamily: "weather", courtIds: ["calm", "storm"] };
const zodiac = { ...source, regalia: "Zodiac", courtFamily: "zodiac", courtIds: ["fire", "earth", "air", "water"] };
const directional = { ...source, regalia: "Directional", courtFamily: "directional", courtIds: ["north", "east", "south", "west", "center"] };

export const BOOK_OF_COURTS_CONTRACTS: ContractDefinition[] = [
  {
    ...circadian, id: "h-courts:circadian:frost-fire-glance", name: "Frost-Fire Glance", originalName: "Frost-Fire Glance", type: "Comum", page: 103,
    summary: "Make a small visible object dangerously hot or cold.", description: "Make a small visible object dangerously hot or cold.", hasRoll: false, dicePool: "None", cost: "●/●●", action: "Instant", duration: "Mantle turns",
    effect: "Choose a visible object of Size 3 or less. Anyone holding it must succeed at Resolve + Stamina or drop it; retaining it inflicts 1 bashing damage each turn. Spending 2 Glamour makes this lethal damage instead.",
    courtClauses: {
      sun: "The object catches fire and thereafter burns and suffers damage normally until extinguished.",
      moon: "The object becomes tempting to touch; the Storyteller may offer Willpower to a character willing to grasp it, including someone who dropped it and tries again.",
    }, loophole: "The object belongs to the changeling.",
  },
  {
    ...circadian, id: "h-courts:circadian:horizon-step", name: "Horizon Step", originalName: "Horizon Step", type: "Comum", page: 103,
    summary: "Create a simple bridge or ladder from sunlight or moonlight.", description: "Create a simple bridge or ladder from sunlight or moonlight.", hasRoll: false, dicePool: "None", cost: "●", action: "Instant", duration: "One scene",
    effect: "Draw a simple bridge or ladder into existence where the changeling stands. It may be up to Mantle × 2 meters long, is only centimeters thick and nearly weightless, yet supports any person and resists mundane destruction.",
    courtClauses: { sun: "Add a safety feature such as railings or platform steps.", moon: "Spend 1 additional Glamour to make the structure invisible." }, loophole: "The changeling is wearing suspenders.",
  },
  {
    ...circadian, id: "h-courts:circadian:secrets-and-lies", name: "Secrets and Lies", originalName: "Secrets and Lies", type: "Comum", page: 103,
    summary: "Discover a secret or deception guarded by the target.", description: "Discover a secret or deception guarded by the target.", hasRoll: true, dicePool: "Wits + Investigation + Mantle vs. Resolve + Wyrd", cost: "●", action: "Contested", duration: "Instant",
    success: "Learn the secret or deception foremost in the target's mind. To seek a specific secret, maneuver the target into thinking about it.", exceptionalSuccess: "Narrow the desired secret to a category, such as political or romantic.", failure: "The Contract fails.", dramaticFailure: "The target realizes that someone tried to delve into their mind.",
    courtClauses: { sun: "Learn the identity of one additional person involved.", moon: "Spend 1 additional Glamour to witness up to one turn of circumstances surrounding the secret or deception from the target's perspective." }, loophole: "The changeling committed a crime within the last 24 hours.",
  },
  {
    ...circadian, id: "h-courts:circadian:shimmering-mirage", name: "Shimmering Mirage", originalName: "Shimmering Mirage", type: "Comum", page: 104,
    summary: "Surround someone with dazzling light or a moonlit echo that makes attacks difficult.", description: "Surround someone with dazzling light or a moonlit echo that makes attacks difficult.", hasRoll: false, dicePool: "None", cost: "●", action: "Instant", duration: "Mantle turns",
    effect: "Choose the changeling or another character in the scene. Attacks against the subject begin with a penalty equal to Mantle, reduced by one each turn until it vanishes. The Contract cannot end early or be invoked again before its full duration passes.",
    courtClauses: { sun: "A successful attacker must succeed at Resolve + Composure or suffer Blinded.", moon: "A successful attacker must succeed at Resolve + Composure or gain Confused." }, loophole: "The changeling looks directly at the sun or moon while invoking the Contract.",
  },
  {
    ...circadian, id: "h-courts:circadian:twin-beacons", name: "Twin Beacons", originalName: "Twin Beacons", type: "Comum", page: 104,
    summary: "Illuminate the way ahead while obscuring the trail behind.", description: "Illuminate the way ahead while obscuring the trail behind.", hasRoll: false, dicePool: "None", cost: "●", action: "Instant", duration: "One scene",
    effect: "Add Mantle to Investigation and perception rolls while exploring or traveling. Trackers pursuing the changeling subtract Mantle.",
    courtClauses: { sun: "The changeling cannot be surprised.", moon: "The changeling automatically knows whether anyone is pursuing him and how many pursuers there are." }, loophole: "The changeling carries a lantern.",
  },
  {
    ...circadian, id: "h-courts:circadian:celestial-summons", name: "Celestial Summons", originalName: "Celestial Summons", type: "Real", page: 104,
    summary: "Compel a target in the same freehold or city to make their way to the changeling.", description: "Compel a target in the same freehold or city to make their way to the changeling.", hasRoll: true, dicePool: "Presence + Persuasion + Wyrd vs. Composure + Wyrd", cost: "●●", action: "Instant", duration: "Until the end of the chapter or the target arrives",
    success: "The target knows the changeling wants her presence and travels to him as soon as reasonably possible, without risking serious harm. She must be in the same freehold or city and have some feasible means of reaching him.", exceptionalSuccess: "The Contract works beyond the freehold, including in the Hedge. The changeling may delay its onset until she relocates before the next sunrise or sunset.", failure: "The Contract fails.", dramaticFailure: "The target learns of the failed attempt.",
    courtClauses: { sun: "If the summoned target is an ally, she regains 1 Willpower.", moon: "Obscure the changeling's identity, so the target knows only that she must reach a particular place." }, loophole: "The changeling has some form of authority over the target.",
  },
  {
    ...circadian, id: "h-courts:circadian:climate-change", name: "Climate Change", originalName: "Climate Change", type: "Real", page: 105,
    summary: "Bring extreme heat or cold to a wide surrounding area.", description: "Bring extreme heat or cold to a wide surrounding area.", hasRoll: true, dicePool: "Resolve + Survival + Mantle", cost: "●●○", action: "Instant", duration: "One scene",
    success: "Inflict Extreme Heat for Sun or Extreme Cold for Moon over an area up to two kilometers around the changeling. The changeling is immune to this Tilt.", exceptionalSuccess: "Double the maximum affected area.", failure: "The Contract fails.", dramaticFailure: "The changeling cannot use Contracts for the rest of the scene.",
    courtClauses: { sun: "Inflict Sick from sunstroke on one person caught in the Tilt.", moon: "Create an intense snowstorm and inflict Lost on one person caught in the Tilt." }, loophole: "The real environmental condition affected the area within the last month.",
  },
  {
    ...circadian, id: "h-courts:circadian:celestial-might", name: "Celestial Might", originalName: "Celestial Might", type: "Real", page: 105,
    summary: "Channel sunlight or moonlight into a weapon so it can inflict aggravated damage.", description: "Channel sunlight or moonlight into a weapon so it can inflict aggravated damage.", hasRoll: true, dicePool: "Dexterity + Occult + Mantle", cost: "●○", action: "Instant", duration: "Mantle turns",
    success: "Outdoors at the Court's appropriate time, make a weapon's damage bonus aggravated (minimum one); rolled successes still inflict its normal damage type.", exceptionalSuccess: "Invocation is reflexive instead.", failure: "The Contract fails.", dramaticFailure: "The weapon reflects the light and inflicts 1 aggravated damage on the changeling.",
    courtClauses: { sun: "Add two dice to perception rolls for the rest of the scene.", moon: "Dim the area within ten meters and add two dice to Stealth rolls for the rest of the scene." }, loophole: "The weapon bears a permanent image of the appropriate sun or moon.",
  },
  {
    ...circadian, id: "h-courts:circadian:celestial-shield", name: "Celestial Shield", originalName: "Celestial Shield", type: "Real", page: 105,
    summary: "Shape sunlight or moonlight into a handheld shield or immobile barricade.", description: "Shape sunlight or moonlight into a handheld shield or immobile barricade.", hasRoll: false, dicePool: "None", cost: "●●", action: "Instant", duration: "One scene",
    effect: "Create a handheld shield or a Size 6 barricade sheltering up to three people. The shield reduces all damage except cold iron by two. The barricade provides Substantial Concealment, Tough Cover, Durability equal to Mantle, and the same damage reduction.",
    courtClauses: { sun: "The handheld shield imposes no Initiative penalty.", moon: "The barricade may become opaque and conceal those behind it." }, loophole: "The changeling uses the shield to protect another person under her care or authority.",
  },
  {
    ...circadian, id: "h-courts:circadian:vigil-of-silver-and-gold", name: "Vigil of Silver and Gold", originalName: "Vigil of Silver and Gold", type: "Real", page: 105,
    summary: "Ward an owned or responsible area and sense everyone crossing its boundary.", description: "Ward an owned or responsible area and sense everyone crossing its boundary.", hasRoll: false, dicePool: "None", cost: "●●", action: "Instant", duration: "Until the next sunset or sunrise",
    effect: "Trace a sun or moon in four corners of an area up to 300 square meters. Sense everyone who enters or leaves, recognizing acquaintances and receiving a broad description of strangers or supernatural beings. Supernatural concealment triggers a Clash of Wills.",
    courtClauses: { sun: "Add Mantle to Socialize rolls involving anyone detected by the Contract.", moon: "Add Mantle to Investigation rolls involving anyone detected by the Contract." }, loophole: "The changeling owns land or a building within the protected area.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:goodnight-moon", name:"Goodnight Moon", originalName:"Goodnight Moon", type:"Comum", page:106,
    summary:"Tell a beloved childhood story to grant a companion restorative sleep.", description:"Tell a beloved childhood story to grant a companion restorative sleep.", hasRoll:true, dicePool:"Presence + Expression + Wyrd", cost:"●●", action:"Instant", duration:"Instant",
    success:"Grant another character peaceful sleep. While sleeping, the target halves healing time for current physical damage; a changeling also heals one severe Clarity damage or all mild Clarity damage.", exceptionalSuccess:"The target also heals Conditions associated with Clarity loss.", failure:"The Contract fails.", dramaticFailure:"The sleep provides no benefit and the target wakes with one additional mild Clarity damage.", loophole:"Both changeling and target are wearing pajamas.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:pep-talk", name:"Pep Talk", originalName:"Pep Talk", type:"Comum", page:106,
    summary:"Encourage someone to bring their best to a chosen Skill.", description:"Encourage someone to bring their best to a chosen Skill.", hasRoll:false, dicePool:"None", cost:"●", action:"Instant", duration:"Instant", effect:"After a brief encouraging conversation, the target gains Inspired regarding a Skill they choose.", loophole:"The changeling has no dots in that Skill.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:nothing-to-see-here", name:"Nothing to See Here", originalName:"Nothing to See Here", type:"Comum", page:106,
    summary:"Reduce the emotional impact of a recent traumatic or supernatural event and support recovery.", description:"Reduce the emotional impact of a recent traumatic or supernatural event and support recovery.", hasRoll:true, dicePool:"Manipulation + Empathy + Wyrd vs. Composure + Wyrd", cost:"●", action:"Contested", duration:"Instant",
    success:"Discuss an event from the last day. The target retains the memory but its emotional impact diminishes and their mind supplies a mundane explanation if needed. Add Mantle to later actions involving its trauma, including breaking points and insomnia.", exceptionalSuccess:"Clear Conditions caused by the event.", failure:"The Contract fails.", dramaticFailure:"The target remembers the conversation negatively, as though the changeling denied the experience.", loophole:"The changeling experienced the event with the target.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:rooted-in-the-past", name:"Rooted in the Past", originalName:"Rooted in the Past", type:"Comum", page:106,
    summary:"Use nostalgia to ward the changeling's emotions against influence.", description:"Use nostalgia to ward the changeling's emotions against influence.", hasRoll:false, dicePool:"None", cost:"●●", action:"Reflexive", duration:"One scene",
    effect:"Focus on a beloved person or event to become immune to emotional Conditions, including suppressing a known current Condition. Supernatural emotional influence suffers a penalty equal to Undercourt Mantle.", loophole:"The changeling eats a favorite childhood food.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:safeguarded-supplies", name:"Safeguarded Supplies", originalName:"Safeguarded Supplies", type:"Comum", page:107,
    summary:"Protect a complex item so it continues functioning in the Hedge.", description:"Protect a complex item so it continues functioning in the Hedge.", hasRoll:true, dicePool:"Intelligence + Crafts + Mantle", cost:"●", action:"Instant", duration:"One chapter",
    success:"A chosen complex item functions normally in the Hedge, although unavailable infrastructure such as the Internet remains unavailable.", exceptionalSuccess:"Grant the item either +1 Equipment or +1 Durability.", failure:"The Contract fails.", dramaticFailure:"The item appears functional but malfunctions at an inopportune moment.", loophole:"The changeling slept with the item under their pillow the previous night.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:family-friendly-feud", name:"Family-Friendly Feud", originalName:"Family-Friendly Feud", type:"Real", page:107,
    summary:"Make violence in the vicinity less lethal.", description:"Make violence in the vicinity less lethal.", hasRoll:false, dicePool:"None", cost:"●●", action:"Instant", duration:"One scene",
    effect:"Downgrade all violent damage nearby one step: aggravated becomes lethal, lethal becomes bashing, and bashing is halved, rounded up. This affects everyone present, including the changeling.", loophole:"The changeling has used no curse words within the last day.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:frozen-in-time", name:"Frozen in Time", originalName:"Frozen in Time", type:"Real", page:107,
    summary:"Trap a listening target in a spoken memory loop.", description:"Trap a listening target in a spoken memory loop.", hasRoll:true, dicePool:"Manipulation + Occult + Mantle vs. Resolve + Wyrd", cost:"●●", action:"Contested", duration:"Wyrd turns",
    success:"The target fixates on a spoken phrase and suffers Stunned. The target must hear the words but need not understand them; suffering lethal damage ends the effect early.", exceptionalSuccess:"The target also gains Shaken.", failure:"The Contract fails.", dramaticFailure:"The changeling suffers Stunned for one turn.", loophole:"An analog clock is visible nearby.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:hearths-respite", name:"Hearth's Respite", originalName:"Hearth's Respite", type:"Real", page:107,
    summary:"Turn the changeling's home or establishment into a sanctuary of calm and recovery.", description:"Turn the changeling's home or establishment into a sanctuary of calm and recovery.", hasRoll:true, dicePool:"Composure + Empathy + Mantle", cost:"●○", action:"Instant", duration:"One week",
    success:"After cleaning or redecorating an owned or inhabited place, welcomed changelings heal one mild Clarity damage per hour inside. Anyone who eats or drinks there gains either -2 to their next Clarity attack or +2 to their first Integrity breaking point during the next week. Aggressive or violent rolls inside lose 10-again.", exceptionalSuccess:"A character who heals Clarity also heals their oldest Clarity Condition.", failure:"The Contract fails.", dramaticFailure:"The Contract cannot be attempted again for one week.", loophole:"A visible picture of the changeling's mortal family hangs nearby.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:protection-of-the-innocent", name:"Protection of the Innocent", originalName:"Protection of the Innocent", type:"Real", page:108,
    summary:"Place a mortal under strong protection against supernatural harm.", description:"Place a mortal under strong protection against supernatural harm.", hasRoll:true, dicePool:"Resolve + Medicine + Mantle", cost:"●●●○", action:"Instant", duration:"One lunar month",
    success:"Supernatural powers targeting the mortal subtract Mantle from activation; powers without rolls fail. The mortal gains general armor equal to Mantle against supernatural damage, and mundane attacks by supernatural beings lose 10-again.", exceptionalSuccess:"The mortal also gains 1 general armor against mundane harm.", failure:"The Contract fails.", dramaticFailure:"The changeling gains Obsession concerning the mortal's safety.", loophole:"The Contract has never before been used on this mortal.",
  },
  {
    ...undercourt, id:"h-courts:undercourt:shared-remembrance", name:"Shared Remembrance", originalName:"Shared Remembrance", type:"Real", page:108,
    summary:"Experience one of the target's memories through their senses.", description:"Experience one of the target's memories through their senses.", hasRoll:true, dicePool:"Wits + Empathy + Mantle vs. Resolve + Wyrd", cost:"●●", action:"Contested", duration:"Up to one hour or the memory's length",
    success:"View a known memory identified by time, date, or content, or the target's most recent emotionally intense memory. Gain 8-again on Empathy rolls involving the target for the rest of the chapter.", exceptionalSuccess:"View up to three hours of memory.", failure:"The Contract fails.", dramaticFailure:"Flashes of memory intrude on reality, imposing -2 on perception rolls for the scene.", loophole:"The changeling tells the target one of his own important memories.",
  },
  {...weather,id:"h-courts:weather:brainstorm",name:"Brainstorm",originalName:"Brainstorm",type:"Comum",page:108,summary:"Send a flash of inspiration into another person's thoughts.",description:"Send a flash of inspiration into another person's thoughts.",hasRoll:false,dicePool:"None",cost:"●/●●",action:"Instant",duration:"Instant",effect:"Grant Inspired for a new idea related to the target's current thoughts, or Informed by supplying a specific idea about a subject the changeling knows. For 2 Glamour, grant both about such a subject. The target believes the idea is their own but need not act on it.",courtClauses:{calm:"Add Mantle to teamwork rolls that willingly help the target act on the idea.",storm:"Instead overwhelm the target with random ideas, inflicting Distracted for the scene."},loophole:"The target is sleeping peacefully and receives the inspiration on waking."},
  {...weather,id:"h-courts:weather:cloud-gazing",name:"Cloud Gazing",originalName:"Cloud Gazing",type:"Comum",page:108,summary:"Read weather patterns to foresee events during the next 24 hours.",description:"Read weather patterns to foresee events during the next 24 hours.",hasRoll:true,dicePool:"Wits + Survival + Mantle",cost:"●",action:"Extended (5 successes; one minute per roll)",duration:"Instant",success:"Ask up to Mantle yes-or-no questions about events within the next 24 hours; 'maybe' is possible when ambiguous. During the same day, add Mantle to one roll that brings about or prevents a foreseen event.",exceptionalSuccess:"The enhanced action also gains 8-again.",failure:"The Contract fails.",dramaticFailure:"Receive false information, and the next failed roll becomes dramatic without granting a Beat.",courtClauses:{calm:"The changeling may also read the flight of birds or insects.",storm:"The changeling may also read crashing waves or leaves caught in gusts."},loophole:"Draw an eye in condensation on a window."},
  {...weather,id:"h-courts:weather:light-as-a-feather",name:"Light as a Feather",originalName:"Light as a Feather",type:"Comum",page:109,summary:"Call winds to prevent harm from a fall.",description:"Call winds to prevent harm from a fall.",hasRoll:false,dicePool:"None",cost:"●",action:"Reflexive",duration:"Instant",effect:"The changeling and anyone touching him suffer no damage from falling, regardless of height.",courtClauses:{calm:"Extend protection to up to Mantle visible targets.",storm:"The winds return the falling Storm Courtier to the point from which she fell."},loophole:"The changeling is outdoors in natural wind."},
  {...weather,id:"h-courts:weather:troubled-hearts-confession",name:"Troubled Heart's Confession",originalName:"Troubled Heart's Confession",type:"Comum",page:109,summary:"Discern what currently troubles the target most.",description:"Discern what currently troubles the target most.",hasRoll:true,dicePool:"Wits + Empathy + Mantle vs. Composure + Wyrd",cost:"●",action:"Contested",duration:"Instant",success:"Learn what most troubles the target's thoughts, even if the target is unaware of it.",exceptionalSuccess:"Gain Informed regarding the target.",failure:"The Contract fails.",dramaticFailure:"The changeling confesses her own troubles and gains Leveraged toward the target.",courtClauses:{calm:"Also learn what would most easily ease the target's stress.",storm:"Also learn what would most easily motivate the target to confront the trouble."},loophole:"Changeling and target willingly hold hands."},
  {...weather,id:"h-courts:weather:whispering-winds",name:"Whispering Winds",originalName:"Whispering Winds",type:"Comum",page:109,summary:"Send a short spoken message on the wind.",description:"Send a short spoken message on the wind.",hasRoll:false,dicePool:"None",cost:"●/●●",action:"Instant",duration:"Instant",effect:"Carry up to Mantle short sentences to a target within Mantle × 2 kilometers along uninterrupted wind, enabling a mundane Social action needing neither reply nor eye contact. An additional Glamour broadcasts it across a wide area.",courtClauses:{calm:"Add Mantle to Persuasion actions through the Contract.",storm:"Add Mantle to Intimidation actions through the Contract."},loophole:"The changeling told a secret to an enemy since the sun last crossed the horizon."},
  {...weather,id:"h-courts:weather:nothing-to-see-here",name:"Nothing to See Here",originalName:"Nothing to See Here",type:"Real",page:109,summary:"Summon dense fog that conceals perceptions and supernatural activity.",description:"Summon dense fog that conceals perceptions and supernatural activity.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"One scene",effect:"Fog fills an outdoor Mantle × 2 kilometer area and seeps through open portals. Perception suffers -Mantle and mundane Stealth gains +Mantle; the changeling and up to Mantle named people ignore the penalty. Supernatural concealment gains 9-again, and mortals with Resolve below Mantle rationalize supernatural events.",courtClauses:{calm:"Obvious supernatural powers used before mortal witnesses require a Clash of Wills.",storm:"Suppress mortal rationalization and instead inflict Paranoid through hints of impossible threats."},loophole:"Since the last sunrise, spend at least two consecutive waking hours blindfolded or otherwise blinded."},
  {...weather,id:"h-courts:weather:rain-of-terror",name:"Rain of Terror",originalName:"Rain of Terror",type:"Real",page:110,summary:"Conjure a vast storm of impossible phenomena that traumatizes witnesses.",description:"Conjure a vast storm of impossible phenomena that traumatizes witnesses.",hasRoll:true,dicePool:"Intelligence + Occult + Mantle vs. Composure + Wyrd (each victim)",cost:"●●○",action:"Contested and extended (each 5 successes adds one scene; two turns per roll; maximum Mantle rolls)",duration:"One scene per 5 successes",success:"Create a harmless impossible storm in a Mantle × 2 kilometer radius. Others inside gain Distracted; mortal witnesses gain Frightened, Spooked, or Shaken, and directly exposed targets who fail to contest also gain Madness. All end without resolution when the storm ends.",exceptionalSuccess:"Targets receiving Madness also receive either Delusional or Fugue, chosen once for everyone.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Madness from hallucinations.",courtClauses:{calm:"Conjure a wondrous display; mortals gain Inspired rather than fear Conditions.",storm:"Inflict (Mantle - Durability) lethal damage every 10 minutes on unprotected people and structures."},loophole:"From the area's highest point, scatter samples that simulate the intended weather."},
  {...weather,id:"h-courts:weather:storm-of-the-century",name:"Storm of the Century",originalName:"Storm of the Century",type:"Real",page:110,summary:"Build a prolonged violent storm from selectable effects.",description:"Build a prolonged violent storm from selectable effects.",hasRoll:true,dicePool:"Presence + Survival + Mantle",cost:"●●●○",action:"Extended (5 successes; two turns per roll; maximum Mantle rolls)",duration:"Mantle hours",options:["Raise Extreme Environment by 1, up to Mantle - 1.","Impose an appropriate Environmental Tilt.","Add thunder and lightning; invested successes determine blinding or deafening, random or aimed strikes. Lightning inflicts Mantle + Wyrd bashing damage.","Make one person or object immune to the storm.","Extend duration by Mantle hours."],success:"Outdoors, summon a storm centered on the changeling over Mantle × 2 kilometers. It affects everyone except protected subjects and cannot end early. Assign each success to one option.",exceptionalSuccess:"Double total duration.",failure:"The Contract fails.",dramaticFailure:"Lightning strikes the changeling for Mantle + Wyrd bashing damage, even through immunity.",courtClauses:{calm:"Reverse it to reduce Extreme Environment by up to Mantle or remove that many Environmental Tilts.",storm:"Conjure severe weather indoors throughout the current structure."},loophole:"Carve a lightning bolt into the changeling's flesh and suffer 1 lethal damage."},
  {...weather,id:"h-courts:weather:tempestuous-hearts",name:"Tempestuous Hearts",originalName:"Tempestuous Hearts",type:"Real",page:111,summary:"Channel Bedlam through a remarkable weather phenomenon.",description:"Channel Bedlam through a remarkable weather phenomenon.",hasRoll:false,dicePool:"None",cost:"●●●○",action:"Instant",duration:"One scene",effect:"Incite Bedlam with its cost included, channeling Glamour into notable weather. Anyone who perceives that weather is affected as though they perceived the changeling.",courtClauses:{calm:"Channel it through calm weather out to Mantle × 2 kilometers.",storm:"Add Mantle to the roll to incite Bedlam."},loophole:"Incite Bedlam without focusing on one emotion, intensifying each person's current emotions."},
  {...weather,id:"h-courts:weather:thunder-steed",name:"Thunder Steed",originalName:"Thunder Steed",type:"Real",page:111,summary:"Travel across a storm as a bolt of lightning.",description:"Travel across a storm as a bolt of lightning.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"Instant",effect:"Outdoors beneath a storm or fully clouded sky, vanish in lightning and appear beneath the same storm within Mantle × 2 kilometers. Anyone else struck at departure or arrival suffers Mantle + Wyrd bashing damage.",courtClauses:{calm:"Bring up to Mantle touching companions and protect them from lightning.",storm:"Departure and arrival create Mantle × 3 meter shockwaves; failing reflexive Dexterity + Athletics with Mantle successes inflicts Knocked Down."},loophole:"Since the sun last crossed the horizon, spend an hour exposed to natural rain."},
  {...zodiac,id:"h-courts:zodiac:balancing-the-four-humours",name:"Balancing the Four Humours",originalName:"Balancing the Four Humours",type:"Comum",page:111,summary:"Rebalance a patient's symbolic elements to cure disease.",description:"Rebalance a patient's symbolic elements to cure disease.",hasRoll:false,dicePool:"None",cost:"●/●●",action:"Instant",duration:"Instant",effect:"For 1 Glamour, cure minor or moderate disease instantly. For 2, reduce a severe disease to moderate so recovery or remission becomes possible. Chronic illness and diseases with no plausible modern cure are unaffected.",courtClauses:{fire:"Also resolve Competitive, Berserk, or a similar choleric Condition.",earth:"Also resolve Lethargic, Broken, or a similar melancholic Condition.",air:"Also resolve Wanton, Distracted, or a similar sanguine Condition.",water:"Also resolve Withdrawn, Stoic, or a similar phlegmatic Condition."},loophole:"Use an antiquated treatment such as bloodletting, trepanation, or heated glass that inflicts damage."},
  {...zodiac,id:"h-courts:zodiac:horoscope",name:"Horoscope",originalName:"Horoscope",type:"Comum",page:111,summary:"Impress broad astrological advice upon a target until sunrise.",description:"Impress broad astrological advice upon a target until sunrise.",hasRoll:true,dicePool:"Intelligence + Occult + Mantle vs. Resolve + Wyrd",cost:"●",action:"Contested",duration:"Until the next sunrise",success:"Name the target and nonspecific advice. Rolls that follow that advice gain Mantle dice. The changeling cannot target himself; a consenting target may waive resistance.",exceptionalSuccess:"Duration becomes one lunar month or until the zodiac enters another sign, whichever comes first.",failure:"The Contract fails.",dramaticFailure:"For the rest of the scene, every failure by the changeling becomes dramatic without a Beat.",courtClauses:{fire:"Add three dice when the advice concerns ambition or adventure.",earth:"Add three dice when it concerns wealth or work.",air:"Add three dice when it concerns travel or learning.",water:"Add three dice when it concerns love or relationships."},loophole:"The advice matches the target's published horoscope for that day in a publication at hand."},
  {...zodiac,id:"h-courts:zodiac:match-made-in-heaven",name:"Match Made in Heaven",originalName:"Match Made in Heaven",type:"Comum",page:112,summary:"Bring two people into emotional alignment or drive them apart.",description:"Bring two people into emotional alignment or drive them apart.",hasRoll:true,dicePool:"Manipulation + Expression + Mantle vs. highest Composure + Wyrd",cost:"●●",action:"Instant",duration:"Instant",success:"Inflict Swooned on both targets when increasing compatibility, or Contemptuous on both when decreasing it.",exceptionalSuccess:"Each target must fulfill the resolution twice; only final resolution grants a Beat.",failure:"The Contract fails.",dramaticFailure:"Inflict the opposite Condition from the one intended.",courtClauses:{fire:"Once per chapter while affected, each target regains 1 Willpower for significant interaction with the other.",earth:"Teamwork involving both targets gains +2 with Swooned or -2 with Contemptuous.",air:"Affect up to Mantle + 1 people, paying 1 additional Glamour for each after the second.",water:"Both targets gain 9-again on Empathy involving each other."},loophole:"A third party asked the changeling to act as matchmaker or poison pill."},
  {...zodiac,id:"h-courts:zodiac:star-sign",name:"Star Sign",originalName:"Star Sign",type:"Comum",page:112,summary:"Read the astrological influences that shape a target's personality.",description:"Read the astrological influences that shape a target's personality.",hasRoll:true,dicePool:"Wits + Occult + Mantle vs. Composure + Wyrd",cost:"●",action:"Instant",duration:"Instant",success:"Learn relevant birth-chart influences and the general shape of the target's personality, including Thread and Needle, Virtue and Vice, or equivalents.",exceptionalSuccess:"Gain +2 on mundane rolls to predict or influence the target's actions for one month.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Disoriented.",courtClauses:{fire:"Learn the target's greatest source of confidence and related Conditions, Tilts, or Aspirations.",earth:"Learn the target's current determination, related Conditions or Tilts, and available Willpower.",air:"Learn who or what inspires the target and related Conditions, Tilts, or Aspirations.",water:"Learn who or what the target most pities and related Conditions, Tilts, or Touchstones."},loophole:"Consult the target's stars as part of a genuine astrological reading."},
  {...zodiac,id:"h-courts:zodiac:stellar-thread",name:"Stellar Thread",originalName:"Stellar Thread",type:"Comum",page:113,summary:"Let fate draw the changeling toward something important to an Aspiration.",description:"Let fate draw the changeling toward something important to an Aspiration.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One scene",effect:"Fateful events and decisions guide the changeling toward a person, place, or thing important to a chosen Aspiration. If time expires first, gain a vague idea of the destination and how to find it later.",courtClauses:{fire:"On arrival, add Mantle to the first roll to use or affect the subject.",earth:"Add Mantle to rolls overcoming obstacles between the changeling and the subject.",air:"Arriving in time begins another one-scene journey toward a new soon-important subject.",water:"Instead seek a fetch of imminent importance."},loophole:"The changeling seeks a solution to a time-sensitive problem with no more than one hour remaining."},
  {...zodiac,id:"h-courts:zodiac:aether-crossing",name:"Aether Crossing",originalName:"Aether Crossing",type:"Real",page:113,summary:"Enter a large elemental mass and emerge through its uninterrupted extent.",description:"Enter a large elemental mass and emerge through its uninterrupted extent.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"Instant",effect:"Touch a representation of fire, earth, air, or water large enough to contain the changeling. Enter it and emerge on its far side or elsewhere along its continuous extent within Mantle meters, bypassing barriers when the element has uninterrupted access.",courtClauses:{fire:"After emerging from a raging fire, set touched objects alight for three turns without being harmed until moving on.",earth:"Treat manufactured minerals and metals such as concrete and steel as continuous with natural earth and stone.",air:"Ride a gust for up to Mantle minutes before being safely deposited.",water:"Exit a body of water anywhere within Mantle × 2 kilometers; duration becomes one scene."},loophole:"Carry a sample of every element, such as a flame, running fan, earth, and water."},
  {...zodiac,id:"h-courts:zodiac:age-of-aquarius",name:"Age of Aquarius",originalName:"Age of Aquarius",type:"Real",page:114,summary:"Overlay an alternate social destiny and identity upon a target.",description:"Overlay an alternate social destiny and identity upon a target.",hasRoll:true,dicePool:"Manipulation + Socialize + Mantle vs. Resolve + Wyrd",cost:"●●●○",action:"Contested",duration:"One week or chapter, whichever is shorter",success:"Name a broad social category. Everyone but the changeling and motley perceives the target as belonging to it; even friends roll Wits + Composure - Mantle to recognize her. Grant twice Mantle temporary Merit dots appropriate to the role and suppress incompatible Merits, which may use Sanctity of Merits.",exceptionalSuccess:"Duration becomes one story or one week, whichever is longer; Storyteller-approved pieces may become permanent if purchased with Experience.",failure:"The Contract fails.",dramaticFailure:"The changeling gains Dissociation and loses 10-again on all actions for the scene.",courtClauses:{fire:"Suppress the imposed destiny for one scene and improve the changeling's impression with the target by two steps.",earth:"Ignore untrained Skill penalties relevant to the role and add Mantle to relevant equipment bonuses.",air:"Role-aligned actions gain 9-again; actions aligned with the original persona lose 10-again.",water:"A Lost target may instead become socially identified as her fetch, gaining its relevant Merits without losing her own; the fetch's associates cease treating it as real."},loophole:"During the same scene, the target expressed dissatisfaction with their life or desire for a change."},
  {...zodiac,id:"h-courts:zodiac:assuming-the-stellar-mantle",name:"Assuming the Stellar Mantle",originalName:"Assuming the Stellar Mantle",type:"Real",page:114,summary:"Draw out a target's sun sign and grant three fitting Skill Specialties.",description:"Draw out a target's sun sign and grant three fitting Skill Specialties.",hasRoll:true,dicePool:"Manipulation + Persuasion + Mantle vs. Composure + Wyrd",cost:"●●",action:"Instant",duration:"One week",success:"Grant the target the three listed temporary Skill Specialties for their sun sign. Actions using them achieve exceptional success on three successes and restore 1 Willpower on such a result; changelings may regain 1 Glamour instead.",exceptionalSuccess:"Duration lasts until the zodiac changes signs, or through the following sign if it changes in less than a week.",failure:"The Contract fails.",dramaticFailure:"The worst qualities of the changeling's own sign intensify, inflicting Competitive, Paranoid, Withdrawn, or Wanton for the scene.",courtClauses:{fire:"Impose the qualities of any chosen fire sign.",earth:"Impose the qualities of any chosen earth sign.",air:"Impose the qualities of any chosen air sign.",water:"Impose the qualities of any chosen water sign."},loophole:"The zodiac is currently in the target's sign.",detailTables:[{title:"Example Stellar Mantles",columns:["Sign","Specialties"],rows:[["Aries","Direct Threats; Leadership; Sports"],["Taurus","Carousing; Gardening; Stare Down"],["Gemini","Doublespeak; Gossip; Puzzles"],["Cancer","Calming Emotions; Cooking; Diagnosis"],["Leo","Delegating; Drama; Speeches"],["Virgo","Hiding in Plain Sight; First Aid; Literature"],["Libra","Arbitration; Deference; Motives"],["Scorpio","Detecting Lies; Secrets; Seduction"],["Sagittarius","Translation; Navigation; Offroad Driving"],["Capricorn","Hiding Emotions; Interrogation; Scandals"],["Aquarius","Organizing; Programming; Research"],["Pisces","Music; Sermons; Uncovering Emotions"]]}]},
  {...zodiac,id:"h-courts:zodiac:elemental-cycle",name:"Elemental Cycle",originalName:"Elemental Cycle",type:"Real",page:115,summary:"Permanently transform a limited mass of one classical element into another.",description:"Permanently transform a limited mass of one classical element into another.",hasRoll:false,dicePool:"None",cost:"●●●○",action:"Instant",duration:"Permanent",effect:"Transform up to Mantle Size of predominantly fire, earth, air, or water into an ordinary form of another element. If this drops material onto someone, inflict Mantle bashing unless Dexterity + Athletics succeeds.",courtClauses:{fire:"Created fire burns for the scene without fuel and resists mundane extinguishing, but does not spread directly.",earth:"Once per story, created earth may be any natural unprocessed mineral or metal except iron.",air:"Created air may become a blast that inflicts Knocked Down.",water:"Triple the affected area when creating water."},loophole:"Transform along the cycle: fire to earth, earth to air, air to water, or water to fire."},
  {...zodiac,id:"h-courts:zodiac:restringing-the-loom",name:"Restringing the Loom",originalName:"Restringing the Loom",type:"Real",page:115,summary:"Sever an externally imposed fate, destiny, or doom.",description:"Sever an externally imposed fate, destiny, or doom.",hasRoll:false,dicePool:"None",cost:"●●○",action:"Instant",duration:"Instant",effect:"End an externally imposed magical destiny, such as Spinning Wheel, Horoscope, mage magic, or a ghostly hex, but not an inherent destiny. This normally causes a Clash of Wills, adding Mantle to the changeling's pool.",courtClauses:{fire:"The opposing Clash receives no dice tricks such as 10-again.",earth:"Use a Resistance rather than Finesse Attribute for the changeling's Clash pool.",air:"The changeling's Clash gains 8-again.",water:"The opposing Clash adds no duration bonus."},loophole:"The destiny was imposed by the changeling or a motley member."},
  {...directional,id:"h-courts:directional:break-in",name:"Break In",originalName:"Break In",type:"Comum",page:130,summary:"Open a locked Hedgeway without its required Key, at a lasting personal cost.",description:"Open a locked Hedgeway without its required Key, at a lasting personal cost.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"Instant",effect:"Learn the gate's required Key and open it only for the changeling. Thereafter, that Hedgeway recognizes the changeling as an intruder and refuses to open for her for the rest of the story, even with its Key.",courtClauses:{north:"Allow one other character through; only the Northern Courtier suffers the lasting prohibition.",east:"Regain 1 Willpower at the end of the scene if the changeling uses the gate while others want to but cannot.",south:"Up to Mantle changelings may pass, but all suffer the lasting prohibition.",west:"Leave the gate open for one additional person; crossing inflicts 1 lethal damage on that person.",center:"Ignore the lasting prohibition by spending 1 Willpower and performing a short ceremony to placate the gate."},loophole:"Encourage a mortal nearby to indulge their Vice."},
  {...directional,id:"h-courts:directional:key-to-the-heart",name:"Key to the Heart",originalName:"Key to the Heart",type:"Comum",page:131,summary:"Discover the most effective leverage for a Social maneuver against the target.",description:"Discover the most effective leverage for a Social maneuver against the target.",hasRoll:true,dicePool:"Manipulation + Empathy + Mantle vs. Composure + Wyrd",cost:"●",action:"Contested",duration:"Instant",success:"Learn what would best improve the target's impression during Social maneuvering, such as a suitable bribe, gift, or the target's Vice.",exceptionalSuccess:"Automatically open the target's first Door.",failure:"The Contract fails.",dramaticFailure:"The target gains two Doors.",courtClauses:{north:"Gain 9-again during the maneuver when using the changeling's lowest-rated Social Skill that has at least one dot.",east:"Actions using Soft Leverage gain 9-again.",south:"Rolls using Vice Leverage gain 9-again.",west:"Gain 9-again if the best leverage is a threat of violence.",center:"Improve the courtier's impression level by one."},loophole:"Openly state a similar weakness of the changeling where others can hear."},
  {...directional,id:"h-courts:directional:know-the-path",name:"Know the Path",originalName:"Know the Path",type:"Comum",page:131,summary:"Learn a trod's destination and instinctively navigate its route.",description:"Learn a trod's destination and instinctively navigate its route.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One scene",effect:"Learn the trod's destination and general environment, and gain +2 to actions made while traveling on it.",courtClauses:{north:"Gain +3 instead when taking a much longer route than necessary.",east:"Regain 1 Willpower on arrival if no Glamour was spent during the journey.",south:"Add Mantle to Defense after initiating violence during the journey.",west:"Learn specific hazards lurking just off the trod.",center:"First impressions made while on the trod are never hostile."},loophole:"Carry a physical map of an area the changeling has never visited."},
  {...directional,id:"h-courts:directional:redirect-trod",name:"Redirect Trod",originalName:"Redirect Trod",type:"Comum",page:131,summary:"Send pursuers leaving a trod to an unpredictable alternate destination.",description:"Send pursuers leaving a trod to an unpredictable alternate destination.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"Instant",effect:"When stepping off a trod, move its destination for pursuers by up to Wyrd × 2 kilometers in the mortal world or an equivalent Hedge distance. The Contract chooses the new destination.",courtClauses:{north:"Also inflict Stunned on the pursuer.",east:"For 1 additional Glamour, narrow the exit to five possible destinations; the Storyteller chooses which.",south:"Apply the redirection to the changeling instead, invoking it just before leaving the trod.",west:"Inflict Mantle dice of lethal damage on the pursuer.",center:"Send the pursuer back to the trod's entrance instead."},loophole:"Smash or otherwise break a compass."},
  {...directional,id:"h-courts:directional:show-me-the-way",name:"Show Me the Way",originalName:"Show Me the Way",type:"Comum",page:132,summary:"Find the fastest route to a nearby loved person or treasured object.",description:"Find the fastest route to a nearby loved person or treasured object.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"One scene",effect:"Know the quickest path to a motley member, Touchstone, mortal blood relation, or treasured object within roughly a medium-sized city, reaching it within a scene. Supernatural concealment triggers a Clash of Wills.",courtClauses:{north:"Regain 1 Willpower by taking an additional scene to finish the journey.",east:"Add Mantle to any resulting Clash of Wills.",south:"Track someone or something the changeling hates instead.",west:"Gain Danger Sense while following the path, or +2 Initiative if the changeling already has it and is attacked.",center:"Reduce the activation cost to 1 Glamour."},loophole:"Carry a piece of the sought subject, such as hair or clothing."},
  {...directional,id:"h-courts:directional:all-roads-closed",name:"All Roads Closed",originalName:"All Roads Closed",type:"Real",page:132,summary:"Fill every route to a defended location with obstructive hazards.",description:"Fill every route to a defended location with obstructive hazards.",hasRoll:true,dicePool:"Intelligence + Streetwise + Mantle",cost:"●●●●●",action:"Extended (10 successes; one minute per roll)",duration:"One chapter",success:"Obstruct all routes within Mantle × 2 kilometers leading to a previously visited location. Travelers must spend 1 Willpower to attempt passage and suffer -Mantle on relevant rolls. Mortals later forget or rationalize events. In the Hedge, treat this as a paradigm shift with up to activation successes in free changes.",exceptionalSuccess:"Sense the location and progress, but not identity, of anyone trying to find or attack the defended place.",failure:"The Contract fails.",dramaticFailure:"Anyone seeking or attacking the location gains Mantle dice to reach it.",courtClauses:{north:"Defenders gain 2 general armor that stacks with other armor.",east:"Defenders roll Initiative twice and keep the better result, and add Mantle to Speed.",south:"Apply an Environmental Tilt to one route, with level up to half Mantle rounded up.",west:"Defenders gain +1 weapon damage on attacks made to defend the location.",center:"Once per use, regain 1 Willpower when someone abandons an attempt to reach the location."},loophole:"Walk 800 steps in a cardinal direction away from the location."},
  {...directional,id:"h-courts:directional:cast-out",name:"Cast Out",originalName:"Cast Out",type:"Real",page:133,summary:"Expel a target through the nearest Hedgeway and strand them on the other side.",description:"Expel a target through the nearest Hedgeway and strand them on the other side.",hasRoll:true,dicePool:"Presence + Occult + Mantle vs. Stamina + Wyrd",cost:"●●",action:"Contested",duration:"One scene",success:"Force the chosen nearby Hedgeway open and the opponent through it. The gate closes and refuses the victim for the duration; choose the gate if several are present.",exceptionalSuccess:"Optionally inflict Mantle bashing damage on the victim.",failure:"The Contract fails.",dramaticFailure:"The changeling is expelled and stranded instead.",courtClauses:{north:"Extend the victim's imprisonment by one scene.",east:"Steal 1 Willpower from the victim.",south:"Pay 1 less Glamour while defending the freehold against the victim.",west:"A normal success also inflicts the exceptional effect; an exceptional success inflicts lethal damage instead.",center:"Set a condition for escape; agreement creates the equivalent of a strengthened sealing that Glamour cannot annul."},loophole:"Force together two repelling magnets that have never touched."},
  {...directional,id:"h-courts:directional:create-path",name:"Create Path",originalName:"Create Path",type:"Real",page:133,summary:"Hedgespin a temporary trod to a chosen endpoint.",description:"Hedgespin a temporary trod to a chosen endpoint.",hasRoll:true,dicePool:"Presence + Survival + Mantle",cost:"●●●○",action:"Extended (10 successes; one turn of Hedgespinning per roll)",duration:"Until the changeling completes the journey",success:"While in the Hedge, create a trod rated equal to Mantle to a chosen endpoint. It remains visible and usable by others until the changeling finishes the journey.",exceptionalSuccess:"Define the trod's milestones to provide a degree of safety.",failure:"The Contract fails.",dramaticFailure:"A trod opens to a disastrous destination or contains a catastrophic flaw chosen by the Storyteller.",courtClauses:{north:"Actions by others to locate the trod suffer -Mantle.",east:"Actions by others to locate the trod gain +Mantle.",south:"Other travelers must spend Willpower to attempt navigation rolls, without gaining +3.",west:"Others must succeed at Resolve + Composure - Mantle to enter the trod.",center:"Navigation actions on the trod exceptionally succeed on three successes."},loophole:"Possess one of the changeling's Icons personally recovered from the Thorns within the last 24 hours."},
  {...directional,id:"h-courts:directional:escape-route",name:"Escape Route",originalName:"Escape Route",type:"Real",page:133,summary:"Open a portal without asking and optionally control its destination.",description:"Open a portal without asking and optionally control its destination.",hasRoll:false,dicePool:"None",cost:"●● (+ ○ optional)",action:"Instant",duration:"One scene",effect:"When portaling into or out of the Hedge, open the gate without a request. It snaps shut after the changeling and requires its Key for the rest of the scene. Spend 1 Willpower to choose a destination that is not a secure location where the changeling is unwelcome; afterward the gate resumes its normal destination.",courtClauses:{north:"Add a 1 Willpower cost to activating the Hedgegate.",east:"Use any portal-shaped opening even if it cannot close.",south:"Alter the gate's Key for the scene to something possible to discover or perform within a scene.",west:"Gain +3 Initiative and Speed for the following scene.",center:"Redirect the portal to the changeling's home or Hollow without spending Willpower."},loophole:"Create a cloud such as smoke, dust, or flour."},
  {...directional,id:"h-courts:directional:labyrinth",name:"Labyrinth",originalName:"Labyrinth",type:"Real",page:134,summary:"Trap a victim's perceptions inside an illusory maze.",description:"Trap a victim's perceptions inside an illusory maze.",hasRoll:true,dicePool:"Manipulation + Subterfuge + Mantle vs. Resolve + Wyrd",cost:"●●",action:"Contested",duration:"Mantle turns",success:"The victim cannot perform Physical actions or benefit from Defense. Each later turn they may contest Resolve + Wyrd against the activation successes to escape; lethal damage ends the effect. Escaping inflicts Stunned and, for a changeling victim, a Mantle-die Clarity attack. The courtier then suffers a three-die Clarity attack.",exceptionalSuccess:"The victim remains trapped for the scene and cannot roll to escape, though damage still releases them.",failure:"The Contract fails.",dramaticFailure:"The changeling becomes trapped as the intended victim and suffers the associated Clarity attack.",courtClauses:{north:"The victim suffers -2 on rolls to escape early.",east:"Regain 1 Willpower if the victim escapes early.",south:"The invocation exceptionally succeeds on three successes.",west:"Inflict Demoralized after the victim escapes.",center:"The victim may accept Beaten Down to end the effect early and avoid the Clarity attack; the courtier still suffers theirs."},loophole:"Carry a completed puzzle and return it to its unsolved state."},
];
