import type { ContractDefinition } from "./contracts";

const base = {
  categoryKind: "Regalia" as const,
  regalia: "Crown",
  sourceId: "ctl-core",
  source: "Changeling the Lost",
};

export const CORE_CONTRACTS: ContractDefinition[] = [
  {...base,id:"ctl-core:hostile-takeover",name:"Hostile Takeover",originalName:"Hostile Takeover",type:"Comum",page:128,description:"Declare a right to occupy a dwelling. Mundane security ignores the changeling, doors open, and animal or hobgoblin sentries stand aside. Extend the effect to up to Presence companions kept in sight. Supernatural dwellings prompt a Clash of Wills, and the Contract cannot overcome a resident who also knows it.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant",duration:"One scene",loophole:"Carry an object belonging to the owner or main resident.",seemingBenefits:{Beast:"Animal sentries actively serve the Beast.",Fairest:"Gain +2 on the Clash of Wills against a supernatural dwelling's owner."}},
  {...base,id:"ctl-core:mask-of-superiority",name:"Mask of Superiority",originalName:"Mask of Superiority",type:"Comum",page:128,description:"Walk into a location as though entitled to belong to one organization represented there.",hasRoll:true,dicePool:"Presence + Subterfuge + Wyrd",cost:"●",action:"Instant",duration:"One scene",success:"Observers believe the changeling has Status in the chosen organization equal to Presence. Acting out of character may require Presence + Subterfuge contested by Wits + Empathy to preserve the deception.",exceptionalSuccess:"Observers instead believe he is a trusted Ally rated at Presence and excuse most gaps in institutional knowledge.",failure:"The Contract fails.",dramaticFailure:"Members immediately recognize the lie and become hostile.",loophole:"Dress loosely according to the organization's dress code.",seemingBenefits:{Fairest:"Reduce starting Doors by one in Social maneuvering against affected characters.",Ogre:"Add invocation successes, maximum +5, to Intimidation against anyone who believes the ruse."}},
  {...base,id:"ctl-core:paralyzing-presence",name:"Paralyzing Presence",originalName:"Paralyzing Presence",type:"Comum",page:129,description:"Overwhelm a target whose attention the changeling has captured with a magnificent and terrible presence.",hasRoll:true,dicePool:"Presence + Intimidation + Wyrd vs. Composure + Tolerance",cost:"●●",action:"Contested",duration:"One scene",success:"The target suffers Insensate.",exceptionalSuccess:"The target also gains Cowed.",failure:"The Contract fails.",dramaticFailure:"The unimpressed target inflicts Shaken on the changeling.",loophole:"Touch the target while they are otherwise alone.",seemingBenefits:{Darkling:"Use Manipulation instead of Presence.",Fairest:"Gain +3 dice to invoke the Contract."}},
  {...base,id:"ctl-core:summon-the-loyal-servant",name:"Summon the Loyal Servant",originalName:"Summon the Loyal Servant",type:"Comum",page:129,description:"Animate a drop of blood and nearby ephemeral or discarded matter into a simple loyal servant with Power 1, Finesse 3, Resistance 2, iron as its only frailty, and Size 1–7. It has appropriate natural advantages, obeys simple commands, and watches for threats.",hasRoll:false,dicePool:"None",cost:"●",action:"Instant",duration:"One scene or until destroyed",loophole:"Perform a significant favor for the chosen element or material during the scene.",seemingBenefits:{Elemental:"For +●○, merge with it, substitute its Attributes where desired, become immune to its material or element, and add +1L to weapon modifiers.",Fairest:"For +○, bind one servant to a Hollow indefinitely while it remains there."}},
  {...base,id:"ctl-core:tumult",name:"Tumult",originalName:"Tumult",type:"Comum",page:129,description:"Write a visible target's true name on a leaf and fold it into an origami bird to read and manipulate shards of dreams and nightmares.",hasRoll:true,dicePool:"Presence + Empathy + Wyrd - Resolve",cost:"●●",action:"Instant",duration:"Instant",success:"Learn whether the target has Disoriented, Guilty, Lost, Paranoid, Obsession, Spooked, Stoic, or Withdrawn. Per success, inflict one listed temporary Condition or define one trigger that delays the Contract.",exceptionalSuccess:"Apply one additional effect.",failure:"The Contract fails.",dramaticFailure:"The changeling gains one listed Condition of the player's choice.",loophole:"Plant an origami bird on the target during the scene.",seemingBenefits:{Fairest:"Also read and inflict Inspired, Swooned, and Wanton.",Ogre:"Also read and inflict Bestial, Cowed, and Frightened."}},
  {...base,id:"ctl-core:discreet-summons",name:"Discreet Summons",originalName:"Discreet Summons",type:"Real",page:130,description:"Reach blindly into a small container to summon an object, or open a door and invite a Wyrd 3 or lower hobgoblin to perform one task.",hasRoll:true,dicePool:"Manipulation + Persuasion + Wyrd vs. Composure + Tolerance",cost:"●/●●",action:"Instant for an object; Contested for a hobgoblin",duration:"One scene or until released or ignored",success:"Produce a functional Size 1, Availability 3 or lower object previously seen or handled, or summon a normal hobgoblin to perform one task. A sufficiently enticed hobgoblin comes willingly and makes the roll uncontested.",exceptionalSuccess:"The object may be Size 5 and Availability 5; a hobgoblin enthusiastically serves the assignment's spirit and performs useful follow-up tasks.",failure:"The summons fails.",dramaticFailure:"Retrieve an item with Volatile, or summon a secretly hostile hobgoblin.",loophole:"Draw the object from an enemy's holdings, or promise and deliver something practically or morally difficult for the hobgoblin.",seemingBenefits:{Darkling:"Draw the object or hobgoblin from a sufficiently large shadow.",Fairest:"The hobgoblin serves until the next sunrise or sunset even when ignored."}},
  {...base,id:"ctl-core:masterminds-gambit",name:"Mastermind's Gambit",originalName:"Mastermind's Gambit",type:"Real",page:130,description:"Spend at least five minutes monologuing a concrete goal into a parchment plan or repository granting +5 equipment. It lasts until chapter's end or definitively succeeds or fails.",hasRoll:false,dicePool:"None",cost:"●●",action:"Instant; takes at least five minutes",duration:"One chapter or until the plan succeeds or fails",loophole:"Draw the plan, hierarchy, or repository index on paper at least 50 years old.",seemingBenefits:{Elemental:"For +○, a repository lasts one story and expands to a Mental Specialty the Elemental possesses.",Fairest:"Create an organization suited to counter an enemy's influence instead of a plan."}},
  {...base,id:"ctl-core:pipes-of-the-beastcaller",name:"Pipes of the Beastcaller",originalName:"Pipes of the Beastcaller",type:"Real",page:131,description:"Play a silver flute to call all animals of one named species within Animal Ken miles and give them understandable verbal commands.",hasRoll:true,dicePool:"Manipulation + Animal Ken + Wyrd vs. Resolve + Composure",cost:"●",action:"Instant for willing animals; Contested for hostile animals",duration:"Until the task is completed or becomes impossible",success:"The animals gather, obey simple commands to the best of their ability, and return to report completion or an insurmountable obstacle.",exceptionalSuccess:"Control them for a day and night and issue new commands whenever speaking with them; mistreatment or impossible demands allow a new contest.",failure:"The summons fails.",dramaticFailure:"A large hostile animal or swarm arrives and attacks the changeling.",loophole:"Dance while playing the flute, mimicking the desired species.",seemingBenefits:{Beast:"Maintain an empathic link, awareness of condition and relative location, and give new orders remotely.",Fairest:"For +●, summon and command a second species."}},
  {...base,id:"ctl-core:the-royal-court",name:"The Royal Court",originalName:"The Royal Court",type:"Real",page:131,description:"Assume leadership of a meeting and prevent anyone present from inflicting bodily harm. Supernatural compulsions toward violence prompt a Clash of Wills. The Contract cannot stop violence already underway.",hasRoll:false,dicePool:"None",cost:"●●●○",action:"Instant",duration:"One scene",loophole:"Stand and deliver a speech lasting at least five minutes.",seemingBenefits:{Fairest:"Also prohibit Social intimidation and threats while allowing goodwill.",Wizened:"Also prohibit mental harm, including Clarity attacks but not breaking points."}},
  {...base,id:"ctl-core:spinning-wheel",name:"Spinning Wheel",originalName:"Spinning Wheel",type:"Real",page:132,description:"Name one reasonably probable, not overly specific experience for the target within the next lunar month. The changeling may maintain up to Wyrd pending destinies.",hasRoll:true,dicePool:"Intelligence + Occult + Wyrd - Resolve",cost:"●●●○",action:"Extended; each roll takes 10 minutes; target is the higher of Wyrd or Resolve",duration:"Until the lunar month ends or the event occurs",success:"Apply invocation successes, maximum ±5, as bonuses to rolls leading toward the event and penalties to rolls obstructing it. The Contract creates the event, not its outcome.",exceptionalSuccess:"Specify an action the target can take to prevent the experience and end the Contract.",failure:"The Contract fails.",dramaticFailure:"The changeling suffers a dramatic failure on a crucial roll chosen by the Storyteller during the next chapter.",loophole:"Prick the target with a needle or pin and draw blood; doing this to a willing target inflicts 1 lethal damage.",seemingBenefits:{Fairest:"Gain +3 to invoke a positive destiny and Inspired for actions supporting it.",Ogre:"Gain +3 to invoke a negative destiny and Steadfast for actions supporting it."}},
];
