export type EntitlementRole={id:string;name:string;prerequisites:string;privilege:string;duties:string;heraldryColor?:string;tokenBonus:string;tokenDrawback:string};
export type EntitlementBlessing={id:string;name:string;description:string;conditional?:boolean;choiceLabel?:string};
export type EntitlementDefinition={
  id:string;name:string;meritName:string;source:string;sourceCode:string;page:number;
  sourceId?:"h-courts"|"h-seemings";
  prerequisites:string;purpose:string;privileges:string;duties:string;maskAndMien:string;
  heraldry:string;token:{name:string;description:string;effect:string;catch:string;drawback:string};
  blessings:EntitlementBlessing[];roles?:EntitlementRole[];touchstone:string;curse:string;beat:string;legends:string[];
};

export const entitlementAvailable=(definition:EntitlementDefinition,activeSourceIds:ReadonlySet<string>)=>!definition.sourceId||activeSourceIds.has(definition.sourceId);

const COMMON_BLESSINGS:EntitlementBlessing[]=[
  {id:"glamour-gain",name:"Glamour Gain",description:"When the noble regains Willpower through her Needle in direct pursuit of the title's role, she also regains 1 Glamour. She may spend it immediately or store it in the heraldry token, up to her Wyrd. Stored Glamour empties at the end of the story."},
  {id:"inherited-expertise",name:"Inherited Expertise",description:"Gain a new Specialty relevant to the title's duty. Rolls using it achieve exceptional success with three successes.",choiceLabel:"Skill and Specialty"},
  {id:"predecessors-thread",name:"Predecessor's Thread",description:"Once per chapter, accept Shaken to remember a predecessor's traumatic experience and gain that predecessor's Thread in addition to the character's own for the chapter.",choiceLabel:"Predecessor's Thread"},
];

type HomebrewEntitlementSeed={id:string;name:string;meritName:string;sourceId:"h-courts"|"h-seemings";page:number;prerequisites:string;purpose:string;tokenName:string;tokenEffect:string;tokenCatch:string;tokenDrawback:string;specialBlessings:[EntitlementBlessing,EntitlementBlessing];touchstone:string;curse:string;beat:string};
const homebrewEntitlement=(seed:HomebrewEntitlementSeed):EntitlementDefinition=>({
  ...seed,source:seed.sourceId==="h-courts"?"Book of Courts":"Book of Seemings",sourceCode:seed.sourceId==="h-courts"?"BoC":"BoS",
  privileges:`The title grants the authority, reputation, and supernatural advantages described by ${seed.meritName}.`,duties:`The titleholder must pursue ${seed.purpose.toLowerCase()} and uphold the title's traditions.`,maskAndMien:"The title reshapes the changeling's mien and marks her with its heraldic imagery.",heraldry:`The heraldry associated with ${seed.name}.`,
  token:{name:seed.tokenName,description:`The hereditary heraldry token of ${seed.name}; its rating equals the ranks allocated to Heraldry.`,effect:seed.tokenEffect,catch:seed.tokenCatch,drawback:seed.tokenDrawback},
  blessings:[...COMMON_BLESSINGS,...seed.specialBlessings],touchstone:seed.touchstone,curse:seed.curse,beat:seed.beat,legends:[],
});

const HOMEBREW_ENTITLEMENTS:EntitlementDefinition[]=[
  homebrewEntitlement({id:"adjudicator-wheel",name:"Adjudicator of the Wheel",meritName:"Judge's Zeal",sourceId:"h-courts",page:34,prerequisites:"Resolve 3, Investigation 2, Trained Observer 1.",purpose:"Right wrongs and impose justice even when the law fails.",tokenName:"Wheel of Fortune",tokenEffect:"Gain 9-again on mission-related Investigation actions. Its rating can twist an unfolding story within the Judge's presence, and once per chapter it can grant rote action to a roll that indirectly furthers justice.",tokenCatch:"Place a thread from the current target's clothing on the Wheel and cut it in half.",tokenDrawback:"Gain Obsession concerning the investigation or punishment.",specialBlessings:[{id:"judges-kenning",name:"Judge's Kenning",description:"When using Kenning, spend 1 Glamour to see the most likely future of one observed subject up to Wyrd/2 days ahead.",conditional:true},{id:"vicarious-hostile-oath",name:"Vicarious Hostile Oath",description:"Swear a hostile oath on another person's behalf, making its effects bind the Adjudicator and a third party."}],touchstone:"A mortal whom the Adjudicator previously failed to protect from injustice.",curse:"Clarity attacks caused by knowingly allowing injustice add dice equal to invested ranks.",beat:"Right an injustice at significant personal or motley cost."}),
  homebrewEntitlement({id:"blackbird-bishop",name:"The Blackbird Bishop",meritName:"Bishop's Benevolence",sourceId:"h-courts",page:37,prerequisites:"Empathy 2, Wits 3, Composure 3.",purpose:"Ease anguish, hear confession, and guide the suffering toward restitution.",tokenName:"Argent Aspersorium",tokenEffect:"Transfer Clarity damage and mental Conditions from others to the Bishop, affect up to twice its rating subjects per chapter, add its rating to Perception, and temporarily store the Bishop's own Clarity Conditions.",tokenCatch:"Fill it with natural water mixed with the Bishop's tears.",tokenDrawback:"Gain Confused, Guilty, or Withdrawn, chosen by the Storyteller.",specialBlessings:[{id:"blackbird-flock",name:"Blackbird Flock",description:"Gain a Wyrd/2-dot Retainer, rounded up, formed by dark-feathered birds that recognize mental Conditions.",conditional:true},{id:"sealed-amends",name:"Sealed Amends",description:"Freely seal a sincere confession and plan for amends; fulfillment restores Clarity damage or Integrity lost to the wrongdoing and restores 1 Willpower to the Bishop.",conditional:true}],touchstone:"A mortal whose mental anguish the Bishop eased.",curse:"Clarity attacks caused by inflicting Clarity damage or breaking points on others add dice equal to invested ranks.",beat:"Enter physical danger to preserve another person's Clarity or Integrity."}),
  homebrewEntitlement({id:"diviners-worms",name:"Diviners of Worms",meritName:"Diviner's Foresight",sourceId:"h-courts",page:40,prerequisites:"Occult 2, Diviner 3, Trained Observer 1.",purpose:"Read omens and warn others of dangers written into Fate.",tokenName:"Diviner's Instrument",tokenEffect:"Use Diviner without entering a dream: each question takes two turns, ask up to the Instrument's rating questions plus one follow-up each without consuming dream-based questions. Once per chapter, perform an extended Intelligence + Occult Research action (ten minutes per roll), adding rating as Library dots, to gain Informed; the roll that spends Informed gains the same bonus. Once per chapter, spend 1 Glamour before persuading others about a prophecy to exceptionally succeed on three successes.",tokenCatch:"Take 1 lethal damage from a helpless victim and spread the blood on the Instrument; self-harm cannot satisfy this Catch.",tokenDrawback:"Gain Distracted as everything appears portentous; it does not penalize use of the token or rolls benefiting from it.",specialBlessings:[{id:"omens-common-sense",name:"Omens of Fate",description:"Use Common Sense through observed omens with a bonus equal to Wyrd/2, rounded up.",conditional:true},{id:"prophetic-danger-sense",name:"Prophetic Danger Sense",description:"Gain enhanced Danger Sense against every immediate threat, including environmental dangers; double its bonus if the Instrument was activated this scene."}],touchstone:"A mortal once protected by the Diviner's prophecies.",curse:"Clarity attacks suffered when someone rejects the Diviner's prophecy add dice equal to invested ranks.",beat:"Offer helpful prophecy that seriously endangers or inconveniences the Diviner."}),
  homebrewEntitlement({id:"duchess-truth-loss",name:"Duchess of Truth and Loss",meritName:"Hunting Truth and Hiding Loss",sourceId:"h-courts",page:43,prerequisites:"Wits 3, Investigation 2, and must have killed a fetch.",purpose:"Hunt concealed people and reveal the truth of stolen lives.",tokenName:"False Face of Truth",tokenEffect:"Feed its mouth a subject's hair or blood to identify them infallibly as fetch, human, or changeling, bypassing concealment without a Clash; it remains silent for other beings. When worn, impose the token's rating as a penalty on any mundane or mystical attempt by a fetch to locate the user. A fetch can never use it.",tokenCatch:"Stab yourself with its pin and leave it in your flesh for the scene, suffering -1 to actions.",tokenDrawback:"You cannot knowingly lie during the next scene; serious trouble caused by this grants a Beat.",specialBlessings:[{id:"relentless-quarry",name:"Relentless Quarry",description:"Add Wyrd/2, rounded up, to Investigation, Survival, and Perception rolls to locate someone actively hiding from the Duchess.",conditional:true},{id:"preserve-fetch",name:"Preserve Fetch",description:"Touch a dead or dying fetch and spend 1 Glamour to prevent its dissolution for one lunar month; presenting it to its changeling heals one minor Clarity damage and refreshes Willpower."}],touchstone:"An object instrumental in the death of the first fetch the Duchess killed.",curse:"Clarity attacks caused by others defending the Duchess's quarry add dice equal to invested ranks.",beat:"Pursue a hidden truth despite grave personal consequences."}),
  homebrewEntitlement({id:"goldspinner-guildmaster",name:"Guildmaster of Goldspinners",meritName:"Plutomancer's Privilege",sourceId:"h-courts",page:46,prerequisites:"Academics with a Finance or Business Specialty, Resources 3.",purpose:"Manipulate wealth, debt, and desperation through fae economics.",tokenName:"Spindle's Talon",tokenEffect:"After a spoken bargain between user and petitioner, spin any form of wealth for one hour, producing one dot of Resources per hour. The user can never spend it; attempting to do so destroys the thread. Bargaining and negotiation in the Talon's presence, including supernatural contracts, exceptionally succeed on three successes.",tokenCatch:"Burn the equivalent of one dot of Resources before the Spindle.",tokenDrawback:"When spinning ends, the user pricks a finger and gains Lethargic until sleeping it off.",specialBlessings:[{id:"plutomancer-merits",name:"Accumulated Expertise",description:"Gain Mental Merit dots equal to Wyrd/2, rounded up, distributed as desired.",choiceLabel:"Mental Merits"},{id:"sense-desperation",name:"Sense Desperation",description:"Spend 1 Glamour to identify who nearby is most desperate for money."}],touchstone:"A cherished item owned since before taking the title that has no significant monetary value.",curse:"Clarity attacks connected to valuing wealth over people add dice equal to invested ranks.",beat:"Suffer meaningful loss by putting another person's financial needs first."}),
  homebrewEntitlement({id:"paragon-story-heroes",name:"Paragon of Story Heroes",meritName:"Threadmender",sourceId:"h-courts",page:49,prerequisites:"Wits 3, Academics 2, Persuasion or Subterfuge 2.",purpose:"Repair stories, rescue people from disastrous narratives, and embody heroic turns.",tokenName:"Scroll of Shifting Threads",tokenEffect:"Ask about the narratives affecting a person or situation to learn its Conditions, Tilts, and supernatural powers without their origins. Spend 1 Glamour for 9-again on Social and Mental actions involving someone read this scene. Ask directions to gain Direction Sense until arrival or scene end. Once per chapter, spend 1 Willpower to give rote quality to three actions serving one stated goal.",tokenCatch:"Tell a complete story from memory for at least ten minutes.",tokenDrawback:"The next Hedge entry provokes a three-die Clarity attack; exceptional success grants a Beat. Without Clarity, take lethal damage instead.",specialBlessings:[{id:"rescued-allies",name:"Rescued Allies",description:"Gain Allies equal to Wyrd/2, rounded up, representing people saved by current or previous Paragons.",conditional:true,choiceLabel:"Allied group"},{id:"pivotal-speech",name:"Pivotal Speech",description:"Spend 1 Glamour at a pivotal moment to deliver an uninterruptible short speech that bends the scene toward an appropriate heroic turn."}],touchstone:"A mortal whose life was saved from a disastrous turn by the Paragon.",curse:"Clarity attacks caused by allowing a story to end disastrously add dice equal to invested ranks.",beat:"Accept hardship to give another person's story a better ending."}),
  homebrewEntitlement({id:"sacred-band-golden-standard",name:"Sacred Band of the Golden Standard",meritName:"The Best Around",sourceId:"h-courts",page:52,prerequisites:"Presence 3, Wyrd 2, one chosen Skill at 3+ with an appropriate Specialty.",purpose:"Perform legendary feats and inspire witnesses through peerless mastery.",tokenName:"Golden Bands",tokenEffect:"On activation, add the Band's rating to Presence-based pools. The user need not resist unconsciousness or bleeding out when the last Health box holds bashing or lethal damage. Once per week, spend 1 Willpower while pursuing glory against impossible odds to prevent death a number of times equal to rating for the scene.",tokenCatch:"Dramatically fail an action in full view of witnesses.",tokenDrawback:"Gain Competitive when the token activates.",specialBlessings:[{id:"golden-standard-points",name:"Golden Standard",description:"Each chapter gain Wyrd/2 points, rounded up; spend one to make three successes an exceptional success or deny an opposing roll 10-again in a relevant contest."},{id:"inspiring-mastery",name:"Inspiring Mastery",description:"Once per chapter, success with the chosen Skill can grant Inspired to everyone who personally witnessed it."}],touchstone:"A mortal fan or small fan club won by witnessing an apparently impossible feat.",curse:"Failure or dramatic failure with the chosen Skill acts as a Clarity attack with dice equal to invested ranks.",beat:"Defy expectations by succeeding at an incredible challenge."}),
  homebrewEntitlement({id:"squire-broken-bough",name:"Squire of the Broken Bough",meritName:"Squire's Vow",sourceId:"h-courts",page:55,prerequisites:"Composure 3, Resolve 3, Weaponry 2.",purpose:"Champion a victim's cause until justice or vengeance is complete.",tokenName:"Broken Blade",tokenEffect:"Functions as its current cutting weapon and passively gains Durability equal to rating. When activated, if the Squire dies, Blade and body dissolve and return on the Thorns side of the nearest Hedge gate at the next sunrise or sunset in their activation state, removing all injuries and Conditions except Clarity Conditions.",tokenCatch:"Destroy something personally important with the Blade.",tokenDrawback:"Resurrection marks the leftmost Clarity box with permanent mild damage and grants a Beat; characters without Clarity permanently lose one Willpower dot.",specialBlessings:[{id:"squires-reserve",name:"Squire's Reserve",description:"After swearing to a victim's cause, gain extra Willpower equal to Wyrd/2, rounded up, until spent or a new cause is taken."},{id:"deathly-reputation",name:"Deathly Reputation",description:"Once per scene spend 1 Willpower to inflict Frightened on someone who previously witnessed the Squire's death.",conditional:true}],touchstone:"The Squire's current client.",curse:"Clarity attacks suffered when someone breaks a formal oath or pledge to the Squire add dice equal to invested ranks.",beat:"Suffer serious hardship or injury while championing another's cause."}),
];

HOMEBREW_ENTITLEMENTS.push(
  homebrewEntitlement({id:"companion-resigned",name:"Companion of the Resigned",meritName:"Best Friend Ever",sourceId:"h-seemings",page:31,prerequisites:"Empathy 3, Expression 2, Stealth 2.",purpose:"Become the steadfast companion of someone who has lost hope.",tokenName:"Infinite Popup Book",tokenEffect:"Show the book to one person to gain 8-again on Empathy, Expression, and Subterfuge actions with them for 24 hours. When unobserved, hide one Size 2 or smaller object between its pages. Once per chapter, whisper the name of a close person in trouble to learn their rough location and circumstances, subject to Clash of Wills against magical concealment.",tokenCatch:"Tell the book a short anecdote about a friend that it has never heard.",tokenDrawback:"While drawing power from the book, lose three dice to detect lies or resist emotional manipulation by strangers and enemies.",specialBlessings:[{id:"true-friend-project",name:"True Friend Project",description:"Gain True Friend for the Companion's current project. When their life is fixed or cannot be fixed, Sanctity of Merits applies only toward a new True Friend project.",conditional:true,choiceLabel:"Current friend"},{id:"friend-present-stealth",name:"Always Another Cousin",description:"Gain +5 Stealth in any scene where the Companion's friend is present.",conditional:true}],touchstone:"The Companion's current best friend.",curse:"Clarity attacks for harming someone who is not obviously hostile add dice equal to invested ranks.",beat:"Cheer up someone who was previously despondent."}),
  homebrewEntitlement({id:"castellan-broken-cage",name:"Castellan of the Broken Cage",meritName:"Spark of Metamorphosis",sourceId:"h-seemings",page:50,prerequisites:"Manipulation 3, Empathy or Socialize 2, Wyrd 2+.",purpose:"Push chosen chrysalids beyond convention toward radical personal change.",tokenName:"Lepidopteran Locket",tokenEffect:"Know the current chrysalid's location and activity, add rating to rolls encouraging change, and spend 1 Glamour to grant a chrysalid rote action on one growth-related action per scene.",tokenCatch:"Make a noticeable, difficult-to-reverse change to the surroundings.",tokenDrawback:"After succeeding with a dice pool, repeating that pool in the scene suffers a cumulative -1.",specialBlessings:[{id:"former-chrysalids",name:"Former Chrysalids",description:"Gain Allies equal to Wyrd/2, rounded up, representing grateful former chrysalids.",conditional:true,choiceLabel:"Allied chrysalids"},{id:"desire-sense",name:"Desire Sense",description:"Always know when someone lies about what they desire; unconscious desires produce a fainter impression."}],touchstone:"A former chrysalid whose life was completely transformed by the Castellan.",curse:"Clarity attacks when a chrysalid suffers negative consequences from the Castellan's attention add dice equal to invested ranks.",beat:"Be confronted by someone from a chrysalid's life."}),
  homebrewEntitlement({id:"duke-icebound-heart",name:"Duke of the Icebound Heart",meritName:"Icebound Promises",sourceId:"h-seemings",page:53,prerequisites:"Presence or Manipulation 3, Socialize 2, Empathy 2.",purpose:"Win hearts, break them, and embody the cold distance of the consummate rake.",tokenName:"Winter's Heart",tokenEffect:"Speak a known subject's name on activation to become the focus of their thoughts for a moment anywhere in the world. Spend 1 Glamour at a social gathering to perceive the emotional connections among those present. Add the token's rating to seduction, romance, and innocent-seeming social manipulation.",tokenCatch:"Write the full name of someone truly loved, show it to someone new, then burn it.",tokenDrawback:"Gain Wanton until resolved or until it fades after the user's next sleep.",specialBlessings:[{id:"icebound-social-merits",name:"Icebound Social Standing",description:"Gain mundane Social Merit dots equal to Wyrd/2, rounded up, representing the Duke's methods and reputation.",conditional:true,choiceLabel:"Social Merits"},{id:"escape-machinations",name:"Escape Machinations",description:"Gain +3 Defense and Speed when escaping danger caused by the Duke's own schemes."}],touchstone:"A mortal whose heart the Duke broke, past or present.",curse:"Clarity attacks while another suffers because of the titleholder's intentional actions add dice equal to invested ranks.",beat:"Suffer a negative consequence because of a current or former romance."}),
  homebrewEntitlement({id:"eternal-echo",name:"The Eternal Echo",meritName:"Echo's Memory",sourceId:"h-seemings",page:56,prerequisites:"Resolve 3, Academics 2, Expression 2.",purpose:"Record the lives and stories of the Lost so their truth cannot disappear.",tokenName:"Record of the Lost",tokenEffect:"Play any known recording; otherwise roll Wits + Occult with a bonus equal to rating or hear random audio on failure. Holding it penalizes breaking-point pools caused by its contents by rating. Spend 1 Glamour to record one scene of permanent, perfect audio. Once per activation, transfer one recording into memory or one scene of memory into the Record; hold foreign memories up to rating.",tokenCatch:"Tell the Record a truth never told to anyone else.",tokenDrawback:"Forget the truth used to activate the Record.",specialBlessings:[{id:"echo-eidetic",name:"Eidetic Echo",description:"Gain Eidetic Memory; if already possessed, gain two Merit dots to distribute instead. Spend 1 Glamour to double its bonus."},{id:"immutable-memory",name:"Immutable Memory",description:"The Echo's memory cannot be altered artificially. Add invested ranks to rolls resisting forced disclosure."}],touchstone:"The mortal family of a changeling recorded in the Record of the Lost within living memory.",curse:"Clarity attacks caused by discovering important lies add dice equal to invested ranks.",beat:"Hear a morally repugnant story, or an enemy's story, without judging the teller."}),
  homebrewEntitlement({id:"knights-knowledge-tongue",name:"Knights of the Knowledge of the Tongue",meritName:"Symphony for the Senses",sourceId:"h-seemings",page:59,prerequisites:"Stamina 3, Crafts 2 with a Cooking Specialty.",purpose:"Create transformative cuisine from rare ingredients and share sensory wonder.",tokenName:"Magical Measuring Spoons",tokenEffect:"The spoons always measure perfectly and grant rote action on cooking. Spend 1 Glamour while cooking to give each diner Inspired for a chosen Skill or one dot of a Changeling Merit other than Mantle until day's end, ignoring prerequisites. Add the token's rating to smell- or taste-based Perception.",tokenCatch:"Eat three bites of a food the user hates.",tokenDrawback:"When exposed to intense or unpleasant sensations, roll Resolve + Stamina; failure inflicts Distracted for the scene.",specialBlessings:[{id:"culinary-network",name:"Culinary Network",description:"Gain Wyrd/2 dots, rounded up, split among Contacts and Allies connected to food and rare ingredients.",conditional:true,choiceLabel:"Culinary contacts"},{id:"ingredient-lore",name:"Ingredient Lore",description:"Gain +3 to locate or identify unusual ingredients and recognize any animal previously cooked with."}],touchstone:"A favorite mundane cooking implement or recipe book.",curse:"Clarity attacks when disaster results from the Knight's cooking add dice equal to invested ranks.",beat:"Suffer personal harm while seeking rare ingredients."}),
  homebrewEntitlement({id:"legate-black-apple",name:"Legate of the Black Apple",meritName:"Benediction of the Orchard",sourceId:"h-seemings",page:62,prerequisites:"Two Social Skills at 4+, combined Resolve and Composure 7+, Wyrd 3+.",purpose:"Act as diplomat and protector between the Lost and dangerous fae societies.",tokenName:"Apple Pendant",tokenEffect:"Whisper a True Fae Title to compel a response to a request for negotiation; on activation gain at least Wyrd minutes to plead before it may act. Add rating to Wits or Manipulation actions tied to the Legate's duties. Once per day, spend 1 Glamour to add Composure to Defense for the scene.",tokenCatch:"Let the pendant's thorn pierce the user and take 1 lethal damage.",tokenDrawback:"After making any physical attack, suffer -2 to all Wits, Manipulation, and Dexterity actions for the rest of the scene.",specialBlessings:[{id:"orchard-courage",name:"Orchard Courage",description:"Spend 1 Glamour to grant +3 to resist fear and intimidation for the scene."},{id:"legate-hedge-merits",name:"Hedge Retinue",description:"Gain Wyrd/2 Merit dots, rounded up, distributed among Fae Mount, Hedge Sense, Hedgewise, and Hob Kin.",conditional:true,choiceLabel:"Hedge Merits"}],touchstone:"A mortal whom the Legate or a predecessor saved from the Gentry as a child.",curse:"Clarity attacks involving someone the Legate could not assist add dice equal to invested ranks.",beat:"Suffer serious physical injury or Clarity damage while performing the title's duties."}),
  homebrewEntitlement({id:"lost-pantheon",name:"The Lost Pantheon",meritName:"Primordial Incarnation",sourceId:"h-seemings",page:65,prerequisites:"Presence 3, Occult 2 with a Specialty in the chosen deity, Wyrd 3+.",purpose:"Incarnate an ancient deity's domain and establish worship within the freehold.",tokenName:"Celestial Medallion",tokenEffect:"The Medallion returns to its rightful keeper within 24 hours if stolen. Gain 8-again on first impressions with humans, upgraded to rote for worshippers. Spend 1 Glamour in a sacred place or ritual to add rating for the scene to actions demanding worship, obedience, or duty. Reaping willing worshippers grants them Inspired and Ravaged.",tokenCatch:"Immerse or pass the Medallion through the deity's element for one hour while reciting prayers.",tokenDrawback:"For the rest of the day, gain Distracted from pervasive visions of the Wyrd.",specialBlessings:[{id:"pantheon-temple",name:"Consecrated Temple",description:"Consecrate one permitted Hollow as a temple; entrants who offer nothing must overcome Resolve + Composure penalized by invested ranks."},{id:"divine-element",name:"Divine Element",description:"Spend 1 Willpower to imbue an object with the deity's element for the scene; an aligned Sprite may absorb it once per day to heal one superficial Clarity damage.",conditional:true}],touchstone:"An icon, relic, statue, or sacred object representing the deity.",curse:"Clarity attacks when others scorn, disbelieve, or ignore the deity add dice equal to invested ranks.",beat:"Place the deity's domain above the needs of the motley, court, or freehold, or enter danger for it."}),
  homebrewEntitlement({id:"magistrates-wax-mask",name:"Magistrates of the Wax Mask",meritName:"Magistrate's Discretion",sourceId:"h-seemings",page:68,prerequisites:"Composure 3, Socialize 2, Subterfuge 3.",purpose:"Serve clients with absolute discretion while remaining unseen and unread.",tokenName:"Wax Masks",tokenEffect:"Press a Servant Mask to a human-shaped effigy and name a profession to animate it for 24 hours with a strengthened Mask and abilities limited to that profession. Activate the Master Mask and spend 1 Glamour per effigy to command them for 24 hours.",tokenCatch:"Servant: seal the Mask with blood for 1 bashing damage. Master: irretrievably pay each effigy one hour of local minimum wage.",tokenDrawback:"Servant effigies sometimes reveal their true nature. The Master Mask deals 1 lethal damage for each promised service the user definitively fails to perform.",specialBlessings:[{id:"magistrate-unnoticed",name:"Unnoticed Magistrate",description:"Unless actively drawing attention, simple Perception rolls notice the Magistrate only on an exceptional success.",conditional:true},{id:"perfect-discretion",name:"Perfect Discretion",description:"Add Wyrd/2, rounded up, to Composure or Subterfuge rolls to hide reactions and later deny witnessing an event.",conditional:true}],touchstone:"A solitary hobby pursued alone.",curse:"Clarity attacks while favoring personal needs over a client's add dice equal to invested ranks.",beat:"Sacrifice personal safety in the name of professionalism."}),
  homebrewEntitlement({id:"magus-gilded-thorns",name:"Magus of the Gilded Thorns",meritName:"Heart of the Brambles",sourceId:"h-seemings",page:71,prerequisites:"Composure 3, Stealth 2, Hedge Sense, Wyrd 2+.",purpose:"Commune with the Hedge, shelter travelers, and turn its paths against pursuers.",tokenName:"Thorned Crown",tokenEffect:"Attune the wearer to the Hedge's impossible logic and impose the token's rating against beings unaccustomed to it.",tokenCatch:"Willingly take 1 lethal damage from the Hedge.",tokenDrawback:"Removing the Crown inflicts Confused while the user readjusts to mundane reality.",specialBlessings:[{id:"false-trail",name:"False Trail",description:"Spend 1 Glamour to make a Hedge traveler's traces point elsewhere unless tracking achieves exceptional success; even Huntsmen are misled until the traveler exits."},{id:"deep-hedge-sight",name:"Deep Hedge Sight",description:"Add Wyrd/2, rounded up, to navigation; at Wyrd 3 see through Hedge gates, and at Wyrd 6 see what waits at a trod's end.",conditional:true}],touchstone:"A lush mundane garden, typically centered on a bramble bush.",curse:"Clarity attacks caused by lack of human contact add dice equal to invested ranks.",beat:"Deny shelter to a fleeing changeling or aid its fae pursuer at the Hedge's whim."}),
  homebrewEntitlement({id:"margrave-brim",name:"Margrave of the Brim",meritName:"Thorn Threnody",sourceId:"h-seemings",page:74,prerequisites:"Brawl or Weaponry 3, Survival 2, Wyrd 2+.",purpose:"Guard, map, and stabilize the Hedge surrounding vulnerable freeholds.",tokenName:"Petrified Blade",tokenEffect:"Reveal nearby Hedge dangers and guide the bearer through hostile terrain; the Blade's rating reinforces combat and navigation appropriate to the title.",tokenCatch:"Announce yourself loudly and hold the sword aloft for at least one minute.",tokenDrawback:"Gain Reckless, convinced that no challenge or foe is beyond you.",specialBlessings:[{id:"hedge-interdisciplinary",name:"Hedge Interdisciplinary Specialty",description:"Gain Interdisciplinary Specialty focused on the Hedge.",conditional:true},{id:"hedge-chase",name:"Master of Hedge Chases",description:"In a Hedge chase, reduce the base successes needed to prevail by twice the ranks invested in this Merit."}],touchstone:"A mortal whose life improved through the Margrave's aid.",curse:"Clarity attacks when someone promised protection or guidance suffers physical injury add dice equal to invested ranks.",beat:"Assist an ungrateful person or someone who questioned the Margrave's ability."}),
  homebrewEntitlement({id:"noble-sages",name:"Noble Sages of the Unknown Reaches",meritName:"Sage's Expertise",sourceId:"h-seemings",page:77,prerequisites:"Occult 2, plus the chosen role: Archivist — Intelligence 3 and Academics 2; Diplomat — Wits 3 and Persuasion 2; Bane — Resolve 3 and Athletics 2.",purpose:"Study non-fae supernatural beings as archivist, diplomat, or hunter.",tokenName:"Arcane Rings",tokenEffect:"Name a kind of supernatural being while examining a subject to receive an infallible yes-or-no identification in person.",tokenCatch:"Recite a piece of lore about the named being that this user has never used for the Catch before.",tokenDrawback:"Gain Obsession focused on learning something new about the named being.",specialBlessings:[{id:"supernatural-contacts",name:"Supernatural Contacts",description:"Gain Contacts equal to Wyrd/2, rounded up, each representing a different non-fae supernatural community.",conditional:true,choiceLabel:"Supernatural communities"},{id:"supernatural-barfly",name:"Supernatural Barfly",description:"Gain a version of Barfly that applies to gatherings of non-fae supernatural creatures and ignores the usual prerequisites."}],touchstone:"A mundane scholar of folklore, mythology, or monster-focused popular culture.",curse:"Clarity attacks caused by breaking a promise to non-fae supernatural beings add dice equal to invested ranks.",beat:"Place the pursuit of supernatural knowledge above the needs of the motley, court, or freehold."}),
  homebrewEntitlement({id:"scarecrow-minister",name:"The Scarecrow Minister",meritName:"Scarecrow's Duty",sourceId:"h-seemings",page:80,prerequisites:"Composure 3, Empathy 2 with a Fear Specialty, Intimidation 3.",purpose:"Protect mortals by cultivating fear, warnings, and cautionary legends.",tokenName:"Bugbear Mask",tokenEffect:"Magnify fear and embody a chosen cautionary monster while the Mask is worn.",tokenCatch:"Scare someone the wearer considers a friend or ally during the same scene.",tokenDrawback:"The Mask adheres to the skin for the day; removing it requires Strength and deals three dice of bashing damage.",specialBlessings:[{id:"read-fears",name:"Read Fears",description:"After succeeding at Empathy against a sapient being, roll Wyrd and learn one fear per success; this is automatic."},{id:"fear-harvest",name:"Fear Harvest",description:"Successful Glamour harvests created by fear gain extra Glamour equal to invested ranks."}],touchstone:"A mortal safeguarded from the supernatural by the Minister frightening them away from it.",curse:"Clarity attacks after gaining fear-based Conditions such as Spooked or Frightened add dice equal to invested ranks.",beat:"Sacrifice personal goals or relationships to strengthen an urban legend or cautionary tale."}),
  homebrewEntitlement({id:"tolltaker-knight",name:"The Tolltaker Knight",meritName:"Chevalier's Oath",sourceId:"h-seemings",page:83,prerequisites:"Composure 3, Brawl or Weaponry 2, Intimidation 2.",purpose:"Accept a quarry and collect the promised price without abandoning the hunt.",tokenName:"Luminous Lodestar",tokenEffect:"Track an identified quarry; spend 1 Glamour while seeing a fleeing or hiding target to impose -3 Speed and Stealth for the scene.",tokenCatch:"Make a promise to the Wyrd, treated as a sealing without Glamour cost.",tokenDrawback:"Suffer -5 to Stealth and Subterfuge for the rest of the scene.",specialBlessings:[{id:"tolltaker-quarry",name:"Tolltaker's Quarry",description:"Spend 1 Willpower before combat with the quarry to halve its Defense, rounded up, and impose -2 Initiative; only one quarry at a time."},{id:"predecessor-payment",name:"Predecessor's Payment",description:"Gain a Token or Hollow rated Wyrd/2, rounded up, inherited as payment for a predecessor's difficult assignment.",conditional:true,choiceLabel:"Token or Hollow"}],touchstone:"An item taken from the Knight's first bounty.",curse:"Clarity attacks when someone is harmed by keeping a promise add dice equal to invested ranks.",beat:"The Knight's reputation causes someone to think poorly of him."}),
);

const nobleSages=HOMEBREW_ENTITLEMENTS.find((item)=>item.id==="noble-sages");
if(nobleSages)nobleSages.roles=[
  {id:"archivist",name:"Archivist",prerequisites:"Intelligence 3, Academics 2, Occult 2",privilege:"Catalog and interpret supernatural lore.",duties:"Preserve accurate records of non-fae beings.",tokenBonus:"Use the Arcane Ring as an investigator and scholar.",tokenDrawback:"Obsession"},
  {id:"diplomat",name:"Diplomat",prerequisites:"Wits 3, Persuasion 2, Occult 2",privilege:"Negotiate with non-fae supernatural communities.",duties:"Maintain lines of communication and honor agreements.",tokenBonus:"Use the Arcane Ring to identify those met in negotiation.",tokenDrawback:"Obsession"},
  {id:"bane",name:"Bane",prerequisites:"Resolve 3, Athletics 2, Occult 2",privilege:"Confront dangerous non-fae supernatural beings.",duties:"Protect others when research and diplomacy fail.",tokenBonus:"Use the Arcane Ring to identify a quarry before acting.",tokenDrawback:"Obsession"},
];

export const ENTITLEMENTS:EntitlementDefinition[]=[
  {
    id:"baron-lesser-ones",name:"Baron of the Lesser Ones",meritName:"Baron's Bond",source:"Oak, Ash, and Thorn",sourceCode:"OA&T",page:37,
    prerequisites:"Empathy 2; Intimidation or Persuasion 2; Gentrified Bearing, Hob Kin, or Interdisciplinary Specialty (Goblins).",
    purpose:"Act as liaison, mediator, messenger, and when necessary defender between the Lost and Hedge natives.",
    privileges:"Goblins treat the Baron as kin, trust him with gossip and exclusive deals, and favor him when assigning tasks that repay Goblin Debt.",
    duties:"Mediate conflicts and negotiations between changelings and hobgoblins, deliver messages or packages, and defend whichever side is in the right rather than serving personal interests.",
    maskAndMien:"Durable traveling clothes or diplomatic dress carry winding thorn motifs recording the Baron's dealings. The Baron's fae features resemble a chosen hobgoblin, adding one goblin feature per two ranks invested.",
    heraldry:"A shield composed of interlocking stylized brambles.",
    token:{name:"Seal of Thorns",description:"A pewter and carnelian signet ring whose sigil glows when active.",effect:"In the mundane world, automatically locate the nearest Hedge gate. In the Hedge, spend 1 Glamour up to rating times per chapter to make the Storyteller roll twice and take the worse result for one Hedge chase roll. Add rating to rolls made to safely deliver a missive or package bearing the seal.",catch:"Affix the seal to a missive or package the user does not want safely delivered and send it in good faith during the same scene.",drawback:"Activation inflicts a temporary Hedge Addiction Condition until the Baron yields to it at a highly inconvenient or dangerous time."},
    blessings:[...COMMON_BLESSINGS,
      {id:"hobgoblin-allies",name:"Hobgoblin Allies",description:"Gain Allies equal to Wyrd/2, rounded up, for one particular hobgoblin group. These Allies remember favors performed by previous Barons.",conditional:true,choiceLabel:"Hobgoblin group"},
      {id:"hostile-oath",name:"Inherited Hostile Oath",description:"Gain a hostile oath toward one specific changeling, inherited from unresolved enmity caused by a predecessor. Definitively fulfilling it refills all spent Willpower.",choiceLabel:"Oath and target"},
    ],
    touchstone:"A mortal the Baron rescued from danger in the Hedge.",
    curse:"Clarity attacks suffered while favoring hobgoblin interests over changeling interests add damage dice equal to ranks invested in this Merit.",
    beat:"Resolve a conflict with goblins, peacefully or otherwise, in a way that personally inconveniences the Baron or the motley.",
    legends:["A Baron became a Goblin Queen and built a Hedge fund of debts and favors.","A Bridge-Burner Baron waged war on Hedge denizens until a successor took the title and repaired the damage.","A Baron inherited an oath of vengeance against his own husband and sacrificed himself to fulfill it."],
  },
  {
    id:"dauphines-wayward-children",name:"Dauphines of Wayward Children",meritName:"Dauphine's Gift",source:"Oak, Ash, and Thorn",sourceCode:"OA&T",page:40,
    prerequisites:"Wyrd 3; the selected role requires two dots in its Attribute and Skill.",
    purpose:"Gather, guide, and protect willing wayward mortal or Lost children until they find a home or reach adulthood.",
    privileges:"The legion title commands freehold respect and resources. Each role has its own reputation and authority concerning its wards.",
    duties:"Never take an unwilling ward; aid the other Dauphines in protecting their wards; fulfill the selected role's particular method of care.",
    maskAndMien:"The Sophomore becomes youthful and fantastical, the Chaperone mysterious and comforting, and the Dowager stern and protective. Each bears the appearance associated with the role.",
    heraldry:"A stylized lily: yellow for Sophomore, blue for Chaperone, or violet for Dowager.",
    token:{name:"Dauphine's Lily",description:"A dead flower brooch in the Mask and a vibrant living lily in the mien, colored for the role.",effect:"Name up to rating current wards to know their distance and direction for the scene, or locate the nearest unclaimed wayward child. Add rating to the role's applicable actions. Spend 1 Glamour to let a ward see through fae Masks for the scene, up to rating times per scene.",catch:"Tell someone a treasured or haunting childhood secret they did not already know.",drawback:"The user gains Wanton (Sophomore), Spooked (Chaperone), or Stoic (Dowager)."},
    roles:[
      {id:"sophomore",name:"Sophomore",prerequisites:"Presence 2, Persuasion 2",privilege:"A celebrated trickster and maverick who wins young hearts with freedom and wonder.",duties:"Offer a carefree wondrous life and teach wards how to pursue what they want, obeying no commands but their hearts.",heraldryColor:"Yellow",tokenBonus:"Add token rating to Hedgespinning rolls to amaze a ward or grant the ward's heart's desire.",tokenDrawback:"Wanton"},
      {id:"chaperone",name:"Chaperone",prerequisites:"Manipulation 2, Empathy 2",privilege:"A trusted, miraculous caretaker to whom others entrust their most precious dependents and secrets.",duties:"Provide for wards and teach lessons through strange tests, magical puzzles, scavenger hunts, and other indirect wonders.",heraldryColor:"Blue",tokenBonus:"Add token rating to Contract rolls that lead a ward through riddles and adventures to learn something new.",tokenDrawback:"Spooked"},
      {id:"dowager",name:"Dowager",prerequisites:"Composure 2, Intimidation 2",privilege:"A formidable protector whose wards receive shelter, resources, and escape routes from other Lost.",duties:"Discipline, guard, train, and prepare wards to survive; punish both wards who imperil others and those responsible for a ward's harm.",heraldryColor:"Violet",tokenBonus:"Add token rating to mundane rolls to protect or avenge a ward.",tokenDrawback:"Stoic"},
    ],
    blessings:[...COMMON_BLESSINGS,
      {id:"inherited-token",name:"Inherited Gift Token",description:"Gain a separate inherited token with rating equal to Wyrd/2, rounded up. Design it with the normal token rules.",choiceLabel:"Inherited token details"},
      {id:"warded-dreams",name:"Warded Dreams",description:"Non-changeling wards gain Lucid Dreamer and treat their Bastions as Fortitude 1. Successful mundane actions in a ward's Bastion gain one additional success usable only for dreamweaving shifts.",conditional:true},
    ],
    touchstone:"One of the Dauphine's mortal wards. This Touchstone is Conditional.",
    curse:"Clarity attacks suffered because a ward is lost for any reason add damage dice equal to ranks invested in this Merit.",
    beat:"Abandon an important responsibility or suffer harm to the Dauphine or motley while chasing and collecting a new ward.",
    legends:["A Sophomore and her wards traded their memories to remain children forever.","A Chaperone staged an egg hunt to secretly choose the heir to the Blue Lily.","A Dowager's mortal murderer kept the Violet Lily, awaiting the changeling who would seek it."],
  },
  {
    id:"master-of-keys",name:"Master of Keys",meritName:"Key Mastery",source:"Oak, Ash, and Thorn",sourceCode:"OA&T",page:44,
    prerequisites:"Investigation 2, Empathy 2, and any Merit concerned with uncovering secrets, such as Diviner, Hedge Sense, or Trained Observer.",
    purpose:"Discover meaningful secrets, hidden places, locked wonders, and metaphorical keys, then preserve them for the title.",
    privileges:"Supernatural beings often grant access to secret sanctuaries and resources because the Master could otherwise find a way inside; discovered secrets and treasures are the title's central reward.",
    duties:"Continuously pursue meaningful secrets and keep them from indiscriminate revelation or use against the Master and allies.",
    maskAndMien:"Keys constantly spill from the Master's clothes in the Mask. In the mien, fingers, toes, and even the tongue become keys, never made of iron.",
    heraldry:"The Last Key: an ominous silver key with an elegant design of creeping vines and peering eyes.",
    token:{name:"Last Key",description:"The key that represents the Master's unknowable doom; its Mask and mien are identical.",effect:"Passively tarnishes near someone who secretly means the Master deadly harm, once per moonlit night. If the Master knowingly permits that enemy to act, regain 1 Willpower. When activated, grant rote quality on rating rolls per story to unlock keyed physical, Social, or mystical barriers.",catch:"Dramatically fail one of the user's own actions during the scene, before or after activation; a later dramatic failure refunds the Glamour spent.",drawback:"The user suffers a temporary Obsession concerning whatever is found after unlocking something."},
    blessings:[...COMMON_BLESSINGS,
      {id:"hidden-library",name:"Hidden Library",description:"Gain Safe Place 1 containing Library 2 for a chosen Mental Skill. The Last Key may make any mundane door lead there through portaling.",conditional:true,choiceLabel:"Library Mental Skill"},
      {id:"rekey-hedgeway",name:"Rekey Hedgeway",description:"Spend 1 additional Glamour when portaling through a closeable Hedge portal to assign the dormant Hedgeway a new Key that mortals could research, possess, or perform.",choiceLabel:"Example new Key"},
    ],
    touchstone:"A mortal whose secret the Master knows and keeps. This Touchstone is Conditional.",
    curse:"Clarity attacks suffered when choosing to keep a secret whose revelation would aid the Master or an ally add damage dice equal to ranks invested in this Merit.",
    beat:"After investing at least one rank, maintain an additional Aspiration tied to pursuing a dangerous secret; replace it at chapter end after fulfillment.",
    legends:["A Master opened the Underworld and traded his life to save the freehold from a ghost army.","A Master found a Huntsman's heart in dreams and bound it to his Wyrd as a token.","A Master traded escaped changelings' secrets to the Smiling Lady and passed the dangerous bargain onward."],
  },
  {
    id:"thorn-dancer",name:"Thorn Dancer",meritName:"Unscathed",source:"The Hedge",sourceCode:"Hedge",page:146,
    prerequisites:"Socialize 2, Athletics 3, Expression 2, and at least one Specialty related to movement, such as Wrestling, Parkour, or Ballet.",
    purpose:"Travel the Hedge with grace and panache, guide others through its dangers, and preserve the stories found along the way.",
    privileges:"Move through the Hedge without fearing many dangers that threaten ordinary changelings. Courts, freeholds, Groves, Hollows, hobgoblins, and even some True Fae react strongly to the Dancer's fame and freedom.",
    duties:"Transport others through the Hedge and make a memorable performance of the journey; the title does not require that every charge be brought to safety.",
    maskAndMien:"The Thorn Dancer appears immaculate and sharply in focus. Her fae features become deliberate and vivid, petrichor and fresh earth follow her, and gentle breezes make her clothing billow.",
    heraldry:"A winged sandal encircled, but not pierced, by a rose vine.",
    token:{name:"Talaria",description:"Old casual sandals in the Mask; blooming-vine gladiator boots with fluttering wings in the mien.",effect:"Passively ignore environmental levels 1-3 and falling damage from less than 30 yards or meters. When activated in the Hedge, ignore Conditions inflicted by the Thorns; spend 1 Willpower per other person to extend this protection.",catch:"Accept Reckless instead of spending Glamour to activate the Talaria.",drawback:"Gain Notoriety whenever the Talaria are activated in the Hedge."},
    blessings:[...COMMON_BLESSINGS,
      {id:"hedge-native-merits",name:"Hedge Native",description:"Gain Arcadian Metabolism and Hob Kin automatically."},
      {id:"hedge-clarity-guard",name:"Hedge Clarity Guard",description:"Clarity attacks suffered in the Hedge are reduced by two dice instead of one."},
    ],
    touchstone:"The first song that made the Thorn Dancer cry after taking up the title.",
    curse:"Clarity attacks suffered outside the Hedge add damage dice equal to ranks invested in this Merit.",
    beat:"Willingly help someone cross an enemy-infested region of the Hedge without payment or oath.",
    legends:["A Dancer snubbed a Spring King to help his Avowed wife, who had been trapped in hobgoblin form.","A murdered Dancer's voice haunted her motley through dreams until they avenged her.","A Huntsman fell in love with a Dancer during their chase and may still seek the current title holder."],
  },
  {
    id:"sibylline-fisher",name:"Sibylline Fisher",meritName:"Third Eye",source:"The Hedge",sourceCode:"Hedge",page:149,
    prerequisites:"Computer 3, Investigation 2, Wyrd 3.",
    purpose:"Collect secrets from the BriarNet, dreams, and Thorns, then connect hidden truths with the people who seek them.",
    privileges:"Secrets reveal themselves in fragments, petitioners seek the Fisher as an oracle or information broker, and even Gentry and Huntsmen may pay generously for true answers.",
    duties:"Seek meaningful secrets, interpret them in context, and deliver them to those who need to hear them while accepting the questions and consequences that follow.",
    maskAndMien:"A closed-eye mark appears as a scar, tattoo, or device engraving in the Mask. The mien gains an uncovered pitch-black oracle's eye whose placement shifts when concealed.",
    heraldry:"A stylized closed eye, surrounded by the individual Fisher title's personal ciphers and symbols.",
    token:{name:"Pythia Program",description:"A Glamour-coded program accessible on any internet-capable device, appearing as an unpolished site or app in the Mask.",effect:"Activation organizes accumulated secrets into past, present, or future insight. Past grants Investigation Clues or Social leverage equal to rating. Present functions as Cracking Software with rating as its bonus, including in the BriarNet. Future extracts a promise from the Wyrd after the Fisher accepts damage, a detrimental Condition, or another price set by the Storyteller.",catch:"The Fisher was formally petitioned, received no compensation, and expects none.",drawback:"Gain Notoriety because Hedge denizens recognize that the Fisher knows too much."},
    blessings:[...COMMON_BLESSINGS,
      {id:"secrets-cannot-hide",name:"Secrets Cannot Hide",description:"Automatically know the precise wording of fates and destinies connected to those you meet. Investigation rolls to uncover a secret gain 8-again."},
      {id:"oracular-gravity",name:"Oracular Gravity",description:"While acting according to the oracle's duties, roll Presence + Expression, penalized by group size (-1 small group, -2 small crowd, -3 large crowd), to gain Connected (Persistent).",conditional:true},
    ],
    touchstone:"A mortal supplicant who has repeatedly sought the Fisher's advice since she took the title. This Touchstone is Conditional.",
    curse:"Suffer a Clarity attack whenever one of the Fisher's own secrets is revealed, even voluntarily.",
    beat:"Connect a secret to the individual trying to keep it hidden.",
    legends:["A rumored seventh Fisher searched other realms through a BriarNet backdoor and never returned.","The Fishers blackmailed a Keeper into returning one of their own, but none remembers the secret they used.","A Fisher erased his memories after finding an unbearable secret, only for his successor to repeat his path."],
  },
  {
    id:"spiderborn-rider",name:"Spiderborn Rider",meritName:"Breaker of Chains",source:"The Hedge",sourceCode:"Hedge",page:152,
    prerequisites:"Resolve 3.",
    purpose:"Roam the trods freely, oppose slavery and coercion, and keep the Hedge safe for changelings who refuse masters.",
    privileges:"Riders are recognized by their colors as uncompromising liberators who can be relied on when chains, privateers, or tyrannical rulers threaten the Lost.",
    duties:"Never surrender a changeling to privateers, help those who ask to escape bondage, accept no master, and preserve personal choice even when doing so disrupts allies' plans.",
    maskAndMien:"The Rider always wears a vest whose patches tell his history. In the mien, the blue broken web and lightning become a tattoo, bodily pattern, or mark on cloth-like skin.",
    heraldry:"A blue web ripped apart by a lightning bolt.",
    token:{name:"The Colors",description:"Cut-off vest patches or insignia that identify a Spiderborn Rider.",effect:"Spend 1 Glamour after a glance and handshake, up to rating times per chapter, to learn all oaths, pledges, and formal bonds a person possesses. Add rating to Intimidation rolls against servants of the Fae.",catch:"For the rest of the chapter, do not spend Willpower to improve your own dice pools unless doing so explicitly benefits others.",drawback:"Gain Shaken as fear of the durance and renewed captivity overwhelms the Rider."},
    blessings:[...COMMON_BLESSINGS,
      {id:"indomitable-rider",name:"Indomitable Rider",description:"Gain Indomitable. If already possessed, instead gain two additional dice to resist supernatural mental influence.",conditional:true},
      {id:"where-needed",name:"Where Needed Most",description:"When finding a path through the Hedge, spend 1 Glamour to be led not where you want to go, but where you are needed most."},
    ],
    touchstone:"A mortal known before taking the title who reminds the Rider how much she has changed and why the Hedge is now her true home.",
    curse:"Clarity attacks suffered after refusing to assist another changeling in the Hedge or others in comparable need add damage dice equal to ranks invested in this Merit.",
    beat:"Free someone from a dangerous bargain or make the Hedge safer for all Lost.",
    legends:["A nameless Rider fought the Highway Kings and may now secretly rule and sabotage them.","A Rider died fighting his own motley to stop them from freeing hobgoblins devoted to a Goblin Queen.","A paranoid Rider exiled herself into the Hedge to destroy her own mind rather than risk serving her Keeper."],
  },
  ...HOMEBREW_ENTITLEMENTS,
];

export const findEntitlement=(id:unknown)=>ENTITLEMENTS.find((item)=>item.id===String(id??""));

export type EntitlementAllocation={id:string;target:"token"|"blessing";blessingId?:string;sequence:number};
export type EntitlementState={definitionId:string;roleId:string;accepted:boolean;touchstone:{name:string;status:"active"|"lost"|"suspended"};suspendedBenefitIds:string[];token:{rating:number;storedGlamour:number};allocations:EntitlementAllocation[];choices:Record<string,string>};

const record=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
export function normalizeEntitlementState(value:unknown,wyrd:number):EntitlementState{
  const raw=record(value),rawTouchstone=record(raw.touchstone),rawToken=record(raw.token),definition=findEntitlement(raw.definitionId);
  const allocations=(Array.isArray(raw.allocations)?raw.allocations:[]).flatMap((value,index)=>{
    const item=record(value),target=item.target==="token"||item.target==="blessing"?item.target:null;
    if(!target)return [];
    const blessingId=String(item.blessingId??"");
    if(target==="blessing"&&!definition?.blessings.some((entry)=>entry.id===blessingId))return [];
    return [{id:String(item.id??`allocation-${index}`),target,blessingId:target==="blessing"?blessingId:undefined,sequence:Number(item.sequence??index)} as EntitlementAllocation];
  }).sort((a,b)=>a.sequence-b.sequence).slice(0,Math.max(1,Math.min(10,Math.trunc(wyrd)||1)));
  const unique:EntitlementAllocation[]=[];let tokenCount=0;const blessingIds=new Set<string>();
  for(const allocation of allocations){
    if(allocation.target==="token"){if(tokenCount>=5)continue;tokenCount+=1;unique.push(allocation);continue;}
    if(!allocation.blessingId||blessingIds.has(allocation.blessingId))continue;
    blessingIds.add(allocation.blessingId);unique.push(allocation);
  }
  const choices=Object.fromEntries(Object.entries(record(raw.choices)).map(([key,item])=>[key,String(item??"")]));
  return {definitionId:definition?.id??"",roleId:definition?.roles?.some((role)=>role.id===raw.roleId)?String(raw.roleId):"",accepted:raw.accepted===true,touchstone:{name:String(rawTouchstone.name??""),status:["active","lost","suspended"].includes(String(rawTouchstone.status))?rawTouchstone.status as EntitlementState["touchstone"]["status"]:"active"},suspendedBenefitIds:Array.isArray(raw.suspendedBenefitIds)?raw.suspendedBenefitIds.map(String):[],token:{rating:tokenCount,storedGlamour:Math.max(0,Math.min(Math.trunc(wyrd)||1,Number(rawToken.storedGlamour??0)))},allocations:unique,choices};
}

export function entitlementPrerequisitesMet(definition:EntitlementDefinition,state:EntitlementState,sheet:{attributes:Record<string,number>;skills:Record<string,number>;merits:Array<{name:string;dots?:number;configuration?:Record<string,unknown>}>;line_data:Record<string,unknown>}){
  const meritNames=new Set(sheet.merits.map((item)=>item.name));
  const attribute=(...names:string[])=>Math.max(0,...names.map((name)=>Number(sheet.attributes[name]??0)));
  const skill=(...names:string[])=>Math.max(0,...names.map((name)=>Number(sheet.skills[name]??0)));
  const wyrd=Number(sheet.line_data.wyrd??1);
  if(definition.id==="baron-lesser-ones") return Number(sheet.skills.Empatia??0)>=2&&(Number(sheet.skills.Intimidação??0)>=2||Number(sheet.skills.Persuasão??0)>=2)&&(meritNames.has("Gentrified Bearing")||meritNames.has("Hob Kin")||sheet.merits.some((item)=>item.name==="Interdisciplinary Specialty"&&JSON.stringify(item.configuration??{}).toLowerCase().includes("goblin")));
  if(definition.id==="dauphines-wayward-children"){
    const role=definition.roles?.find((item)=>item.id===state.roleId);if(!role||Number(sheet.line_data.wyrd??1)<3)return false;
    const requirements:Record<string,[string,string]>={sophomore:["Presença","Persuasão"],chaperone:["Manipulação","Empatia"],dowager:["Compostura","Intimidação"]};
    const [attribute,skill]=requirements[role.id];return Number(sheet.attributes[attribute]??0)>=2&&Number(sheet.skills[skill]??0)>=2;
  }
  if(definition.id==="master-of-keys") return Number(sheet.skills.Investigação??0)>=2&&Number(sheet.skills.Empatia??0)>=2;
  if(definition.id==="thorn-dancer") return Number(sheet.skills.Socialização??0)>=2&&Number(sheet.skills.Atletismo??0)>=3&&Number(sheet.skills.Expressão??0)>=2;
  if(definition.id==="sibylline-fisher") return Number(sheet.skills.Computação??0)>=3&&Number(sheet.skills.Investigação??0)>=2&&Number(sheet.line_data.wyrd??1)>=3;
  if(definition.id==="spiderborn-rider") return Number(sheet.attributes.Perseverança??0)>=3;
  if(definition.id==="adjudicator-wheel")return attribute("Resolve","Perseverança")>=3&&skill("Investigation","Investigação")>=2&&meritNames.has("Trained Observer");
  if(definition.id==="blackbird-bishop")return skill("Empathy","Empatia")>=2&&attribute("Wits","Raciocínio")>=3&&attribute("Composure","Compostura")>=3;
  if(definition.id==="diviners-worms")return skill("Occult","Ocultismo")>=2&&meritNames.has("Diviner")&&meritNames.has("Trained Observer");
  if(definition.id==="duchess-truth-loss")return attribute("Wits","Raciocínio")>=3&&skill("Investigation","Investigação")>=2;
  if(definition.id==="goldspinner-guildmaster")return sheet.merits.some((item)=>item.name==="Resources"&&Number(item.dots??0)>=3);
  if(definition.id==="paragon-story-heroes")return attribute("Wits","Raciocínio")>=3&&skill("Academics","Erudição")>=2&&Math.max(skill("Persuasion","Persuasão"),skill("Subterfuge","Dissimulação"))>=2;
  if(definition.id==="sacred-band-golden-standard")return attribute("Presence","Presença")>=3&&wyrd>=2&&Object.values(sheet.skills).some((value)=>Number(value)>=3);
  if(definition.id==="squire-broken-bough")return attribute("Composure","Compostura")>=3&&attribute("Resolve","Perseverança")>=3&&skill("Weaponry","Armamento")>=2;
  if(definition.id==="companion-resigned")return skill("Empathy","Empatia")>=3&&skill("Expression","Expressão")>=2&&skill("Stealth","Furtividade")>=2;
  if(definition.id==="castellan-broken-cage")return attribute("Manipulation","Manipulação")>=3&&Math.max(skill("Empathy","Empatia"),skill("Socialize","Socialização"))>=2&&wyrd>=2;
  if(definition.id==="duke-icebound-heart")return Math.max(attribute("Presence","Presença"),attribute("Manipulation","Manipulação"))>=3&&skill("Socialize","Socialização")>=2&&skill("Empathy","Empatia")>=2;
  if(definition.id==="eternal-echo")return attribute("Resolve","Perseverança")>=3&&skill("Academics","Erudição")>=2&&skill("Expression","Expressão")>=2;
  if(definition.id==="knights-knowledge-tongue")return attribute("Stamina","Vigor")>=3&&skill("Crafts","Ofícios")>=2;
  if(definition.id==="legate-black-apple")return Object.values(sheet.skills).filter((value)=>Number(value)>=4).length>=2&&attribute("Composure","Compostura")+attribute("Resolve","Perseverança")>=7&&wyrd>=3;
  if(definition.id==="lost-pantheon")return attribute("Presence","Presença")>=3&&skill("Occult","Ocultismo")>=2&&wyrd>=3;
  if(definition.id==="magistrates-wax-mask")return attribute("Composure","Compostura")>=3&&skill("Socialize","Socialização")>=2&&skill("Subterfuge","Dissimulação")>=3;
  if(definition.id==="magus-gilded-thorns")return attribute("Composure","Compostura")>=3&&skill("Stealth","Furtividade")>=2&&meritNames.has("Hedge Sense")&&wyrd>=2;
  if(definition.id==="margrave-brim")return Math.max(skill("Brawl","Briga"),skill("Weaponry","Armamento"))>=3&&skill("Survival","Sobrevivência")>=2&&wyrd>=2;
  if(definition.id==="noble-sages"){
    if(skill("Occult","Ocultismo")<2)return false;
    if(state.roleId==="archivist")return attribute("Intelligence","Inteligência")>=3&&skill("Academics","Erudição")>=2;
    if(state.roleId==="diplomat")return attribute("Wits","Raciocínio")>=3&&skill("Persuasion","Persuasão")>=2;
    if(state.roleId==="bane")return attribute("Resolve","Perseverança")>=3&&skill("Athletics","Atletismo")>=2;
    return false;
  }
  if(definition.id==="scarecrow-minister")return attribute("Composure","Compostura")>=3&&skill("Empathy","Empatia")>=2&&skill("Intimidation","Intimidação")>=3;
  if(definition.id==="tolltaker-knight")return attribute("Composure","Compostura")>=3&&Math.max(skill("Brawl","Briga"),skill("Weaponry","Armamento"))>=2&&skill("Intimidation","Intimidação")>=2;
  return true;
}

export function synchronizeEntitlement<T>(sheet:T):T{
  const target=sheet as T&{game_line?:string;attributes?:Record<string,number>;skills?:Record<string,number>;merits?:Array<{instanceId?:string;name:string;dots:number;configuration?:Record<string,unknown>;grantedBy?:string}>;specializations?:Array<{skill:string;name:string;grantedBy?:string}>;line_data?:Record<string,unknown>};
  if(target.game_line!=="CtL"||!target.merits||!target.line_data)return sheet;
  target.merits=target.merits.filter((item)=>!item.grantedBy?.startsWith("Entitlement:"));
  target.specializations=(target.specializations??[]).filter((item)=>!item.grantedBy?.startsWith("Entitlement:"));
  const merit=target.merits.find((item)=>item.name==="Entitlement"&&!item.grantedBy);
  if(!merit){delete target.line_data.entitlement;return sheet;}
  const configuration=record(merit.configuration),saved=record(target.line_data.entitlement),configuredDefinitionId=String(configuration.definitionId??"");
  const current=configuredDefinitionId&&saved.definitionId&&configuredDefinitionId!==saved.definitionId?{}:saved;
  const definitionId=String(configuredDefinitionId||current.definitionId||""),roleId=String(configuration.roleId||current.roleId||"");
  const state=normalizeEntitlementState({...current,definitionId,roleId},Number(target.line_data.wyrd??1));
  merit.configuration={...configuration,definitionId:state.definitionId,roleId:state.roleId};target.line_data.entitlement=state;
  const definition=findEntitlement(state.definitionId);if(!definition)return sheet;
  const eligible=entitlementPrerequisitesMet(definition,state,{attributes:target.attributes??{},skills:target.skills??{},merits:target.merits,line_data:target.line_data});
  const owner=`Entitlement:${definition.id}`,active=new Set(state.accepted&&eligible&&state.touchstone.status==="active"&&Boolean(state.touchstone.name.trim())?state.allocations.filter((item)=>item.target==="blessing"&&!state.suspendedBenefitIds.includes(String(item.blessingId))).map((item)=>item.blessingId):[]);
  const grant=(name:string,dots:number,configuration:Record<string,unknown>={})=>target.merits!.push({instanceId:`grant-${owner}-${name}`,name,dots,configuration,grantedBy:owner});
  if(active.has("inherited-expertise")){const skill=state.choices["inherited-expertise-skill"],name=state.choices["inherited-expertise-name"];if(skill&&name)target.specializations!.push({skill,name,grantedBy:owner});}
  if(active.has("hobgoblin-allies"))grant("Allies",Math.ceil(Number(target.line_data.wyrd??1)/2),{groups:[state.choices["hobgoblin-allies"]??""]});
  if(active.has("inherited-token")){const rating=Math.ceil(Number(target.line_data.wyrd??1)/2),token={name:state.choices["inherited-token-name"]??"Inherited Token",rating,cost:state.choices["inherited-token-cost"]??"",effect:state.choices["inherited-token-effect"]??"",catch:state.choices["inherited-token-catch"]??"",drawback:state.choices["inherited-token-drawback"]??""};grant("Token",rating,{items:[JSON.stringify(token)]});}
  if(active.has("hidden-library")){grant("Safe Place",1);grant("Library",2,{subject:state.choices["hidden-library"]??""});}
  if(active.has("hedge-native-merits")){
    if(!target.merits.some((item)=>item.name==="Arcadian Metabolism"))grant("Arcadian Metabolism",2);
    if(!target.merits.some((item)=>item.name==="Hob Kin"))grant("Hob Kin",1);
  }
  if(active.has("indomitable-rider")&&!target.merits.some((item)=>item.name==="Indomitable"&&!item.grantedBy))grant("Indomitable",2);
  if(active.has("blackbird-flock"))grant("Retainer",Math.ceil(Number(target.line_data.wyrd??1)/2),{name:"Blackbird Flock"});
  if(active.has("former-chrysalids"))grant("Allies",Math.ceil(Number(target.line_data.wyrd??1)/2),{groups:[state.choices["former-chrysalids"]??""]});
  if(active.has("rescued-allies"))grant("Allies",Math.ceil(Number(target.line_data.wyrd??1)/2),{groups:[state.choices["rescued-allies"]??""]});
  if(active.has("hedge-interdisciplinary"))grant("Interdisciplinary Specialty",1,{subject:"Hedge"});
  if(active.has("supernatural-contacts"))grant("Contacts",Math.ceil(Number(target.line_data.wyrd??1)/2),{groups:[state.choices["supernatural-contacts"]??""]});
  if(active.has("supernatural-barfly"))grant("Barfly",2,{subject:"Non-fae supernatural gatherings"});
  return sheet;
}
