import { CHANGELING_CONDITIONS, type ChangelingCondition } from "./changeling-conditions";

export type MageCondition = ChangelingCondition;

const common = CHANGELING_CONDITIONS.filter((item) => item.sourceCode === "CofD" || item.sourceCode === "HL");
const mageSpecific: MageCondition[] = [
  {id:"addicted",name:"Viciado",originalName:"Addicted",category:"Mental",description:"O personagem é dependente de uma substância ou comportamento destrutivo e precisa alimentá-lo regularmente.",resolution:"Recupere ou perca um ponto de Integridade ou Sabedoria, ou obtenha sucesso excepcional em um ponto de ruptura ou Ato de Hubris.",beat:"Escolha satisfazer o vício em vez de cumprir uma obrigação.",persistent:true,source:"Mage the Awakening",sourceCode:"MTA 2e",page:314},
  {id:"strained",name:"Tensionado",originalName:"Strained",category:"Mental",description:"A alma reteve o choque de testemunhar magia Supernal, e a pressão continua.",penalty:"As consequências da Quiescência permanecem represadas e podem retornar quando a tensão cede.",resolution:"A pressão é liberada pela forma indicada pelo efeito que impôs a Condition.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:318},
  {id:"soul-shocked",name:"Alma Abalada",originalName:"Soul Shocked",category:"Sobrenatural",description:"O senso de identidade ainda se recupera de experimentar a morte fora do corpo.",penalty:"A recuperação espiritual limita o personagem conforme as regras de projeção e retorno da alma.",resolution:"Conclua a recuperação da alma e restabeleça plenamente a identidade do personagem.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:318},
  {id:"thrall",name:"Servo",originalName:"Thrall",category:"Sobrenatural",description:"O personagem sucumbiu à perda da alma e tornou-se apenas uma casca de quem era.",penalty:"Não recupera Força de Vontade normalmente e sofre os efeitos avançados da perda da alma.",resolution:"Recupere a alma do personagem.",beat:"A perda da alma força o personagem a abandonar uma necessidade, relação ou obrigação importante.",persistent:true,source:"Mage the Awakening",sourceCode:"MTA 2e",page:318},
  {id:"charmed",name:"Encantado",originalName:"Charmed",category:"Sobrenatural",description:"Uma bênção de sorte protege o personagem e garante uma virada favorável importante.",resolution:"Invoque a boa fortuna para evitar uma desgraça ou obter a oportunidade decisiva descrita.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:315},
  {id:"defeated",name:"Derrotado",originalName:"Defeated",category:"Sobrenatural",description:"Um rival venceu o personagem no Duelo Arcano e ganhou vantagem mágica sobre ele.",penalty:"Não pode gastar Força de Vontade nem usar magia para ferir o vencedor; o vencedor possui simpatia Forte.",resolution:"Humilhe-se publicamente com grande custo pessoal, ou seja ferido/abusado quando o vencedor usar a simpatia.",beat:"Sofra abuso ou humilhação em consequência da derrota.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:315},
  {id:"humbled",name:"Humilhado",originalName:"Humbled",category:"Sobrenatural",description:"A humanidade de alguém ou de um símbolo derrubou a arrogância do personagem; ele não consegue ferir essa fonte.",resolution:"Sacrifique-se dramaticamente em nome da pessoa ou símbolo que o humilhou.",beat:"Ao agir com hubris ou arrogância, escolha uma falha dramática em vez de realizar o teste.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:316},
  {id:"megalomaniacal",name:"Megalomaníaco",originalName:"Megalomaniacal",category:"Sobrenatural",description:"A hubris cega o personagem para suas próprias falhas e faz sua aptidão parecer infalível.",penalty:"Falha automaticamente em Empatia; recebe o Vício Egoísta e a Obsessão Dominar os Outros.",resolution:"Fira alguém importante de modo que arrisque nova perda de Sabedoria.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:317},
  {id:"mystery-commands",name:"Ordens do Mistério",originalName:"Mystery Commands",category:"Sobrenatural",description:"O personagem recebe a vontade arcana dos Exarcas como uma ordem irresistível.",penalty:"A ordem ocupa uma Obsessão e conduz ações de acordo com o Mistério.",resolution:"Cumpra ou rompa definitivamente a ordem sobrenatural conforme o efeito que a impôs.",beat:"A ordem provoca uma complicação grave ou força o personagem a agir contra seus interesses.",persistent:true,source:"Mage the Awakening",sourceCode:"MTA 2e",page:317},
  {id:"rampant",name:"Desenfreado",originalName:"Rampant",category:"Sobrenatural",description:"O personagem usa magia de forma imprudente e resolve até problemas banais com feitiços.",penalty:"Quando houver solução mágica razoável, usar uma solução mundana custa 1 Força de Vontade; recebe a Obsessão Empunhar Magia Indiscriminadamente.",resolution:"Cause dano colateral significativo com magia e enfrente suas consequências.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:317},
  {id:"triumphant",name:"Triunfante",originalName:"Triumphant",category:"Sobrenatural",description:"A vitória no Duelo Arcano acompanha o personagem na sociedade Desperta.",penalty:"A reputação e a simpatia obtidas no duelo concedem a vantagem descrita pela fonte.",resolution:"Use publicamente a vitória ou sua simpatia para obter uma vantagem decisiva.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:319},
  {id:"abyssal-backlash",name:"Reação Abissal",originalName:"Abyssal Backlash",category:"Sobrenatural",description:"Um Paradoxo paira sobre o personagem e ameaça irromper no próximo feitiço que lhe der abertura.",penalty:"A próxima conjuração vulnerável recebe a intrusão abissal descrita pelo Paradoxo.",resolution:"A reação é acionada ou dissipada pelo efeito que a criou.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:117},
  {id:"abyssal-imago",name:"Imago Abissal",originalName:"Abyssal Imago",category:"Sobrenatural",description:"Um Paradoxo invade os feitiços imaginados e força Reach perigoso.",penalty:"A Imago inclui Reach adicional e seus riscos de Paradoxo.",resolution:"Conjure o feitiço afetado ou purgue a intrusão abissal.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:117},
  {id:"abyssal-nimbus",name:"Nimbus Abissal",originalName:"Abyssal Nimbus",category:"Sobrenatural",description:"O Paradoxo vazou pelo Nimbus e convida manifestações do Abismo.",penalty:"O Nimbus carrega sinais abissais e facilita manifestações conforme a fonte.",resolution:"Expurgue a contaminação ou permita que a manifestação se complete.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:116},
  {id:"abyssal-debilitation",name:"Debilitação Abissal",originalName:"Abyssal Debilitation",category:"Sobrenatural",description:"A exposição da alma ao Abismo torna todo dano resistente e enfraquece ações e magia.",penalty:"−1 cumulativo por feitiço maculado em todos os testes; conjurar sem macular exige Perseverança + Autocontrole.",resolution:"Obtenha sucesso excepcional ou falha dramática ao tentar evitar macular um feitiço.",beat:"Beats desta Condition são Beats Arcanos.",source:"Nameless and Accursed",sourceCode:"NH-NA",page:163},
  {id:"degenerate-mana",name:"Mana Degenerado",originalName:"Degenerate Mana",category:"Sobrenatural",description:"O personagem só recupera Mana após realizar algo que seria um Ato de Hubris contra Sabedoria baixa.",resolution:"Encerre a maldição Abissal.",beat:"Sofra dano ou revés significativo por ficar sem Mana.",persistent:true,source:"Nameless and Accursed",sourceCode:"NH-NA",page:163},
  {id:"dissonant-tuning",name:"Sintonia Dissonante",originalName:"Dissonant Tuning",category:"Sobrenatural",description:"A alma de um Adormecido ressoa com a Mentira e amplifica Paradoxo e Dissonância.",penalty:"A testemunha conta como um grupo maior; em grupos grandes concede qualidade de Rota e sucessos excepcionais ocorrem com três sucessos.",resolution:"Ganhe um ponto de Integridade ou obtenha sucesso excepcional em um ponto de ruptura.",beat:"Se persistente, um feitiço ou fenômeno testemunhado obtém sucesso excepcional em Paradoxo ou Dissonância.",source:"Nameless and Accursed",sourceCode:"NH-NA",page:163},
  {id:"mage-hunter",name:"Caçador de Magos",originalName:"Mage Hunter",category:"Sobrenatural",description:"O personagem é consumido pela obsessão de caçar e destruir magia.",penalty:"Recebe a Obsessão Destruir Magia e precisa gastar Força de Vontade para não agir sobre cada gatilho da Visão de Mago Periférica.",resolution:"Ganhe Integridade, obtenha sucesso excepcional em um ponto de ruptura, ou passe três dias sem gatilhos da Visão de Mago.",beat:"Sofra dano ou trauma mágico ao perseguir a Obsessão; destruir um mago concede dois Beats uma vez por cena.",persistent:true,source:"Nameless and Accursed",sourceCode:"NH-NA",page:164},
  {id:"supernal-harrowing",name:"Flagelo Supernal",originalName:"Supernal Harrowing",category:"Sobrenatural",description:"Um Banisher Flagelado contaminou a alma do personagem; usar magia causa dor física.",penalty:"Sofre dano contundente ao usar magia e −1 a ações; a penalidade pode chegar a −3 na cena.",resolution:"Recupere Sabedoria ou obtenha sucesso excepcional em Ato de Hubris fora da presença do Flagelado.",beat:"Falhe em conjurar devido à penalidade ou desmaie pelo dano causado ao usar magia.",persistent:true,source:"Nameless and Accursed",sourceCode:"NH-NA",page:164},
  {id:"tainted-aspiration",name:"Aspiração Maculada",originalName:"Tainted Aspiration",category:"Sobrenatural",description:"Uma Aspiração foi contaminada por uma maldição Abissal.",penalty:"−3 em todos os testes em busca da Aspiração; toda falha torna-se dramática.",resolution:"Encerre a maldição Abissal.",beat:"Sofra uma falha dramática devido à maldição.",persistent:true,source:"Nameless and Accursed",sourceCode:"NH-NA",page:164},
];

export const MAGE_CONDITIONS: MageCondition[] = [...common, ...mageSpecific].filter((item,index,array)=>array.findIndex(other=>other.id===item.id)===index);
export const findMageCondition=(id:string)=>MAGE_CONDITIONS.find(item=>item.id===id);
