import { MAGE_MERIT_INDEX } from "./merits-mage-index";
import type { MeritDefinition } from "./merits";

type MageRecord = Omit<MeritDefinition,"translatedName"|"descriptionEn"|"priority">;
const corrections: Record<string, Partial<MageRecord>> = {
  "Adamant Hand": {repeatable:true,prerequisites:"Awakened; Adamantine Arrow Status •; Athletics or Brawl or Weaponry •••",description:"Choose Athletics, Brawl, or Weaponry at 3+. Using that Skill in combat is a reflexive Order tool Yantra for an instant spell on a subsequent turn, or a reflexive spell in the same turn. May be purchased separately for each eligible Skill."},
  "Artifact": {unbounded:true,repeatable:true,description:"A Supernal item with its own effects. Cost: highest Arcanum of its greatest effect (minimum 3), plus half the highest Arcanum of each additional effect, rounded up, plus one per included Utility Attainment. No five-dot limit. Mana capacity is twice Merit dots; effective Gnosis is half dots, rounded up. Record its effects and activation circumstances. Its highest Arcanum determines its Path tool affinity. Paradox and Reach follow Mage pp. 99–100."},
  "Astral Adept": {description:"Choose an attunement ceremony. After performing it, spend one Willpower to meditate into the Astral Realms without a place of power. The printed prerequisite also permits Sleepwalkers; this catalog exposes the Awakened version."},
  "Awakened Status": {repeatable:true,description:"Consilium/Order Status: choose a Consilium or Order Caucus. Gain Status protections and use its dots for temporary magical requisitions; permanent requisitions increase Availability by two. Normally only one Order may have more than one dot: a second Order permits one dot, without requisitions. Seer Status also adds to Resources for mundane acquisitions. Status outside the home Caucus suffers the geographical penalties on Mage p. 100."},
  "Cabal Theme": {prerequisites:"Awakened",description:"Record the cabal theme's name and description. Each member counts Shadow Name as one dot higher for persona Yantras, even without Shadow Name or above three dots. Agreement and membership of the cabal are handled outside the app."},
  "Cognoscente": {description:"Rotes cast from your Grimoires do not double ritual casting time. You may imprint your Signature Nimbus into a scribed rote. Once per story, gain +2 on a Social roll relying on your reputation as a scribe and the benefits of Occultation 3; this latter benefit does not function if you already have Occultation."},
  "Daimonomikon": {repeatable:true,description:"A text for a particular Legacy, granting access to initiation and Attainments up to the purchased level if their prerequisites are met. A text containing only one Attainment costs one Experience less, minimum one. It does not grant Attainments automatically.",levels:[1,2,3,4,5].map((rating)=>({rating,name:["Initiate","Apprentice","Disciple","Adept","Master/Holistic"][rating-1],description:`Access to Attainment ${rating} of the recorded Legacy.`}))},
  "Destiny": {description:"Each chapter, gain Destiny points equal to Merit dots. Spend one for rote quality before a mundane roll or to reroll a mundane action afterward, keeping the new result. Also spend Willpower to affect spellcasting. Record a Doom: Willpower gives only +2 dice (or +1 static) to avoid it; a failed action furthering it refunds the Willpower spent."},
  "Dream": {description:"Once per chapter, after four hours of sleep or meditation, ask up to Merit dots yes/no questions about a topic you understand. The Storyteller answers accurately, using maybe only if neither answer is true. Enter your own dreams without a meditation roll."},
  "Enhanced Item": {unbounded:true,repeatable:true,description:"Record an item and its indefinite spell enhancements. Each dot buys one dot of spells up to five; later Merit dots each buy half a dot of spells. Use the highest Arcanum of a conjunctional spell. A dot may instead buy +1 equipment bonus, Structure, or Durability. May share an item with Imbued Item, but not Artifact."},
  "Enriched Item": {repeatable:true,description:"Choose an item and a spell. At two dots, that spell gains a +1 tool Yantra when cast on the item, which also has +1 equipment bonus (or 1/1 armor) over a mundane equivalent. At four dots, its Yantra and equipment bonuses are +2."},
  "Familiar": {repeatable:true,description:"A bonded ghost, spirit, or Goetia. At two dots it has Rank 1; at four, Rank 2. Record the entity and whether it is in Twilight or Fettered to an item or animal. Its full traits follow the ephemeral entity rules."},
  "Grimoire": {repeatable:true,description:"Record a book containing up to two rotes per Merit dot. If you can cast them, follow its instructions to cast as rotes or learn them with Experience. Owning the book does not automatically teach its rotes."},
  "Imbued Ally": {unbounded:true,repeatable:true,description:"Modify a linked Retainer or Familiar with one imbued spell. Cost is its highest Arcanum, plus one dot per extra Mana capacity beyond the initial one. No five-dot ceiling. The ally or a touching Mana user who knows the trigger can activate it; each cast costs at least one Mana. Record the spell and trigger."},
  "Imbued Item": {unbounded:true,repeatable:true,description:"An item with one triggered spell. Cost is its highest Arcanum plus one per included Utility Attainment; each extra dot buys two Mana capacity beyond the initial one. No five-dot ceiling. Each cast costs at least one Mana and uses the spell's Arcanum plus the Awakened user's Gnosis. Record the spell and trigger. May combine with Enhanced Item, not Artifact."},
  "Infamous Mentor": {repeatable:true,prerequisites:"Awakened; Mentor (equal or higher rating)",description:"Link one Mentor of at least this Merit rating. Record that Mentor's Order and Consilium Status and Social Merits totaling twice Infamous Mentor dots. You may invoke them by name-dropping and accepting the social consequences. These are conditional borrowed benefits, not permanent grants to the student's sheet."},
  "Lex Magica": {prerequisites:"Awakened; Silver Ladder Status •",description:"When acting in an official capacity, add the relevant Silver Ladder or Consilium Status to Doors. Others cannot spend Willpower to boost Social actions or magic influencing your behavior. Use half the higher Status, rounded up, as a Yantra directly enforcing the Lex Magica."},
  "Mana Battery": {unbounded:true,repeatable:true,description:"An item storing two Mana per Merit dot. Draw from it into your Pattern or replenish it using Channel Mana. May combine with Enhanced Item or Enriched Item."},
  "Mystery Cult Influence": {description:"Lead, worshipfully inspire, or decisively influence a mystery cult. Receive Mystery Cult Initiation benefits at the same rating without ordinary membership responsibilities, retaining deniability and the freedom to leave. This Mage-specific definition takes precedence over the shared Core record.",levels:[{rating:1,name:"Initiation 1",description:"A Specialty or one-dot Merit."},{rating:2,name:"Initiation 2",description:"A one-dot Merit."},{rating:3,name:"Initiation 3",description:"A Skill dot or a two-dot Merit."},{rating:4,name:"Initiation 4",description:"A three-dot Merit."},{rating:5,name:"Initiation 5",description:"A three-dot Merit or a comparable significant advantage."}]},
  "Occultation": {excludes:["Fame"],prerequisites:"Awakened; Cannot have Fame",description:"Penalize magical aura-reading, identification and tracking of your Signature Nimbus by Merit dots. Sympathy's Withstand against targeting you has a minimum equal to these dots. Incompatible with Fame; public notoriety may cause its loss."},
  "Order Archive": {prerequisites:"Awakened; Consilium/Order Status •",description:"Link a Consilium/Order Status and record its archive. Add Merit dots to the maximum rolls for extended actions using its resources; penalize security breaches by dots, with defenses inflicting up to dots lethal damage. Choose one protected Arcanum and one asset type per dot; protective Shielding spells have Potency equal to dots. These dots describe available resources, not your requisition authority."},
  "Perfected Item": {repeatable:true},
  "Potent Nimbus": {description:"At one dot, add two to effective Gnosis for your Nimbus Tilt; at two dots, add four. Add Merit dots to rolls to flare the Nimbus."},
  "Shadow Name": {description:"Record the symbolism of your existing Shadow Name. Use those symbols as a persona Yantra worth Merit dots. Apply dots as Withstand against identification and sympathetic or temporal targeting of your mundane persona, and as a penalty to mundane attempts to connect your identities."},
  "Shadow Self": {prerequisites:"Awakened; Shadow Name •••; Mind •",description:"Those affected by your Nimbus Tilt take −2 on contested rolls against you for the scene when aligned with your Shadow identity. In Astral travel or mental projection, one chosen Social Attribute increases by one, within its normal maximum. If your identity reflects a known mythic/divine Goetia, gain +2 to summon or interact with it while behaving accordingly. Prerequisite corrected to Shadow Name 3 and Mind 1 as instructed."},
  "Soul Stone": {repeatable:true,description:"Own another mage's soul stone. One dot: creator's Gnosis is no higher than yours; two: it is higher. Record creator and Legacy. The stone grants a +2/+3 tool Yantra respectively and Connected sympathy. Order tradition entitles you to three services before returning it; it may also support a Demesne or learning the creator's Legacy."},
  "Techné": {repeatable:true,prerequisites:"Awakened; Free Council Status •",description:"Choose a cultural, scientific, or artistic focus. Treat its use as a Free Council Order tool, and Sleepers engaged in it as a separate tool for non-obvious magic. A ritual team sharing the same focus gains 8-again for its leader. Repeatable for different fields."},
};
const ancientPaths: Record<string,string>={"Fire Keeper":"Obrimos","Sea's Hunger":"Moros","Sky's Whispers":"Acanthus","Spirit Warden":"Thyrsus","Trail Walker":"Mastigos"};
export const MAGE_MERITS: MageRecord[] = MAGE_MERIT_INDEX.map(item=>{
  const result: MageRecord={...item,ratings:[...item.ratings],...corrections[item.name]};
  if(ancientPaths[item.name]){
    result.prerequisites=`Awakened; ${ancientPaths[item.name]}`;
    result.description+=` Historical Merit from Dark Eras, available here to modern ${ancientPaths[item.name]} characters by chronicle ruling.`;
  }
  return result;
});
