// Gerado exclusivamente dos 13 PDFs locais por work/extract-rule-fields.mjs.
export const MERIT_PREREQUISITES_PT: Record<string, string> = {
  "core-2ed:greyhound": "Atletismo •••, Raciocínio •••, Vigor •••",
  "ctl-hedge:hedge-sorcerer": "Ocultismo •, Mentor ••",
  "ctl-hedge:frightful-incantation": "Feiticeiro do Espinheiro ••••, Perseverança ••, Manto •• que permita impor Condições de Desvario baseadas em medo",
  "ctl-hedge:magic-dreams": "Feiticeiro do Espinheiro ••••, Ocultismo •••",
  "ctl-2ed:manymask": "Fado ••, Manipulação •••",
  "ctl-2ed:rigid-mask": "Subterfúgio ••",
  "ctl-dark-eras:oath-blood-liege": "Juramento a um vampiro",
  "core-2ed:area-of-expertise": "Perseverança •• e uma Especialização de Perícia",
  "core-2ed:eye-for-the-strange": "Perseverança ••, Ocultismo •",
  "core-2ed:fast-reflexes": "Raciocínio ••• ou Destreza •••",
  "core-2ed:good-time-management": "Erudição •• ou Ciência ••",
  "core-2ed:indomitable": "Perseverança •••",
  "core-2ed:interdisciplinary-specialty": "Perícia em ••• ou mais com uma Especialização",
  "core-2ed:investigative-aide": "Perícia escolhida em •••+",
  "core-2ed:investigative-prodigy": "Raciocínio •••, Investigação •••",
  "core-2ed:tolerance-for-biology": "Perseverança •••",
  "core-2ed:automotive-genius": "Ofícios •••, Condução •, Ciência •",
  "core-2ed:crack-driver": "Condução •••",
  "core-2ed:demolisher": "Força ••• ou Inteligência •••",
  "core-2ed:double-jointed": "Destreza •••",
  "core-2ed:fleet-of-foot": "Atletismo ••",
  "core-2ed:hardy": "Vigor •••",
  "core-2ed:iron-stamina": "Vigor ••• ou Perseverança •••",
  "core-2ed:parkour": "Destreza •••, Atletismo ••",
  "core-2ed:quick-draw": "Raciocínio •••, uma Especialização na arma ou estilo de combate escolhido",
  "core-2ed:relentless": "Atletismo ••, Vigor •••",
  "core-2ed:seizing-the-edge": "Raciocínio •••, Compostura •••",
  "core-2ed:sleight-of-hand": "Furto •••",
  "core-2ed:stunt-driver": "Destreza •••, Condução •••, Raciocínio •••",
  "core-2ed:anonymity": "Não pode possuir Fama",
  "core-2ed:barfly": "Socialização ••",
  "core-2ed:closed-book": "Manipulação •••, Perseverança •••",
  "core-2ed:fast-talking": "Manipulação •••, Subterfúgio ••",
  "core-2ed:fixer": "Contatos ••, Raciocínio •••",
  "core-2ed:hobbyist-clique": "Participação em uma confraria. Todos os membros devem possuir este Mérito e a Perícia escolhida em ••+",
  "core-2ed:inspiring": "Presença •••",
  "core-2ed:iron-will": "Perseverança ••••",
  "core-2ed:pusher": "Persuasão ••",
  "core-2ed:small-unit-tactics": "Presença •••",
  "core-2ed:spin-doctor": "Manipulação •••, Subterfúgio ••",
  "core-2ed:table-turner": "Compostura •••, Manipulação •••, Raciocínio •••",
  "core-2ed:taste": "Ofícios ••, e uma Especialização em Ofícios ou Expressão",
  "core-2ed:untouchable": "Manipulação •••, Subterfúgio ••",
  "core-2ed:medium": "Empatia ••",
  "core-2ed:mind-of-a-madman": "Empatia •••",
  "core-2ed:armed-defense": "Destreza •••, Armas Brancas ••, Combate Defensivo: Armas Brancas",
  "core-2ed:cheap-shot": "Briga de Rua •••, Subterfúgio ••",
  "core-2ed:choke-hold": "Briga ••",
  "core-2ed:defensive-combat": "Briga • ou Armas Brancas •; escolha um ao selecionar este Mérito",
  "core-2ed:fighting-finesse": "Destreza •••, uma Especialização em Armas Brancas ou Briga",
  "core-2ed:firefight": "Compostura •••, Destreza •••, Atletismo ••, Armas de Fogo ••",
  "core-2ed:grappling": "Vigor •••, Força ••, Atletismo ••, Briga ••",
  "core-2ed:heavy-weapons": "Vigor •••, Força •••, Atletismo ••, Armas Brancas ••",
  "core-2ed:iron-skin": "Artes Marciais •• ou Briga de Rua ••, Vigor •••",
  "core-2ed:light-weapons": "Raciocínio ••• ou Acuidade em Combate, Destreza •••, Atletismo ••, Armas Brancas ••",
  "core-2ed:marksmanship": "Compostura •••, Perseverança •••, Armas de Fogo ••",
  "core-2ed:martial-arts": "Perseverança •••, Destreza •••, Atletismo ••, Briga ••",
  "core-2ed:shiv": "Briga de Rua ••, Armas Brancas •",
  "core-2ed:street-fighting": "Vigor •••, Compostura •••, Briga ••, Manha ••",
  "ctl-2ed:acute-senses": "Raciocínio ou Compostura •••",
  "ctl-2ed:cloak-of-leaves": "Manto de Outono •••",
  "ctl-2ed:cold-hearted": "Manto de Inverno •••",
  "ctl-2ed:diviner": "Compostura •••, Raciocínio •••",
  "ctl-2ed:dream-warrior": "Wyrd 2+, um Atributo Social •••, uma Especialização em Briga ou Armas Brancas",
  "ctl-2ed:dreamweaver": "Wyrd 3+",
  "ctl-2ed:firebrand": "Manto de Verão •••",
  "ctl-2ed:gentrified-bearing": "Wyrd 2+",
  "ctl-2ed:grounded": "Manto de Primavera •••",
  "ctl-2ed:hedge-brawler": "Briga, Armas de Fogo, ou Armas Brancas ••",
  "ctl-2ed:hedge-duelist": "Presença ou Manipulação ••, Briga ou Armas Brancas ••, qualquer Perícia Social ••",
  "ctl-2ed:noblesse-oblige": "Apropriado Manto da Corte •",
  "ctl-2ed:pandemoniacal": "Wyrd 6+",
  "ctl-2ed:warded-dreams": "Perseverança igual aos pontos em Sonhos Protegidos",
  "ctl-2ed:workshop": "Hollow",
  "ctl-2ed:anonymity": "Não pode possuir Fama.",
  "ctl-2ed:demolisher": "Força ou Inteligência •••",
  "ctl-2ed:fast-reflexes": "Raciocínio ••• ou Destreza •••",
  "ctl-2ed:fast-talking": "Manipulação •••, Subterfúgio ••",
  "ctl-2ed:fighting-finesse": "Destreza •••, uma Especialização em Armas Brancas ou Briga",
  "ctl-2ed:fixer": "Contatos ••, Raciocínio •••",
  "ctl-2ed:fleet-of-foot": "Atletismo ••",
  "ctl-2ed:inspiring": "Presença •••",
  "ctl-2ed:interdisciplinary-specialty": "Perícia em ••• ou mais com uma Especialização",
  "ctl-2ed:iron-stamina": "Vigor ••• ou Perseverança •••",
  "ctl-2ed:lucid-dreamer": "Não changeling, Perseverança •••",
  "ctl-2ed:parkour": "Destreza •••, Atletismo ••",
  "ctl-2ed:pusher": "Persuasão ••",
  "ctl-2ed:trained-observer": "Raciocínio ou Compostura •••",
  "ctl-kith-kin:dramaturge": "Raciocínio •••, Expressão •••, Subterfúgio •••",
  "ctl-kith-kin:understudy": "Mérito Dramaturgo, Expressão ••••",
  "ctl-hedge:holding": "Hollow ou Passagem Estável",
  "ctl-hedge:thistle-guardian": "Wyrd 3+, participante da Demarcação (p. XX)",
  "ctl-hedge:dream-tripper": "Tocado pelas Fadas, Moldador de Sonhos, Dreamsteps",
  "ctl-hedge:dream-ghost": "Tocado pelas Fadas, Sonhador Lúcido",
  "ctl-hedge:twice-shy": "Tocado pelas Fadas, Olhar do Sonhador, o fetch do changeling está vivo",
  "h-courts:dressed-to-kill": "Corte da Primavera ou Manto de Verão ••, Socialização ••",
  "h-courts:friends-in-low-places": "Barfly",
  "h-courts:spring-loaded": "Vigor •••",
  "h-courts:no-rest-for-the-wicked": "Vigor ou Perseverança •••",
  "h-courts:street-pharmacist": "Medicina ou Manha ••",
  "h-courts:a-taste-of-honey": "Expressão ••",
  "h-courts:beware-of-dog": "Seguidor •",
  "h-courts:hey-watch-this": "Corte do Verão ou Manto de Primavera ••, Presença •••",
  "h-courts:quiet-rage": "Compostura •••",
  "h-courts:rageaholic": "Empatia ••",
  "h-courts:seen-some-shit": "Wyrd •• ou Compostura ••••",
  "h-courts:acquired-taste": "Ocultismo ••",
  "h-courts:can-t-spook-a-spooker": "Manto de Outono ••",
  "h-courts:favored-phobia": "Intimidação ••",
  "h-courts:hedgewalker": "Sentido da Sebe, Wyrd •••",
  "h-courts:i-love-a-good-scare": "Não pode possuir Habituado ao Terror",
  "h-courts:intuitive-artificer": "Ocultismo ••",
  "h-courts:inured-to-terror": "Não pode possuir Adoro um Bom Susto",
  "h-courts:grief-connoisseur": "Empatia ••",
  "h-courts:gtfo": "Senso de Perigo, Raciocínio ••, Furtividade ••, Manto de Inverno ••",
  "h-courts:ice-water-veins": "Compostura •••",
  "h-courts:shivers": "Manto de Inverno ••, Raciocínio •••",
  "h-courts:shoulder-to-cry-on": "Empatia ••",
  "h-courts:snow-cover": "Manto de Inverno ••",
  "h-seemings:blood-and-bone": "Fera",
  "h-seemings:debaucher": "Fera",
  "h-seemings:fae-pet": "Fera ou Empatia com Animais •••; Seguidor ••",
  "h-seemings:green-grocer": "Fera, Sobrevivência ••",
  "h-seemings:hot-pursuit": "Fera, Pés Ligeiros •",
  "h-seemings:running-with-the-wolves": "Fera, Empatia com Animais •••",
  "h-seemings:screw-it": "Fera; Compostura ou Perseverança •••",
  "h-seemings:total-abandon": "Fera, Atletismo ••, Briga ••",
  "h-seemings:from-the-shadows": "Trevoso, Atletismo ••, Furtividade ••",
  "h-seemings:hidden-life": "Trevoso, Subterfúgio ••, Anonymity •",
  "h-seemings:lucidity-in-lunacy": "Trevoso",
  "h-seemings:perfect-stillness": "Trevoso ou Raciocínio •••; Furtividade ••",
  "h-seemings:poor-little-paranoid": "Trevoso, Senso de Perigo",
  "h-seemings:puzzler": "Trevoso; Inteligência ou Raciocínio •••",
  "h-seemings:secret-seer": "Trevoso",
  "h-seemings:wrapped-in-an-enigma": "Trevoso, Subterfúgio •••",
  "h-seemings:conjuror-s-call": "Elemental",
  "h-seemings:foiled-forensics": "Elemental",
  "h-seemings:resting-birch-face": "Elemental, Intimidação ••",
  "h-seemings:smelling-like-a-rose": "Elemental",
  "h-seemings:stomach-of-steel": "Elemental ou Vigor •••",
  "h-seemings:unbroken-branches": "Elemental, Wyrd 3+",
  "h-seemings:stone-hearted": "Elemental; Compostura ou Perseverança •••",
  "h-seemings:eerie-eyes": "Elemental",
  "h-seemings:still-waters-run-deep": "Elemental",
  "h-seemings:fire-forged-friends": "Elemental ou Ocultismo •••; Empatia ••; Contrato de Glória Primordial",
  "h-seemings:confessional-countenance": "Belo, Empatia •••",
  "h-seemings:just-your-type": "Belo, Barfly",
  "h-seemings:not-just-a-pretty-face": "Belo, Aparência Marcante •",
  "h-seemings:sanguine-sacrifice": "Belo",
  "h-seemings:soothing-presence": "Belo, Presença •••",
  "h-seemings:cast-iron-stomach": "Ogro, Vigor ••",
  "h-seemings:living-large": "Ogro, Recursos •, Size 6+",
  "h-seemings:looming-large": "Ogro, Size 6+",
  "h-seemings:thick-headed": "Ogro; Vigor ou Força •••",
  "h-seemings:thick-skinned": "Ogro, Vigor •••",
  "h-seemings:tickets-to-the-gun-show": "Ogro ou Força •••; Atletismo ••",
  "h-seemings:too-simple-to-fool": "Ogro, Inteligência • (no máximo)",
  "h-seemings:gnarled": "Mirrado, Wyrd 2+",
  "h-seemings:iron-toes": "Mirrado",
  "h-seemings:know-it-all": "Mirrado, Inteligência •••, two dots em a Perícia escolhida",
  "h-seemings:perfectionist": "Mirrado; Raciocínio ••; Ofícios, Expressão, ou Ocultismo •••",
  "h-seemings:pinchpenny": "Mirrado, Raciocínio •••",
  "h-seemings:razor-tongue": "Mirrado, Expressão ••",
  "h-seemings:spiteful-competence": "Mirrado",
  "h-seemings:tinkerer": "Mirrado, Ofícios ••",
  "h-seemings:token-crucible": "Workshop •, Workshop Especialização em Token Crafting",
  "mta-2ed:adamant-hand": "Status na Seta Adamantina •, (Atletismo, Briga, ou Armas Brancas •••, Especial)",
  "mta-2ed:astral-adept": "Desperto ou Sonâmbulo",
  "mta-2ed:between-the-ticks": "Raciocínio •••, Tempo •",
  "mta-2ed:cabal-theme": "Pertencer a um Cabal, todos os membros devem possuir este Mérito",
  "mta-2ed:dream": "Compostura •••, Raciocínio •••",
  "mta-2ed:egregore": "Status no Mysterium •",
  "mta-2ed:fast-spells": "Armas de Fogo ••, Tempo •",
  "mta-2ed:infamous-mentor": "Mentor (nível igual ou superior)",
  "mta-2ed:lex-magica": "Status na Escada de Prata •",
  "mta-2ed:mana-sensitivity": "Primórdio •, Raciocínio •••",
  "mta-2ed:masque": "Status nos Guardiões do Véu •",
  "mta-2ed:potent-resonance": "Gnose 3+",
  "mta-2ed:prelacy": "Status nos Videntes do Trono •••",
  "mta-2ed:sanctum": "Lugar Seguro",
  "mta-2ed:techne": "Status no Conselho Livre •",
  "mta-2ed:defensive-combat": "Briga • ou Armas Brancas •; escolha um ao selecionar este Mérito",
  "mta-2ed:library-advanced": "Biblioteca •••, Lugar Seguro (Especial)",
  "mta-2ed:trained-observer": "Raciocínio ••• ou Compostura •••",
  "mta-signs:broad-dedication": "Primórdio •",
  "mta-signs:inheritance": "Fama •",
  "mta-signs:cognoscente": "Primórdio •••, Erudição ou Ocultismo ••",
  "mta-signs:legacy-pedagogue": "Primórdio •••, Gnose ••• +",
  "mta-pentacle:exoteric-arete": "Status nos Guardiões da Palavra •• +, uma Perícia em ••••+ com uma Especialização.",
  "mta-pentacle:perfecti": "Status no Pancryptiato •••+, nenhum Mérito Social que represente Adormecidos",
  "mta-pentacle:seasoned-duelist": "ao menos três Condições Triunfante resolvidas",
  "mta-pentacle:faction-member": "Status na Ordem ••",
  "nh-nameless:hand-of-destiny": "Desperto; Destino 1",
  "h-courts:bedside-manner": "Medicina ••",
  "h-courts:i-meant-to-do-that": "Presença •••",
  "h-courts:sucker-born-every-minute": "Manipulação •••",
  "h-courts:don-t-mess-with-jim": "Intimidação ••",
  "h-courts:get-the-manager": "Intimidação ••, Manto de Verão ••",
  "h-courts:improvised-ritual": "Ocultismo •••",
  "h-courts:misery-loves-company": "Manipulação •••",
  "h-seemings:just-try-me": "Fera, Intimidação ••",
  "h-seemings:mad-bad-and-dangerous": "Fera, Aparência Marcante •",
  "h-seemings:malignant-mien": "Fera ou Semblante Letal",
  "h-seemings:mirror-me": "Trevoso",
  "h-seemings:riddle-me-this": "Trevoso, Expressão ••, Subterfúgio ••",
  "h-seemings:mover-and-shaker": "Belo",
  "h-seemings:multimask": "Belo ou Subterfúgio •••, Manymask",
  "h-seemings:throne": "Belo, Manipulação •••",
  "h-seemings:meat-shield": "Ogro, Vigor •••, Intimidação •••",
  "h-seemings:material-affinity": "Mirrado; Ofícios ou Expressão ••",
  "h-seemings:percussive-maintenance": "Mirrado"
};

export const CONTRACT_DICE_POOLS_PT: Record<string, string> = {
  "ctl-2ed:hostile-takeover": "Nenhuma",
  "ctl-2ed:mask-of-superiority": "Presença + Subterfúgio + Wyrd",
  "ctl-2ed:paralyzing-presence": "Presença + Intimidação + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:summon-the-loyal-servant": "Nenhuma",
  "ctl-2ed:tumult": "Presença + Empatia + Wyrd − Perseverança",
  "ctl-2ed:discreet-summons": "Manipulação + Persuasão + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:masterminds-gambit": "Nenhuma",
  "ctl-2ed:pipes-of-the-beastcaller": "Manipulação + Empatia com Animais + Wyrd vs. Perseverança + Compostura",
  "ctl-2ed:the-royal-court": "Nenhuma",
  "ctl-2ed:spinning-wheel": "Inteligência + Ocultismo + Wyrd − Perseverança",
  "ctl-2ed:blessing-of-perfection": "Nenhuma",
  "ctl-2ed:changing-fortunes": "Raciocínio + Ocultismo + Wyrd − Perseverança",
  "ctl-2ed:light-shy": "Nenhuma",
  "ctl-2ed:murkblur": "Manipulação + Subterfúgio + Wyrd vs. Raciocínio + Wyrd",
  "ctl-2ed:trivial-reworking": "Nenhuma",
  "ctl-2ed:changeling-hours": "Nenhuma",
  "ctl-2ed:dance-of-the-toys": "Nenhuma",
  "ctl-2ed:hidden-reality": "Nenhuma",
  "ctl-2ed:stealing-the-solid-reflection": "Força + Furto + Wyrd",
  "ctl-2ed:tatterdemalions-workshop": "Nenhuma",
  "ctl-2ed:glimpse-of-a-distant-mirror": "Nenhuma",
  "ctl-2ed:know-the-competition": "Manipulação + Socialização + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:portents-and-visions": "Manipulação + Ocultismo + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:read-lucidity": "Manipulação + Empatia + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:walls-have-ears": "Nenhuma",
  "ctl-2ed:props-and-scenery": "Manipulação + Persuasão + Wyrd",
  "ctl-2ed:reflections-of-the-past": "Inteligência + Ocultismo + Wyrd",
  "ctl-2ed:riddle-kith": "Manipulação + Furto + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:skinmask": "Nenhuma",
  "ctl-2ed:unravel-the-tapestry": "Raciocínio + Ocultismo + Wyrd",
  "ctl-2ed:cloak-of-night": "Nenhuma",
  "ctl-2ed:fae-cunning": "Nenhuma",
  "ctl-2ed:shared-burden": "Nenhuma",
  "ctl-2ed:thorns-and-brambles": "Nenhuma",
  "ctl-2ed:trapdoor-spiders-trick": "Nenhuma",
  "ctl-2ed:fortifying-presence": "Presença + Empatia + Wyrd vs. Perseverança + Wyrd",
  "ctl-2ed:hedgewall": "Inteligência + Sobrevivência + Wyrd",
  "ctl-2ed:pure-clarity": "Perseverança + Compostura + Wyrd",
  "ctl-2ed:vow-of-no-compromise": "Nenhuma",
  "ctl-2ed:whispers-of-morning": "Nenhuma",
  "ctl-2ed:boon-of-the-scuttling-spider": "Nenhuma",
  "ctl-2ed:dreamsteps": "Inteligência + Empatia + Wyrd vs. Bas tion’s Fortification",
  "ctl-2ed:nevertread": "Nenhuma",
  "ctl-2ed:pathfinder": "Nenhuma",
  "ctl-2ed:seven-league-leap": "Nenhuma",
  "ctl-2ed:chrysalis": "Nenhuma",
  "ctl-2ed:flickering-hours": "Nenhuma",
  "ctl-2ed:leaping-toward-nightfall": "Inteligência + Ocultismo + Wyrd vs. Perseverança + Wyrd",
  "ctl-2ed:mirror-walk": "Raciocínio + Sobrevivência + Wyrd",
  "ctl-2ed:talon-and-wing": "Nenhuma",
  "ctl-2ed:elemental-weapon": "Presença + Sobrevivência + Wyrd",
  "ctl-2ed:might-of-the-terrible-brute": "Nenhuma",
  "ctl-2ed:overpowering-dread": "Presença + Intimidação + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:primal-glory": "Nenhuma",
  "ctl-2ed:touch-of-wrath": "Inteligência + Ofícios + Wyrd",
  "ctl-2ed:elemental-fury": "Nenhuma",
  "ctl-2ed:oathbreakers-punishment": "Raciocínio + Empatia + Wyrd − Compostura",
  "ctl-2ed:red-revenge": "Nenhuma",
  "ctl-2ed:relentless-pursuit": "Nenhuma",
  "ctl-2ed:thief-of-reason": "Presença + Subterfúgio + Wyrd − Perseverança",
  "ctl-2ed:cupids-arrow": "Raciocínio + Empatia + Manto vs. Compostura + Wyrd",
  "ctl-2ed:dreams-of-the-earth": "Presença + Expressão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:gift-of-warm-breath": "Nenhuma",
  "ctl-2ed:springs-kiss": "Nenhuma",
  "ctl-2ed:wyrd-faced-stranger": "Presença + Subterfúgio + Manto vs. Compostura + Wyrd",
  "ctl-2ed:blessing-of-spring": "Inteligência + Medicina + Manto vs. Vigor + Wyrd (sapient creatures)",
  "ctl-2ed:gift-of-warm-blood": "Raciocínio + Medicina + Manto",
  "ctl-2ed:pandoras-gift": "Nenhuma",
  "ctl-2ed:prince-of-ivy": "Presença + Expressão + Manto",
  "ctl-2ed:waking-the-inner-fae": "Manipulação + Expressão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:baleful-sense": "Raciocínio + Intimidação + Manto vs. Com posure + Wyrd",
  "ctl-2ed:child-of-the-hearth": "Nenhuma",
  "ctl-2ed:helios-light": "Nenhuma",
  "ctl-2ed:high-summers-zeal": "Presença + Persuasão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:vigilance-of-ares": "Nenhuma",
  "ctl-2ed:fiery-tongue": "Presença + Intimidação + Manto − Perseverança",
  "ctl-2ed:flames-of-summer": "Vigor + Sobrevivência + Manto",
  "ctl-2ed:helios-judgment": "Destreza + Atletismo + Manto",
  "ctl-2ed:solstice-revelation": "Nenhuma",
  "ctl-2ed:sunburnt-heart": "Manipulação + Persuasão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:autumns-fury": "Nenhuma",
  "ctl-2ed:last-harvest": "Nenhuma",
  "ctl-2ed:tale-of-the-baba-yaga": "Manipulação + Subterfúgio + Manto vs. Compostura + Wyrd",
  "ctl-2ed:twilights-harbinger": "Nenhuma",
  "ctl-2ed:witches-intuition": "Raciocínio + Subterfúgio + Manto vs. Compostura + Wyrd",
  "ctl-2ed:famines-bulwark": "Raciocínio + Ocultismo + Manto",
  "ctl-2ed:mien-of-the-baba-yaga": "Presença + Intimidação + Manto vs. Compostura + Wyrd",
  "ctl-2ed:riding-the-falling-leaves": "Destreza + Ocultismo + Manto",
  "ctl-2ed:sorcerers-rebuke": "Manipulação + Ocultismo + Manto – Perseverança",
  "ctl-2ed:tasting-the-harvest": "Presença + Subterfúgio + Manto",
  "ctl-2ed:the-dragon-knows": "Raciocínio + Empatia + Manto vs. Compostura + Wyrd",
  "ctl-2ed:heart-of-ice": "Nenhuma",
  "ctl-2ed:ice-queens-call": "Nenhuma",
  "ctl-2ed:slipknot-dreams": "Manipulação + Empatia + Manto vs. Perseverança + Wyrd",
  "ctl-2ed:touch-of-winter": "Inteligência + Ciência + Manto",
  "ctl-2ed:ermines-winter-coat": "Nenhuma",
  "ctl-2ed:fallow-fields": "Manipulação + Empatia + Manto vs. Perseverança + Wyrd",
  "ctl-2ed:field-of-regret": "Presença + Empatia + Manto − Perseverança",
  "ctl-2ed:mantle-of-frost": "Nenhuma",
  "ctl-2ed:winters-curse": "Presença + Sobrevivência + Manto vs. Perseverança + Wyrd",
  "ctl-kith-kin:filling-the-cup": "Nenhuma",
  "ctl-kith-kin:sleeps-sweet-embrace": "Manipulação + Expressão + Wyrd − Perseverança",
  "ctl-kith-kin:curses-cure": "Inteligência + Medicina + Wyrd",
  "ctl-kith-kin:dreamers-phalanx": "Nenhuma",
  "ctl-kith-kin:closing-deaths-door": "Manipulação + Empatia + Wyrd",
  "ctl-kith-kin:feast-of-plenty": "Presença + Socialização + Wyrd",
  "ctl-kith-kin:still-waters-run-deep": "Manipulação + Subterfúgio + Wyrd − Perseverança",
  "ctl-kith-kin:poison-the-well": "Manipulação + Expressão + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:shared-cup": "Presença + Ocultismo + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:book-of-black-and-red": "Raciocínio + Erudição + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:give-and-take": "Nenhuma",
  "ctl-kith-kin:beggar-knight": "Manipulação + Erudição + Wyrd – Com posure",
  "ctl-kith-kin:grease-the-wheels": "Presença + Persuasão + Wyrd",
  "ctl-kith-kin:exchange-of-gilded-contracts": "Presença + Socialização + Wyrd – Disponibilidade atual",
  "ctl-kith-kin:golden-promise": "Presença + Socialização + Wyrd – Disponibilidade atual",
  "ctl-kith-kin:grand-revel-of-the-harvest": "Raciocínio + Empatia + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:thirty-pieces": "Raciocínio + Empatia + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:burning-ambition": "Nenhuma",
  "ctl-kith-kin:jealous-vengeance": "Presença + Intimidação + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:litany-of-rivals": "Inteligência + Ocultismo + Wyrd",
  "ctl-kith-kin:knights-oath": "Nenhuma",
  "ctl-kith-kin:unmask-the-dark-horse": "Presença + Persuasão + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:a-benevolent-hand": "Nenhuma",
  "ctl-kith-kin:tempters-quest": "Presença + Persuasão + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:curse-of-hidden-strings": "Manipulação + Furto + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:spare-not-the-rod": "Nenhuma",
  "ctl-kith-kin:pole-star": "Nenhuma",
  "ctl-kith-kin:cynosure": "Manipulação + Empatia + Wyrd vs. Com posure + Wyrd",
  "ctl-kith-kin:shooting-star": "Nenhuma",
  "ctl-kith-kin:retrograde": "Presença + Expressão + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:frozen-star": "Inteligência + (Empatia ou Persuasão) + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:light-of-ancient-stars": "Nenhuma",
  "ctl-kith-kin:pinch-of-stardust": "Inteligência + Ofícios + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:briars-herald": "Manipulação + Furto + Wyrd vs. Com posure +Wyrd",
  "ctl-kith-kin:by-the-pricking-of-my-thumbs": "Nenhuma",
  "ctl-kith-kin:thistles-rebuke": "Nenhuma",
  "ctl-kith-kin:the-gouging-curse": "Manipulação + Ocultismo + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:embrace-of-nettles": "Nenhuma",
  "ctl-kith-kin:acanthas-fury": "Presença + Sobrevivência + Wyrd vs. Vigor + Wyrd",
  "ctl-kith-kin:awaken-portal": "Nenhuma",
  "ctl-kith-kin:crown-of-thorns": "Presença + Ocultismo + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:shrikes-larder": "Nenhuma",
  "ctl-kith-kin:witchs-brambles": "Nenhuma",
  "ctl-kith-kin:coming-darkness": "Nenhuma",
  "ctl-kith-kin:pomp-and-circumstance": "Nenhuma",
  "ctl-kith-kin:shadow-puppet": "Nenhuma",
  "ctl-kith-kin:dread-companion": "Manipulação + Ocultismo + Wyrd vs. Resis tance + Wyrd",
  "ctl-kith-kin:cracked-mirror": "Manipulação + Furto + Wyrd vs. Vigor + Wyrd",
  "ctl-kith-kin:listen-with-the-winds-ears": "Nenhuma",
  "ctl-kith-kin:momentary-respite": "Vigor + Sobrevivência + Wyrd",
  "ctl-kith-kin:steal-influence": "Raciocínio + Furto + Wyrd vs Perseverança + Wyrd",
  "ctl-kith-kin:earths-gentle-movements": "Força + Ofícios + Wyrd",
  "ctl-kith-kin:earths-impenetrable-walls": "Força + Ofícios + Wyrd",
  "ctl-dark-eras:peacemakers-draw": "Destreza + (Armas de Fogo ou Atletismo) + Manto vs. Vigor + Wyrd",
  "ctl-oak-ash-thorn:donning-the-grand-mantle": "Presença + Expressão + Manto",
  "ctl-oak-ash-thorn:autonomous-payload": "Manipulação + Computação + Manto vs. (Inteligência ou Computação) + Fortification",
  "ctl-oak-ash-thorn:the-widening-gyre": "Presença + Atletismo + Manto vs. Vigor + Wyrd",
  "ctl-oak-ash-thorn:principle": "Presença + Política + Manto vs. Perseverança + Wyrd",
  "h-courts:celestial-summons": "Presença + Persuasão + Wyrd vs. Compostura + Wyrd",
  "h-courts:climate-change": "Perseverança + Sobrevivência + Manto",
  "h-courts:celestial-might": "Destreza + Ocultismo + Manto",
  "h-courts:celestial-shield": "Nenhuma",
  "h-courts:vigil-of-silver-and-gold": "Presença + Expressão + Wyrd",
  "h-courts:family-friendly-feud": "Nenhuma",
  "h-courts:frozen-in-time": "Manipulação + Ocultismo + Manto vs. Perseverança + Wyrd",
  "h-courts:hearths-respite": "Compostura + Empatia + Manto",
  "h-courts:protection-of-the-innocent": "Perseverança + Medicina + Manto",
  "h-courts:shared-remembrance": "Raciocínio + Empatia + Manto vs. Perseverança + Wyrd",
  "h-courts:nothing-to-see-here": "Manipulação + Empatia + Wyrd vs. Compostura + Wyrd",
  "h-courts:rain-of-terror": "Inteligência + Ocultismo + Manto vs. Compostura + Wyrd (disputada separadamente por cada vítima)",
  "h-courts:storm-of-the-century": "Presença + Sobrevivência + Manto",
  "h-courts:tempestuous-hearts": "Nenhuma",
  "h-courts:thunder-steed": "Nenhuma",
  "h-courts:aether-crossing": "Nenhuma",
  "h-courts:age-of-aquarius": "Nenhuma",
  "h-courts:assuming-the-stellar-mantle": "Manipulação + Persuasão + Manto vs Compostura + Wyrd",
  "h-courts:elemental-cycle": "Nenhuma",
  "h-courts:restringing-the-loom": "Nenhuma",
  "h-courts:all-roads-closed": "Inteligência + Manha + Manto",
  "h-courts:cast-out": "Presença + Ocultismo + Manto vs. Vigor + Wyrd",
  "h-courts:create-path": "Presença + Sobrevivência + Manto",
  "h-courts:escape-route": "Nenhuma",
  "h-courts:labyrinth": "Manipulação + Subterfúgio + Manto vs. Perseverança + Wyrd",
  "h-courts:harmony-enforced": "Presença + Empatia + Manto vs. maior Perseverança + Wyrd",
  "h-courts:one-with-the-elements": "Nenhuma",
  "h-courts:shifting-balance": "Nenhuma",
  "h-courts:steal-harmony": "Presença + Empatia + Manto – Compostura",
  "h-courts:weaponize-mob": "Manipulação + Persuasão + Manto – maior Compostura em a group",
  "h-courts:davy-jones-locker": "Presença + Sobrevivência + Manto",
  "h-courts:dredge-the-depths": "Raciocínio + Investigação + Manto",
  "h-courts:gone-by-the-board": "Nenhuma",
  "h-courts:red-sky-at-morning": "Nenhuma",
  "h-courts:red-sky-at-night": "Nenhuma",
  "h-courts:always-solvent": "Nenhuma",
  "h-courts:cook-the-books": "Nenhuma",
  "h-courts:if-two-are-dead": "Presença + Intimidação + Manto vs. Compostura + Wyrd",
  "h-courts:raise-the-band": "Nenhuma",
  "h-courts:supply-and-demand": "Presença + Intimidação + Manto vs. Perseverança + Wyrd",
  "h-seemings:carrion-feast": "Nenhuma",
  "h-seemings:no-escape": "Vigor + Atletismo + Wyrd vs. Vigor + Wyrd (rolagem de resistência separada para cada vítima)",
  "h-seemings:starvations-savagery": "Presença + Intimidação + Wyrd vs. Compostura + Wyrd",
  "h-seemings:swallow-whole": "Força + Atletismo + Wyrd vs. Vigor + Wyrd",
  "h-seemings:you-are-who-you-eat": "Nenhuma",
  "h-seemings:last-hope": "Nenhuma",
  "h-seemings:the-troll-toll": "Presença + Subterfúgio + Wyrd vs. Perseverança + Wyrd (maior do grupo)",
  "ctl-kith-kin:coin-mark": "Nenhuma",
  "ctl-kith-kin:blood-debt": "Nenhuma"
};
