export const CONTRACT_DICE_POOLS_PT: Record<string, string> = {
  "ctl-2ed:hostile-takeover": "Nenhuma",
  "ctl-2ed:mask-of-superiority": "Presença + Subterfúgio + Wyrd",
  "ctl-2ed:paralyzing-presence": "Presença + Intimidação + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:summon-the-loyal-servant": "Nenhuma",
  "ctl-2ed:tumult": "Presença + Empatia + Wyrd − Perseverança",
  "ctl-2ed:discreet-summons": "Manipulação + Persuasão + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:masterminds-gambit": "Nenhuma",
  "ctl-2ed:pipes-of-the-beastcaller": "Manipulação + Empatia com Animais + Wyrd vs. Perseverança + Compostura",
  "ctl-2ed:the-royal-court": "Nenhuma",
  "ctl-2ed:spinning-wheel": "Inteligência + Ocultismo + Wyrd − Perseverança",
  "ctl-2ed:blessing-of-perfection": "Nenhuma",
  "ctl-2ed:changing-fortunes": "Raciocínio + Ocultismo + Wyrd − Perseverança",
  "ctl-2ed:light-shy": "Nenhuma",
  "ctl-2ed:murkblur": "Manipulação + Subterfúgio + Wyrd vs. Raciocínio + Wyrd",
  "ctl-2ed:trivial-reworking": "Nenhuma",
  "ctl-2ed:changeling-hours": "Nenhuma",
  "ctl-2ed:dance-of-the-toys": "Nenhuma",
  "ctl-2ed:hidden-reality": "Nenhuma",
  "ctl-2ed:stealing-the-solid-reflection": "Força + Furto + Wyrd",
  "ctl-2ed:tatterdemalions-workshop": "Nenhuma",
  "ctl-2ed:glimpse-of-a-distant-mirror": "Nenhuma",
  "ctl-2ed:know-the-competition": "Manipulação + Socialização + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:portents-and-visions": "Manipulação + Ocultismo + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:read-lucidity": "Manipulação + Empatia + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:walls-have-ears": "Nenhuma",
  "ctl-2ed:props-and-scenery": "Manipulação + Persuasão + Wyrd",
  "ctl-2ed:reflections-of-the-past": "Inteligência + Ocultismo + Wyrd",
  "ctl-2ed:riddle-kith": "Manipulação + Furto + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:skinmask": "Nenhuma",
  "ctl-2ed:unravel-the-tapestry": "Raciocínio + Ocultismo + Wyrd",
  "ctl-2ed:cloak-of-night": "Nenhuma",
  "ctl-2ed:fae-cunning": "Nenhuma",
  "ctl-2ed:shared-burden": "Nenhuma",
  "ctl-2ed:thorns-and-brambles": "Nenhuma",
  "ctl-2ed:trapdoor-spiders-trick": "Nenhuma",
  "ctl-2ed:fortifying-presence": "Presença + Empatia + Wyrd vs. Perseverança + Wyrd",
  "ctl-2ed:hedgewall": "Inteligência + Sobrevivência + Wyrd",
  "ctl-2ed:pure-clarity": "Perseverança + Compostura + Wyrd",
  "ctl-2ed:vow-of-no-compromise": "Nenhuma",
  "ctl-2ed:whispers-of-morning": "Nenhuma",
  "ctl-2ed:boon-of-the-scuttling-spider": "Nenhuma",
  "ctl-2ed:dreamsteps": "Inteligência + Empatia + Wyrd vs. Bas tion’s Fortification",
  "ctl-2ed:nevertread": "Nenhuma",
  "ctl-2ed:pathfinder": "Nenhuma",
  "ctl-2ed:seven-league-leap": "Nenhuma",
  "ctl-2ed:chrysalis": "Nenhuma",
  "ctl-2ed:flickering-hours": "Nenhuma",
  "ctl-2ed:leaping-toward-nightfall": "Inteligência + Ocultismo + Wyrd vs. Perseverança + Wyrd",
  "ctl-2ed:mirror-walk": "Raciocínio + Sobrevivência + Wyrd",
  "ctl-2ed:talon-and-wing": "Nenhuma",
  "ctl-2ed:elemental-weapon": "Presença + Sobrevivência + Wyrd",
  "ctl-2ed:might-of-the-terrible-brute": "Nenhuma",
  "ctl-2ed:overpowering-dread": "Presença + Intimidação + Wyrd vs. Compostura + Wyrd",
  "ctl-2ed:primal-glory": "Nenhuma",
  "ctl-2ed:touch-of-wrath": "Inteligência + Ofícios + Wyrd",
  "ctl-2ed:elemental-fury": "Nenhuma",
  "ctl-2ed:oathbreakers-punishment": "Raciocínio + Empatia + Wyrd − Compostura",
  "ctl-2ed:red-revenge": "Nenhuma",
  "ctl-2ed:relentless-pursuit": "Nenhuma",
  "ctl-2ed:thief-of-reason": "Presença + Subterfúgio + Wyrd − Perseverança",
  "ctl-2ed:cupids-arrow": "Raciocínio + Empatia + Manto vs. Compostura + Wyrd",
  "ctl-2ed:dreams-of-the-earth": "Presença + Expressão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:gift-of-warm-breath": "Nenhuma",
  "ctl-2ed:springs-kiss": "Nenhuma",
  "ctl-2ed:wyrd-faced-stranger": "Presença + Subterfúgio + Manto vs. Compostura + Wyrd",
  "ctl-2ed:blessing-of-spring": "Inteligência + Medicina + Manto vs. Vigor + Wyrd (sapient creatures)",
  "ctl-2ed:gift-of-warm-blood": "Raciocínio + Medicina + Manto",
  "ctl-2ed:pandoras-gift": "Nenhuma",
  "ctl-2ed:prince-of-ivy": "Presença + Expressão + Manto",
  "ctl-2ed:waking-the-inner-fae": "Manipulação + Expressão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:baleful-sense": "Raciocínio + Intimidação + Manto vs. Com posure + Wyrd",
  "ctl-2ed:child-of-the-hearth": "Nenhuma",
  "ctl-2ed:helios-light": "Nenhuma",
  "ctl-2ed:high-summers-zeal": "Presença + Persuasão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:vigilance-of-ares": "Nenhuma",
  "ctl-2ed:fiery-tongue": "Presença + Intimidação + Manto − Perseverança",
  "ctl-2ed:flames-of-summer": "Vigor + Sobrevivência + Manto",
  "ctl-2ed:helios-judgment": "Destreza + Atletismo + Manto",
  "ctl-2ed:solstice-revelation": "Nenhuma",
  "ctl-2ed:sunburnt-heart": "Manipulação + Persuasão + Manto vs. Compostura + Wyrd",
  "ctl-2ed:autumns-fury": "Nenhuma",
  "ctl-2ed:last-harvest": "Nenhuma",
  "ctl-2ed:tale-of-the-baba-yaga": "Manipulação + Subterfúgio + Manto vs. Compostura + Wyrd",
  "ctl-2ed:twilights-harbinger": "Nenhuma",
  "ctl-2ed:witches-intuition": "Raciocínio + Subterfúgio + Manto vs. Compostura + Wyrd",
  "ctl-2ed:famines-bulwark": "Raciocínio + Ocultismo + Manto",
  "ctl-2ed:mien-of-the-baba-yaga": "Presença + Intimidação + Manto vs. Compostura + Wyrd",
  "ctl-2ed:riding-the-falling-leaves": "Destreza + Ocultismo + Manto",
  "ctl-2ed:sorcerers-rebuke": "Manipulação + Ocultismo + Manto – Perseverança",
  "ctl-2ed:tasting-the-harvest": "Presença + Subterfúgio + Manto",
  "ctl-2ed:the-dragon-knows": "Raciocínio + Empatia + Manto vs. Compostura + Wyrd",
  "ctl-2ed:heart-of-ice": "Nenhuma",
  "ctl-2ed:ice-queens-call": "Nenhuma",
  "ctl-2ed:slipknot-dreams": "Manipulação + Empatia + Manto vs. Perseverança + Wyrd",
  "ctl-2ed:touch-of-winter": "Inteligência + Ciência + Manto",
  "ctl-2ed:ermines-winter-coat": "Nenhuma",
  "ctl-2ed:fallow-fields": "Manipulação + Empatia + Manto vs. Perseverança + Wyrd",
  "ctl-2ed:field-of-regret": "Presença + Empatia + Manto − Perseverança",
  "ctl-2ed:mantle-of-frost": "Nenhuma",
  "ctl-2ed:winters-curse": "Presença + Sobrevivência + Manto vs. Perseverança + Wyrd",
  "ctl-kith-kin:filling-the-cup": "Nenhuma",
  "ctl-kith-kin:sleeps-sweet-embrace": "Manipulação + Expressão + Wyrd − Perseverança",
  "ctl-kith-kin:curses-cure": "Inteligência + Medicina + Wyrd",
  "ctl-kith-kin:dreamers-phalanx": "Nenhuma",
  "ctl-kith-kin:closing-deaths-door": "Manipulação + Empatia + Wyrd",
  "ctl-kith-kin:feast-of-plenty": "Presença + Socialização + Wyrd",
  "ctl-kith-kin:still-waters-run-deep": "Manipulação + Subterfúgio + Wyrd − Perseverança",
  "ctl-kith-kin:poison-the-well": "Manipulação + Expressão + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:shared-cup": "Presença + Ocultismo + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:book-of-black-and-red": "Raciocínio + Erudição + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:give-and-take": "Nenhuma",
  "ctl-kith-kin:beggar-knight": "Manipulação + Erudição + Wyrd – Com posure",
  "ctl-kith-kin:grease-the-wheels": "Presença + Persuasão + Wyrd",
  "ctl-kith-kin:exchange-of-gilded-contracts": "Presença + Socialização + Wyrd – Disponibilidade atual",
  "ctl-kith-kin:golden-promise": "Presença + Socialização + Wyrd – Disponibilidade atual",
  "ctl-kith-kin:grand-revel-of-the-harvest": "Raciocínio + Empatia + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:thirty-pieces": "Raciocínio + Empatia + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:burning-ambition": "Nenhuma",
  "ctl-kith-kin:jealous-vengeance": "Presença + Intimidação + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:litany-of-rivals": "Inteligência + Ocultismo + Wyrd",
  "ctl-kith-kin:knights-oath": "Nenhuma",
  "ctl-kith-kin:unmask-the-dark-horse": "Presença + Persuasão + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:a-benevolent-hand": "Nenhuma",
  "ctl-kith-kin:tempters-quest": "Presença + Persuasão + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:curse-of-hidden-strings": "Manipulação + Furto + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:spare-not-the-rod": "Nenhuma",
  "ctl-kith-kin:pole-star": "Nenhuma",
  "ctl-kith-kin:cynosure": "Manipulação + Empatia + Wyrd vs. Com posure + Wyrd",
  "ctl-kith-kin:shooting-star": "Nenhuma",
  "ctl-kith-kin:retrograde": "Presença + Expressão + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:frozen-star": "Inteligência + (Empatia ou Persuasão) + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:light-of-ancient-stars": "Nenhuma",
  "ctl-kith-kin:pinch-of-stardust": "Inteligência + Ofícios + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:briars-herald": "Manipulação + Furto + Wyrd vs. Com posure +Wyrd",
  "ctl-kith-kin:by-the-pricking-of-my-thumbs": "Nenhuma",
  "ctl-kith-kin:thistles-rebuke": "Nenhuma",
  "ctl-kith-kin:the-gouging-curse": "Manipulação + Ocultismo + Wyrd vs. Compostura + Wyrd",
  "ctl-kith-kin:embrace-of-nettles": "Nenhuma",
  "ctl-kith-kin:acanthas-fury": "Presença + Sobrevivência + Wyrd vs. Vigor + Wyrd",
  "ctl-kith-kin:awaken-portal": "Nenhuma",
  "ctl-kith-kin:crown-of-thorns": "Presença + Ocultismo + Wyrd vs. Perseverança + Wyrd",
  "ctl-kith-kin:shrikes-larder": "Nenhuma",
  "ctl-kith-kin:witchs-brambles": "Nenhuma",
  "ctl-kith-kin:coming-darkness": "Nenhuma",
  "ctl-kith-kin:pomp-and-circumstance": "Nenhuma",
  "ctl-kith-kin:shadow-puppet": "Nenhuma",
  "ctl-kith-kin:dread-companion": "Manipulação + Ocultismo + Wyrd vs. Resis tance + Wyrd",
  "ctl-kith-kin:cracked-mirror": "Manipulação + Furto + Wyrd vs. Vigor + Wyrd",
  "ctl-kith-kin:listen-with-the-winds-ears": "Nenhuma",
  "ctl-kith-kin:momentary-respite": "Vigor + Sobrevivência + Wyrd",
  "ctl-kith-kin:steal-influence": "Raciocínio + Furto + Wyrd vs Perseverança + Wyrd",
  "ctl-kith-kin:earths-gentle-movements": "Força + Ofícios + Wyrd",
  "ctl-kith-kin:earths-impenetrable-walls": "Força + Ofícios + Wyrd",
  "ctl-dark-eras:peacemakers-draw": "Destreza + (Armas de Fogo ou Atletismo) + Manto vs. Vigor + Wyrd",
  "ctl-oak-ash-thorn:donning-the-grand-mantle": "Presença + Expressão + Manto",
  "ctl-oak-ash-thorn:autonomous-payload": "Manipulação + Computação + Manto vs. (Inteligência ou Computação) + Fortification",
  "ctl-oak-ash-thorn:the-widening-gyre": "Presença + Atletismo + Manto vs. Vigor + Wyrd",
  "ctl-oak-ash-thorn:principle": "Presença + Política + Manto vs. Perseverança + Wyrd",
  "h-courts:celestial-summons": "Presença + Persuasão + Wyrd vs. Compostura + Wyrd",
  "h-courts:climate-change": "Perseverança + Sobrevivência + Manto",
  "h-courts:celestial-might": "Destreza + Ocultismo + Manto",
  "h-courts:celestial-shield": "Nenhuma",
  "h-courts:vigil-of-silver-and-gold": "Presença + Expressão + Wyrd",
  "h-courts:family-friendly-feud": "Nenhuma",
  "h-courts:frozen-in-time": "Manipulação + Ocultismo + Manto vs. Perseverança + Wyrd",
  "h-courts:hearths-respite": "Compostura + Empatia + Manto",
  "h-courts:protection-of-the-innocent": "Perseverança + Medicina + Manto",
  "h-courts:shared-remembrance": "Raciocínio + Empatia + Manto vs. Perseverança + Wyrd",
  "h-courts:nothing-to-see-here": "Manipulação + Empatia + Wyrd vs. Compostura + Wyrd",
  "h-courts:rain-of-terror": "Inteligência + Ocultismo + Manto vs. Compostura + Wyrd (disputada separadamente por cada vítima)",
  "h-courts:storm-of-the-century": "Presença + Sobrevivência + Manto",
  "h-courts:tempestuous-hearts": "Nenhuma",
  "h-courts:thunder-steed": "Nenhuma",
  "h-courts:aether-crossing": "Nenhuma",
  "h-courts:age-of-aquarius": "Nenhuma",
  "h-courts:assuming-the-stellar-mantle": "Manipulação + Persuasão + Manto vs Compostura + Wyrd",
  "h-courts:elemental-cycle": "Nenhuma",
  "h-courts:restringing-the-loom": "Nenhuma",
  "h-courts:all-roads-closed": "Inteligência + Manha + Manto",
  "h-courts:cast-out": "Presença + Ocultismo + Manto vs. Vigor + Wyrd",
  "h-courts:create-path": "Presença + Sobrevivência + Manto",
  "h-courts:escape-route": "Nenhuma",
  "h-courts:labyrinth": "Manipulação + Subterfúgio + Manto vs. Perseverança + Wyrd",
  "h-courts:harmony-enforced": "Presença + Empatia + Manto vs. maior Perseverança + Wyrd",
  "h-courts:one-with-the-elements": "Nenhuma",
  "h-courts:shifting-balance": "Nenhuma",
  "h-courts:steal-harmony": "Presença + Empatia + Manto – Compostura",
  "h-courts:weaponize-mob": "Manipulação + Persuasão + Manto – maior Compostura em a group",
  "h-courts:davy-jones-locker": "Presença + Sobrevivência + Manto",
  "h-courts:dredge-the-depths": "Raciocínio + Investigação + Manto",
  "h-courts:gone-by-the-board": "Nenhuma",
  "h-courts:red-sky-at-morning": "Nenhuma",
  "h-courts:red-sky-at-night": "Nenhuma",
  "h-courts:always-solvent": "Nenhuma",
  "h-courts:cook-the-books": "Nenhuma",
  "h-courts:if-two-are-dead": "Presença + Intimidação + Manto vs. Compostura + Wyrd",
  "h-courts:raise-the-band": "Nenhuma",
  "h-courts:supply-and-demand": "Presença + Intimidação + Manto vs. Perseverança + Wyrd",
  "h-seemings:carrion-feast": "Nenhuma",
  "h-seemings:no-escape": "Vigor + Atletismo + Wyrd vs. Vigor + Wyrd (rolagem de resistência separada para cada vítima)",
  "h-seemings:starvations-savagery": "Presença + Intimidação + Wyrd vs. Compostura + Wyrd",
  "h-seemings:swallow-whole": "Força + Atletismo + Wyrd vs. Vigor + Wyrd",
  "h-seemings:you-are-who-you-eat": "Nenhuma",
  "h-seemings:last-hope": "Nenhuma",
  "h-seemings:the-troll-toll": "Presença + Subterfúgio + Wyrd vs. Perseverança + Wyrd (maior do grupo)",
  "ctl-kith-kin:coin-mark": "Nenhuma",
  "ctl-kith-kin:blood-debt": "Nenhuma"
};
