export const SKILL_SPECIALTY_SUGGESTIONS:Record<string,string[]>={
  "Erudição":["Antropologia","Arte","História","Direito","Linguística","Religião","Pesquisa"],
  "Computação":["Inteligência Artificial","Recuperação de Dados","Segurança Digital","Gráficos","Hacking","Internet","Programação","Design de Interface"],
  "Ofícios":["Automóveis","Aeronaves","Carpintaria","Improvisação","Pintura","Forja","Escultura","Costura"],
  "Investigação":["Artefatos","Autópsias","Linguagem Corporal","Cenas de Crime","Criptografia","Sonhos","Contabilidade Forense","Enigmas","Experimentos Científicos"],
  "Medicina":["Cardiologia","Atendimento de Emergência","Primeiros Socorros","Patologia","Farmacologia","Fisioterapia","Cirurgia"],
  "Ocultismo":["Crenças Culturais","Fantasmas","Folclore","Magia","Monstros","Fenômenos Psíquicos","Superstições","Lendas Urbanas","Bruxaria"],
  "Política":["Suborno","Burocracia","Eleições","Política Local","Política Nacional","Escândalos","Partido Político"],
  "Ciência":["Biologia","Química","Genética","Geologia","Metalurgia","Óptica","Física de Partículas"],
  "Esportes":["Acrobacia","Basquete","Escalada","Caiaque","Corrida de Longa Distância","Corrida de Velocidade","Natação","Arremesso"],
  "Briga":["Bloqueio","Boxe","Golpes Sujos","Agarramento","Kung Fu","Muay Thai","Projeções"],
  "Condução":["Evasão","Carros de Alto Desempenho","Motocicletas","Fora de Estrada","Pilotagem","Perseguição","Corrida","Manobras"],
  "Armas de Fogo":["Fogo Automático","Arco","Saque Rápido","Pistolas","Rifles","Espingardas","Tiro de Precisão","Tiro Acrobático"],
  "Furto":["Sistemas de Alarme","Arrombamento","Ocultar Bens Roubados","Abrir Fechaduras","Bater Carteira","Cofres","Prestidigitação"],
  "Furtividade":["Camuflagem","Multidões","Esconder-se","Mover-se no Escuro","Mover-se Silenciosamente","Seguir Alvos","Vigilância"],
  "Sobrevivência":["Coleta","Caça","Navegação","Meteorologia","Abrigos"],
  "Armas Brancas":["Porretes","Duelos","Armas Improvisadas","Facas","Espadas"],
  "Empatia com Animais":["Necessidades Animais","Cães","Animais Exóticos","Cavalos","Treinamento","Ataque Iminente","Animais Selvagens"],
  "Empatia":["Sentimentos Ocultos","Acalmar","Emoções","Mentiras","Motivações","Personalidades"],
  "Expressão":["Dança Clássica","Composição","Drama","Reportagens","Jornalismo","Instrumento Musical","Discursos"],
  "Intimidação":["Ameaças Diretas","Interrogatório","Olhar Assassino","Ameaças Físicas","Tortura","Ameaças Veladas"],
  "Persuasão":["Lábia","Inspirar","Argumentos de Venda","Discursos Motivacionais","Sedução","Sermões"],
  "Socialização":["Bares","Bailes de Gala","Festas Universitárias","Eventos Formais","Arrecadações Políticas","Clubes Privados"],
  "Manha":["Mercado Negro","Gangues","Navegação Urbana","Rumores","Operações Infiltradas"],
  "Dissimulação":["Golpes","Detectar Mentiras","Significados Ocultos","Esconder Emoções","Mentir","Desorientação"]
};
