import type { Locale } from "./i18n";

const ENGLISH_TERMS: Record<string,string> = {
  "Mental":"Mental", "Mentais":"Mental", "Físicos":"Physical", "Físicas":"Physical", "Sociais":"Social",
  "Inteligência":"Intelligence", "Raciocínio":"Wits", "Perseverança":"Resolve",
  "Força":"Strength", "Destreza":"Dexterity", "Vigor":"Stamina",
  "Presença":"Presence", "Manipulação":"Manipulation", "Compostura":"Composure",
  "Erudição":"Academics", "Computação":"Computer", "Ofícios":"Crafts",
  "Investigação":"Investigation", "Medicina":"Medicine", "Ocultismo":"Occult",
  "Política":"Politics", "Ciência":"Science", "Atletismo":"Athletics", "Briga":"Brawl",
  "Condução":"Drive", "Armas de Fogo":"Firearms", "Furto":"Larceny",
  "Armas Brancas":"Weaponry", "Furtividade":"Stealth", "Sobrevivência":"Survival",
  "Empatia com Animais":"Animal Ken", "Empatia":"Empathy", "Expressão":"Expression",
  "Intimidação":"Intimidation", "Persuasão":"Persuasion", "Socialização":"Socialize",
  "Manha":"Streetwise", "Subterfúgio":"Subterfuge",
  "Morte":"Death", "Destino":"Fate", "Forças":"Forces", "Vida":"Life",
  "Matéria":"Matter", "Mente":"Mind", "Primórdio":"Prime", "Espaço":"Space",
  "Espírito":"Spirit", "Tempo":"Time",
  "Fera":"Beast", "Trevoso":"Darkling", "Elemental":"Elemental",
  "Belíssimo":"Fairest", "Ogro":"Ogre", "Mirrado":"Wizened",
  "Coroa":"Crown", "Joias":"Jewels", "Espelho":"Mirror", "Escudo":"Shield",
  "Corcel":"Steed", "Espada":"Sword", "Cálice":"Chalice", "Moeda":"Coin",
  "Cetro":"Scepter", "Estrelas":"Stars", "Espinho":"Thorn", "Garganta":"Maw",
  "Mestre de Xadrez":"Chess Master", "Comandante":"Commander", "Compositor":"Composer", "Conselheiro":"Counselor", "Audacioso":"Daredevil", "Dínamo":"Dynamo", "Protetor":"Protector", "Provedor":"Provider", "Erudito":"Scholar", "Contador de Histórias":"Storyteller", "Professor":"Teacher", "Tradicionalista":"Traditionalist", "Visionário":"Visionary",
  "Aceitação":"Acceptance", "Raiva":"Anger", "Família":"Family", "Amizade":"Friendship", "Ódio":"Hate", "Honra":"Honor", "Alegria":"Joy", "Amor":"Love", "Memória":"Memory", "Vingança":"Revenge", "Ferro Frio":"Cold Iron",
  "Sem Corte":"Courtless", "Primavera":"Spring", "Corte da Primavera":"Spring", "Verão":"Summer", "Corte do Verão":"Summer",
  "Outono":"Autumn", "Corte do Outono":"Autumn", "Inverno":"Winter", "Corte do Inverno":"Winter",
  "Seta Adamantina":"Adamantine Arrow", "Conselho Livre":"Free Council",
  "Guardiões do Véu":"Guardians of the Veil", "Escada de Prata":"Silver Ladder",
  "Videntes do Trono":"Seers of the Throne", "Sem Ordem":"Nameless",
  "Fado":"Wyrd", "Gnose":"Gnosis", "Lucidez":"Clarity", "Sabedoria":"Wisdom",
  "Força de Vontade":"Willpower", "Sebe":"Hedge", "Semblante":"Seeming",
  "Frátria":"Kith", "Regalia":"Regalia", "Corte":"Court", "Manto":"Mantle",
  "Nenhuma opção disponível":"No options available",
  "Todas":"All", "Todos":"All",


  "Nome":"Name",
  "Jogador":"Player",
  "Crônica":"Chronicle",
  "Conceito":"Concept",
  "Agulha":"Needle",
  "Linha":"Thread",
  "Vício":"Vice",
  "Virtude":"Virtue",
  "Nome das Sombras":"Shadow Name",
  "Caminho":"Path",
  "Ordem":"Order",
  "Legado":"Legacy",
  "Resumo":"Summary",
  "Principal":"Main",
  "Atributos":"Attributes",
  "Perícias":"Skills",
  "Detalhes":"Details",
  "Poderes":"Powers",
  "Combate":"Combat",
  "Companheiros":"Companions",
  "Anotações":"Notes",
  "Experiência":"Experience",
  "Feitiço":"Spell",
  "Méritos":"Merits",
  "Méritos Expandidos":"Expanded Merits",
  "Aspirações":"Aspirations",
  "Obsessões":"Obsessions",
  "Fragilidades":"Frailties",
  "Touchstones":"Touchstones",
  "Condições":"Conditions",
  "Nimbus":"Nimbus",
  "Feitiços Ativos":"Active Spells",
  "Regalias Favorecidas":"Favored Regalia",
  "Contratos":"Contracts",
  "Débito Goblin":"Goblin Debt",
  "Juramentos":"Oaths",
  "Arcanos":"Arcana",
  "Rotas":"Rotes",
  "Práxis":"Praxes",
  "Attainments":"Attainments",
  "Ferramentas Mágicas":"Magical Tools",
  "Inclinação do Nimbus":"Nimbus Tilt",
  "Itens Encantados":"Enchanted Items",
  "Condições do Paradoxo":"Paradox Conditions",
  "Vitalidade":"Health",
  "Características da Linha":"Line Traits",
  "Outras Características":"Other Traits",
  "Escolhas dos Méritos":"Merit Choices",
  "Armadura":"Armor",
  "Armas":"Weapons",
  "Equipamentos":"Equipment",
  "Veículos":"Vehicles",
  "Modificador":"Modifier",
  "Tamanho":"Size",
  "Durabilidade":"Durability",
  "Estrutura":"Structure",
  "Velocidade":"Speed",
  "Iniciativa":"Initiative",
  "Defesa":"Defense",
  "Deslocamento":"Speed",
  "Armadura geral":"General Armor",
  "Armadura balística":"Ballistic Armor",
  "Bênção da Frátria":"Kith Blessing",
  "Bênção do Semblante":"Seeming Blessing",
  "Maldição do Semblante":"Seeming Curse",
  "Benefícios da Corte":"Court Benefits",
  "Perícias de Ordem":"Order Skills",
  "Contrato":"Contract",
  "Disciplina":"Discipline",
  "Devoção":"Devotion",
  "Benefício de Contrato":"Contract Benefit",
  "Rota":"Rote",
  "Nenhum registro.":"No entries.",
  "Nenhum Mérito selecionado":"No Merit selected",
  "Nenhum Mérito Expandido adquirido.":"No Expanded Merit acquired.",

  };

const PORTUGUESE_TERMS: Record<string,string> = {
  Mental:"Mental", Physical:"Físico", Social:"Social",
  Intelligence:"Inteligência", Wits:"Raciocínio", Resolve:"Perseverança", Strength:"Força", Dexterity:"Destreza", Stamina:"Vigor", Presence:"Presença", Manipulation:"Manipulação", Composure:"Compostura",
  Academics:"Erudição", Computer:"Computação", Crafts:"Ofícios", Investigation:"Investigação", Medicine:"Medicina", Occult:"Ocultismo", Politics:"Política", Science:"Ciência", Athletics:"Atletismo", Brawl:"Briga", Drive:"Condução", Firearms:"Armas de Fogo", Larceny:"Furto", Weaponry:"Armas Brancas", Stealth:"Furtividade", Survival:"Sobrevivência", "Animal Ken":"Empatia com Animais", Empathy:"Empatia", Expression:"Expressão", Intimidation:"Intimidação", Persuasion:"Persuasão", Socialize:"Socialização", Streetwise:"Manha", Subterfuge:"Subterfúgio",
  Crown:"Coroa", Jewels:"Joias", Mirror:"Espelho", Shield:"Escudo",
  Steed:"Corcel", Sword:"Espada", Chalice:"Cálice", Coin:"Moeda",
  Scepter:"Cetro", Stars:"Estrelas", Thorn:"Espinho",
  Needle:"Agulha", Thread:"Linha", Durance:"Cativeiro", Arcadia:"Arcádia", Motley:"Retalho", Bargain:"Barganha", Bastion:"Bastião",
  "Wild Hunt":"Caçada Selvagem", Huntsman:"Monteiro", Huntsmen:"Monteiros", Keeper:"Carcereiro", Keepers:"Carcereiros",
  Contract:"Contrato", Contracts:"Contratos", "Goblin Contract":"Contrato Goblin", Court:"Corte", "Spring Court":"Corte da Primavera", "Summer Court":"Corte do Verão", "Autumn Court":"Corte do Outono", "Winter Court":"Corte do Inverno",
  Privateer:"Corsário", "Goblin Debt":"Débito Goblin", Bedlam:"Desvario", Fetch:"Duplo", Echoes:"Ecos", Thorns:"Espinhos", "Dream Roads":"Estradas dos Sonhos", Wyrd:"Fado",
  "Hedge Ghosts":"Fantasmas da Sebe", Fae:"Fae", "True Fae":"Fae Verdadeiro", Faerie:"Feéria", Seeming:"Semblante", Freehold:"Povoado", Frailty:"Fragilidade", Kith:"Frátria",
  "Goblin Fruit":"Fruta Goblin", Glamour:"Glamour", Goblin:"Goblin", Hobgoblin:"Hobgoblin", Icon:"Ícone", Oath:"Juramento", Loyalist:"Legalista", "True Loyalist":"Legalista Verdadeiro", Lord:"Lorde",
  Clarity:"Lucidez", Mantle:"Manto", Mask:"Mascarilha", "Goblin Market":"Mercado Goblin", "Hedge Shaping":"Tecer a Sebe", Hedgespinning:"Tecer a Sebe", Oneiromancy:"Oniromancia", Oneiropomp:"Onirompo",
  Others:"Outros", Token:"Penhor", Lost:"Perdido", Portaling:"Passagem", Promise:"Promessa", Oathbreaker:"Quebrador de Juramento", "Bridge-Burner":"Queima-Pontes", "Goblin Queen":"Rainha dos Goblins", "Goblin King":"Rei dos Goblins",
  Regalia:"Regalia", Renegade:"Renunciado", Hedge:"Sebe", Sealing:"Selagem", Mien:"Semblante Fae", Dreamweaving:"Tecelagem de Sonhos", Kenning:"Tino", Title:"Título", "Fae-Touched":"Tocado por Fae", Touchstone:"Touchstone", trod:"trod", Hollow:"Vão",
  "Chess Master":"Mestre de Xadrez", Commander:"Comandante", Composer:"Compositor", Counselor:"Conselheiro", Daredevil:"Audacioso", Dynamo:"Dínamo", Protector:"Protetor", Provider:"Provedor", Scholar:"Erudito", Storyteller:"Contador de Histórias", Teacher:"Professor", Traditionalist:"Tradicionalista", Visionary:"Visionário",
  Discipline:"Disciplina", Devotion:"Devoção",
  Acceptance:"Aceitação", Anger:"Raiva", Family:"Família", Friendship:"Amizade", Hate:"Ódio", Honor:"Honra", Joy:"Alegria", Love:"Amor", Memory:"Memória", Revenge:"Vingança", "Cold Iron":"Ferro Frio",
  Courtless:"Sem Corte", Spring:"Corte da Primavera", Summer:"Corte do Verão", Autumn:"Corte do Outono", Winter:"Corte do Inverno",
};

/** Localizes presentation only. Stored character values remain unchanged. */
export function systemTerm(value:string,locale:Locale){return locale==="en-US"?(ENGLISH_TERMS[value]??value):(PORTUGUESE_TERMS[value]??value)}
export function systemTerms(values:readonly string[],locale:Locale){return values.map(value=>systemTerm(value,locale))}
