export type TiltDefinition = {
  id: string; name: string; translatedName: string; category: "Personal" | "Environmental";
  description: string; effect: string; causing: string; ending: string;
  source: string; sourceCode: string; page: number;
};

const core = (id:string,name:string,translatedName:string,category:TiltDefinition["category"],page:number,description:string,effect:string,causing:string,ending:string):TiltDefinition => ({id,name,translatedName,category,page,description,effect,causing,ending,source:"Chronicles of Darkness",sourceCode:"CofD",});
const boc = (id:string,name:string,translatedName:string,page:number,description:string,effect:string,causing:string,ending:string):TiltDefinition => ({id,name,translatedName,category:"Environmental",page,description,effect,causing,ending,source:"Book of Courts",sourceCode:"BoC"});

export const TILTS: TiltDefinition[] = [
  core("arm-wrack","Arm Wrack","Braço Lesionado","Personal",280,"An arm is sprained, dislocated, broken, or otherwise unusable.","Drop held items and cannot use that arm. Manual dexterity suffers off-hand penalties; both arms reduce manual tasks to a chance die and impose -3 on other Physical actions.","A targeted blow to the arm dealing more than Stamina damage, a damaging hit to the hand, or an appropriate supernatural power.","Heal the marked damage that caused it; aggravated damage may make the loss permanent."),
  core("beaten-down","Beaten Down","Derrotado","Personal",280,"The character has had the fight knocked out of them.","Spend 1 Willpower for each violent action; running, Dodge, and Defense remain available.","Suffer bashing damage exceeding Stamina or any lethal damage.","Surrender and grant the aggressor what they want, regaining 1 Willpower and taking a Beat but leaving the fight."),
  core("blinded","Blinded","Cego","Personal",281,"One or both eyes are disabled.","One eye imposes -3 on vision rolls and halves Defense; both impose -5 and remove Defense.","A targeted attack to the eyes or a temporary blinding attack such as thrown sand.","Temporary blindness lasts one turn; otherwise heal the marked damage, while aggravated injury may be permanent."),
  core("deafened","Deafened","Surdo","Personal",281,"The character cannot hear properly.","One ear imposes -3 on hearing Perception; both reduce it to a chance die and impose -2 on combat-related pools.","A sufficiently loud noise or targeted attack to the ear.","Noise fades after 10 - Stamina + Resolve turns; injury ends when its marked damage heals, unless aggravated."),
  core("drugged","Drugged","Drogado","Personal",281,"Mind-altering substances impair coordination and perception.","Apply -2 Speed and -3 to combat rolls, including Defense and Perception, but ignore wound penalties.","Voluntary consumption or administration through an attack.","A generic narcotic lasts 10 - Stamina + Resolve hours; medical treatment halves this time."),
  core("immobilized","Immobilized","Imobilizado","Personal",284,"Bindings, confinement, or a grappler prevents movement.","Cannot move, apply Defense, or take combat actions; spending Willpower may permit a limited attack against a restrainer.","The Restrain grapple move, bindings, confinement, or supernatural restraint.","Break free from the grapple or succeed at Strength + Athletics penalized by the binding's Durability, suffering 1 bashing per attempt."),
  core("insane","Insane","Insano","Personal",285,"A panic attack or psychotic break overwhelms reason.","Gain +1 on combat rolls, act after everyone else, cannot spend Willpower in combat, and suffer -3 on Social rolls.","An appropriate Condition, overwhelming horror, deliberate psychological sabotage, or supernatural influence.","Usually ends with the scene; contest Resolve + Composure against 10 - Willpower while taking no other action to recover early."),
  core("insensate","Insensate","Insensível","Personal",285,"Fear, pleasure, or intoxication leaves the character unresponsive.","Cannot act, but may move and apply Defense; damage ends the Tilt.","Overwhelming emotion, supernatural influence, or powerful intoxicants.","Ends at scene end, upon damage, or for one turn by spending Willpower; drug-induced instances become Drugged afterward."),
  core("knocked-down","Knocked Down","Derrubado","Personal",285,"The character is knocked prone.","Lose the current action if not yet taken; attacks from the ground suffer -2, though Defense still applies.","A sufficiently damaging weapon or targeted attack to the legs that sacrifices half its damage.","Stand as an action, or succeed reflexively at Dexterity + Athletics before acting to avoid the Tilt."),
  core("leg-wrack","Leg Wrack","Perna Lesionada","Personal",285,"A leg is sprained, dislocated, broken, or otherwise unusable.","One leg halves Speed and imposes -2 on movement-related Physical actions and Defense; both cause Knocked Down, Speed 1, and chance-die movement actions.","A targeted blow to a leg dealing more than Stamina damage or an appropriate supernatural power.","Heal the marked damage that caused it; aggravated injury may make the loss permanent."),
  core("poisoned","Poisoned","Envenenado","Personal",286,"A harmful substance damages the character from within.","Moderate poison deals 1 bashing per turn; grave poison deals 1 lethal per turn.","Ingestion, environmental exposure, injection, or an attack administering poison.","Each turn, reflexively roll Stamina + Resolve, at -3 when taking a non-reflexive action, to prevent that turn's damage; medical care may end it."),
  core("sick","Sick","Doente","Personal",286,"Illness debilitates the character during combat.","Moderate sickness starts at -1 to all actions and worsens every two turns to -5; grave sickness also deals 1 bashing each turn of exertion.","Existing disease, deliberate exposure, or supernatural infection.","After rest becomes possible, penalties fade by one each turn; damage heals normally."),
  core("stunned","Stunned","Atordoado","Personal",286,"The character is dazed and unable to think clearly.","Lose the next action and halve Defense until next able to act.","Take at least Size damage in one hit, suffer a stunning weapon effect, a head strike, or an explosion.","Normally lasts one turn; spend 1 Willpower reflexively to act at -3 that turn."),
  core("blizzard","Blizzard","Nevasca","Environmental",281,"Heavy snow and wind obscure sight and movement.","Visual Perception and ranged attacks suffer -1 at arm's length and another -1 per 10 yards; each four inches of snow imposes -1 on relevant Physical rolls.","Severe weather or an appropriate supernatural power.","Escape or wait it out; suitable gear offsets some penalties."),
  core("earthquake","Earthquake","Terremoto","Environmental",282,"Violent ground movement destabilizes an area.","Dexterity pools and Defense suffer -1 to -5; take 1-3 lethal each turn, downgraded to bashing by Stamina + Athletics or negated on exceptional success.","A natural event, major underground explosion, or tremendous supernatural power.","Most end within about ten turns; otherwise leave the affected area or stop the supernatural cause."),
  core("extreme-cold","Extreme Cold","Frio Extremo","Environmental",282,"Freezing temperatures cause hypothermia and prevent recovery.","Bashing damage does not heal; fast healing is halved. Gain cumulative -1 per hour; at -5, suffer 1 lethal per further hour.","Exposure below freezing, immersion in freezing water, confinement, illness, or supernatural cold.","Reach warmth and obtain medical care when hypothermic."),
  core("extreme-heat","Extreme Heat","Calor Extremo","Environmental",282,"Temperatures above roughly 40°C cause heat injury.","Bashing damage does not heal; fast healing is halved. Gain cumulative -1 per hour; at -5, suffer 1 lethal per further hour.","Environmental heat, fever, confinement near a heat source, or supernatural heat.","Escape the heat and find shade or cooling."),
  core("flooded","Flooded","Inundado","Environmental",282,"Rising liquid impedes movement and may submerge characters.","Each foot of liquid imposes -2 on Physical pools; submerged characters must swim or hold their breath.","Heavy rain, snowmelt, broken infrastructure, sabotage, or supernatural flooding.","Reach high ground or drain the flooded area."),
  core("heavy-rain","Heavy Rain","Chuva Forte","Environmental",283,"Torrential rain overwhelms sight and hearing.","Apply -3 to visual and aural Perception; after prolonged exposure, related Tilts or environmental harm may apply.","Severe weather or supernatural control.","Find shelter, leave the storm, or interrupt its supernatural source."),
  core("heavy-winds","Heavy Winds","Ventos Fortes","Environmental",283,"Powerful wind masks sound and hinders movement.","Aural Perception suffers -3; wind severity penalizes relevant Physical actions and may deal bashing damage or hurl objects.","Severe weather, machinery, explosions, or supernatural control.","Find cover, leave the wind, or interrupt its source."),
  core("ice","Ice","Gelo","Environmental",284,"A slick surface makes footing unreliable.","Halve Speed and apply −2 to all Physical rolls and Defense. Moving at full Speed raises the Physical penalty to −4, and a dramatic failure on a Physical roll inflicts Knocked Down. Vehicles halve Acceleration and suffer −5 to Drive.","Frozen ground, spills, polished surfaces, or supernatural effects.","Leave or treat the surface; suitable equipment may mitigate it."),
  core("zombies","Zombies!","Zumbis!","Environmental",150,"A dense horde of zombies or similar mostly passive monsters fills the area.","Lose the Species Factor contribution to Speed. Moving at less than full running Speed provokes an attack using the horde's best pool; an exceptional success also inflicts Knocked Down. Particularly rotten hordes may require Stamina + Composure each minute to avoid moderate Sick.","A large group of mostly passive monsters, a riot, or a comparable crush of bodies.","Draw the horde away or exploit a Bane strongly enough to drive it back or disperse it."),
  {id:"bleeding",name:"Bleeding",translatedName:"Bleeding",category:"Personal",description:"An open wound is bleeding profusely.",effect:"Increase the character's wound penalty by 1 and suffer 1 automatic bashing damage each turn.",causing:"A firearm or bladed attack that deals more damage than the victim's Stamina in one attack.",ending:"Spend a turn applying pressure, cloth, or a tourniquet; any accelerated healing also ends it. Undead are immune.",source:"Hurt Locker",sourceCode:"HL",page:143},
  {id:"burning",name:"Burning",translatedName:"Burning",category:"Personal",description:"The character has caught fire.",effect:"Suffer automatic damage each turn equal to 1 + the fire's heat level and also suffer Blinded.",causing:"An incendiary blast, flamethrower, or being covered in fuel and ignited.",ending:"Douse the fire; dropping and rolling reduces its heat by one each turn, as does another character spending an instant action to smother it.",source:"Hurt Locker",sourceCode:"HL",page:143},
  {id:"came-prepared",name:"Came Prepared",translatedName:"Came Prepared",category:"Personal",description:"Prior study has exposed an opening in a specific opponent's fighting style.",effect:"Resolve one instance to make one attack against that opponent apply only half Defense, rounded down. Only the first instance resolved in a fight grants a Beat.",causing:"Successfully study the opponent for a scene with Wits + Investigation opposed by Composure + the opponent's Combat Skill; an exceptional success grants two instances.",ending:"Resolve an instance when making the chosen attack against the studied opponent.",source:"Hurt Locker",sourceCode:"HL",page:61},
  {id:"pierced-armor",name:"Pierced Armor",translatedName:"Pierced Armor",category:"Personal",description:"Repeated fire or a devastating strike has damaged the character's armor.",effect:"Halve the armor's effective ratings, rounded down, until it is repaired or readjusted.",causing:"Suffer more damage than the armor's general rating in one attack from a high-caliber weapon or stabbing instrument.",ending:"Spend several turns replacing the armor, or repair it outside combat; supernatural armor may recover or be immune at Storyteller discretion.",source:"Hurt Locker",sourceCode:"HL",page:143},
  {id:"pinned",name:"Pinned",translatedName:"Pinned",category:"Personal",description:"An appendage or clothing is pinned to a surface.",effect:"The victim cannot move, halves Defense, and cannot take actions requiring full-body movement such as Athletics.",causing:"A piercing weapon targets an appendage at -3 and deals at least Stamina damage, or targets clothing at -5 and scores one success.",ending:"Tear an appendage free with Strength + Stamina at -3 and suffer 1 lethal, use tools with Strength + Crafts at -2 without damage, or spend an action escaping pinned clothing.",source:"Hurt Locker",sourceCode:"HL",page:143},
  {id:"flesh-too-solid",name:"Flesh Too Solid",translatedName:"Flesh Too Solid",category:"Personal",description:"Dream immersion makes physical sensations vivid enough for dream wounds to leave real scars.",effect:"Whenever the character would suffer Dream Health damage, she suffers equivalent physical Health damage instead.",causing:"A dramatic failure on oneiromantic actions or Contracts.",ending:"Normally ends at the end of the scene.",source:"Changeling the Lost",sourceCode:"CTL 2e",page:329},
  {id:"nimbus",name:"Nimbus",translatedName:"Nimbus",category:"Environmental",description:"A mage's Immediate Nimbus imposes its unique resonance on witnesses.",effect:"If Nimbus strength equals or exceeds Resolve, apply the mage-defined Attribute modifiers or Skill dice tricks for the spell's Reach in turns, minimum one; a voluntary flare uses Gnosis successes and lasts one turn.",causing:"A mage casts a spell or spends 1 Mana once per scene to flare the Immediate Nimbus without casting.",ending:"The duration expires, the witness leaves the aura, or another aura wins the applicable Clash of Wills.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:89},
  {id:"poor-light",name:"Poor Light",translatedName:"Poor Light",category:"Environmental",description:"Dim, strobing, or flickering light makes movement difficult to track.",effect:"Visual Perception and ranged combat suffer -2 at short range, -3 at medium range, and -4 at long range.",causing:"Natural darkness with dim ambient light or a visually disorienting environment such as a nightclub.",ending:"Bring, find, or create a light source.",source:"Mage the Awakening",sourceCode:"MTA 2e",page:323},
  {id:"shattered-time",name:"Shattered Time",translatedName:"Shattered Time",category:"Environmental",description:"Wounded chronology makes movement, memory, and causality stutter unpredictably.",effect:"Each turn, roll one die to add to Defense, Initiative, Speed, or Perception and another to subtract from one of them. Each rolled 10 causes a minor temporal rewrite; five accumulated 10s cause a major rewrite. Time spells and their Paradox pools both gain +1 and rote action.",causing:"Enter a region scarred by raw, broken Time.",ending:"Leave the affected region or repair its temporal wound through an appropriate supernatural effect.",source:"Dark Eras",sourceCode:"DE",page:46},
  {id:"urban-collapse",name:"Urban Collapse",translatedName:"Urban Collapse",category:"Environmental",description:"Unstable ground and structures collapse under physical stress.",effect:"Moving over half Speed requires reflexive Dexterity + Athletics at -3 or inflicts 3 bashing and Knocked Down. A dramatic failure causes 5 bashing and entrapment; escaping rubble requires Strength + Stamina at -5.",causing:"An exceptional success or dramatic failure during a physical action scene in an unstable location, or an attack made at -2 to force the hazard on a target.",ending:"Ends with the scene, but recurs in later action scenes until extensive construction repairs the site.",source:"Dark Eras",sourceCode:"DE",page:573},
  {id:"riot",name:"Riot",translatedName:"Riot",category:"Environmental",description:"A tense crowd erupts into indiscriminate violence.",effect:"Each turn, reflexively roll Stamina + Athletics; failure inflicts 2 bashing damage. Wider destruction is determined by the Storyteller.",causing:"Story events, a dangerously public act in an already tense situation, an appropriate supernatural power, or Weaponize Mob.",ending:"Usually cannot be stopped by one character and lasts from hours to weeks depending on the crowd and response.",source:"Dark Eras",sourceCode:"DE",page:576},
  boc("drowning","Drowning","Afogamento",141,"The character is immersed and running out of air.","Suffer 1 bashing damage each turn spent drowning.","Immersion in liquid, inability to surface, restraint underwater, or Davy Jones' Locker.","Reach air and clear liquid from the lungs."),
  boc("hobgoblin-band","Hobgoblin Band","Bando Hobgoblin",146,"A conscripted band of hobgoblins fights for the changeling.","Each turn the band deals Mantle lethal damage divided among opponents; Defense does not apply, armor does. Spend 1 Willpower to increase damage by 2.","Raise the Band.","The band has 5 + Mantle Health, no Defense, and takes at most 1 damage per attack. Each lethal above five reduces damage by one; full lethal or aggravated routes or kills it. Successful mental or social powers contested by Mantle count as lethal attacks."),
];

export const findTilt = (id:string) => TILTS.find((tilt) => tilt.id === id);
