export type TiltDefinition = {
  id: string; name: string; translatedName: string; category: "Personal" | "Environmental";
  description: string; effect: string; causing: string; ending: string;
  source: string; sourceCode: string; page: number;
};

const core = (id:string,name:string,translatedName:string,category:TiltDefinition["category"],page:number,description:string,effect:string,causing:string,ending:string):TiltDefinition => ({id,name,translatedName,category,page,description,effect,causing,ending,source:"Chronicles of Darkness",sourceCode:"CofD",});
const boc = (id:string,name:string,translatedName:string,page:number,description:string,effect:string,causing:string,ending:string):TiltDefinition => ({id,name,translatedName,category:"Environmental",page,description,effect,causing,ending,source:"Book of Courts",sourceCode:"BoC"});

export const TILTS: TiltDefinition[] = [
  core("arm-wrack","Arm Wrack","Braço Lesionado","Personal",280,"An arm is sprained, dislocated, broken, or otherwise unusable.","Drop held items and cannot use that arm. Manual dexterity suffers off-hand penalties; both arms reduce manual tasks to a chance die and impose -3 on other Physical actions.","A targeted blow to the arm dealing more than Stamina damage, a damaging hit to the hand, or an appropriate supernatural power.","Heal the marked damage that caused it; aggravated damage may make the loss permanent."),
  core("beaten-down","Beaten Down","Derrotado","Personal",280,"The character has had the fight knocked out of them.","Spend 1 Willpower for each violent action; running, Dodge, and Defense remain available.","Suffer bashing damage exceeding Stamina or any lethal damage.","Surrender and grant the aggressor what they want, regaining 1 Willpower and taking a Beat but leaving the fight."),
  core("blinded","Blinded","Cego","Personal",281,"One or both eyes are disabled.","One eye imposes -3 on vision rolls and halves Defense; both impose -5 and remove Defense.","A targeted attack to the eyes or a temporary blinding attack such as thrown sand.","Temporary blindness lasts one turn; otherwise heal the marked damage, while aggravated injury may be permanent."),
  core("deafened","Deafened","Surdo","Personal",281,"The character cannot hear properly.","One ear imposes -3 on hearing Perception; both reduce it to a chance die and impose -2 on combat-related pools.","A sufficiently loud noise or targeted attack to the ear.","Noise fades after 10 - Stamina + Resolve turns; injury ends when its marked damage heals, unless aggravated."),
  core("drugged","Drugged","Drogado","Personal",281,"Mind-altering substances impair coordination and perception.","Apply -2 Speed and -3 to combat rolls, including Defense and Perception, but ignore wound penalties.","Voluntary consumption or administration through an attack.","A generic narcotic lasts 10 - Stamina + Resolve hours; medical treatment halves this time."),
  core("immobilized","Immobilized","Imobilizado","Personal",284,"Bindings, confinement, or a grappler prevents movement.","Cannot move, apply Defense, or take combat actions; spending Willpower may permit a limited attack against a restrainer.","The Restrain grapple move, bindings, confinement, or supernatural restraint.","Break free from the grapple or succeed at Strength + Athletics penalized by the binding's Durability, suffering 1 bashing per attempt."),
  core("insane","Insane","Insano","Personal",285,"A panic attack or psychotic break overwhelms reason.","Gain +1 on combat rolls, act after everyone else, cannot spend Willpower in combat, and suffer -3 on Social rolls.","An appropriate Condition, overwhelming horror, deliberate psychological sabotage, or supernatural influence.","Usually ends with the scene; contest Resolve + Composure against 10 - Willpower while taking no other action to recover early."),
  core("insensate","Insensate","Insensível","Personal",285,"Fear, pleasure, or intoxication leaves the character unresponsive.","Cannot act, but may move and apply Defense; damage ends the Tilt.","Overwhelming emotion, supernatural influence, or powerful intoxicants.","Ends at scene end, upon damage, or for one turn by spending Willpower; drug-induced instances become Drugged afterward."),
  core("knocked-down","Knocked Down","Derrubado","Personal",285,"The character is knocked prone.","Lose the current action if not yet taken; attacks from the ground suffer -2, though Defense still applies.","A sufficiently damaging weapon or targeted attack to the legs that sacrifices half its damage.","Stand as an action, or succeed reflexively at Dexterity + Athletics before acting to avoid the Tilt."),
  core("leg-wrack","Leg Wrack","Perna Lesionada","Personal",285,"A leg is sprained, dislocated, broken, or otherwise unusable.","One leg halves Speed and imposes -2 on movement-related Physical actions and Defense; both cause Knocked Down, Speed 1, and chance-die movement actions.","A targeted blow to a leg dealing more than Stamina damage or an appropriate supernatural power.","Heal the marked damage that caused it; aggravated injury may make the loss permanent."),
  core("poisoned","Poisoned","Envenenado","Personal",286,"A harmful substance damages the character from within.","Moderate poison deals 1 bashing per turn; grave poison deals 1 lethal per turn.","Ingestion, environmental exposure, injection, or an attack administering poison.","Each turn, reflexively roll Stamina + Resolve, at -3 when taking a non-reflexive action, to prevent that turn's damage; medical care may end it."),
  core("sick","Sick","Doente","Personal",286,"Illness debilitates the character during combat.","Moderate sickness starts at -1 to all actions and worsens every two turns to -5; grave sickness also deals 1 bashing each turn of exertion.","Existing disease, deliberate exposure, or supernatural infection.","After rest becomes possible, penalties fade by one each turn; damage heals normally."),
  core("stunned","Stunned","Atordoado","Personal",286,"The character is dazed and unable to think clearly.","Lose the next action and halve Defense until next able to act.","Take at least Size damage in one hit, suffer a stunning weapon effect, a head strike, or an explosion.","Normally lasts one turn; spend 1 Willpower reflexively to act at -3 that turn."),
  core("blizzard","Blizzard","Nevasca","Environmental",281,"Heavy snow and wind obscure sight and movement.","Visual Perception and ranged attacks suffer -1 at arm's length and another -1 per 10 yards; each four inches of snow imposes -1 on relevant Physical rolls.","Severe weather or an appropriate supernatural power.","Escape or wait it out; suitable gear offsets some penalties."),
  core("earthquake","Earthquake","Terremoto","Environmental",282,"Violent ground movement destabilizes an area.","Dexterity pools and Defense suffer -1 to -5; take 1-3 lethal each turn, downgraded to bashing by Stamina + Athletics or negated on exceptional success.","A natural event, major underground explosion, or tremendous supernatural power.","Most end within about ten turns; otherwise leave the affected area or stop the supernatural cause."),
  core("extreme-cold","Extreme Cold","Frio Extremo","Environmental",282,"Freezing temperatures cause hypothermia and prevent recovery.","Bashing damage does not heal; fast healing is halved. Gain cumulative -1 per hour; at -5, suffer 1 lethal per further hour.","Exposure below freezing, immersion in freezing water, confinement, illness, or supernatural cold.","Reach warmth and obtain medical care when hypothermic."),
  core("extreme-heat","Extreme Heat","Calor Extremo","Environmental",283,"Temperatures above roughly 40°C cause heat injury.","Bashing damage does not heal; fast healing is halved. Gain cumulative -1 per hour; at -5, suffer 1 lethal per further hour.","Environmental heat, fever, confinement near a heat source, or supernatural heat.","Escape the heat and find shade or cooling."),
  core("flooded","Flooded","Inundado","Environmental",283,"Rising liquid impedes movement and may submerge characters.","Each foot of liquid imposes -2 on Physical pools; submerged characters must swim or hold their breath.","Heavy rain, snowmelt, broken infrastructure, sabotage, or supernatural flooding.","Reach high ground or drain the flooded area."),
  core("heavy-rain","Heavy Rain","Chuva Forte","Environmental",283,"Torrential rain overwhelms sight and hearing.","Apply -3 to visual and aural Perception; after prolonged exposure, related Tilts or environmental harm may apply.","Severe weather or supernatural control.","Find shelter, leave the storm, or interrupt its supernatural source."),
  core("heavy-winds","Heavy Winds","Ventos Fortes","Environmental",283,"Powerful wind masks sound and hinders movement.","Aural Perception suffers -3; wind severity penalizes relevant Physical actions and may deal bashing damage or hurl objects.","Severe weather, machinery, explosions, or supernatural control.","Find cover, leave the wind, or interrupt its source."),
  core("ice","Ice","Gelo","Environmental",284,"A slick surface makes footing unreliable.","Apply -2 Speed and -2 to Physical actions; moving more than half Speed risks Knocked Down.","Frozen ground, spills, polished surfaces, or supernatural effects.","Leave or treat the surface; suitable equipment may mitigate it."),
  boc("riot","Riot","Motim",138,"A tense crowd erupts into indiscriminate violence.","Each turn, reflexively roll Stamina + Athletics; failure inflicts 2 bashing damage. Wider destruction is determined by the Storyteller.","Weaponize Mob, Cacophony in a tense situation, or Storyteller judgment.","Usually cannot be stopped by one character and lasts from hours to weeks depending on the crowd and response."),
  boc("drowning","Drowning","Afogamento",141,"The character is immersed and running out of air.","Suffer 1 bashing damage each turn spent drowning.","Immersion in liquid, inability to surface, restraint underwater, or Davy Jones' Locker.","Reach air and clear liquid from the lungs."),
  boc("hobgoblin-band","Hobgoblin Band","Bando Hobgoblin",146,"A conscripted band of hobgoblins fights for the changeling.","Each turn the band deals Mantle lethal damage divided among opponents; Defense does not apply, armor does. Spend 1 Willpower to increase damage by 2.","Raise the Band.","The band has 5 + Mantle Health, no Defense, and takes at most 1 damage per attack. Each lethal above five reduces damage by one; full lethal or aggravated routes or kills it. Successful mental or social powers contested by Mantle count as lethal attacks."),
];

export const findTilt = (id:string) => TILTS.find((tilt) => tilt.id === id);
