"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle } from "@/components/ui/alert-dialog";
import type { CharacterSheet } from "@/lib/core/character/character-types";
import { useLanguage } from "@/lib/i18n";
import { findLegacy,LEGACIES,legacyAttainmentPrerequisites,legacyEntryPrerequisites,normalizeLegacyState } from "@/lib/legacies";
import type { MageAdvancementUndo } from "@/lib/experience-refunds";
import { discardLegacyAdvancements } from "@/lib/legacy-progression";
import { createRandomId } from "@/lib/random-id";
import { RuleSelect } from "./rule-select";

type MageXpEntry={undo?:MageAdvancementUndo;id:string;description:string;regular:number;arcane:number;createdAt:string;before:{attributes:Record<string,number>;skills:Record<string,number>;merits:CharacterSheet["merits"];specializations:CharacterSheet["specializations"];line_data:Record<string,unknown>}};

export function LegacyPage({character,updateSheet,onDiscard}:{character:CharacterSheet;updateSheet:(sheet:CharacterSheet)=>void;onDiscard:()=>void}){
 const { t }=useLanguage(),state=normalizeLegacyState(character.line_data.legacy_state),definition=findLegacy(state.definitionId),checks=definition?legacyEntryPrerequisites(character,definition):undefined;
 const [method,setMethod]=useState<"tutelage"|"daimonomikon"|"soul-study">("tutelage"),[pool,setPool]=useState<"regular"|"arcane">("regular"),[training,setTraining]=useState<"tutor"|"self">("tutor"),[feedback,setFeedback]=useState(""),[discardOpen,setDiscardOpen]=useState(false);
 const regular=Number(character.current_state.mage_experience_available??0),arcane=Number(character.current_state.arcane_experience_available??0),gnosis=Number(character.line_data.gnosis??1);
 const history=Array.isArray(character.current_state.mage_experience_history)?character.current_state.mage_experience_history as MageXpEntry[]:[];
 const selectLegacy=(definitionId:string)=>{const next=structuredClone(character);next.line_data.legacy_state={definitionId,joined:false,attainmentRanks:[],initiationMethod:""};updateSheet(next);setFeedback("");};
 const findPraxis=(name:string)=>{for(const key of ["praxes","learned_praxes"] as const){const list=Array.isArray(character.line_data[key])?character.line_data[key] as Record<string,unknown>[]:[];const index=list.findIndex(item=>String(item.originalName??item.name)===name);if(index>=0)return {key,index,item:list[index]};}};
 const removePraxis=(next:CharacterSheet,praxis:ReturnType<typeof findPraxis>)=>{if(!praxis)return;const list=[...(next.line_data[praxis.key] as Record<string,unknown>[])];list.splice(praxis.index,1);next.line_data[praxis.key]=list;};
 const savePurchase=(next:CharacterSheet,description:string,regularCost:number,arcaneCost:number,undo:MageAdvancementUndo,credits:{regular?:number;arcane?:number;beats?:number}={})=>{const creditedRegular=Number(credits.regular??0),creditedArcane=Number(credits.arcane??0),creditedArcaneBeats=Number(credits.beats??0),finalUndo={...undo,creditedRegular,creditedArcane,creditedArcaneBeats} as MageAdvancementUndo;const entry:MageXpEntry={id:createRandomId(),description,regular:regularCost,arcane:arcaneCost,createdAt:new Date().toISOString(),undo:finalUndo,before:{attributes:structuredClone(character.attributes),skills:structuredClone(character.skills),merits:structuredClone(character.merits),specializations:structuredClone(character.specializations),line_data:structuredClone(character.line_data)}};next.current_state={...next.current_state,mage_experience_available:regular-regularCost+creditedRegular,arcane_experience_available:arcane-arcaneCost+creditedArcane,mage_experience_spent:Number(next.current_state.mage_experience_spent??0)+regularCost,arcane_experience_spent:Number(next.current_state.arcane_experience_spent??0)+arcaneCost,arcane_experience_beats:Number(next.current_state.arcane_experience_beats??0)+creditedArcaneBeats,mage_experience_history:[entry,...history].slice(0,100)};updateSheet(next);};
 const join=()=>{if(!definition||!checks?.met)return setFeedback(t("ui.theLegacyPrerequisitesAreNotYetMet"));const regularCost=method==="tutelage"&&pool==="regular"?1:0,arcaneCost=regularCost?0:1;if(regular<regularCost||arcane<arcaneCost)return setFeedback(t("ui.insufficientExperience"));const praxis=findPraxis(definition.entryPraxis),alternative=!checks.parentage&&checks.praxis,credits=praxis?{regular:alternative?1:0,arcane:alternative?0:1,beats:1+(method==="tutelage"?1:0)}:{beats:method==="tutelage"?1:0},next=structuredClone(character);removePraxis(next,praxis);next.line_data.legacy_state={definitionId:definition.id,joined:true,attainmentRanks:[1],initiationMethod:method};savePurchase(next,`${definition.name} · Initiation`,regularCost,arcaneCost,{kind:"legacyInitiation",previousState:character.line_data.legacy_state,removedPraxis:praxis,creditedRegular:0,creditedArcane:0,creditedArcaneBeats:0},credits);};
 const nextRank=Math.max(1,...state.attainmentRanks)+1,attainment=definition?.attainments.find(item=>item.rank===nextRank),rankMet=Boolean(definition&&attainment&&legacyAttainmentPrerequisites(character,definition,attainment.rank));
 const buyAttainment=()=>{if(!definition||!attainment||!rankMet)return setFeedback(t("ui.theNextAttainmentSPrerequisitesAreNotYet"));const effective=training==="self"?"arcane":pool,regularCost=effective==="regular"?1:0,arcaneCost=effective==="arcane"?1:0;if(regular<regularCost||arcane<arcaneCost)return setFeedback(t("ui.insufficientExperience"));const praxis=findPraxis(attainment.praxisName??""),next=structuredClone(character);removePraxis(next,praxis);next.line_data.legacy_state={...state,attainmentRanks:[...state.attainmentRanks,attainment.rank]};savePurchase(next,`${definition.name} · ${attainment.name}`,regularCost,arcaneCost,{kind:"legacyAttainment",rank:attainment.rank,removedPraxis:praxis,creditedRegular:0,creditedArcane:0,creditedArcaneBeats:0},praxis?{arcane:1,beats:1}:{});};
 const discard=()=>{updateSheet(discardLegacyAdvancements(character));onDiscard();};
 const choices=LEGACIES.map(item=>({value:item.id,label:`${item.name} · ${item.source} · p. ${item.page}`}));
 if(!definition)return <div className="entitlement-page legacy-page"><header className="entitlement-title"><div><h2>{t("ui.legacy")}</h2><p>{t("ui.selectAnAvailableLegacy")}</p></div></header><section className="legacy-selector"><RuleSelect value="__select" onChange={value=>value!=="__select"&&selectLegacy(value)} options={[{value:"__select",label:t("ui.selectLegacy")},...choices]}/></section></div>;
 const pageLabel=definition.id==="the-eleventh-question"?`${definition.page}–202`:String(definition.page);
 return <div className="entitlement-page legacy-page">
  <header className="entitlement-title legacy-title"><div><h2>{definition.name}</h2><p>{definition.source} · p. {pageLabel} · {t("ui.rulingArcanum")}: {definition.rulingArcanum}</p></div>{state.joined?<Button type="button" size="sm" variant="destructive" onClick={()=>setDiscardOpen(true)}>{t("ui.discardLegacy")}</Button>:<Button type="button" size="sm" className="builder-add-action legacy-join-button" disabled={!checks?.met} onClick={join}>{t("ui.joinLegacy")}</Button>}</header>
  {!state.joined&&<div className="legacy-selector"><RuleSelect value={definition.id} onChange={selectLegacy} options={choices}/></div>}
  {(!state.joined||attainment)&&<p className={`entitlement-prerequisites ${state.joined?(rankMet?"met":"unmet"):(checks?.met?"met":"unmet")}`}><strong>{t("ui.prerequisites")}:</strong> {state.joined?attainment?.prerequisites:definition.prerequisites}</p>}
  <section className="legacy-reference"><h3>{t("ui.legacyInformation")}</h3><ul><li>{t("ui.tutorAndStudentHaveAStrongSympatheticLink")}</li><li>{t("ui.afterASignificantMysticalEmotionalOrIntimateInteraction")}</li><li>{t("ui.membersDaimonomikaAndSoulStonesOfTheSame")}</li></ul><small>{t("ui.theSheetDoesNotTrackTheseRulesAutomatically")}</small></section>
  {!state.joined&&<section className="legacy-join"><div className="legacy-requirement-list">{checks?.items.map(item=><span className={item.met?"met":"unmet"} key={item.label}>{item.met?"✓":"×"} {item.label}</span>)}</div><div className="legacy-join-controls"><label>{t("ui.initiationMethod")}<RuleSelect value={method} onChange={value=>{const next=value as typeof method;setMethod(next);if(next!=="tutelage")setPool("arcane");}} options={[{value:"tutelage",label:"Tutelage"},{value:"daimonomikon",label:"Daimonomikon"},{value:"soul-study",label:"Soul or Soul Stone Study"}]}/></label><label>{t("ui.payment")}<RuleSelect value={method==="tutelage"?pool:"arcane"} onChange={value=>setPool(value as typeof pool)} options={method==="tutelage"?[{value:"regular",label:"1 Experience"},{value:"arcane",label:"1 Arcane Experience"}]:[{value:"arcane",label:"1 Arcane Experience"}]}/></label></div>{gnosis>=3&&<details className="experience-rules"><summary>{t("ui.createALegacy")}</summary><p>{t("ui.gnosis3PermitsFoundingALegacyFor1")}</p></details>}</section>}
  {state.joined&&attainment&&<section className="legacy-join legacy-next-attainment"><div className="legacy-attainment-purchase"><p><strong>{t("ui.nextAttainment")}:</strong> {attainment.name} · {t("ui.oneExperience")}</p><RuleSelect value={training} onChange={value=>{const next=value as typeof training;setTraining(next);if(next==="self")setPool("arcane");}} options={[{value:"tutor",label:t("ui.learnFromATutor")},{value:"self",label:t("ui.developWithoutATutor")}]}/>{training==="tutor"&&<RuleSelect value={pool} onChange={value=>setPool(value as typeof pool)} options={[{value:"regular",label:t("ui.oneExperience")},{value:"arcane",label:`1 ${t("ui.arcaneExperience")}`}]}/>}<Button type="button" size="sm" disabled={!rankMet} onClick={buyAttainment}>{t("ui.purchaseAttainment")}</Button></div></section>}
  <div className="entitlement-overview">{!state.joined&&<section><h3>{t("ui.initiation")}</h3><p>{definition.initiation}</p></section>}<section><h3>{t("ui.organization")}</h3><p>{definition.organization}</p></section><section><h3>{t("ui.theory")}</h3><p>{definition.theory}</p></section></div>
  <div className="entitlement-overview"><section><h3>{t("ui.yantras")}</h3><ul>{definition.yantras.map(item=><li key={item}>{item}</li>)}</ul></section><section><h3>{t("ui.oblations")}</h3><ul>{definition.oblations.map(item=><li key={item}>{item}</li>)}</ul></section></div>
  <section><h3>{t("ui.attainments")}</h3><div className="entitlement-blessings legacy-attainments">{definition.attainments.map(item=>{const acquired=state.attainmentRanks.includes(item.rank);return <details key={item.rank} className={acquired?"active":""}><summary><strong>{item.rank}. {item.name}</strong><span>{acquired?t("ui.acquiredb5d1a8"):item.prerequisites}</span></summary><p>{item.description}</p>{item.optional&&<p><strong>{t("ui.optional")}:</strong> {item.optional}</p>}</details>})}</div></section>
  {feedback&&<p className="experience-feedback">{feedback}</p>}
  <AlertDialog open={discardOpen} onOpenChange={setDiscardOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t("ui.discard", { p1: definition.name })}</AlertDialogTitle><AlertDialogDescription>{t("ui.theLegacyAndAllAcquiredAttainmentsWillBe")}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel size="sm" className="catalog-dialog-done">{t("ui.cancel")}</AlertDialogCancel><AlertDialogAction size="sm" className="catalog-dialog-done" variant="destructive" onClick={discard}>{t("ui.discardLegacy")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
